define({
    "home": "主页",
    "settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "radius_settings": "RADIUS 设置",
    "title": "高级 RADIUS 设置",
    "advanced_radiusradius_authorization": "RADIUS 认证",
    "invalid_vendor_specific_stringrefer_help_for_more_information": "无效的厂商指定字串。请参考“帮助”来获取更多信息",
    "strongSuccessMsg": "高级 RADIUS 设置已成功保存。",
    "successMsg": "",
    "strongFailureMsg": "高级 RADIUS 设置保存发生错误。",
    "failureMsg": "",
    "advanced_radiusadministrator": "管理员",
    "advanced_radiush4radius_user_authorization_h4for_authorization_purpose_you_should_configure_radius_user_with_vendor_specific_attribute_in_server_sidebrbrh4vendor_specific_attribute_in_server_sideh4you_have_to_configure_vsa_values_in_radius_serverbrul_styleliststylenoneli_example1li_litestadmin_authtype_papcleartextpasswordadminliliauthtype_pap_vendorspecifich4liulul_styleliststylenoneli_example2lilitestoperator_authtype_papcleartextpassword_operatorliliauthtype_pap_vendorspecifich3liulbrif_you_change_the_vendorspecific_value_then_you_should_change_the_same_values_in_this_pagebrstrongnotestrongbr_ul_styleliststylenonelithese_fields_will_not_allow_more_than_127_characterslili_is_not_allowedliul": "<h4>Radius 用户授权 </h4>为了用户授权，您必需在服务器端配置 RADIUS 用户的供应商特定属性<br><br><h4>在服务器端的供应商特定属性</h4>您必需在 Radius 服务器端设定 VSA<br><ul style=\\\"list-style:none;\\\"><li>- 示例:1</li> <li>testadmin Auth-Type :=PAP,Cleartext-Password:='admin'</li><li>Auth-Type :=PAP, Vendor-Specific='H=4'</li></ul><ul style=\\\"list-style:none;\\\"><li>- 示例:2</li><li>testoperator Auth-Type := PAP,Cleartext-Password := 'operator'</li><li>Auth-Type :=PAP, Vendor-Specific='H=3'</li></ul><br>如果您在服务器端改变了供应商特定属性，您应该在此页变更相同的值。<br><strong>注意:</strong><br> <ul style=\\\"list-style:none;\\\"><li>此栏位不允许超过 127 个字符。</li><li> 不允许使用 '#' 符号。</li></ul>",
    "advanced_radiusoperator": "操作员",
    "advanced_radiususer": "用户",
    "advanced_radiusoem_proprietary": "OEM 所有权",
    "advanced_radiusno_access": "无法存取",
    "saveLabel": "保存",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
});
