define({
   "title" : "资产信息",
   "home" : "主页",
   "systeminfo":"系统信息",
   "load":"加载中",
   "undata" : "无数据",
   //资产信息
   "cpus" : "CPU",
   "mems" : "内存",
   "hdds" : "硬盘",
   "nic" : "网卡",
   "pcie" : "PCIe卡",
   "psus" : "电源",
   "raid" : "RAID",
   "onside" : "已用插槽：",
   "totalSlots" : "插槽总数：",
   "present" : "在位设备：",
   "total" : "所有设备：",
   "totalCapacity" : "已安装容量：",
   //CPU信息
   "Number" : "序号",
   "Location" : "位置",
   "Present" : "在位",
   "BrandName" : "型号",
   "UPIFreq" : "UPI 频率",
   "UPIWidth" : "UPI 位宽",
   "CPUID" : "处理器ID",
   "CoreThread" : "当前核数/当前线程数",
   "CPUFreq" : "主频",
   "Cache" : "一级/二级/三级缓存",
   "SysClock" : "基频",
   "P0CoreFreq" : "Turbo频率",
   "MaxThread" : "最大核数/最大线程数",
   "Sspec" : "S-Spec",
   "PIROMIDFamily": "Family",
   "PIROMIDModel": "Model",
   "PIROMIDStepping": "Stepping",
   "PIROMID" : "PIROM CPU ID",
   "UPILinkNum" : "UPI链路数",
   "UPILinkRate" : "UPI最大链接速率",
   "MaxPCIeLinkRate" : "PCIe最大链接速率",
   "NVMDIMMSize" : "最大可支持Intel DC Persistent Memory容量",
   "Family" : "Family",
   "Tcase" : "Tcase（℃）",
   "TDP" : "TDP",
   "Features" : "指令特性",
   "ExtFamily" : "Ext.Family",
   "ExtModel" : "Ext.Model",
   //内存
   "PN" : "产品号",
   "DimmType" : "内存类型",
   "Module" : "模组类型",
   "Rank" : "Rank",
   "Type" : "类型",
   "Frequency" : "频率",
   "Size" : "容量",
   //硬盘
   "ModelName" : "型号",
   "Mode" : "模式",
   "SN" : "序列号",
   "FwVersion" : "固件版本",
   "VendorName" : "厂商",
   "VendorID" : "厂商ID",
   "MaxLinkSpeed" : "最大链接速率",
   "MaxLinkWidth" : "最大链接宽度",
   "Temp" : "温度（℃）",
   "LeftLife" : "剩余寿命(%)",
   "SMART" : "SMART状态",
   //电源
   "Vendor" : "厂商",
   "Revision" : "版本",
   "Date" : "日期",
   "RatedPower" : "额定功率",
   //网卡
   "Port" : "端口",
   "PCIeAddr" : "PCIe地址",
   "Class" : "类型",
   "Category" : "类别",
   "LinkSpeed" : "链接速率",
   "MacAddr" : "MAC/GUID",
   //PCIE
   "LinkWidth" : "链接宽度",
 //ks_lz_20181018_assetinfo ++>>
   //language
   "NA" : "无",
   "CPU_NA" : "无数据",
   "CPU_Cores": "核",
   "CPU_Threads": "线程",
   "Undefiend":"未知",
   "Present":"在位",
 //ks_lz_20181018_assetinfo ++<<
});
