define({
    "home": "主页",
    "maintenance": "系统维护",
    "title": "BIOS固件更新",
    "info":"BIOS固件更新过程中请不要执行其他操作，点击“确认”将进入固件更新模式。",
    "start_fw_update": "开始固件更新",
    "verifying":"检验中...",
    "cancle":"取消",
    "cancle_info":"BIOS固件更新已取消。",
    "cancle_confirm":"确认放弃BIOS固件更新？",
    "fwimage": "选择固件镜像",
    "pre_flash_error":"准备过程中遇到问题，请检查重试！",
    "strongSuccessMsg": "保存！",
    "successMsg": "保存成功",
    "strongFailureMsg": "",
    "failureMsg": "我会尝试出错误的原因",
    "size32mb": "最大容量 32 MB",
    "reset": "固件已经重置",
    "confirm1":"点击\“确认\”将会执行BIOS固件更新，新的镜像将会被写入，更新过程不能中断，确定执行吗？",
    //"cont_update": "更新所选的部分",
    "cont_update": "开始更新",
    "select_all": "全部选择",
    "select_none": "没有选择",
    "section_name": "部分名称",
    "bios_flash_progress":"BIOS固件更新正在进行，请稍后重试！",
    "bios_prepare_error":"设备准备过程中发生错误，请检查后重试。",
    "bios_verify_error":"BIOS固件检验不成功，请检查是否上传正确的镜像，点击\“确定\”离开更新模式。",
    "image_information":"固件版本信息",
    "current_image_version":"现有固件版本信息：",
    "new_image_version":"上传固件版本信息：",
    "diff_image_info":"上传固件与现有固件版本不同。",
    "different_image_info":"上传固件与现有固件版本不同。",
    "same_image_info":"上传固件与现有固件版本相同。",
    "flash_error":"更新BIOS固件失败，请检查！",
    "update_section": "更新部分",
    "prepare_flash":"准备更新...",
    "start_flash":"开始更新...",
    "process":"处理中...",
    "upload":"上传 ",
    "uploading":"上传...",
    "flashing":"更新...",
    "con_reset":"重置",
    "protocol_type":"协议类型:",
    "server_address":"服务器地址:",
    "image_name":"固件名称:",
    "retry_count":"重试次数:",
    "fwimage_maintance_info":"固件更新文件传输协议如下所示。请通过系统维护下的\"选择文件\"按钮选择需要上传的固件。",
    "confirm_start_fw_upgrade":"固件升级将要开始，固件升级期间请不要操作服务器，确定继续吗？",
    "notify_chose_fw_image_file":"请选择要更新的固件文件",
    "alert_upload_fail":"上传BIOS固件失败",
    "alert_flash_finish":"BIOS固件更新成功! 如需要使升级的BIOS FW生效，请掉AC后重新上AC启动系统。",
    "updateMe":"保留 ME 信息",
    "updateMeGbe":"保留 ME GBE 信息",
    "updateNvram":"保留 NVRAM 信息",
    "updatePreserve":"保留 BIOS 配置",
    "selectFile":"选择文件",
    "fw_FirmwareUpgrade": "固件更新",
    "fw_BMCFirmwareUpgrade": "BMC 固件更新",
    "fw_BIOSFirmwareUpgrade": "BIOS 固件更新",
    "fw_CPLDUpgrade": "CPLD 固件更新",
    "fw_PSUUpgrade": "PSU 固件更新",
    "fw_BPUpgrade": "背板固件更新",
});
