define({
    "home": "主页",
    "settings": "BMC 设置",
    "network_setting": "网络设置",
    "title": "网络绑定配置",
    "bond": "",
    "strongSuccessMsg": "网络绑定配置已重置成功。将会花数秒时间使配置生效,请关闭浏览器并使用新的 IP 再次开启浏览器",
    "successMsg": "---注销",
    "strongFailureMsg": "保存网络绑定配置成功",
    "failureMsg": "",
    "bondenable_bonding": "启用绑定",
    "bondcheck_this_option_to_enable_network_bonding_for_network_interfaces_strongnotestrong_if_vlan_is_enabled_for_slave_interfaces_then_bonding_cannot_be_enabled_vlan_can_be_disabled_under_configuration_network_vlan": "选中此选项以启用网络接口的网络连接。 <strong>注意:<\/strong> 如果启用从界面的 VLAN 接口,则绑定无法启用。VLAN 可以在 选项 -> 网络 -> VLAN 中禁用。",
    "bondauto_configuration": "自动配置",
    "bondh4auto_configurationh4_enable_this_option_to_configure_the_interfaces_automatically_strongnotestrong_if_auto_configuration_is_disabled_then_interfaces_in_services_can_be_configured_via_ipmi_command_if_auto_configuration_is_enabled_then_all_the_services_will_be_restarted_automatically": "<h4>自动配置<\/h4> 启用此选项来自动配置接口。 <strong>注意:<\/strong> 如果禁用自动配置, 然后服务中的接口可以通过 IPMI 指令来配置。如果启用自动配置，所有的服务都会自动重启。",
    "bondbond_interface": "绑定界面",
    "bondDedicate": "专用网络",
    "bondShare": "共享网络",
    "bondthis_page_is_used_to_configure_the_network_bonding_for_the_network_interfaces_this_is_enabled_by_default_strongnotestrong_minimum_of_2_network_interfaces_are_required_in_order_to_enable_network_bonding_for_the_device": "本选项用来配置网络接口中的网络绑定。默认为启用。 <strong>注意:<\/strong> 最少需要两个网络接口才可启用装置的网络绑定。",
    "bondbond_mode": "绑定模式",
    "bondthis_field_displays_the_network_bonding_mode_strongnotestrong_this_field_is_not_configurable": "此栏位显示网络绑定模式。 <strong>注意:<\/strong> 本栏位不可配置。",
    "saveConfirmLabel": "保存 LAN 设置会重启 BMC 的网络服务。请关闭浏览器并再次连线来启用变更的设定。确定要继续进行?",
    "saveLabel": "保存",
    "same_bond_settings": "网络绑定配置没有改变,不需要保存。",
    "nt_ip": "网络 IP 设置",
    "nt_bond": "网络绑定配置",
    "nt_dns": "DNS 配置",
    "nt_ncsi": "Sideband 界面 (NC-SI)",
    //ks_lz20181108_vlan_bondmode ++
    "bonding_note": "当前网络设置已启用Vlan，在此情况下不允许启用绑定模式",

});
