define({

    "title": "Server Mgmt",
    "home": "主页",
    "welcome": "欢迎",
    "fwVersion": "版本",
    "fwDate": "日期",
    "online": "主机在线",
    "offline": "主机离线",
    "dashboard": "仪表板",
    "sensors": "传感器",
    "logs": "日志",
    "configure": "配置",
    "remote_control": "远程控制",
    "image_redirection": "镜像重定向",
    "power": "电源控制",
    "maintenance": "系统维护",
    "tasks": "任务＆时间表",
    "upgrade": "升级",
    "automation_engine": "自动引擎",
    "help": "帮助",
    "refguide": "参考指南",
    "search_help": "搜索帮助",
    "logout": "注销",
    "server_preview": "主机预览",
    "filter_by": "筛选",
    "all": "所有",
    "firstview": "SPX",
    "critical": "临界",
    "warning": "警报",
    "queue_task": "任务队列",
    "upcoming_schedules": "即将执行的时间表",
    "alerts": "警报",
    "events": "事件",
    "thresholds": "阈值",
    "email": "电子邮件 ID",
    "disabled": "禁用",
    "additional": "额外",
    "created": "登录",
    "suggestion": "建议",

    "brand": "MEGARAC SPX",
    "rememberme": "记住用户名",
    "signmein": "登录",
    "logining": "登录中...",
    "forgotpassword": "忘记密码",
    "toggle_navigation": "启动导览",
    "msg_title": "你有一个消息",
    "trap_alert": "Trap 警报",
    "trap_alert_triggered": "Trap 警报已被触发",
    "see_allmsg": "观看所有消息",
    "notifications_msg": "你有两个通知",
    "critical_event_logged": "记录关键事件",
    "description_page_designprob": "这里很长的描述可能不适合页面并可能导致设计问题",
    "view_all": "查看所有",
    "check_server_power": "确认服务器电源供应",
    "run_server_diag": "运行服务器诊断",
    "run_firmware_update": "运行管理控制器固件更新",
    "view_alltask": "查看所有任务",
    "user_privilage": "权限",
    "user_activities": "活动",
    "user_profile": "配置文件",
    "sign_out": "注销",
    "fru_information": "FRU 信息",
    "logs_report": "日志 &amp; 报告",
    "ipmi_event_log": "IPMI 事件日志",
    "settings": "BMC 设置",
    "tasks_event": "任务 &amp; 事件",
    "store": "储存",
    "created_time": "创建",
    "runs_on": " 运行中 ",
    "system_inventory": "系统清单",

    "sync": "同步",
    "refresh": "刷新",
    "languageChoice": "语言选择",
    //tooltip
    "sync_desc": "开/关与最新的传感器和事件日志同步更新。",
    "refresh_desc": "重新载入目前页面。",
    "admin_desc": "可以查看管理员配置文件。",
    "lang_choice": "选择系统语言",
    "task_desc": "显示所有的工作。",
    "notification_desc": "显示所有已收到的通知。",
    "message_desc": "显示所有已收到的消息。",
    "logout_confirm_msg": "确定要注销当前会话? 如果确定,请按“确定”来注销,如要取消请按“取消”。",


    "loading": "载入中..",

    // Scripts
    "scripts": " 脚本",
    "available_scriptauto": "自动化可用的脚本",
    "seach_scripts": "搜索脚本",
    "close": "关闭",
    "test_run": "测试运行",
    "save_changes": "保存变更",
    "import": "输入",
    "upload_script": "上传脚本",
    "script_id": "脚本 ID",
    "name": "名称",
    "creator": "创建者",
    "actions": "动作",
    "click_confirm_deletion": "点击再一次来确认删除?",


    //SENSORS
    "search_sensors": "搜索传感器",
    "view_events": "查看事件",
    "view_alerts": "查看警报",
    "pin_to_dashboard": "钉在仪表板",
    "low_non_recoverable": "低不可恢复",
    "low_critical": "低临界",
    "low_non_critical": "低非临界",
    "upper_non_recoverable": "高不可恢复",
    "upper_critical": "高临界",
    "upper_non_critical": "高非临界",


    //AUDIT LOG
    "search_auditlog": "搜索审计日志",

    //SYSTEM LOG
    "search_systemlog": "搜索系统日志",
    "event_filters": "事件筛选器",
    "alert_option": "警报",
    "critical_option": "临界",
    "notification_option": "通知",
    "warning_option": "警报",
    "debug_option": "调试",
    "emergency_option": "紧急",
    "information_option": "信息",
    "alert_event": "显示警报事件",
    "critical_event": "显示临界事件",
    "error_event": "显示错误事件",
    "notification_event": "显示通知事件",
    "warning_event": "显示警报事件",
    "debug_event": "显示调试事件",
    "emergency_event": "显示紧急事件",
    "information_event": "显示信息事件",

    //VIDEO LOG
    "videolog": "视频日志",
    "download": "下载",
    "search_videolog": "搜索视频日志",
    "video_notsupport": "你的浏览器不支持播放此视频",

    //EVENT LOG
    "sensor": "传感器",
    "eventlog": "事件日志",
    "allsensor_eventlog": "所有的传感器事件日志",
    "search_filterevent": "搜索或筛选事件",
    "filter_bydate": "日期筛选",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "filter_bytype": "类型筛选",
    "allevents": "所有事件",
    "allsensors": "所有传感器",
    "eventlog_statistics": "事件日志统计",
    "system_events": "系统事件日志",
    "oem_events": "OEM 事件日志",
    "bios_events": "由 BIOS 产生的事件",
    "smi_events": "SMI 处理事件",
    "system_management_events": "系统管理软事件",
    "system_oem_events": "系统软件 - OEM 事件",
    "remove_console_events": "远程控制台软事件",
    "terminal_mode_events": "终端模式远程控制台软事件",
    "show_sensor_list": "显示传感器清单",
    "sensor_category": "传感器类别",
    "system_event_record": "系统事件日志",
    "oem_record": "OEM 日志",
    "bios": "BIOS",
    "smi_handler": "SMI",
    "system_management_software": "系统管理软件",
    "system_software_oem": "系统软件 OEM 事件",
    "remote_console_software": "远程控制台软件",
    "terminal_mode_remote_console_software": "终端模式远程控制台软件",
    "oem_timestamped": "OEM 时间戳",
    "oem_non_timestamped": "OEM 无-时间戳",
    "asserted": "断言",
    "deasserted": "未断言",
    "discrete": "离散的",
    "threshold": "阈值",
    "clear_sel": "清除事件日志",
    "save_sel": "下载事件日志",
    "save_type_raw": "原始格式",
    "save_type_trans": "转换格式",

    //MAINTENANCE
    "update_firmware": "更新固件",
    "restore_defaults": "恢复出厂设置",
    "cancel_update": "你确定要中止固件更新过程？此设备将去重置为正常操作模式",
    "flashing_alert": "Flashing 进行中。导航将会禁用。",
    "flashing_refresh_warning": "固件更新进行中。重刷页面将会中断固件更新的进行并且导致 BMC 无法正常进行固件更新的运行,强烈建议不要再固件更新时进行重刷页面。",

    //PRESERVE CONFIGURATION
    "preserve_configuration": "保存配置",
    "preserve_conf_0": "SDR",
    "preserve_conf_1": "FRU",
    "preserve_conf_2": "SEL",
    "preserve_conf_3": "IPMI",
    "preserve_conf_4": "Network",
    "preserve_conf_5": "NTP",
    "preserve_conf_6": "SNMP",
    "preserve_conf_7": "SSH",
    "preserve_conf_8": "KVM",
    "preserve_conf_9": "认证",

    //IMAGE TRANSFER PROTOCOL
    "image_transfer": "镜像传输协议",
    "upload_firmware": "上传固件",
    "choose_firmware": "选择固件(*.ima)",
    "http": "HTTP",
    "tftp": "TFTP",
    "ftp": "FTP",
    "source_path": "源路径",
    "retry_count": "重试次数",
    "closing_request": "Step (1 of 6): 关闭所有活动客户端要求",
    "preparing_device": "Step (2 of 6): 设备固件升级做准备",
    "firmware_upload": "Step (3 of 6): 上传固件镜像",
    "verify_firmware": "Step (4 of 6): 验证固件镜像",
    "flash_firmware": "Step (5 of 6): 刷新固件镜像",
    "reset_device": "Step (6 of 6): 重启设备",

    //SECTION BASED UPDATE
    "section_update": "基于部分固件更新",
    "select_section": "按一下来选择要进行固件更新的部分",
    "selection_alert": "请选择至少一个部分来进行固件更新",
    "section": "部分",
    "existing_version": "现存版本",
    "current_version": "当前版本",

    //MEDIA REDIRECTION SETTINGS
    "mediaredirection": "媒体重定向设置",

    //SERVICES
    "services": "服务",
    "active": "启用中",
    "inactive": "未启用",
    "search_services": "搜索服务",


    //LOG SETTINGS
    "log": "日志设置",
    "locallog": "本地日志",
    "remotelog": "远程日志",
    "systemlog": "系统日志",
    "auditlog": "审计日志",
    "save": "保存",
    "cancel": "取消",
    "filesize": "文件大小(字节)",
    "rotatecount": "旋转数量",
    "serveraddress": "服务器地址",

    //SMTP SETTINGS
    "smtp": "SMTP 设置",
    "ip": "IP 地址",
    "port": "端口",
    "lanchannelnumber": "LAN 信道数",
    "primary_smtp_name": "主要 SMTP 服务器名称",
    "primary_smtp": "主要 SMTP 服务器",
    "primary_smtp_enable": "主要 SMTP 支持",
    "primary_smtpauth": "主要 SMTP 认证",
    "primary_server_address": "主要 SMTP 服务器地址",
    "secondary_smtp_name": "次要 SMTP 服务器名称",
    "secondary_smtp": "次要 SMTP 服务器",
    "secondary_smtp_enable": "次要 SMTP 支持",
    "secondary_smtpauth": "次要 SMTP 认证",
    "secondary_server_address": "次要 SMTP 服务器地址",
    "username": "用户名称",
    "password": "密码",

    //NETWORK, LINK, BOND SETTINGS
    "network": "网络设置",
    "eth0": "eth0",
    "eth1": "eth1",
    "both": "both",
    "network_lan_interface": "LAN 界面",
    "network_lansettings": "启用 LAN 设置",
    "network_macaddress": "MAC 地址",
    "netwrok_ipv4_conf": "IPv4 配置",
    "network_dhcp": "启用 DHCP",
    "network_ipv4_address": "IPv4 地址",
    "network_submnet_mask": "子网掩码",
    "network_default_gateway": "默认网关",
    "netwrok_ipv6_conf": "启用 IPv6 配置",
    "network_ipv6_settings": "启用 IPv6 设置",
    "network_ipv6_address": "IPv6 地址",
    "network_submnet_prefix": "子网掩码前缀长度",
    "network_vlan_conf": "VLAN 配置",
    "network_vlan_settings": "VLAN 设置",
    "network_vlan_id": "VLAN ID",
    "network_vlan_priority": "VLAN 优先权",
    "network_bond_conf": "Network 绑定配置",
    "network_bonding": "启用绑定",
    "network_default_interface": "默认界面",
    "network_auto_conf": "自动配置",
    "network_link_conf": "网络连接配置",
    "select_Networks": "选择要绑定的网络",
    "mbps_10": "10 Mbps",
    "mbps_100": "100 Mbps",
    "mbps_1000": "1000 Mbps",
    "full": "全双工",
    "half": "半双工",
    "enable_auto_negotiation": "启动自动协商",

    //BI系统SETTING
    //	"bios" : "BIOS 升级",
    "raid": "RAID 更新",
    "backplane": "背板更新",
    "bios_setting": "BIOS 设置",

    //DATE TIME SETTINGS
    "datetime": "日期 & 时间",
    "date_time": "日期&时间设置",
    "gmt": "(GMT",
    "ntp_server_1": "主要 NTP 服务器",
    "ntp_server_2": "次要 NTP 服务器",
    "syncdatetime": "与服务器同步日期与时间",
    "utcTimeZone": "UTC 时区(小时)",
    "auto": "自动",
    "manual": "手动",
    "time": "时间 (时:分:秒)",
    "date": "日期 (月/日/年)",
    "cd_dvd_rom": "CD/DVD-ROM",

    //PAM SETTINGS
    "pam": "PAM 设置",
    "pamorder": "PAM 顺序设置",
    "drag_to_change": "拖动来改变顺序:",

    //SSL-SETTINGS
    "ssl": "SSL 设置",
    "ssl_certificate": "SSL 凭证",
    "generated": "产生",
    "viewssl": "查看所有的 SSL 凭证",
    "modifyssl": "修改 SSL 凭证",
    "ssl_cert_info": "凭证信息",
    "ssl_version": "版本",
    "ssl_serial": "序号",
    "ssl_signature_algo": "签名算法",
    "ssl_owner_info": "所有者信息",
    "ssl_issued_to": "发出给",
    "ssl_owner_name": "常用名(CN)",
    "ssl_owner_org": "组织(O)",
    "ssl_owner_unit": "组织单位(OU)",
    "ssl_owner_city": "城市/地点(L)",
    "ssl_owner_state": "州/省(ST)",
    "ssl_owner_country": "国家(C)",
    "ssl_owner_email": "电子邮件地址",
    "ssl_validity_info": "凭证认证",
    "ssl_valid_from": "有效自",
    "ssl_valid_to": "有效到",
    "ssl_user_info": "用户信息",
    "ssl_valid_days": "有效日 (天数)",
    "ssl_key_length": "密钥长度",
    "ssl_curr_cert_date": "当前的凭证日期",
    "ssl_curr_priv_key_date": "当前的私钥日期",
    "ssl_cert_generate": "产生",
    "ssl_new_certificate": "新凭证",
    "ssl_new_privatekey": "新的私钥",
    "ssl_cert_upload": "上传",
    "ssl_upload_cert": "添加凭证 (*.pem)",
    "ssl_upload_key": "添加私钥 (*.pem)",
    "ssl_generate_button": "产生凭证",
    "ssl_upload_button": "上传凭证",
    "browse": "浏览",
    "ssl_browse_cert": "添加凭证",
    "ssl_browse_key": "添加私钥",
    "service_name": "服务名称",
    "activate": "启动",
    "inactivate": "未启动",
    "service_interface": "界面",
    "services_nonsecure_port": "不安全的端口号",
    "services_secure_port": "安全端口号",
    "services_timeout": "超时(秒)",
    "services_sessions": "可用的会话",
    "services_sessions_active": "活动中的会话",

    //Video Settings
    "videorecord": "视频录制",
    "video_conf": "视频配置设置",
    "video_remote_conf": "视频录制远程设置",
    "remote_video_support": "录制视频到远程服务器",
    "path_to_record_video": "录制视频的服务器路径",
    "share_type": "分享类型",
    "domain_name": "网域名称",
    "nfs": "NFS",
    "samba": "CIFS",

    //Active Directory Settings
    "ad": "活动目录设置",
    "ad_settings": "活动目录",
    "ad_domain_name": "用户域名",
    "ad_enable_settings": "启用活动目录",
    //	"ad_timeout" : "超时 (秒)",
    "ad_secret_user": "加密用户",
    "ad_secret_password": "加密密码",
    "ad_server_1": "网域控制服务器 1",
    "ad_server_2": "网域控制服务器 2",
    "ad_server_3": "网域控制服务器 3",
    "ad_users_list": "列出活动目录用户",

    //Active Directory and LDAP Add Edit Users
    "group_name": "群组名称",
    "user": "用户",
    "admin": "管理员",
    "operator": "操作员  ",
    "oem": "OEM",
    "none": "无",
    "group_privilage": "群组权限",
    "group_domain": "群组网域",
    "search_base": "群组搜索基点",
    "ad_users": "活动目录用户",
    "ldap_users": "LDAP 用户",
    "ad_users_management": "活动目录用户管理",
    "ldap_users_management": "LDAP 用户管理",
    "add_user": "添加用户",
    "add_edit_user": "添加/编辑用户",

    //LDAP Settings
    "ldap": "LDAP 设置",
    "ldap_settings": "LDAP/E-Directory",
    "ldap_enable": "启用 LDAP/E-Directory",
    "ssl_enable": "启用 SSL",
    "ldap_server_address": "服务器地址",
    "ldap_port_number": "端口号",
    "ldap_binddn": "绑定 DN",
    "ldap_user_attr_cn": "cn",
    "ldap_user_attr_uid": "uid",
    "ldap_users_list": "列出 LDAP 用户",

    //PEF Settings
    "pef": "PEF",
    "pef_event_filter": "事件筛选",
    "pef_alert_policy": "警报机制",
    "pef_destination": "警报目的地",
    "pef_add_destination": "添加目的地",
    "pef_conf_destination": "警报目的地",

    //USER ADD EDIT SETTINGS
    "usermgt": "用户管理",
    "password_length": "密码长度",
    "change_user_password": "更改密码",
    "confirm_password": "确认密码",
    "byte_16": "16 Bytes",
    "byte_20": "20 Bytes",
    "user_access": "启用用户访问",
    "privilage": "网络权限",
    "user_extended_privileges": "延伸权限",
    "kvm_privilege": "KVM",
    "vmedia_privilege": "VMedia",
    "snmp_privilege": "SNMP",
    "snmp_access": "SNMP 访问",
    "snmp_auth_protocol": "认证协议",
    "snmp_priv_protocol": "私有协议",
    "read_only": "只读",
    "read_write": "读写",
    "sha": "SHA",
    "md5": "MD5",
    "des": "DES",
    "aes": "AES",
    "ssh_key": "上传 SSH 密钥",
    "existing_ssh_key": "当前的 SSH 密钥",
    "done": "完成",
    "back": "返回",
    "email_format": "电子邮件格式",
    "ssh_upload_key": "添加 SSH 密钥 (*.pub)",
    "no_password_change": "密码未改变",

    /*
	"video_critical_event" : "Critical Events (Temperature/Voltage)",
	"video_noncritical_event" : "Non Critical Events (Temperature/Voltage)",
	"video_nonrecoverable_event" : "Non Recoverable Events (Temperature/Voltage)",
	"video_fanstate_event" : "Fan state changed Events",
	"video_watchdog_event" : "Watchdog Timer Events",
	"video_chasison_event" : "Chassis Power ON Event",
	"video_chasisoff_event" : "Chassis Power OFF Event",
	"video_chasis_reset_event" : "Chassis Reset Event",
	"video_date_event" : "Date and Time Event",
	"video_lpc_event" : "LPC Reset Event",
	*/

    //LOGS
    "jan": "一月",
    "feb": "二月",
    "mar": "三月",
    "apr": "四月",
    "may": "五月",
    "jun": "六月",
    "jul": "七月",
    "aug": "八月",
    "sep": "九月",
    "oct": "十月",
    "nov": "十一月",
    "dec": "十二月",
    "sun": "星期日",
    "mon": "星期一",
    "tue": "星期二",
    "wed": "星期三",
    "thu": "星期四",
    "fri": "星期五",
    "sat": "星期六",

    // TOOLTIP MESSAGE STRINGS
    "server_name": "名字应为字母数字且不能有空白,不能以数字为开头且长度在 4-15 个字符之间",
    "server_pass": "密码应包含 (至少4 以及至多 64) 字符,不含空格",
    "server_ip": "IP 地址 (例如:10.0.0.4, 最大范围 : 255.255.255.254), 不能以 '0' 开头",
    "server_port": "输入端口号 (范围自 0 到 255)",
    "server_mail_addr": "服务器地址 (例如:xxx@yyy.com)",
    "file_size": "输入文件大小(大小范围从 3 到 65535)",
    "rotate_count": "输入旋转计数的数值 (范围从 0 到 255)",
    "non_sec_port": "不安全端口号应介于 1 到 65535 (端口号只支持数字)",
    "sec_port": "安全端口号应该介于 1 到 65535 (端口号只支持数字)",
    "timeout": "超时应该介于 60 到 1800 之间 (端口号只支持数字)",
    "max_sessions": "可用的会话 ,且数值不应该小于 0 (端口号只支持数字)",
    "curr_sessions": "活动中的会话,且数值不应该小于 0 (端口号只支持数字)",
    "video_event_0": "临界事件 (温度/电压)",
    "video_event_1": "非临界事件 (温度/电压)",
    "video_event_2": "不可恢复事件 (温度/电压)",
    "video_event_3": "风扇状态改变事件",
    "video_event_4": "看门狗计时器事件",
    "video_event_5": "机箱开机事件",
    "video_event_6": "机箱关机事件",
    "video_event_7": "机箱重置事件",
    "video_event_8": "LPC 重置事件",
    "video_event_9": "日期和时间事件",
    "date_entry": "所选日期应晚于 JAN 19, 2038",
    "hr_entry": "此处只可填入数字且介于 0-23 之间用以表示小时",
    "min_entry": "此处只可填入数字且介于 0-59 之间用以表示分钟",
    "sec_entry": "此处只可填入数字且介于 0-59 之间用以表示秒钟",
    "ntp_server_entry": "此处为服务器 IP 地址,可以使用 iPv4(例如:10.0.0.1) 或 iPv6 规范(例如:2002:c001:109:b:211:22ff:fe87:6745)",
    "ipv4_subnet": "子网掩码地址 (例如:10.0.0.4, 最大范围 : 255.255.255.254), 且不能以 '0' 作为起始",
    "ipv4_default": "默认网关地址 (例如:10.0.0.4, 最大范围 : 255.255.255.255), 且不能以 '0' 作为起始",
    "ipv6_addr": "指定一个固定的 IPv6 地址并配置给所选的界面",
    "ipv6_subnet": "子网掩码前缀长度数值范围为 0 到 128.",
    "ipv6_default": "指定 v6 默认网关作为 IPv6 设置",
    "vlan_id": "VLAN ID 数值范围介于 2 到 4094. VLAN ID 0, 1, 4095 为保留数值,不可使用",
    "vlan_priority": "VLAN 优先权数值介于0 到 7 之间",
    "user_name": "用户名应为字母数字且不能有空白,不能以数字为开头且最多支持16个字符",
    "mail_id": "电子信箱 Id (例如:xxx@yyy.com)",
    "ldap_ip": "IP 地址 (例如:10.0.0.4, Max range : 255.255.255.254), 不应该以 '0' 作为起始。支持 IPV4 和 IPV6 格式",
    "ldap_port": "端口号应该介于 1 到 65535 之间 (端口号应为数字).默认端口号为 389. 默认的端口号(安全连线)为 636",
    "ldap_bind_dn": "绑定 DN 是一个字符串为 4 到 64 个字母数字的字符。且不能以数字作为起始字符。例如:cn=manager,ou=login, dc=domain,dc=com",
    "ldap_pass": "密码应该要包含 (最小 1 且最大 48) 字符不含空白",
    "ldap_search_base": "搜索基点是一个字符串且由字母数字组成。不应由数字作为起始。例如:ou=login, dc=domain,dc=com",
    "active_dir_domain_name": "指定一个网域名称给用户。例如:MyDomain.com",
    //	"active_dir_timeout" : "Timeout value should be between 15 and 300 seconds (only numbers supported). Default Time out value is 120 seconds",
    "active_dir_secret_user": "用户名为一个字母数字组成的字符串,由数字作为起始且不含任何特殊字符如 ',/.:()|=+<>?& $#'",
    "active_dir_secret_password": "密码至少要由六个字符组成且不能含有空白",
    "active_dir_ip": "服务器 IP 地址 (例如:10.0.0.4, 最大范围 : 255.255.255.254), 不应以 '0' 作为起始。支持 IPV4 和 IPV6 格式。3个服务器的 IP 地址不应相同",
    "active_group_name": "用户名应该由字母数字组成不含空白,不应由数字作起始并最多支持64个字符",
    "ldap_group_name": "用户名称该由字母数字组成不含空白,不应由数字作起始并最多支持255个字符",
    "active_group_domain": "角色群组网域名称应该由字母数字组成不含空白,不应由数字作起始并最多支持255个字符。例如:megatrends.com",
    "ldap_group_search_base": "角色群组搜索基点名称应该由字母数字组成不含空白,不应由数字作起始并最多支持255个字符。例如:dc=domain",
    "user_password": "用户密码不应为空, 根据所选的设定其最多可包含 16 到 20 字节",
    "remote_server_pass": "密码应该包含 (至少 1 且最多 32) 字符不含空白",
    "remote_server_path": "源地址来存储视频 (例如:'\\home\\share'). 不允许特别字符如 '<', '>', ':', '*', '|', '.', '?'",
    "ssh_key_browse": "浏览 SSH 秘钥(*.pub)",
    "ssl_key_browse": "浏览 for 私钥(.pem)",
    "ssl_cert_browse": "浏览凭证(.pem)",
    "browse_firmware": "浏览固件(.ima)",
    "firmware_source_path": "输入完整的源路径(包含镜像名称)到其在服务器地址",
    "server_retry_count": "固件传输失败重试数目。范围介于 1 到 15",

    //TITLE HELP STRINGS
    "more": "更多 ...",
    "video_recording_help": "选择列出的事件触发自动录像",
    "services_help": "此页显示 BMC 中运行的服务的列表",
    "users_help": "本页显示目前配置的用户及其权限",
    "delete_user": "请再次按下删除的图示来确认删除用户",
    "ssl_cert_view_help": "本页显示已上传 SSL 凭证的细节",
    "ssl_cert_upload_help": "本页用来生成或是上传 SSL 凭证",
    "smtp_help": "本页用以配置 SMTP 设置",
    "date_time_help": "本页用来配置日期&时间或是 NTP 服务设置",
    "log_help": "本页用来配置系统及审计日志设置",
    "active_dir_help": "本页用来配置活动目录设置",
    "ldap_help": "本页用以配置 LDAP/E-Directory 设置",
    "network_settings_help": "本页用以配置可用的 LAN Channel 网络设置",
    "network_bond_help": "本页用来配置网络界面之绑定配置",
    "network_link_help": "本页用来配置可用的网络界面之网络连接设置",
    "bios_info_help": "此画面用以显示 BIOS 信息",
    "power_settings_help": "此画面用以配置电源设置",
    "boot_order_help": "此画面用以更改 Boot Order",
    "advanced_settigns_help": "用来观看高级 BIOS 设置的设置",
    "ldap_users_help": "本页用来显示已配置的 LDAP  用户群组以及其权限",
    "ldap_users_add_limitaion": "服务器上的 LDAP 用户最多可配置的数量为 5 位",
    "ad_users_add_limitaion": "服务器上的活动目录用户最多可配置的数量为 5 位",
    "users_add_limitation": "服务器只提供 10 位用户可供配置",
    "active_directory_users_help": "本页用来显示已配置的活动目录用户群组以及其权限",

    //FETCHING DATA FROM SERVER STRINGS
    "fetch_model": "获取模式",

    //SAVE SUCCESS STRINGS
    "success": "保存成功",
    "successfully": "成功",
    "delete_success": "删除成功",
    "uploaded": "已上传",

    "user_add_saved_success": "添加用户成功",
    //	"ldap_user_add_succes" : "LDAP User Added Successfully",
    "add_succes": "添加成功",
    "ldap_user": "LDAP 用户",
    "ad_user": "活动目录用户",
    "new": "添加",
    "edit": "已修改",

    //ERROR STRINGS
    "fetch_error": "获取时发生错误",
    "save_error": "保存时发生错误",
    "delete_error": "删除时发生错误",
    "server": "来自服务器",
    "ntp_sync_error": "与 NTP 服务器同步时发生暂时性的错误!",
    "remote_mount_failure": "挂载远程分享发生暂时性的错误!",
    "prepare_flash_error": "在准备固件更新时发生错误,请重新登入并重新操作一次",

    //WARNING STRINGS
    "no_users_fetched": "没有任何的用户配置。请点击增加用户来配置一个新的用户",

    //INFORMATION STRINGS
    "no_logs": "没有任何日志",
    "no_audit_log": "没有任何审计日志",
    "no_video_log": "没有任何视频日志",
    "no_event_log": "没有任何事件日志",

    //EVENT DESCRIPTION STRINGS
    "lower_non_critical_going_low": "低非临界 - 变得低",
    "lower_non_critical_going_high": "低非临界 - 变得高",
    "lower_critical_going_low": "低临界 - 变得低",
    "lower_critical_going_high": "低临界 - 变得高",
    "lower_non_recoverable_going_low": "低不可恢复 - 变得低",
    "lower_non_recoverable_going_high": "低不可恢复 - 变得高",
    "upper_non-critical_going_low": "高非临界 - 变得低",
    "upper_non_critical_going_high": "高非临界 - 变得高",
    "upper_critical_going_low": "高临界 - 变得低",
    "upper_critical_going_high": "高临界 - 变得高",
    "upper_non_recoverable_going_low": "高不可恢复 - 变得低",
    "upper_non_recoverable_going_high": "高不可恢复 - 变得高",

    "transition_to_idle": '转至空闲(Idle)',
    "transition_to_active": "转至活动(Active)",
    "transition_to_busy": "转至忙碌(Busy)",

    "state_deasserted": "状态未声明",
    "state_asserted": "状态声明",

    "predictive_failure_deasserted": "预测失败的未声明",
    "predictive_failure_asserted": "预测失败的声明",

    "limit_not_exceeded": "权限没有超出",
    "limit_exceeded": "权限超出",

    "performance_met": "性能满足",
    "performance_lags": "性能滞后",

    "transition_to_ok": "转换成正常(OK)",
    "transition_to_non_critical_from_ok": "从正常(OK)转换成非临界",
    "transition_to_critical_from_less_severe": "从不严重转换成临界",
    "transition_to_non_recoverable_from_less_severe": "从不严重转换成不可恢复",
    "transition_to_non_critical_from_more_severe": "从更严重转换成非临界",
    "transition_to_critical_from_non_recoverable": "从不可恢复转换成临界",
    "transition_to_non_recoverable": "转成不可恢复",
    "monitor": "监视器",
    "informational": "信息",

    "device_removed_device_absent": "装置移除 / 装置空缺",
    "device_inserted_device_present": "装置插入 / 装置在位",

    "device_disabled": "装置禁用",
    "device_enabled": "装置启用",

    "transition_to_running": "转换成运行中(Running)",
    "transition_to_in_test": "转换成测试中(In Test)",
    "transition_to_power_off": "转换成关机(Power Off)",
    "transition_to_on_line": "转换成上线(On Line)",
    "transition_to_off_line": "转换成离线(Off Line)",
    "transition_to_off_duty": "转换成下班(Off Duty)",
    "transition_to_degraded": "转换成降级(Degraded)",
    "transition_to_power_save": "转换成省电(Power Save)",
    "install_error": "安装错误",

    "fully_redundant_redundancy_regained": "完全冗余(冗余恢复)",
    "redundancy_lost": "冗余丢失",
    "redundancy_degraded": "冗余下降",
    "non_redundant_sufficient_resources_from_redundant": "非冗余: 从冗余足够资源",
    "non_redundant_sufficient_resources_from_insufficient_resources": "非冗余: 从不足资源充足的资源",
    "non_redundant_insufficient_resources": "非冗余: 资源不足",
    "redundancy_degraded_from_fully_redundant": "冗余程度从完全冗余降级",
    "redundancy_degraded_from_non_redundant": "冗余程度从非冗余降级",

    "d0_power_state": "D0 电源状态",
    "d1_power_state": "D1 电源状态",
    "d2_power_state": "D2 电源状态",
    "d3_power_state": "D3 电源状态",


    "temperature": "温度",
    "voltage": "电压",
    "current": "电流",
    "fan": "风扇",

    "general_chassis_intrusion": "机箱入侵检测",
    "drive_bay_intrusion": "驱动器托盘指令",
    "io_card_area_intrusion": "I/O 卡区域指令",
    "processor_area_intrusion": "处理器区域指令",
    "lan_leash_lost": "LAN 释放丢失 (系统未接上 LAN)",
    "unauthorized_dock": "未授权的插槽",
    "fan_area_intrusion": "风扇区域指令",

    "secure_mode_violation_attempt": "安全模式违规的尝试",
    "pre_boot_password_violation_user_password": "预引导密码违规 - 用户密码",
    "pre_boot_password_violation_setup_password": "预引导密码违规尝试 - 安装密码",
    "pre_boot_password_violation_network_boot_password": "预引导密码违规 - 网络启动密码",
    "other_pre_boot_password_violation": "其他预引导密码违规",
    "out_of_band_password_violation": "带外存取密码违规",

    "ierr": "IERR",
    "thermal_trip": "极限温度",
    "frb1_bist_failure": "FRB1/BIST 失败",
    "frb2_hang_in_post_faliure": "FRB2/Hang 在 POST 失败",
    "frb3_processor_startup_failure": "FRB3/处理器启动/初始化失败",
    "configuration_error_dmi": "配置错误 (DMI)",
    "smbios_uncorrectable_error": "SM BIOS 不可修正 CPU-complex 错误",
    "processor_presence_detected": "侦测到处理器存在",
    "Processor_disabled": "禁用处理器",
    "terminator_presence_detected": "侦测到中止存在",
    "processor_automatically_throttled": "处理器自动调节",
    "machine_check_exception": "Machine Check Exception",
    "correctable_machine_check_error": "可修正的机器检查错误",

    "presence_detected": "侦测到存在",
    "power_supply_failure_detected": "侦测到电源供应失败",
    "power_supply_input_lost_ac_or_dc": "电源供应输入丢失 (AC/DC)",
    "power_supply_input_lost_or_out_of_Range": "丢失电源供应输入或超出范围",
    "power_supply_input_out_of_range_but_present": "存在电源供应输入但超出范围",

    "power_off": "电源关闭 / 切断电源",
    "power_cycle": "电源循环",
    "power_down_240kva": "240VA 电源关闭",
    "interlock_power_down": "Interlock 电源关闭",
    "power_input_lost": "丢失 AC/ 输入电源丢失",
    "soft_power_control_failure": "软电源控制器失败",
    "power_unit_failure_detected": "侦测到电源单元故障",
    "predictive_failure": "可预测的故障",

    "correctable_ecc": "可修正 ECC",
    "uncorrectable_ecc": "不可修正 ECC",
    "parity": "奇偶校验",
    "memory_scrub_failure": "内存擦除失败",
    "memory_device_disabled": "内存设备已禁用",
    "correctable_ecc_logging_limit_reached": "可修正的 ECC 日志记录已满",
    "spare": "空闲的",
    "memory_automatically_throttled": "内存自动调节",
    "critical_overtemperature": "临界过热",

    "drive_presence": "驱动存在",
    "drive_fault": "驱动错误",
    "hot_spare": "热备份",
    "consistency_or_parity_check_in_progress": "持续性检测/同质性检测进行中",
    "in_critical_array": "在临界阵列",
    "in_failed_array": "在故障阵列",
    "rebuild_or_remap_in_progress": "重建/映射进行中",
    "rebuild_or_remap_aborted": "重建/映射中止",

    "unspecified": "未指定",
    "no_system_memory": "没有任何实体的系统内存安装于系统中",
    "no_usable_system_memory": "没有任何可用的系统内存,所有已安装的系统内存发生了不可恢复的故障",
    "unrecoverable_hard_disk": "不可恢复的硬盘/ATAPI/IDE设备故障",
    "unrecoverable_system_board_failure": "不可恢复的主板故障",
    "unrecoverable_diskette_subsystem_failure": "不可恢复的软盘子系统故障",
    "unrecoverable_hard_disk_controller_failure": "不可恢复的硬盘驱动故障",
    "unrecoverable_ps_2_or_usb_keyboard_failure": "不可恢复的 PS/2 或 USB 键盘故障",
    "removable_boot_media_not_found": "找不到可移动引导媒体",
    "unrecoverable_video_controller_failure": "不可恢复的视频控制器故障",
    "no_video_device_detected": "没有侦测到任何的视频设备",
    "firmware_bios_rom_corruption_detected": "侦测到固件 (BIOS) 镜像损毁",
    "cpu_voltage_mismatch": "CPU 电压不匹配 (处理器分享信息有关于供应电源与需求电压不匹配)",
    "cpu_speed_matching_failure": "CPU 速度匹配失败",

    "memory_initialization": "内存初始化",
    "hard_disk_initialization": "硬盘初始化",
    "secondary_processor_initialization": "副处理器初始化",
    "user_authentication": "用户认证",
    "user_initiated_system_setup": "用户初始化于系统安装",
    "usb_resource_configuration": "USB 资源配置",
    "pci_resource_configuration": "PCI 资源配置",
    "option_rom_initialization": "可选的 ROM 初始化",
    "video_initialization": "视频初始化",
    "cache_initialization": "快取初始化",
    "sm_bus_initialization": "SM 总线初始化",
    "keyboard_controller_initialization": "键盘控制初始化",
    "embedded_controller_initialization": "嵌入式控制/管理控制初始化",
    "docking_station_attachment": "Docking station 附件",
    "enabling_docking_station": "启用 Docking station",
    "docking_station_ejection": "弹出 Docking station",
    "disabling_docking_station": "禁用 Docking station",
    "calling_os_wake_up": "调用操作系统唤醒矢量",
    "starting_os_boot_process": "启动操作系统引导进程",
    "baseboard_initialization": "机板或主板初始化",
    "reserved": "保留",
    "floppy_initialization": "软盘驱动器初始化",
    "keyboard_test": "键盘测试",
    "pointing_device_test": "指向设备测试",
    "primary_processor_initialization": "主要处理器初始化",

    "error": "错误",
    "hang": "挂起",
    "progress": "进程",

    "correctable_memory_error_logging_disabled": "禁用可修正的内存错误日志记录",
    "event_type_logging_disabled": "禁用事件 \"类型\" 日志",
    "log_area_reset": "日志区重置/清除",
    "all_event_logging_disabled": "禁用所有事件日志",
    "sel_full": "SEL 栏位已满",
    "sel_almost_full": "SEL 栏位几乎已满",
    "correctable_machine_check_error_logging_disabled": "禁用可修正机器检查错误日志",

    "bios_watchdog_reset": "BIOS 看门狗重置",
    "os_watchdog_reset": "系统看门狗重置",
    "os_watchdog_shutdown": "系统看门狗关闭",
    "os_watchdog_power_down": "系统看门狗电源关闭",
    "os_watchdog_power_cycle": "系统W看门狗电源循环",
    "os_watchdog_nmi": "系统看门狗 NMI",
    "os_watchdog_expired": "系统看门狗过期",
    "os_watchdog_pre_timeout_interrupt": "系统看门狗预超时中断, non-NMI",

    "system_reconfigured": "系统重配置",
    "oem_system_boot_event": "OEM 系统启动事件",
    "undetermined_system_hardware_failure": "无法定义的系统硬件故障",
    "entry_added_to_auxiliary_log": "添加栏位到辅助日志",
    "pef_action": "PEF 动作",
    "timestamp_clock_sync": "时戳时钟同步",

    "front_panel_nmi": "NMI 前控制板",
    "bus_timeout": "总线超时",
    "io_channel_check_nmi": "I/O 通道检查 NMI",
    "software_nmi": "软 NMI",
    "pci_perr": "PCI PERR",
    "pci_serr": "PCI SERR",
    "eisa_fail_safe_timeout": "EISA 防故障超时",
    "bus_correctable_error": "总线可修正错误",
    "bus_uncorrectable_error": "总线不可修正错误",
    "fatal_nmi": "NMI 致命错误",
    "bus_fatal_error": "总线致命错误",
    "bus_degraded": "总线降级",

    "power_button_pressed": "已按下电源按钮",
    "sleep_button_pressed": "已按下休眠按钮",
    "reset_button_pressed": "已按下重置按钮",
    "fru_latch_open": "FRU 锁存器打开",
    "fru_service_request_button": "FRU 服务请求按钮",

    "cable_is_connected": "电缆/互连已连接",
    "configuration_error": "配置错误",

    "initiated_by_power_up": "由于开机所以已初始化",
    "initiated_by_hard_reset": "由于硬复位所以已初始化",
    "initiated_by_warm_reset": "由于热复位所以已初始化",
    "user_requested_pxe_boot": "用户要求 PXE 引导",
    "automatic_boot_to_diagnostic": "自动引导进行诊断",
    "os_or_run_time_hard_reset": "系统/运行时间软初始化硬复位",
    "os_or_run_time_warm_reset": "系统/运行时间软初始化热复位",
    "system_restart": "系统重置",

    "no_bootable_media": "没有可启动的媒体",
    "non_bootable_diskette_left_in_drive": "不可开机的软盘留在驱动器中",
    "pxe_server_not_found": "找不到 PXE 服务器",
    "invalid_boot_sector": "无效的开机扇区",
    "timeout_waiting_for_user_selection_of_boot_source": "暂停以等待用户选择引导源",

    "a_boot_completed": "A: 引导完成",
    "c_boot_completed": "C: 引导完成",
    "pxe_boot_completed": "PXE 引导完成",
    "diagnostic_boot_completed": "诊断引导完成",
    "cd_rom_boot_completed": "CD-ROM 引导完成",
    "rom_boot_completed": "ROM 引导完成",
    "boot_completed_boot_device_not_specified": "引导完成 -未指定引导设备",

    "critical_stop_during_os_initialization": "临界中止于操作系统读取中/初始化",
    "run_time_critical_stop": "运行时间临界停止",
    "os_graceful_stop": "系统正常中止",
    "os_graceful_shutdown": "系统正常关机",
    "soft_shutdown_initiated_by_pef": "软关机由 PEF 启动",
    "agent_not_responding": "代理没有回应",

    "fault_status_asserted": "错误状态已断言",
    "identify_status_asserted": "标示状态已断言",
    "slot_or_connector_installed_or_attached": "插槽/连接器设备已安装/已附加",
    "slot_or_connector_ready_for_device_installation": "插槽/连接器已准备好进行设备安装",
    "slot_or_connector_ready_for_device_removal": "插槽/连接器准备好进行设备卸载",
    "slot_power_is_off": "插槽电源已关闭",
    "slot_or_connector_device_removal_request": "插槽/连接器设备卸载请求",
    "interlock_asserted": "互锁已断言",
    "slot_is_disabled": "禁用插槽",
    "slot_holds_spare_device": "插槽拥有备用设备",

    "s0_or_g0_working": "S0/G0 “正在工作”",
    "s1_sleeping_with_system_hw_processor_context_maintained": "S1 “系统硬件的睡眠 & 处理器文件已维护”",
    "s2_sleeping_processor_context_lost": "S2 “休眠, 处理器文件丢失”",
    "s3_sleeping_processor_hw_context_lost_memory_retained": "S3 “休眠, 处理器 & 硬件文件丢失, 内存保留”",
    "s4_non_volatile_sleep_Suspend_to_disk": "S4 “非易失性休眠/中止并存到硬盘中”",
    "s5_or_g2 _soft_off": "S5/G2 “软关机”",
    "s4_or_s5_soft_off": "S4/S5 软关机",
    "g3-or_mechanical_off": "G3 / 机械性关闭",
    "sleeping_in_s1_s2_or_s3": "休眠在 S1、 S2 或 S3",
    "g1_sleeping": "G1 休眠",
    "s5_entered_by_override": "S5 由覆盖输入",
    "legacy_on_state": "留下状态",
    "legacy_off_state": "丢失状态",
    "unknown": "未知",

    "timer_expired": "计时器超时",
    "hard_reset": "硬复位",
    "power_down": "关机",
    "timer_interrupt": "计时器中断",

    "platform_generated_page": "平台产生的页面",
    "platform_generated_lan_alert": "平台产生的 LAN 警报",
    "platform_event_trap_generated": "平台产生的事件 Trap",
    "platform_generated_snmp_trap_oem_format": "平台产生的 SNMP Trap, OEM 格式",

    "entity_present": "实体存在",
    "entity_absent": "实体不存在",
    "entity_disabled": "实体禁用",

    "lan_heartbeat_lost": "LAN 脉搏丢失",
    "lan_heartbeat": "LAN 脉搏",

    "sensor_access_degraded_or_unavailable": "传感器访问降级或不可用",
    "controller_access_degraded_or_unavailable": "控制器访问降级或不可用",
    "management_controller_off_line": "管理控制器离线",
    "management_controller_unavailable": "管理控制器不可用",
    "sensor_failure": "传感器故障",
    "fru_failure": "FRU 故障",

    "battery_low": "电量不足",
    "battery_failed": "电池故障",
    "battery_presence_detected": "探测到电池存在",

    "session_activated": "会话活动中",
    "session_deactivated": "会话未活动",
    "_nvalid_username_or_password": "无效的用户名或密码",
    "invalid_password_disable": "禁用无效的密码",
    "missing_username": "请输入用户名。",
    "missing_password": "请输入密码。",
    "user_locked": "该用户已被锁定。",
    "invalide_password": "输入的密码不正确。",
    "invalide_username": "输入的用户名不正确。",
    //sugon_Song_tapd1015370_20190216
    "username_password_not_match": "用户名或密码不正确。",
    "invalide_password_expiry": "用户的密码已过有效期。",
    "login_error": "登录失败，稍后重试。",
    "user_password_lock_fail_count": "失败次数",
    "user_password_lock_allow_count": "允许次数",
    "user_password_lock_unlock": "用户锁定",
    "user_password_lock_fail": "重试锁定",
    "pw_reset_confirm": "点击 OK 如果你想要进行重置用户密码。",
    "pw_reset_success": "新密码将会传送给之前配置的电子邮件信箱",
    "pw_reset_smtp_disabled": "SMTP 服务器禁用此通道",
    "pw_reset_smtp_fail_1": "SMTP 服务器不支持此认证类别",
    "pw_reset_smtp_fail_2": "SMTP 服务器认证错误",
    "pw_reset_smtp_fail_3": "无法连接上 SMTP 服务器",
    "pw_reset_email_fail_1": "该用户不存在",
    "pw_reset_email_fail_2": "用户未配置电子邮件信箱 ID",
    "pw_reset_fail": "无法重置该用户的密码",
    "pw_reset_fail_email": "无法生成新的密码发送到配置的电子邮件 ID",


    "hardware_change_detected": "侦测到硬件更改",
    "firmware_or_software_change_detected": "侦测到固件/软件更改",
    "hardware_incompatibility_detected": "侦测到硬件不兼容",
    "firmware_or_software_incompatibility_detected": "侦测到固件/软件不兼容",
    "invalid_or_unsupported_hardware_version": "无效或不支持的硬件版本",
    "invalid_or_unsupported_firmware_or_software_version": "无效或不支持的固件/软件版本",
    "hardware_change_detected_was_successful": "侦测到硬件更改成功",
    "firmware_or_software_change_detected_was_successful": "侦测到固件/软件更改成功",

    "fru_not_installed": "FRU 未安装",
    "fru_inactive": "FRU 处于非活动状态",
    "fru_activation_requested": "FRU 启动要求",
    "fru_activation_in_progress": "FRU 启动进行中",
    "fru_active": "FRU 已启动",
    "fru_deactivation_requested": "FRU 停用要求",
    "fru_deactivation_in_progress": "FRU 停用进行中",
    "fru_communication_lost": "FRU 失去连线",

    "transition_to_m0": "转换至 M0",
    "transition_to_m1": "转换至 M1",
    "transition_to_m2": "转换至 M2",
    "transition_to_m3": "转换至 M3",
    "transition_to_m4": "转换至 M4",
    "transition_to_m5": "转换至 M5",
    "transition_to_m6": "转换至 M6",
    "transition_to_m7": "转换至 M7",

    "ipmb_a_disabled_ipmb_b_disabled": "IPMB-A 禁用, IPMB-B 禁用",
    "ipmb_a_enabled_ipmb_b_disabled": "IPMB-A 启用, IPMB-B 禁用",
    "ipmb_a_disabled_ipmb_b_enabled": "IPMB-A 禁用, IPMB-B 启用",
    "ipmb_a_nabled_ipmb-b_enabled": "IPMB-A 启用, IPMP-B 启用",

    "module_handle_closed": "模块控制关闭",
    "module_handle_opened": "模块控制打开",
    "quiesced": "停顿",

    "oem_specific": "OEM 指定",

    "media_refresh_warning": "虚拟媒体已连接。请问是否确认要更新页面并中断已连结的虚拟媒体?",
    "media_nav_alert": "导览被禁用由于虚拟媒体已连接。请中止连接媒体并重试。",

    //SENSOR TYPES STRING
    "physical_security": "物理安全 (机箱干扰)",
    "platform_security": "平台安全违规尝试",
    "processor": "处理器",
    "power_supply": "电源供应器",
    "power_unit": "电源单元",
    "cooling_device": "冷却设备",
    "other_units_based_sensor": "其他基于单元的传感器",
    "memory": "内存",
    "drive_slot": "驱动插槽 (Bay)",
    "post_memory_resize": "POST 内存调整",
    "bios_post_progress": "BIOS POST 进程",
    "event_logging_disabled": "禁用事件日志",
    "watchdog_1": "看门狗 1",
    "system_event": "系统事件",
    "critical_interrupt": "临界中断",
    "button_or_switch": "按钮/切换",
    "module_or_board": "模块/板子",
    "microcontroller_or_coprocessor": "微控制器/副处理器",
    "add_in_card": "插卡",
    "chassis": "机箱",
    "chip_set": "芯片集",
    "other_fru": "其他 FRU",
    "cable_or_interconnect": "电缆/互连",
    "terminator": "终端",
    "system_boot_or_restart_initiated": "系统启动/重启初始化",
    "boot_error": "启动错误",
    "os_boot": "系统启动",
    "os_stop_or_shutdown": "系统停止/关机",
    "slot_or_connector": "插槽/连接器",
    "system_acpi_power_state": "系统 ACPI 电源状态",
    "watchdog_2": "看门狗 2",
    "platform_alert": "平台警报",
    "entity_presence": "实体存在",
    "monitor_asic_or_ic": "监视器 ASIC/IC",
    "lan": "LAN",
    "management_subsystem_health": "管理子系统运行状况",
    "battery": "电池",
    "session_audit": "会话审计",
    "version_change": "版本改变",
    "fru_state": "FRU 状态",
    "fru_hot_swap": "FRU 热插拔",
    "ipmb_0_status": "IPMB-0 状态",
    "module_hot_swap": "模块热插拔",

    //SENSOR UNIT STRINGS
    "deg_c": "&摄氏温度;C",
    "deg_f": "&华氏温度;F",
    "deg_k": "&开氏温度;K",
    "volts": "伏特 (volts)",
    "amps": "安培 (amps)",
    "watts": "瓦特 (watts)",
    "joules": "焦耳 (joules)",
    "coulombs": "库伦 (coulombs)",
    "va": "VA",
    "nits": "尼特 (nits)",
    "lumen": "流明 (lumen)",
    "lux": "勒克司 (lux)",
    "candela": "坎德拉 (Candela)",
    "kpa": "千帕 (kPa)",
    "psi": "PSI",
    "newton": "牛顿(Newton)",
    "cfm": "CFM",
    "rpm": "RPM",
    "hz": "赫兹 (Hz)",
    "micro_second": "微秒 (microsecond)",
    "milli_second": "毫秒 (millisecond)",
    "second": "秒",
    "minute": "分",
    "hour": "时",
    "day": "日",
    "week": "周",
    "mil": "密耳 (mil)",
    "inches": "英寸 (inches)",
    "feet": "英尺 (feet)",
    "cu_in": "立方英寸 (cu in)",
    "cu_feet": "立方英尺 (cu feet)",
    "mm": "毫米 (mm)",
    "cm": "厘米 (cm)",
    "m": "米 (m)",
    "cu_cm": "立方厘米 (cu cm)",
    "cu_m": "立方米 (cu m)",
    "liters": "公升 (liters)",
    "fluid_ounce": "液体盎司 (fluid ounce)",
    "radians": "弧度 (radians)",
    "steradians": "立体弧度 (steradians)",
    "revolutions": "转数 (revolutions)",
    "cycles": "周期 (cycles)",
    "gravities": "重力 (gravities)",
    "ounce": "盎司 (ounce)",
    "pound": "磅 (pound)",
    "ft_lb": "英尺-磅 (ft-lb)",
    "oz_in": "盎司-英寸 (oz-in)",
    "gauss": "高斯 (gauss)",
    "gilberts": "吉伯 (gilberts)",
    "henry": "亨利 (henry)",
    "millihenry": "毫亨 (millihenry)",
    "farad": "法拉 (farad)",
    "microfarad": "微法拉 (microfarad)",
    "ohms": "欧姆 (ohms)",
    "siemens": "西门子 (siemens)",
    "mole": "摩尔 (mole)",
    "becquerel": "贝可勒尔 (becquerel)",
    "ppm": "PPM (parts/million)",
    "decibels": "分贝 (Decibels)",
    "dba": "DbA",
    "dbc": "DbC",
    "gray": "格雷 (gray)",
    "sievert": "西弗特 (sievert)",
    "color_temp ": "色温 (color temp &deg;K)",
    "bit": "比特",
    "kilobit": "千比特",
    "megabit": "兆比特",
    "gigabit": "千兆比特",
    "byte": "字节",
    "kilobyte": "千字节",
    "megabyte": "兆字节",
    "gigabyte": "千兆字节",
    "word_data": "字 (data)",
    "dword": "双字节",
    "qword": "四字节",
    "line": "line",
    "hit": "命中",
    "miss": "失误",
    "retry": "重试",
    "reset": "重置",
    "overrun_or_overflow": "过载运行/超限",
    "underrun": "低载运行",
    "collision": "碰撞",
    "packets": "封包",
    "messages": "消息",
    "characters": "字符",
    "correctable_error": "可修正的错误",
    "uncorrectable_error": "不可修正的错误",

    //Privilege Error Message
    "non_privilege_user_error_message": "你没有权限访问此栏目。",
    "login_error_code_8001": "无权限用户",
    "disable_refresh": "本页面不允许更新。",

    "c_overview": "系统摘要",
    //资产信息
    "c_asset": "资产信息",
    //硬件监控
    "c_monitor": "硬件监控",
    "c_systemAbstract": "系统摘要",
    "c_systemInfo": "系统信息",
    "c_dmiInfo": "DMI 信息",
    "c_realTimeMonitor": "实时监控",
    "c_sensorInfo": "传感器信息",
    "c_historical": "历史记录",
    "c_longRangeControl": "远程控制",
    "c_remoteControl": "控制台重定向",
    "c_powerControl": "开关机控制",
    "c_serverSelection": "服务器定位",
    "c_mediaRedirection": "介质重定向",
    "c_powerHotStandby": "电源备份策略",
    "c_powerPolicy": "功耗封顶",
    "c_biosConifg": "BIOS 设置",
    "c_powerRestoreControl": "系统掉电恢复策略",
    "c_firstBootDevice": "系统启动顺序",
    "c_powerButtonLock": "前面板锁定",
    "c_coolingPolicy": "散热策略",
    "c_network": "BMC 网络",
    "c_SNMPv": "SNMP 设定",

    "c_logReport": "日志和报告",
    "c_logSEL": "传感器事件日志",
    "c_AuditLog": "审计日志",
    "c_SystemLog": "系统日志",
    "c_solLog": "SOL 日志",
    "c_faultDiagnosis": "故障诊断",
    "c_troubleshooting": "服务重启",
    "c_BSOD": "BSOD",
    "c_BootSelfInspection": "开机自检代码",
    "c_BlackBox": "服务器黑匣子",
    "c_SystemMaintenance": "系统维护",
    "c_BMCFirmwareUpgrade": "BMC 固件升级",
    "c_BIOSFirmwareUpgrade": "BIOS 固件升级",
    "c_CPLDUpgrade": "CPLD 升级",
    "c_PSUUpgrade": "PSU 升级",
    "c_RestoreFactorySettings": "恢复出厂设置",
    "c_Administrator": "系统管理员",
    "c_SystemSettings": "系统设置",
    "c_raid_management": "RAID管理",
    "c_storage_system": "存储系统",
    "c_faultScreenshot": "故障截屏",
    "c_sasit_management": "SAS IT 管理",
    "c_logs_infor": "日志查询",
    "c_logs_settings": "日志设置",
    "c_power_energy": "电源与能耗",
    "c_system_admin": "系统管理员",
    "c_backup_restore_config": "备份/恢复配置",
    "c_firmware_update": "固件更新",

    //二级菜单名称
    "c_date_time": "日期 & 时间",
    "c_external_userservice": "外部用户服务",
    "c_alarm_settings": "告警设置",
    "c_manage_licence": "管理授权",
    "c_media_redir_settings": "媒体重定向",
    "c_network_settings": "网络设置",
    "c_services": "服务",
    "c_user_mngt": "用户/用户组",
    "c_safe_settings": "安全设置",


    //登录页多语化切换
    "lg_language": "English", //不可修改
    "lg_language_tag": "zh-cn", //用于判断当前多语化，不可修改

    "curCapacity": "当前容量 (字节)：",
    "maxCapacity": "最大容量(字节)：",
    "maxNumber": "最大数量：",

    "password_expiry_info": "用户密码已过期，请使用管理员账号登录并修改。",
    "password_is_expiry_please_modify": "密码已过期，请修改密码有效期；修改完毕后，请重新登录系统。",
    "modify_initial_password": "admin 用户当前使用默认密码，建议尽快修改。",
    "already_exist_session": "浏览器中已经存在相同会话。",

    "pass_greater_20_characters": "密码长度不能大于20个字符",

    "change_initial_user": "目前使用初始用户名和密码，建议尽快修改密码。",
});