define({
    "home": "主页",
    "settings": "BMC 设置",
    "parenttitle":"系统信息",
    "raid_management": "RAID 管理",
    "storage_system" : "存储系统",
    "title": "创建虚拟设备",
    "create_logical_device": "",
    "strongSuccessMsg": "保存!",
    "successMsg": "保存成功!",
    "strongFailureMsg": "",
    "failureMsg": "保存失败。",
    "create_logical_deviceraid_level": "RAID 等级",
    "create_logical_devicechoose_raid_levels": "选择 RAID 等级。",
    "create_logical_devicelogical_name": "逻辑名称",
    "create_logical_device_enter_the_virtual_device_name": "输入虚拟设备名称。",
    "create_logical_devicecapacity_gb": "容量 (GB)",
    "create_logical_device_enter_virtual_device_size": "输入虚拟设备大小。",
    "create_logical_deviceinitialization": "初始化",
    "create_logical_deviceno_initialization": "未初始化",
    "create_logical_devicequick_initialization": "快速初始化",
    "create_logical_devicefull_initialization": "完整初始化",
    "create_logical_deviceselect_initial_state": "选择初始化状态",
    "create_logical_devicestripe_size": "带宽",
    "create_logical_device256kb": "256KB",
    "create_logical_deviceselect_stripe_size": "选择带宽",
    "create_logical_deviceread_policy": "读取机制",
    "create_logical_deviceno_read_ahead": "不提前读取",
    "create_logical_devicealways_read_ahead": "总提前读取",
    "create_logical_deviceselect_read_policy": "选择读取机制",
    "create_logical_devicewrite_policy": "写入机制",
    "create_logical_devicewrite_through": "直写",
    "create_logical_devicealways_write_back": "总是回写",
    "create_logical_devicewrite_back_with_bbu": "回写 BBU",
    "create_logical_deviceselect_write_policy": "选择写入机制",
    "create_logical_deviceio_policy": "IO 机制",
    "create_logical_devicedirect_io": "直接 IO",
    "create_logical_devicecache_io": "IO 快取",
    "create_logical_deviceselect_io_policy": "选择 IO 机制",
    "create_logical_deviceaccess_policy": "存取机制",
    "create_logical_devicereadwrite": "读\/写",
    "create_logical_deviceread_only": "只读",
    "create_logical_deviceblocked": "阻塞",
    "create_logical_deviceselect_access_policy": "选择存取机制",
    "create_logical_devicedisk_cache_policy": "硬盘快取机制",
    "create_logical_deviceunchanged": "未改变的",
    "create_logical_deviceenabled": "启用",
    "create_logical_devicedisabled": "禁用",
    "create_logical_deviceselect_disk_policy": "选择硬盘机制",
    "create_logical_deviceunconfigured_physical_drives": "物理驱动器配置",
    "create_logical_deviceselect_unconfigured_physical_device": "物理驱动器未配置",
    "saveLabel": "保存",
	"raid_levels_0":"RAID 0",
	"type_0": "HDD",
    "type_1": "SSD",
    "type_2": "SSM",
	"create_logical_device_ctrl_name": "选择控制器名称",
    "span_depth_err0":"输入有宽度深度",
    "span_depth_err1":"输入有效的每个阵列宽度具有的设备数量",
    "span_label1":"宽度深度",
    "span_label2":"每个阵列宽度具有的硬盘设备",
    "span_label3":"未配置的实体驱动",
    "create_span_err1":"已选的未配置驱动数目应该要与宽度数量乘上每一宽度具有的驱动个数相同",
    "span_label4":"选择实体装置",
    "span_label5":"宽度 Id",
    "create_span_err2":"请映射到适当的宽度 Id",
    "create_span_err3":"逻辑名称不应该为空",
    "create_span_err4":"容量不应该为空",
    "create_span_err5":"至少选择一个物理设备",
    "create_span_err6":"物理设备应该按照所选的 RAID 等级来配置",
    "create_logical_devicechoose_raid_ctrl": "选择RAID控制器名称。",
    "create_logical_device_enter_span_depth": " 输入宽度深度",
    "create_logical_device_enter_drives_per_span": " 输入每个阵列宽度的驱动",
    "create_logical_device_select_un_config_devices": "<strong>注意:</strong>选择的未配置驱动数目应该要与宽度数量乘上每一宽度具有的驱动个数相同。",
    "raidLevels_stripSize_notAvailable": "RAID级别和带宽不可用。",
    "minimum": "最小值为：",
    "maximum": "最大值为：",
    // ks_lz_20190123_tapdid_1014201++>>
    "prepare_create_virtual_disk":"正在创建虚拟设备，请耐心等待。", 
});
