define({
    "home": "主页",
    "maintenance": "系统维修",
    "title": "Dual 镜像配置",
    "dual_image_config": "",
    "strongSuccessMsg": "Dual 镜像配置已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "保存 Dual 镜像配置发生错误。",
    "failureMsg": "",
    "it_displays_the_firmware_version_of_images_1": "显示镜像-1的固件版本。",
    "it_displays_the_current_state_of_image_1":"显示镜像-1的当前状态" ,
    "it_displays_the_firmware_version_of_images_2": "显示镜像-2的固件版本。",
    "it_displays_the_current_state_of_image_2": "显示镜像-2的当前状态",
    "boot_image_to_be_booted_from_upon_reset": "镜像从复位后启动",
    "boot_imagehigher_firmware_version_": "更高版本的固件 ",
    "boot_imagelower_firmware_version": "较低版本的固件",
    "boot_imagemost_recently_updated_firmware_": "最近频繁更新的固件 ",
    "boot_imageleast_recently_updated_firmware": "最近很少更新的固件",
    "Check_this_option_to_boot_image_1_in_the_next_boot_up_process" : "选中此选项可启动镜像-1在下面启动过程中",
    "Check_this_option_to_boot_image_2_in_the_next_boot_up_process" : "选中此选项可启动镜像-2在下面启动过程中",
    "Check_this_option_to_boot_higher_firmware_version_image_in_the_next_boot_up_process" : "选中此选项以启动更高版本的固件镜像在下次启动过程中的 Dual 镜像中",
    "Check_this_option_to_boot_lower_firmware_version_image_in_the_next_boot_up_process" : "选中此选项以启动低版本的固件映像在下次启动过程中的 Dual 镜像中",
    "Check_this_option_to_boot_most_recently_updated_firmware_image_in_the_next_boot_up_process" : "选中此选项以启动最近频繁更新的固件映像在下次启动过程中的 Dual 镜像中",
    "Check_this_option_to_boot_least_recently_updated_firmware_image_in_the_next_boot_up_process" : "选中此选项以启动最近很少更新的固件映像在下次启动过程中的 Dual 镜像中",
    "saveLabel": "保存"
});
