define({
    "home": "主页",
    "settings": "BMC 设置",
    "platform_event_filters": "事件平台筛选",
    "title": "事件筛选",
    "event_filter_configuration":"事件筛选配置",
    "pef_id_": "PEF ID: ",
    "_enabled": " (启用)",
    "_disabled": " (禁用)",
    "_delete": " ( ~ )",
    "when_": "当 ",
    "switches_to_": "切换至",
    "any_severity": "任何严重程度",
    "new_monitor_state": "新监视状态",
    "new_information": "新信息",
    "normal_state": "一般状态",
    "noncritical_state": "非临界状态",
    "critical_state": "临界状态",
    "nonrecoverable_state": "不可恢复状态",
    "run_": "运行",
    "alert_1_": "警报 (1) ",
    "alert_2_": "警报 (2) ",
    "alert_3_": "警报 (3) ",
    "alert_4_": "警报 (4) ",
    "alert_5_": "警报 (5) ",
    "alert_6_": "警报 (6) ",
    "alert_7_": "警报 (7) ",
    "alert_8_": "警报 (8) ",
    "alert_9_": "警报 (9) ",
    "alert_10_": "警报 (10) ",
    "alert_11_": "警报 (11) ",
    "alert_12_": "警报 (12) ",
    "alert_13_": "警报 (13) ",
    "alert_14_": "警报 (14) ",
    "alert_15_": "警报 (15) ",
    "amp": "&amp;",
    "_thats_it_": " 无 ",
    "_power_down_system_": " 关闭系统 ",
    "_power_cycle_system_": " 系统电源循环 ",
    "_reset_system_": " 重启系统 ",
    "event_filters": "事件过滤器",
    "strongSuccessMsg": "保存!",
    "successMsg": "保存成功",
    "strongFailureMsg": "",
    "failureMsg": "我会尝试出错误的原因",
    "event_filtersenable_this_filter": "启用此过滤器",
    "event_filterscheck_the_option_enable_to_enable_the_pef_settings": "点击“启用”选项来启用 PEF 设置",
    "event_filtersevent_severity_to_trigger": "触发事件严重性",
    "event_filtersany_severity": "任何严重性",
    "event_filtersnew_monitor_state": "新监视状态",
    "event_filtersnew_information": "新信息",
    "event_filtersnormal_state": "正常状态",
    "event_filtersnoncritical_state": "非临界状态",
    "event_filterscritical_state": "临界状态",
    "event_filtersnonrecoverable_state": "不可恢复状态",
    "event_filterschoose_any_one_of_the_event_severity_from_the_dropdown_list": "从下拉式选单中选择任何一个事件严重性。",
    "event_filterspower_action": "电源动作",
    "event_filtersnone": "无",
    "event_filterspower_down": "关闭电源",
    "event_filterspower_cycle": "电源循环",
    "event_filtersreset_system": "重启系统",
    "event_filterschoose_power_action_to_be_either_power_down_power_reset_or_power_cycle_from_the_dropdown_list": "从下拉式选单中选择任一电源动作如关闭电源,重启或电源循环。",
    "event_filtersalert_policy_group_number": "警报策略群组号码",
    "event_filters1": "1",
    "event_filters2": "2",
    "event_filters3": "3",
    "event_filters4": "4",
    "event_filters5": "5",
    "event_filters6": "6",
    "event_filters7": "7",
    "event_filters8": "8",
    "event_filters9": "9",
    "event_filters10": "10",
    "event_filters11": "11",
    "event_filters12": "12",
    "event_filters13": "13",
    "event_filters14": "14",
    "event_filters15": "15",
    "event_filterschoose_configured_alert_policy_number_from_the_dropdown_list_strongnotestrong_alert_policy_can_be_configured_under_configurationpefalert_policy": "从下拉式选单中选取一个已配置的警报策略号码。 <strong>注意:<\/strong> 警报策略可以在配置->PEF->警报策略中进行配置。",
    "event_filtersraw_data": "原始数据",
    "event_filtersenable_this_option_to_enter_the_generator_id_with_raw_data": "启用此选项来输入生成 ID 和原始数据。",
    "event_filtersgenerator_id_1": "生成 ID 1",
    "event_filtersenter_the_raw_generator_id1_data_value": "输入原始生成 ID1 资料数值。",
    "event_filtersgenerator_id_2": "生成 ID 2",
    "event_filtersenter_the_raw_generator_id2_data_value_strongnotestrong_in_the_raw_data_field_to_specify_hexadecimal_value_prefix_the_value_with_0x": "输入原始生成 ID1 资料数值。  <strong>注意:<\/strong> 在原始数据中,指定为 16 进制而且前缀带有 '0x'。",
    "event_filtersgenerator_type": "产生类型",
    "event_filtersslave": "从设备",
    "event_filterssoftware": "软件",
    "event_filterschoose_the_event_generator_as_slave_address_if_event_is_generated_from_ipmb": "选择事件产生来作为从设备地址 - 如果事件由 IPMB 所产生。",
    "event_filtersslave_addresssoftware_id": "从设备地址\/软 ID",
    "event_filterschoose_system_software_id_if_event_is_generated_from_system_software": "选择系统软件 ID - 如果事件由 IPMB 所产生",
    "event_filterschannel_number": "通道编号",
    "event_filters0": "0",
    "event_filterschoose_the_particular_channel_number_through_which_the_event_message_is_received_over_choose_0_if_the_event_message_is_received_via_the_system_interface_primary_ipmb_or_internally_generated_by_the_bmc": "选择一个特定的通道编号通过事件信息的接收。如果事件信息由系统界面, 主要 IPMB 或由 BMC 内部产生,则选择“0”。",
    "event_filtersipmb_device_lun": "IPMB 设备 LUN",
    "event_filterschoose_the_corresponding_ipmb_device_lun_if_event_generated_by_ipmb": "如果事件由 IPMB 产生,选择对应的 IPMB 设备 LUN。",
    "event_filterssensor_type": "传感器类型",
    "event_filterstemperature": "温度",
    "event_filtersfan": "风扇",
    "event_filtersvoltage": "电压",
    "event_filtersdiscrete": "离散的",
    "event_filtersthe_type_of_sensor_that_will_trigger_the_event_filter_action": "传感器状态将会触动事件过滤器的动作。",
    "event_filterssensor_name": "传感器名称",
    "event_filterschoose_the_particular_sensor_from_the_sensor_list": "从传感器名单中选择一个特定的传感器。",
    "event_filtersevent_options": "事件选项",
    "event_filtersall_events": "所有事件",
    "event_filterschoose_event_option_to_be_either_all_events_or_sensor_specific_events": "选择事件选项为“所有事件”或“传感器特定事件”",
    "event_filtersevent_trigger": "事件触发",
    "event_filtersthis_field_is_used_to_give_eventreading_type_value_ulli_value_ranges_from_1_to_255liul": "此处用作提供事件\/可读类型数值。  <ul><li> 数值范围从 1 到 255。<\/li><\/ul>",
    "event_filtersevent_data_1_and_mask": "事件数据 1 和掩码",
    "event_filtersthis_field_is_used_to_indicate_wildcarded_or_compared_bits_ulli_value_ranges_from_0_to_255liul": "此处用作使用通配符或比较的位。 <ul><li> 数值范围从 0 到 255。<\/li><\/ul>",
    "event_filtersevent_data_1_compare_1": "事件数据 1 比较 1",
    "event_filtersthis_field_is_used_to_indicate_whether_each_bit_positions_comparison_is_an_exact_comparison_or_notbrulli_value_ranges_from_0_to_255liul": "此处用作指定任一位置的位是否进行比较。<br><ul><li> 数值范围从 1 到 255。<\/li><\/ul>",
    "event_filtersevent_data_1_compare_2": "事件数据 1 比较 2",
    "event_filtersevent_data_2_and_mask": "事件数据 2 和掩码",
    "event_filtersthis_field_is_similar_to_event_data_1_and_mask": "此处与事件数据 1 和掩码相同。",
    "event_filtersevent_data_2_compare_1": "事件数据 2 比较 1",
    "event_filtersthese_fields_are_similar_to_event_data_1_compare_1_and_event_data_1_compare_2_respectively": "此处分别与事件数据 1 比较 1 和事件数据 1 比较 2 相同",
    "event_filtersevent_data_2_compare_2": "事件数据 2 比较 2",
    "event_filtersevent_data_3_and_mask": "事件数据 3 和掩码",
    "event_filtersevent_data_3_compare_1": "事件数据 3 比较 1",
    "event_filtersevent_data_3_compare_2": "事件数据 3 比较 2",
    "event_filtersall_sensors": "所有的传感器",
    "event_filterssensor_events": "传感器事件",
    "deleteLabel": "删除",
    "saveLabel": "保存",

    "event_filtersentry_added_to_auxiliary_log": "条目添加到辅助日志",
    "event_filtersbus_correctable_error": "总线可纠正的错误",
    "event_filterssoftware_nmi": "软 NMI",
    "event_filtersslot_is_disabled": "禁用插槽",
    "event_filterscorrectable_ecc": "可修正 ECC",
    "event_filterstimer_interrupt": "计时器中断",
    "event_filtersslot_holds_spare_device": "插槽备用设备",
    "event_filterstransition_to_m0": "转换成 M0",
    "event_filterstimestamp_clock_synch": "时间戳时钟同步信号",
    "event_filtersos_watchdog_pretimeout_interrupt_nonnmi": "OS 看门狗预超时中断, non-NMI",
    "event_filtersthermal_trip": "极限温度",
    "event_filtersdiagnostic_boot_completed": "引导诊断完成",
    "event_filterstransition_to_m2": "转换到 M2",
    "event_filtersin_critical_array": "在关键阵列",
    "event_filtersmemory_device_disabled": "内存设备禁用",
    "event_filterscurrent": "目前",
    "event_filtersboot_completed__boot_device_not_specified": "启动完毕 - 启动装置未指定",
    "event_filtersmemory_scrub_failure": "内存抹除错误",
    "event_filtersc_boot_completed": "C: 引导完成",
    "event_filtersbus_degraded": "总线降级",
    "event_filtersinvalid_or_unsupported_firmware__software_version": "无效或不支持的固件/软件版本",
    "event_filtersos_watchdog_nmi": "OS 看门狗 NMI",
    "event_filterspresence_detected": "侦测到存在",
    "event_filterstransition_to_m7": "转换到 M7",
    "event_filtersipmba_enabled_ipmbb_disabled": "IPMB-A 启用, IPMB-B 禁用",
    "event_filtersinitiated_by_power_up": "已初始化",
    "event_filterstransition_to_m6": "转换到 M6",
    "event_filtersbios_watchdog_reset": "BIOS 看门狗重启",
    "event_filterssession_activated": "激活会话",
    "event_filtersslotconnector_device_installedattached": "插槽/连接器装置已安装/已附加",
    "event_filtersfan": "风扇",
    "event_filtersfan_device_removed_device_absent": "装置移除",
    "event_filtersfan_device_inserted_device_present": "装置插入/装置在位",
    "event_filters_hot_plug": "热插拔",
    "event_filtersbattery_presence_detected": "侦测到电池存在",
    "event_filtersentity_absent": "实体不在位",
    "event_filtersbattery_low": "电量不足",
    "event_filtersfru_service_request_button": "FRU 服务请求按钮",
    "event_filtersnonbootable_diskette_left_in_drive": "非可引导软盘留在驱动器",
    "event_filterspredictive_failure_asserted": "确立有可预知的错误",
    "event_filtersg1_sleeping": "G1 休眠中",
    "event_filterspxe_server_not_found": "找不到 PXE 服务器",
    "event_filtersoutofband_access_password_violation": "带外存取密码违规",
    "event_filtersfru_latch_open": "FRU 锁存器打开",
    "event_filterssession_deactivated": "会话失效",
    "event_filtersfan_area_intrusion": "风扇区域指令",
    "event_filterssleeping_in_s1_s2_or_s3": "S1，S2或 S3 休眠",
    "event_filtersfirmware__software_change_detected": "侦测到固件/软件改变",
    "event_filtersprocessor_automatically_throttled": "处理器自动调整",
    "event_filtersos_watchdog_power_down": "OS 看门狗电源关闭",
    "event_filtersierr": "IERR",
    "event_filterspower_button_pressed": "按下电源按钮",
    "event_filterscorrectable_ecc_logging_limit_reached": "可纠正的 ECC 纪录已满",
    "event_filterslog_area_resetcleared": "日志区域重置/清除",
    "event_filterstimeout_waiting_for_user_selection_of_boot_source": "等待用户选择的启动来源超时",
    "event_filtersipmba_disabled_ipmbb_disabled": "IPMB-A 禁用, IPMB-B 禁用",
    "event_filterssm_bios_uncorrectable_cpucomplex_error": "SM BIOS '不可修正 CPU-complex 错误",
    "event_filtersprocessor_disabled": "处理器禁用",
    "event_filtersconfiguration_error_dmi": "配置错误 (DMI)",
    "event_filtersuser_requested_pxe_boot": "用户请求 PXE 启动",
    "event_filterssensor_failure": "传感器错误",
    "event_filtershot_spare": "热备份",
    "event_filtersfru_deactivation_requested": "FRU 请求停止",
    "event_filterss5g2_soft_off": "S5/G2 “软关机”",
    "event_filtersprogress": "进行中",
    "event_filtersinterlock_asserted": "断言互锁",
    "event_filtersrebuildremap_aborted": "重建/映射 中断",
    "event_filterssleep_button_pressed": "休眠按钮已按下",
    "event_filterspower_off__power_down": "电源关闭/关机",
    "event_filterserror": "错误",
    "event_filterscorrectable_memory_error_logging_disabled": "可修正的存储器错误纪录禁用",
    "event_filtersslotconnector_ready_for_device_removal": "插槽/连接器已准备装置移除",
    "event_filtersin_failed_array": "在损坏阵列",
    "event_filterslegacy_on_state": "Legacy ON State",
    "event_filtersslotconnector_device_removal_request": "插槽/连接器装置移除请求",
    "event_filterspreboot_password_violation__user_password": "预引导密码违规 - 用户密码",
    "event_filtersreset_button_pressed": "重置按钮已按下",
    "event_filtersother_preboot_password_violation": "其余的预引导密码违规",
    "event_filterspci_perr": "PCI PERR",
    "event_filtersg3__mechanical_off": "G3 /机械性关机",
    "event_filtersgeneral_chassis_intrusion": "一般机箱干扰",
    "event_filtersall_event_logging_disabled": "所有的事件日志禁用",
    "event_filterss5_entered_by_override": "由 S5 覆盖输入",
    "event_filtersundetermined_system_hardware_failure": "无法定义的系统硬件错误",
    "event_filtersinvalid_username_or_password": "无效的用户名或密码",
    "event_filtersfru_communication_lost": "FRU 通讯遗失",
    "event_filtersfru_active": "FRU 活动中",
    "event_filtersno_bootable_media": "没有可引导介质",
    "event_filtershardware_incompatibility_detected": "检测到的硬件不兼容",
    "event_filtersinterlock_power_down": "互锁断电",
    "event_filtersentity_present": "实体存在",
    "event_filtersdrive_bay_intrusion": "驱动器托盘干扰",
    "event_filterscritical_stop_during_os_load__initialization": "关键性停止由于系统载入/初始化",
    "event_filterspower_supply_input_out_of_range_but_present": "电源输入超出范围,但存在",
    "event_filtersslot_power_is_off": "插槽电源关闭",
    "event_filterspxe_boot_completed": "PXE 启动完成",
    "event_filterspower_supply_failure_detected": "侦测到电源供应器失败",
    "event_filterspower_cycle": "电源循环",
    "event_filterspef_action": "PEF 动作",
    "event_filtershardware_change_detected": "侦测到硬件改变",
    "event_filtersfru_inactive": "FRU 未活动",
    "event_filtersuncorrectable_ecc": "不可修正 ECC",
    "event_filtersfru_failure": "FRU 错误",
    "event_filterspreboot_password_violation__network_boot_password": "预引导密码违规 - 网络启动密码",
    "event_filtershardware_change_detected_was_successful": "侦测到硬件改变成功",
    "event_filtersentity_disabled": "实体禁用",
    "event_filtersos_watchdog_expired": "系统看门狗过期",
    "event_filtersfront_panel_nmi": "前控板 NMI",
    "event_filtersos_watchdog_shutdown": "系统看门狗关闭",
    "event_filtersconfiguration_error": "配置错误",
    "event_filterstimer_expired": "计时器超时",
    "event_filterspredictive_failure": "可预测故障",
    "event_filterss3_sleeping_processor__hw_context_lost_memory_retained": "S3 “睡眠,处理器&硬件环境丢失,内存保留”",
    "event_filterscorrectable_machine_check_error_logging_disabled": "禁用可修正的机器检测错误日志",
    "event_filtersruntime_critical_stop": "运行时关键性停止",
    "event_filtersio_card_area_intrusion": "I/O 卡区域指令",
    "event_filterssoft_power_control_failure": "软电源控制故障",
    "event_filterspower_supply_input_lost_or_out_of_range": "电源输入丢失或超出范围",
    "event_filtersquiesced": "停止",
    "event_filtersa_boot_completed": "A: 启动完成",
    "event_filterspower_unit_failure_detected": "功率单元故障检测",
    "event_filtersac_lost__power_input_lost": "AC 丢失/电源输入遗失",
    "event_filtersslotconnector_ready_for_device_installation": "插槽/连接器已准备好供设备安装",
    "event_filtershard_reset": "硬复位",
    "event_filtersidentify_status_asserted": "确认状态已断言",
    "event_filtersbus_fatal_error": "总线致命错误",
    "event_filtersfrb3processor_startupinitialization_failure": "FRB3/处理器启动/初始化失败",
    "event_filterspreboot_password_violation_attempt__setup_password": "预引导密码违规尝试 - 安装密码",
    "event_filtersvoltage": "电压",
    "event_filtersinitiated_by_warm_reset": "由热复位发起",
    "event_filtersoem_system_boot_event": "OEM 系统启动事件",
    "event_filtersrebuildremap_in_progress": "重建/映射进行中",
    "event_filterslegacy_off_state": "传统关闭状态",
    "event_filtersprocessor_presence_detected": "侦测到处理器出席",
    "event_filterss4_nonvolatile_sleepsuspend_to_disk": "S4 “非易失性休眠/暂停到硬盘”",
    "event_filterspower_supply_input_lost_acdc": "电源供应输入丢失 (AC/DC)",
    "event_filterstransition_to_m1": "切换至 M1",
    "event_filtersfru_not_installed": "FRU 未安装",
    "event_filtersterminator_presence_detected": "侦测到终端机存在",
    "event_filterstransition_to_m4": "转换至 M4",
    "event_filterstransition_to_m5": "转换至 M5",
    "event_filtersbus_timeout": "总线超时",
    "event_filterssel_almost_full": "SEL 几乎已满",
    "event_filterslan_heartbeat": "LAN Heartbeat",
    "event_filtersrom_boot_completed": "ROM 引导完成",
    "event_filterslan_heartbeat_lost": "LAN Heartbeat 丢失",
    "event_filtersspare": "空",
    "event_filtersbattery_failed": "电池故障",
    "event_filtersdrive_presence": "驱动器存在",
    "event_filtersevent_type_logging_disabled": "禁用事件“类型”纪录",
    "event_filtersos_watchdog_power_cycle": "系统看门狗电源循环",
    "event_filters240va_power_down": "240VA 关闭",
    "event_filtersos_graceful_stop": "系统正常停止",
    "event_filtersfirmware__software_incompatibility_detected": "侦测到固件/软件不兼容",
    "event_filtersunauthorized_dock": "未授权的底座",
    "event_filterssensor_access_degraded_or_unavailable": "传感器存取降级或不可使用",
    "event_filtersmanagement_controller_offline": "管理控制器离线",
    "event_filterscorrectable_machine_check_error": "可修正的机器检测错误",
    "event_filtersoem_specific": "OEM 指定",
    "event_filtersmanagement_controller_unavailable": "管理控制器不可用",
    "event_filtersfru_deactivation_in_progress": "FRU 正在停止",
    "event_filterssystem_reconfigured": "系统重配置",
    "event_filterstemperature": "温度",
    "event_filtersinvalid_password_disable": "禁用无效的密码",
    "event_filtersreserved": "保留",
    "event_filtersautomatic_boot_to_diagnostic": "自动启动进行诊断",
    "event_filterssel_full": "SEL 已满",
    "event_filtersfirmware__software_change_detected_was_successful": "侦测到固件/软件改变成功",
    "event_filtersmachine_check_exception": "机器检测异常",
    "event_filterspower_down": "关闭电源",
    "event_filtersfru_activation_in_progress": "FRU 正在启用",
    "event_filtersprocessor_area_intrusion": "处理器区域指令",
    "event_filtersmodule_handle_closed": "模块处理已关闭",
    "event_filtersipmba_enabled_ipmpb_enabled": "IPMB-A 启用, IPMP-B 启用",
    "event_filtersmemory_automatically_throttled": "存储器自动调整",
    "event_filtersconsistency_check__parity_check_in_progress": "正在持续性检测/同质性检测",
    "event_filterss1_sleeping_with_system_hw__processor_context_maintained": "S1 “与系统硬件&处理器方面保持着休眠”",
    "event_filtersos__runtime_software_initiated_hard_reset": "系统/运行时软启动硬重置",
    "event_filterscontroller_access_degraded_or_unavailable": "控制器存取降级或不可用",
    "event_filtersio_channel_check_nmi": "I/O 通道检测 NMI",
    "event_filtersfrb1bist_failure": "FRB1/BIST 错误",
    "event_filtershang": "挂起",
    "event_filtersplatform_generated_page": "平台产生的页面",
    "event_filtersparity": "奇偶校验",
    "event_filtersinvalid_or_unsupported_hardware_version": "无效或不支持的硬件版本",
    "event_filterseisa_fail_safe_timeout": "EISA 容错超时",
    "event_filterspci_serr": "PCI SERR",
    "event_filtersfatal_nmi": "Fetal NMI",
    "event_filtersos__runtime_software_initiated_warm_reset": "系统/运行时软件启动暖复位",
    "event_filtersunknown": "未知",
    "event_filtersfru_activation_requested": "FRU 请求激活",
    "event_filterslan_leash_lost_system_unplugged_from_lan": "LAN 释放丢失 (系统未接上 LAN)",
    "event_filterssoft_shutdown_initiated_by_pef": "软关机由 PEF 启动",
    "event_filterscableinterconnect_is_connected": "电缆/相连已连接",
    "event_filtersos_watchdog_reset": "系统看门狗复位",
    "event_filterss4s5_soft_off_particular_s4s5_state_cannot_be_determined": "S4/S5 软关机",
    "event_filtersbus_uncorrectable_error": "总线不可修正错误",
    "event_filterscdrom_boot_completed": "CD-ROM 启动完成",
    "event_filtersagent_not_responding": "代理无响应",
    "event_filtersplatform_generated_lan_alert": "平台所产生的 LAN 警报",
    "event_filtersmodule_handle_opened": "模块处理已开",
    "event_filtersfrb2hang_in_post_faliure": "FRB2/Hang in POST 失败",
    "event_filtersos_graceful_shutdown": "系统正常关机",
    "event_filtersinvalid_boot_sector": "无效的启动区段",
    "event_filterss2_sleeping_processor_context_lost": "S2 “休眠, 处理器环境丢失”",
    "event_filterscritical_overtemperature": "关键超温",
    "event_filterstransition_to_m3": "转换到 M3",
    "event_filtersinitiated_by_hard_reset": "由硬重置发起",
    "event_filterssystem_restart": "系统重启",
    "event_filtersfault_status_asserted": "故障状态已断言",
    "event_filtersplatform_generated_snmp_trap_oem_format": "平台产生的 SNMP Trap, OEM 格式",
    "event_filterss0g0_working": "S0/G0 '工作中",
    "event_filtersipmba_disabled_ipmbb_enabled": "IPMB-A 禁用, IPMB-B 启用",
    "event_filtersdrive_fault": "驱动器错误",
    "event_filterssecure_mode_violation_attempt": "安全模式违规尝试",
    "event_filtersplatform_event_trap_generated": "平台事件 Trap 已产生",
    "event_filtersstandby": "电源热备模式",
    "event_filtersos_install_start":"基础系统/虚拟机安装开始",
    "event_filtersos_install_complete":"基础系统/虚拟机安装完成",
    "event_filtersos_install_abort":"基础系统/虚拟机安装终止",
    "event_filtersos_install_fail":"基础系统/虚拟机安装失败",
    "event_filterslnc": "低非临界",
    "event_filterslc": "低临界",
    "event_filterslnr": "低不可恢复",
    "event_filtersunc": "高非临界",
    "event_filtersuc": "高临界",
    "event_filtersunr": "高不可恢复",
    "event_filtersgoing_low": "变得低",
    "event_filtersgoing_high": "变得高",
    "hlp_event_filter":"显示所有配置的事件筛选器和可用插槽.可以添加或修改事件筛选器.默认情况下，在40个可用插槽中配置了15个事件筛选器条目." +
    "<br>选择 <strong>All</strong> 查看所有可用和未配置插槽."+
    "<br>选择 <strong>Configured</strong> 查看启用/禁用的可用配置插槽."+
    "<br>选择 <strong>UnConfigured</strong> 查看标记为 '~'的可用配置或可配置的插槽.",
    "required_policy_group": "需要策略群组",
    "required_sensor_type": "需要传感器类型",
});
