define({
    "home": "主页",
    "system_maintenance": "系统维护",
    "title": "固件镜像位置",
    "fwimage_location": "",
    "invalid_tftp_server_address": "无效的 TFTP 服务器地址",
    "image_name_is_required": "镜像名是必需的",
    "invalid_tftp_retry_count": "无效的 TFTP 重试次数",
    "strongSuccessMsg": "固件镜像位置已成功保存。",
    "successMsg": "",
    "strongFailureMsg": "保存固件镜像位置发生错误。",
    "failureMsg": "",
    "fwimage_locationimage_location_type": "镜像位置类型",
    "fwimage_locationweb_upload_during_flash": "在网页更新期间刷新",
    "fwimage_locationtftp_server": "TFTP 服务器",
    "fwimage_locationprotocol_to_be_used_to_transfer_the_firmware_image_into_the_bmc": "将固件镜像传送到用使用的 BMC 的协议",
    "fwimage_locationtftp_server_address": "TFTP 服务器地址",
    "required_if_tftp_is_chosen": "需要, 如果选择 TFTP",
    "fwimage_locationaddress_of_the_server_where_the_firmware_image_is_stored_it_supports_both_ipv4_and_ipv6_ulli_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0liliipv6_address_made_of_8_groups_of_4_hexadecimal_digits_separated_by_colon_as_in_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlilihexadecimal_digits_are_expressed_as_lowercase_lettersliul": "镜像保存的服务器地址。 <ul><li>- IP 地址是由 4 个数字组成并以点隔开如 xxx.xxx.xxx.xxx。</li> <li>- 数字的范围由 0 ～ 255。</li> <li>- 第一个数字不能为 0。</li><li>IPv6 地址由 8 组 16 进制的数字组成并以冒号来分开如： \\\"xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx\\\".</li><li> 16 进制数字表示为小写字母。</li></ul>",
    "fwimage_locationtftp_image_name": "TFTP 镜像名称",
    "fwimage_locationimage_filename_on_tftp_server": "镜像名称在 TFTP 服务器上。",
    "fwimage_locationtftp_retry_count": "TFTP 重试次数",
    "fwimage_locationnumber_of_times_to_be_retried_in_case_a_transfer_failure_occurs_retry_count_ranges_from_0_to_255": "当传输失败发生时的重试次数。重试次数范围为 0 到 255。",
    "saveLabel": "保存",
    "fw_FirmwareUpgrade": "固件更新",
    "fw_BMCFirmwareUpgrade": "BMC 固件更新",
    "fw_BIOSFirmwareUpgrade": "BIOS 固件更新",
    "fw_CPLDUpgrade": "CPLD 固件更新",
    "fw_PSUUpgrade": "PSU 固件更新",
    "fw_BPUpgrade": "背板固件更新",
    "fw_edit_conf": "编辑保存配置",
    "fw_restore_conf": "恢复出厂设置",
    "fw_fwimage_location": "固件镜像位置",
});
