define({
    "home": "主页",
    "settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "active_directory_settings": "Active directory Settings",
    "title": "Active directory 设置",
    "general_active_directory": "",
    "invalid_user_name_refer_help_for_more_information": "无效的用户名。请参考“帮助”来获取更多信息。",
    "invalid_password_refer_help_for_more_information": "无效的密码。请参考“帮助”来获取更多信息。",
    "invalid_user_domain_name_refer_help_for_more_information": "无效的用户域名。请参考“帮助”来获取更多信息。",
    "invalid_domain_controller_server_address_1refer_help_for_more_information": "无效的网域控制器服务器地址 1.请参考“帮助”来获取更多信息。",
    "invalid_domain_controller_server_address_2refer_help_for_more_information": "无效的网域控制器服务器地址 2.请参考“帮助”来获取更多信息。",
    "invalid_domain_controller_server_address_3refer_help_for_more_information": "无效的网域控制器服务器地址 3.请参考“帮助”来获取更多信息。",
    "strongSuccessMsg": "一般 Active Directory 设置已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "一般 Active Directory 设置保存发生错误。",
    "failureMsg": "",
    "general_active_directoryenable_active_directory_authentication": "启用 Active directory 认证",
    "general_active_directoryselect_check_box_to_enable_active_directory_authentication": "选择复选框来启用 Active directory 认证。",
    "general_active_directorysecret_username": "用户名",
    "general_active_directoryspecify_the_username_of_the_active_directory_server_ulli_user_name_is_a_string_of_1_to_64_alphanumeric_characterslili_it_must_start_with_an_alphabetical_characterlili_it_is_casesensitivelili_special_characters_and_space_are_not_allowedliulstrongnotestrong_if_secret_username_and_password_are_not_needed_both_can_stay_empty_": "指定 Active Directory 服务器的用户名。 <ul><li> 用户名是由长度 1 到 64 的字母或数字所组成的字符。</li><li> 开头必需为字母字符。</li><li> 字母区分大小写。</li><li> 不允许特殊符号，如：逗号，句号，冒号，分号，斜线，反斜线，中括号，括弧，管道符号，等号，加号，星号，问号，&符号，双引号，空格。</li></ul><strong>NOTE:</strong> 如果不需要用户名及密码，请保持空白即可。",
    "general_active_directorysecret_password": "密码",
    "general_active_directoryspecify_the_password_of_the_active_directory_serverulli_password_must_be_at_least_6_character_longlili_white_space_is_not_allowedliulstrongnotestrong_this_field_will_not_allow_more_than_127_characters": "指定 Active Directory 服务器的密码。<ul><li> 密码的长度至少需要6个字符。</li><li> 不允许空格。</li></ul><strong>NOTE:</strong> 此栏位不允许超过127个字符。",
    "general_active_directoryuser_domain_name": "用户域名",
    "general_active_directoryspecify_the_domain_name_for_the_usereg_mydomaincom": "指定一个域名给用户。例如：MyDomain.com",
    "general_active_directorydomain_controller_server_address_1": "网域控制器服务器地址 1",
    "general_active_directoryenter_the_ip_address_of_active_directory_server_at_least_one_domain_controller_server_address_must_be_configured_domain_controller_server_address_supports_the_following_formatulliipv4_address_formatlili_ipv6_address_formatliul": "输入 Active Directory 服务器的 IP 地址。至少要输入一个 Domain Controller 服务器地址。Domain Controller 服务器地址支持以下格式：<ul><li>- IPv4 地址的格式。</li><li>- IPv6 地址的格式。</li></ul>",
    "general_active_directorydomain_controller_server_address_2": "网域控制器服务器地址 2",
    "general_active_directorydomain_controller_server_address_3": "网域控制器服务器地址 3",
    "saveLabel": "保存",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
});
