define({
    "home": "主页",
    "bmc_settings": "BMC 设置",
    "title": "安全设置",
    "generate_ssl": "",
    "invalid_common_name": "无效的通用名称",
    "invalid_organization": "无效的组织",
    "invalid_organization_unit": "无效的组织单位",
    "invalid_city_or_locality": "无效的城市或地点",
    "invalid_state_or_province": "无效的州或省",
    "invalid_country": "无效的国家",
    "invalid_email_address": "无效的电子邮件地址",
    "invalid_time_until_expiry": "无效的过期时间",
    "strongSuccessMsg": "HTTPS 认证已更新，页面将在 30秒 后自动跳转到登录页面，请重新登录使新凭证生效!",
    "successMsg": "",
    "strongFailureMsg": "上传 SSL 凭证过程中发生错误",
    "failureMsg": "",
    "generate_sslcommon_name_cn": "通用名称(CN)",
    "generate_sslcommon_name_for_which_the_certificate_is_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "生成通用名称的凭证。 <ul><li> 最大长度为 64 个字符。<\/li> <li> 字串由字母数字组成。 <li> 不支持特殊字符“#”和“$”。 <\/li><\/ul>",
    "generate_sslorganization_o": "组织 (O)",

    "generate_sslorganization_name_for_which_certificate_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "要生成证书的组织名称。 <ul><li> 最大长度为 64 个字符。<\/li> <li> 字串由字母数字组成。 <li> 不支持特殊字符“#”和“$”。<\/li><\/ul>",
    "generate_sslorganization_unit_ou": "组织单位 (OU)",

    
"generate_sslover_all_organization_section_unit_name_for_which_certificate_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "要生成证书的组织单位名称。 <ul><li> 最大长度为 64 个字符。<\/li> <li> 字串由字母数字组成。<li> 不支持特殊字符“#”和“$”。 <\/li><\/ul>",
"generate_sslcity_or_locality_l": "城市或地点 (L)",
   
 "generate_sslcity_or_locality_has_to_be_givenulli_maximum_length_of_128_characterslili_it_is_a_string_of_alphanumeric_charactersli_special_characters_and_are_not_allowedliul": "必须填写城市或地点的信息。<ul><li> 最大长度为 64 个字符。<\/li><li> 字串由字母数字组成。<li> 不支持特殊字符“#”和“$”。 <\/li><\/ul>",
    "generate_sslstate_or_province_st": "州或省 (ST)",
    "generate_sslstate_or_province_has_to_be_given_ulli_maximum_length_of_128_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "必须填写州或省的信息。 <ul><li> 最大长度为 128 个字符。<\/li> <li> 字串由字母数字组成。<li> 不支持特殊字符“#”和“$”。 <\/li><\/ul>",
    "generate_sslcountry_c": "国家 (C)",
    "generate_sslcountry_code_has_to_be_given_ulli_only_two_characters_are_allowedli_li_special_characters_are_not_allowedliul": "必须填写国家的信息。 <ul><li> 只允许 2 个字符。<\/li> <li> 不支持特殊字符。<\/li><\/ul>",
    "generate_sslemail_address": "电子邮件地址",
    "generate_sslemail_address_of_the_organization_has_to_be_given": "必须填写电子邮件地址。",
    "generate_sslvalid_for": "有效自",
    "in_days": "日内",
    "generate_sslnumber_of_days_the_certificate_to_be_validated_ulli_value_ranges_from_1_to_3650_daysliul": "凭证的有效天数。<ul><li> 天数范围为 1 到 3650 天。<\/li><\/ul>",
    "generate_sslkey_length": "密钥长度",
    "generate_sslstr_2048_bits": "2048 bits",
    "generate_sslchoose_the_key_length_bit_value_of_the_certificate": "选择证书的密钥长度的数值。",
    "saveLabel": "保存",
    "view_ssl_certificate": "查看SSL证书",
    "generate_ssl_certificate": "生成SSL证书",
    "upload_ssl_certificate": "上传SSL证书",
    "loginControl": "登录控制",
    "snmpv": "SNMP V1/V2 设置",
    "ssl_settings": "SSL 设置",
    "user_badpassword": "用户密码锁定设置",
    "generate_ssl_tip": "SSL证书生成中，请稍候。",
    "confirm_start_generate": "SSL证书生成将要开始，SSL证书生成期间请不要操作服务器，确定继续吗？",
});
