define({
    "home": "主页",
    "settings": "BMC 设置",
    "firewall": "防火墙",
    "general_firewall_settings": "一般防火墙设置",
    "title": "目前防火墙设置",
    "block_all_": "全部阻塞: ",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "both": "Both",
    "timeout_": "超时: ",
    "disabled": "否",
    "enabled": "是",
    "from_": "从: ",
    "to_": "到: ",
    "start_time_required_when_timeout_is_set": "当你设置超时后，需要设置开始时间",
    "end_time_required_when_timeout_is_set": "当你设置超时后，需要设置结束时间",
    "general_firewall_rules": "",
    "strongSuccessMsg": "防火墙设置已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "获取防火墙设置发生错误。",
    "failureMsg": "",
    "general_firewall_rulesblock_all": "全部阻塞",
    "general_firewall_rulesthis_option_will_block_all_incoming_ips_and_ports": "此选项将会阻塞所有进入的 IPs 和 Ports。",
    "general_firewall_rulesflush_all": "全部清除",
    "general_firewall_rulesthis_is_used_to_flush_all_the_system_firewall_rules": "清除所有的系统防火墙规则。",
    "general_firewall_rulestimeout": "超时",
    "general_firewall_rulesthis_option_is_used_to_enable_or_disable_firewall_rules_with_timeout": "此选项用来 启用\/禁用 防火墙规则与超时。",
    "general_firewall_rulesstart_datetime": "开始日期",
    "general_firewall_rulesthe_respective_firewall_rule_effect_will_start_from_this_date": "对应的防火墙规则将会在开始日期生效。",
    "general_firewall_rulesend_datetime": "结束日期 & 时间",
    "general_firewall_rulesthe_respective_firewall_rule_effect_will_end_from_this_date": "对应的防火墙规则将会在结束日期无效。",
    "deleteConfirmLabeldeleteconfirmlabeldeleteconfirmlabel": "如果你想删除此记录点击 OK 继续。",
    "deleteLabeldeletelabeldeletelabel": "删除",
    "existing_firewall_settings": "目前防火墙设置"
});