define({
    "home": "主页",
    "maintenance": "系统维修",
    "title": "HPM 韧体更新",
    "start_fw_update": "开始韧体更新",
    "prep_flash": "准备中...",
    "stop_fw_update": "更新完成... 重新启动",
    "fwimage": "选择固件镜像",
    "strongSuccessMsg": "保存!",
    "successMsg": "保存成功",
    "strongFailureMsg": "",
    "failureMsg": "我会尝试出错误的原因",
    "size32mb": "最大为 32 MB",
    "reset": "固件重新设置初始化，关闭当前会话并在两分钟后开启新的会话",
    "str_hash": "#",
    "str_component_name": "组件名称",
    "str_fw_existing_version": "当前版本",
    "str_fw_uploaded_version": "上传版本",
    "str_upgrade": "更新",
    "up_status": "进行中",
    "up_queue": "等待中...",
    "up_ongoing": "进行中...",
    "up_failed": "失败",
    "up_success": "成功!",
    "version": "版本比对 Flash",
    "fullversion": "更新所有",
    "update_confirm": "你确认要进行刷写吗?",
    "either_bmc_mmc": "选择 MMC 或 SPI 组件来继续进行",
    "none_checked": "没有选择任何组件!",
    "no_upgrade_done": "不会进行任何更新!",
    "header": "下列区段允许用户来进行配置以进行固件更新。",
    "bios_update":"这个设备已更新。请关掉浏览器会话并重新开启一个新的浏览器会话来连接到设备",
    "choose_firmware" : "选择固件镜像来更新。",
    "start_upgrade" : "点击“开始固件更新”来更新当前装置固件。",
    "note_for_table" : "当进行恢复配置动作时下列配置的项目将会被保存。" ,
});
