define({
    "home": "主页",
    "settings": "BMC 设置",
    "platform_event_filters": "平台事件筛选器",
    "title": "LAN 目的地",
    "lan_destination_configuration":"LAN 目的地配置",
    "lan_channel_": "LAN Channel: ",
    "lan_destination_": "LAN 目的地: ",
    "snmp_trap": "SNMP Trap",
    "email": "E-Mail",
    "sent_to_": "发送到: ",
    "select_the_lan_channel_": "选择 LAN Channel ",
    "invalid_snmp_destiantion_address_refer_help_for_more_information": "无效的 SNMP 目的地地址。请参考“帮助”来获取更多的信息。",
    "invalid_bmc_user_name_refer_help_for_more_information": "无效的 BMC 用户名。请参考“帮助”来获取更多的信息。",
    "invalid_subject_refer_help_for_more_information": "无效的标题。请参考“帮助”来获取更多的信息。",
    "invalid_message_refer_help_for_more_information": "无效的消息。请参考“帮助”来获取更多的信息。",
    "emailConfirmLabel": "用户未配置此电子邮件地址。确定要继续吗?",
    "lan_destinations": "LAN 目的地",
    "strongSuccessMsg": "保存!",
    "successMsg": "LAN 目的地设置",
    "strongFailureMsg": "错误",
    "failureMsg": "当保存 LAN 目的地时",
    "lan_destinationslan_channel": "LAN Channel",
    "lan_destinationsdisplays_lan_channel_number_of_the_selected_slotreadonly": "显示所选的之 LAN Channel 号码 (只读)。",
    "lan_destinationslan_destination": "LAN 目的地",
    "lan_destinationsdisplays_id_for_setting_destination_selector_of_alert_policyreadonly": "显示设置的警报策略的目的地选择器 ID(只读)。",
    "lan_destinationsdestination_type": "目的地类型",
    "lan_destinationssnmp_trap": "SNMP Trap",
    "lan_destinationsemail": "E-Mail",
    "lan_destinationsthe_destination_type_can_be_either_an_snmp_trap_or_an_email_alert_for_snmp_trap_destination_ip_address_has_to_be_filled_for_email_alert_3_fields_username_subject_and_body_of_the_message_have_to_be_filled_the_smtp_server_information_also_has_to_be_added_under_configurationsmtp_": "目的地类型可以是 SNMP Trap 或是电子邮件警报。以 SNMP Trap 而言, 目的地 IP 地址必需要填写。电子邮件警报则需要填写用户名，标题，还有内容三个栏位。SMTP 服务器的信息也将会添加于配置->SMTP 之下。 ",
    "lan_destinationssnmp_destination_address": "SNMP 目的地位址",
    "lan_destinationsif_destination_type_is_snmp_trap_then_give_the_ip_address_of_the_system_that_will_receive_the_alert_destination_address_will_support_the_following_ulli_ipv4_address_format_li_ipv6_address_formatul": "如果目的地类型为 SNMP Trap,请输入接收警报的系统之 IP 地址。目的地地址将会支持以下格式: <ul><li>- IPv4 地址格式。 <li>- IPv6 地址格式。<\/ul>",
    "lan_destinationsbmc_username": "BMC 使用者名称",
    "lan_destinationsif_destination_type_is_email_alert_then_choose_the_user_to_whom_the_email_alert_has_to_be_sentstrongnotestrong_email_address_for_the_user_has_to_be_configured_under_configurationusers": "如果目的地类型为电子邮件警报, 则请选择要发送电子邮件警报的用户。<strong>NOTE:<\/strong> 电子邮件地址可以在配置->用户下面进行配置。",
    "lan_destinationsemail_subject": "Email 标题",
    "lan_destinationsthese_fields_must_be_configured_if_email_alert_is_chosen_asdestination_type_an_email_will_be_sent_to_the_configured_email_address_of_the_user_in_case_of_any_severity_events_with_a_subject_specified_in_subject_field_and_will_contain_the_message_fields_content_as_the_email_body_strongnotestrong_these_fields_are_not_applicable_for_amiformat_email_users": "如果选择电子邮件警报为目的地类型则此处必须要配置。 电子邮件警报会在事件触发时传送给已配置的用户以及对应的标题跟内容。 <strong>注意:<\/strong> 此处不可填入“AMI-Format”电子邮件用户。",
    "lan_destinationsemail_message": "Email 讯息",
    "lan_destinationsthese_fields_must_be_configured_if_email_alert_is_chosen_as_destination_type_an_email_will_be_sent_to_the_configured_email_address_of_the_user_in_case_of_any_severity_events_with_a_subject_specified_in_subject_field_and_will_contain_the_message_fields_content_as_the_email_body_strongnotestrong_these_fields_are_not_applicable_for_amiformat_email_users": "如果选择电子邮件警报为目的地类型则此处必须要配置。 电子邮件警报会在事件触发时传送给已配置的用户以及对应的标题跟内容。 <strong>注意:<\/strong> 此处不可填入“AMI-Format”电子邮件用户。",
    "lan_destinationssend_test_alert": "发送测试的警报",
    "test_email_sent_successfully": "测试警报已发送到目的地。请确认是否有收到警告，系统并不会检查警报接收是否成功",
    "test_email_failed_to_be_sent_please_try_again_after_sometime": "测试邮件发送失败! 请稍候再重试..",
    "hlp_lan_destinations":"显示所有已配置的LAN目的地和可用插槽.您可以从这里修改或添加新的局域网目标入口,最多提供15个可用插槽.<ul><li>选择LAN Channel:从要配置的列表中选择LAN Channel.</li><li>发送测试的警报: 选择已配置的插槽并单击“发送测试的警报”，将发送示例警报到配置的目的地.</li><li><strong>注意:</strong>只有使能SMTP功能才可发送测试警报. SMTP可以通过Settings->SMTP激活.同时请确认SMTP服务器地址和端口号已经正确配置.</li></ul>",
    "deleteConfirmLabel": "确定要删除?",
    "deleteLabel": "删除",
    "saveLabel": "保存"
});
