define({
    "home": "主页",
    "remote_control": "远程控制",
    "image_redirection": "媒体重定向",
    //ks_lz20181024_vmmedia ++>>
    "settings": "BMC 设置",
    "title": "媒体重定向",
    "tag": "",
    "remote_images": "远程镜像",
    "local_images" : "本地镜像",
    "general_setting":"功能设置",
    //ks_lz20181024_vmmedia ++<< 
    
    //"title": "本地媒体",
    //"tag": "模拟 CD\/DVD\/Floppy\/HDD 镜像成 BMC 主机端媒体",
    "media_type": "媒体类型",
    "cddvd": "CD\/DVD",
    "floppy": "Floppy",
    "hard_disk": "Hard disk",
    "media_instance": "媒体数",
    "image_name": "镜像名称",
    "status": "状态",
    "halted": "停止",
    "started": "开始",
    "status_0": " ",
    "status_1": " - 连线接受",
    "status_2": " - 连线拒绝",
    "status_3": " - 登入失败",
    "status_4": " - 连线使用中",
    "status_5": " - 权限拒绝",
    "status_6": " - 未知错误",
    "status_7": " - 媒体分离阶段",
    "status_8": " - 达到最大用户",
    "status_9": " - 无法连线",
    "status_10": " - 无效的镜像",
    "status_11": " - 挂载错误",
    "status_12": " - 无法开启",
    "status_13": " - 媒体权限失效",
    "status_14": " - 连线中断",
    "status_15": " - 用户取消挂载",
    "status_16": " - 装置弹出",
    "status_17": " - 终止会话",
    "session_index": "会话索引",
    "start_redirection": "点击开始重定向",
    "stop_redirection": "点击停止重定向",
    "delete_image": "点击删除镜像",
});
