    define({
	"home": "主页",
    "maintenance": "系统维修",
    "title": "ME 固件更新",
    "start_fw_update": "开始ME固件更新",
    "size3mb": "最大容量 3 MB",
    "reset": "固件重置将会关闭当前的会话并在两分钟后建立出新的会话",
    "image_upload" : "请选择要上载的ME固件镜像檔",
	"fwimage": "选择ME固件镜像档",
	"start_update" : "点击 '开始更新 ME 固件' 后,开始更新现在设备的固件",
	"start_nm_fw_update": "开始更新 ME 固件",
	"chk_uploadimg": "上载 ME 韧体镜像档",
	"chk_switch_flash_device": "切换设备",
	"chk_activate": "激活更新模式",
	"chk_compare_version": "比较ME固件版本",
	"chk_erase_flash": "开始固件更新",
	"chk_ecfstatus": "获取固件更新进度",
	"chk_deactivate": "不激活",
	"h_meimage_upload" : "选好欲上载的 ME 固件镜像档后,点击'上载'按钮并开始上载",
	"h_steps_display" : "每一步骤会在执行完成后被自动勾选",
    "h_start_update" : "按下'开始更新ME固件'按钮以进行更新",
    "process": "加载中……",
});