define({
    "title": "系统摘要",
    "home": "主页",
    //服务器信息
    "serverInfo": "服务器信息",
    "productType": "产品类型",
    "productName": "产品名称",
    "guid": "GUID",
    "uptime": "运行时间",
    "power": "功耗",
    //固件版本信息
    "fwInfo": "固件版本信息",
    "biosVersion": "BIOS版本号",
    "meVersion": "ME版本号",
    "bmcVersion": "BMC版本号",
    "psuVersion": "电源版本号",
    "cpldVersion": "CPLD版本号",
    //网络信息
    "lanShared": "共享网络",
    "lanDeicated": "专用网络",
    "lanBond": "网络",
    "lanSwitchTo": "显示",
    "lineType": "网络类型",
    "macAddress": "MAC地址",
    "ipAddress": "IPv4地址",
    "ipSource": "IPv4类型",
    "webOnline": "在线用户数",
    //服务器运行状态
    "hoston": "开机",
    "hostoff": "关机",
    //sugon_caichb_tapd1011466 ++>>
    "powersts": "电源状态",
    "id_led_blink":"闪烁",
    "id_led_off":"未定位",
    "id_led_on":"定位",
    "uid_led":"UID灯状态",
    //sugon_caichb_tapd1011466 ++<<

    "serverState": "服务器状态",
    "cpuState": "CPU",
    "memState": "内存",
    "hddState": "硬盘",
    "psuState": "电源",
    "fanState": "风扇",
    //常用操作
    "commonOperations": "常用操作",
    "powerControl": "开关机控制",
    "remoteControl": "控制台重定向",
    "userSettings": "用户/用户组",
    "networkSettings": "网络设置",
    "firmwareUpdate": "固件更新",
    "dateOrTime": "日期/时间",
    //告警信息
    "alarmInfo": "告警信息",
    "alarmDetails": "详情",
    "alarmNoData": "无告警",
    "loading": "加载中",
    "Info": "信息",
    "NonCritical": "轻微",
    "Critical": "严重",
    "Urgency": "紧急",
    //CPU使用率
    "cpuUsageRate": "CPU使用率",
    "notBoot": "未开机",
    //内存使用率
    "memUsageRate": "内存使用率",
    //服务器错误等级
    "levelUrgency":"紧急",
    "levelCritical":"严重",
    "levelNonCritical":"轻微",
    "levelNormal":"正常",
    "healthsts":"健康状态",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "IPv4_info": "IPv4信息",
    "IPv6_info": "IPv6信息",
    "ipv6Address": "IPv6地址",
    "ipv6Source": "IPv6类型",
});
