define({
    "home": "主页",
    "maintenance": "系统维护",
    "title": "PSU固件更新",
    "info":"PSU固件更新过程中请不要执行其他操作，点击“确认”将进入固件更新模式。",
    "prepare":"准备中...",
    "upload":"上传镜像...",
    "flash":"更新中...",
    "upload_fail":"PSU镜像上传失败",
    "start_fw_update": "开始固件更新",
    "verifying":"校验中...",
    "success":"PSU固件升级成功！",
    "cancle":"取消",
    "cancle_info":"PSU固件更新已取消！",
    "cancle_confirm":"确认放弃PSU固件更新？",
    "fwimage": "选择固件镜像",
    "pre_flash_error":"准备过程中遇到问题，请检查重试！",
    "chassis_power_is_on":"服务器仍在运行，请先关闭服务器！",
    "strongSuccessMsg": "保存！",
    "successMsg": "保存成功",
    "strongFailureMsg": "",
    "failureMsg": "我会尝试出错误的原因",
    "size512kb": "最大容量 512KB",
    "reset": "固件已经重置",
    "confirm1":"点击\“确认\”将会执行PSU固件更新，新的镜像将会被写入，更新过程不能中断，确定执行吗？",
    //"cont_update": "更新所选的部分",
    "cont_update": "开始更新",
    "select_all": "全部选择",
    "select_none": "没有选择",
    "section_name": "部分名称",
    "psu_flash_progress":"PSU固件更新正在进行，请稍后重试！",
    "psu_prepare_error":"设备准备过程中发生错误，请检查后重试。",
    "psu_verify_error":"PSU固件检验不成功，请检查是否上传正确的镜像，点击\“确定\”离开更新模式。",
    "image_information":"固件版本信息",
    "current_image_version":"现有固件版本信息：",
    "new_image_version":"上传固件版本信息：",
    "diff_image_info":"上传固件与现有固件版本不同。",
    "same_image_info":"上传固件与现有固件版本相同。",
    "different_image_info":"上传固件与现有固件版本不同。",
    "flash_error":"更新PSU固件失败，请检查！",
    "update_section": "更新部分",
    "prepare_flash":"准备更新...",
    "start_flash":"开始更新...",
    "process":"处理中...",
    "upload":"上传 ",
    "uploading":"上传...",
    "flashing":"更新...",
    "con_reset":"重置",
    "protocol_type":"协议类型:",
    "server_address":"服务器地址:",
    "image_name":"固件名称:",
    "retry_count":"重试次数:",
    "fwimage_maintance_info":"固件更新文件传输协议如下所示。请通过PSU固件更新下的\"选择文件\"按钮选择需要上传的固件。请等待页面正确加载PSU设备信息后，选择相应的设备号,再执行升级操作。",
    "PsuNote":"注意：为了保证升级PSU固件升级操作安全，我们将该操作限制在电源备份策略为主从模式，并且要升级的电源不是主设备的情况下才允许更新PSU固件。",
    "confirm_start_fw_upgrade":"固件升级将要开始，固件升级期间请不要操作服务器，确定继续吗？",
    "notify_chose_fw_image_file":"请选择要更新的固件文件",
    "alert_upload_fail":"上传PSU固件失败",
    "alert_flash_finish":"PSU固件更新成功!",
    "selectFile":"选择文件",
    "psuIndex":"选择PSU索引号",
    "getPsuInfo":"获取设备信息中,请稍等..",
    "psuPowerOn_0":"没有检测到PSU设备，请仔细检查PSU设备，确保其工作正常。",
    "psuPowerOn_1":"当前PSU设备数量为1，在此情况下不允许升级PSU固件",
    "psuStatusNotReady":"没有获取到当前PSU设备数量的信息，请等待当前页面正确加载PSU设备信息后，选择相应的设备号,再执行升级操作",
    "psu_power_status_abnormal":"电源状态异常",
    "Note":"请保证PSU设备在正常运行状态情况下，再进行升级操作。",
    "psu_fw_init":"PSU固件正在初始化中，请等待",
    "fw_FirmwareUpgrade": "固件更新",
    "fw_BMCFirmwareUpgrade": "BMC 固件更新",
    "fw_BIOSFirmwareUpgrade": "BIOS 固件更新",
    "fw_CPLDUpgrade": "CPLD 固件更新",
    "fw_PSUUpgrade": "PSU 固件更新",
    "fw_BPUpgrade": "背板固件更新",
    "PSU_checksume":"PSU固件校验中...",
    "Unknown_error":"刷新过程中发生未知错误。请检查电源设备或固件有效性，重新刷新。",
    //ks_lz_20180724 psu ++>>
    "error_code_1308": "PSU固件更新失败，请检查电源设备或固件有效性，重新刷新。",
    "error_code_1488": "PSU进入刷新模式失败，请检查电源设备或固件有效性，重新刷新。",
    "error_code_1489": "PSU恢复工作模式失败，请检查电源设备或固件有效性，重新刷新。",
    "error_code_1490": "写入PSU镜像校验失败，请检查电源设备或固件有效性，重新刷新。",

    "mode_error1":"当前电源模式为负载均衡模式，此模式下不允许更新PSU固件。请将电源备份策略选择设置为主备供电模式，并且要更新的电源不能设为主电源。",
    "mode_error2":"要更新的电源不能是主电源，请重新设置后再更新固件",
    "mode_error_default":"电源状态异常，请检查后重试！"

    //ks_lz_20180724 psu ++>>
});