define({
    "home": "主页",
    "remote_control": "远程控制",
    "image_redirection": "镜像重定向",
    //ks_lz20181024_vmmedia ++>>
    "settings": "BMC 设置",
    "title": "媒体重定向",
    "tag": "",
    "remote_images": "远程镜像",
    "local_images" : "本地镜像",
    "general_setting":"功能设置",
    //ks_lz20181024_vmmedia ++<<
    "media_type": "媒体类型",
    "cddvd": "CD\/DVD",  
    "floppy": "Floppy",
    "hard_disk": "Hard disk",
    "media_instance": "媒体个数",
    "image_name": "镜像名称",
    "status": "状态",
    "halted": "已中止",
    "started": "已开始",
    //ks_lz20190130_tapd_1001755 ++>>
    "start_mounting":"正在挂载...",
    "status_0": " ",
    "status_1": " - 连线接受",
    "status_2": " - 连线拒绝",
    "status_3": " - 登录失败",
    "status_4": " - 连线使用中",
    "status_5": " - 权限拒绝",
    "status_6": " - 未知错误",
    "status_7": " - 媒体分离阶段",
    "status_8": " - 达到最大用户",
    "status_9": " - 无法连接",
    "status_10": " - 无效镜像",
    "status_11": " - 挂载错误",
    "status_12": " - 无法开启",
    "status_13": " - 媒体授权过期",
    "status_14": " - 连接中断",
    "status_15": " - 用户取消挂载",
    "status_16": " - 弹出装置",
    "status_17": " - 会话中止",
    "session_index": "会话索引",
    "refreshImageList":"刷新镜像文件清单",
    "hlpRmedia":"点击刷新镜像文件清单来取得远程储存装置上最新的镜像文件",
    "load_tip": "刷新镜像文件清单",
    "start_redirection": "点击开始重定向",
    "clear_image": "点击移除镜像",
});
