define({
    "rolegroup_ldapstrongnotestrong_freeunconfigured_slots_are_denoted_by_noneullito_add_role_group_select_a_free_slot_and_click_on_it_to_add_a_new_role_group_to_the_devicelilito_modify_role_group_select_a_configured_slot_and_click_on_it_to_modify_that_role_groupli_lito_delete_a_role_group_select_the_desired_role_group_to_be_deleted_and_click_on_delete_icon_present_at_right_top_cornerliul": "<strong>注意:</strong> 空闲/未安装的槽被标记为'None'。 <ul><li>选择一个空闲的槽并点击它去新增角色群组到装置。 </li><li>选择一个安装过的槽且点击它去修改角色群组。 </li> <li>选择一个想要删除的角色群组且点击右上角的删除标示。 </li></ul>",
    "home": "主页",
    "settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "ldapedirectory_settings": "LDAP/E-directory 设置",
    "title": "角色组",
    "none": "无",
    "no_access": "没有存取",
    "administrator": "管理员",
    "oem": "OEM",
    "operator": "操作员",
    "user": "用户",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "invalid_role_group_name_refer_help_for_more_information": "无效的角色组名称。请参考“帮助”来获取更多信息。",
    "invalid_role_group_domain_refer_help_for_more_information": "无效的角色组网域。请参考“帮助”来获取更多信息。",
    "rolegroup_ldap": "",
    "strongSuccessMsg": "角色组已更新成功。",
    "successMsg": "",
    "strongFailureMsg": "更新角色组发生错误。",
    "failureMsg": "",
    "rolegroup_ldapgroup_name": "群组名称",
    "rolegroup_ldapenter_the_role_group_name_this_name_identifies_the_role_group_in_ldapedirectoryulli_role_group_name_is_a_string_of_64_alphanumeric_characterslili_special_symbols_hyphen_and_underscore_are_allowedliul": "输入角色群租名称。此名称在 LDAP/E-directory 标识角色群组。<ul><li> 角色组名称是一个64字母数字组成的字串。</li><li> 允许特殊字符如连字符和下划线。</li></ul>",
    "rolegroup_ldapgroup_domain": "群域",
    "eg_dcdomain": "eg., dc=domain",
    "rolegroup_ldapenter_the_role_group_domain_this_is_the_domain_where_the_role_group_is_located_ulli_domain_name_is_a_string_of_4_to_64_alphanumeric_characterslili_it_must_start_with_an_alphabetical_characterlili_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_cnmanageroulogin_dcdomaindccomliul": "输入群域。这是角色群组所在的域名。 <ul><li> 域名名称是一个64字母数字组成的字串。</li><li> 开头字符必须是字母。</li><li> 允许特殊字符如点(.)，逗号(,)，连字符(-)，下划线(_)，等于号(=)。</li> <li> 范例: cn=manager,ou=login, dc=domain,dc=com</li></ul>",
    "rolegroup_ldapgroup_privilege": "群组权限",
    "rolegroup_ldapuser": "用户",
    "rolegroup_ldapadministrator": "管理员",
    "rolegroup_ldapoperator": "操作员",
    "rolegroup_ldapoem": "OEM",
    "rolegroup_ldapnone": "无",
    "rolegroup_ldapenter_the_role_group_privilege_this_is_the_level_of_privilege_to_be_assigned_for_this_role_group": "输入角色组权限。将特权等级指定分配给角色组",
    "rolegroup_ldapkvm_access": "KVM 存取",
    "rolegroup_ldapthis_field_used_to_assign_the_kvm_privilege_for_this_role_group": "此处用来指定 KVM 权限给角色组。",
    "rolegroup_ldapvmedia_access": "VMedia 存取",
    "rolegroup_ldapthis_field_used_to_assign_the_vmedia_privilege_for_this_role_group": "此处用来指定 VMedia 权限给角色组。",
    "saveLabel": "保存",
    "role_groups": "角色组",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
    "delete_tip": "确定删除该角色组？",
});
