define({
    "system_info": "系统信息",
    "title": "传感器阈值 ",
    "home": "主页",
    "sensor_reading":"传感器信息",
    "sensor_thresholdschange_threshold_values": "更改阈值",
    "invalid_upper_nonrecoverable_value_refer_help_content": "无效的高不可恢复 (Upper Non-recoverable) 数值。请参考帮助内容。",
    "invalid_upper_critical_value_or_upper_critical_value_cannot_be_bigger_than_upper_nonrecoverable_value": "无效的高临界 (Upper Critical) 数值。请参考帮助内容。",
    "invalid_upper_noncritical_value_or_upper_noncritical_value_cannot_be_bigger_than_upper_critical_value": "无效的高非临界 (Upper Non-critical) 数值。请参考帮助内容。",
    "invalid_lower_noncritical_value_or_lower_noncritical_value_cannot_be_bigger_than_upper_noncritical_value": "无效的低非临界 (Lower Non-critical) 数值。请参考帮助内容。",
    "invalid_lower_critical_value_or_lower_critical_value_cannot_be_bigger_than_lower_noncritical_value": "无效的低临界 (Lower Critical) 数值。请参考帮助内容。",
    "invalid_lower_nonrecoverable_value_or_lower_nonrecoverable_value_cannot_be_bigger_than_lower_critical_value": "无效的低不可恢复 (Lower Non-recoverable) 数值。请参考帮助内容。",
    "strongSuccessMsg": "传感器阈值保存成功！",
    "successMsg": "",
    "strongFailureMsg": "传感器阈值保存发生错误！",
    "failureMsg": "",
    "sensor_thresholdssensor_name": "传感器名称",
    "sensor_thresholdsall_data_in_the_text_box_will_be_converted_into_ipmi_data_type_for_more_information_please_refer_to_ipmi_spec_20_chapter_36_sensor_types_adn_data_conversion": "所文本框中的所有数据将被转换成 IPMI 数据类型，更多信息请参考 IPMI SPEC. 2.0，第三十六章，传感器类型和数据转换。",
    "sensor_thresholdsupper_nonrecoverable": "高不可恢复(Upper Non-recoverable)",
    "upper_nonrecoverable": "高不可恢复(Upper Non-recoverable)",
    "sensor_thresholdsset_upper_nonrecoverable_threshold": "设置高不可恢复(Upper non-recoverable)阈值。",
    "sensor_thresholdsupper_critical": "高临界 (Upper Critical)",
    "upper_critical": "高临界 (Upper Critical)",
    "sensor_thresholdsset_upper_critical_threshold": "设置高临界 (Upper Critical) 阈值。",
    "sensor_thresholdsupper_noncritical": "高非临界 (Upper Non-critical)",
    "upper_noncritical": "高非临界 (Upper Non-critical)",
    "sensor_thresholdsset_upper_noncritical_threshold": "设置高非临界 (Upper Non-critical) 阈值。",
    "sensor_thresholdslower_noncritical": "低非临界 (Lower Non-critical)",
    "lower_noncritical": "低非临界 (Lower Non-critical)",
    "sensor_thresholdsset_lower_noncritical_threshold": "设置低非临界 (Lower Non-critical) 阈值。",
    "sensor_thresholdslower_critical": "低临界 (Lower Critical)",
    "lower_critical": "低临界 (Lower Critical)",
    "sensor_thresholdsset_lower_critical_threshold": "设置低临界 (Lower Critical) 阈值。",
    "sensor_thresholdslower_nonrecoverable": "低不可恢复 (Lower Non-recoverable)",
    "lower_nonrecoverable": "低不可恢复 (Lower Non-recoverable)",
    "sensor_thresholdsset_lower_nonrecoverable_threshold": "设置低不可恢复 (Lower Non-recoverable) 阈值。",
    "saveLabel": "保存"
});
