define({
    "home": "主页",
    "parenttitle":"系统信息",
    "sensor_reading": " 传感器信息 ",
    "livereading_allsensor": "活动中传感器状态读取",
    "search_sensors": "搜索传感器",
    "critical_sensor": " 关键传感器",
    "allthreshold_sensors": "所有阈值传感器正常",
    "discrete_sensor": "离散传感器状态",
    "loading": "加载...",
    "sensor_name": "传感器名称",
    "state": "状态",
    "behavior": "行为",
    "power_supply" : "电源供应",
    "present" : "呈现",
    "no_discretesensor": "没有离散传感器!",
    "normal_sensor":"一般传感器",
    "reading":"读取中",
    "nonormal_thresholdsensor":"没有一般阈值传感器!",
    "disabled_sensor" : "传感器禁用",
    "nodisabled_sensor" : "没有禁用的传感器",
    "cpu_temperature" : "CPU 温度",
    "ambientt_emperature" : "周围温度",
    "temperature" : "温度",
    "loading" : "读取中..",
    "battery": "电池",
    "processor" : "处理器",
    "cpu1_temperature" : "CPU 1 温度",
    "cpu2_temperature" : "CPU 2 温度",
    "status_can_cpu" : "状态 Can0 CPU0",
    "memory_err" : "存储器错误",
    "pcie_card_prst" : "PCIe Card Prst",
    "page_desc": "这里将显示所有传感器的相关资讯。即时的读值详细资讯如传感器名称，状态，现在数值，行为。还可以选择要显示的传感器类型。一些例子如温度感应器，风扇感应器，Watchdog感应器，和电压感应器等等。页面会自动刷新。请注意在取得感应器的值时会有一点延迟。<br><b>元件<\/b><br>请选择元件名称. 显示所有感应器(关键, 离散, 一般以及禁用）的详细资讯，如感应器名称，状态和行为。<br>点选任一感应器会展示其特殊感应器资讯，包括阈值及图形化显示相关的事件（只读）。<br><b>感应器详细资讯<\/b><br>从关键传感器或一般传感器清单上选择特定感应器。其感应器资讯就像动态显示，以及会显示其阈值.<br>"
  
});
