define({
    "home": "主页",
    "parentTitle": "BMC 设置",
    "alarm_settings": "告警设置",
    "snmp_trap": "SNMP Trap 设置",
    "snmp": "",
    "no_snmp_trap_information": "查询SNMP Trap 设置信息发生错误。",
    "strongSuccessMsg": "SNMP Trap 设置保存成功",
    "successMsg": "",
    "strongFailureMsg": "SNMP Trap 设置发生错误",
    "failureMsg": "",
    "rw_char": "读写团体名",
    "ro_char": "只读团体名",
    "snmpcheck_this_option_to_enable_snmp_support_for_the_bmc" : "按下此选项将启动BMC上的SNMP支持。",
    "snmp_support": "SNMP 支持",
    "snmp_protocol": "SNMP 协议",
    "snmp_visit": "SNMP 访问",
    "privacy_protocol": "隐私协议",


    "saveLabel": "保存",
    "help_information":"设置SNMP v1/v2服务，团体名的读写权限。\n SNMP v3服务，请通过\"用户管理\"页面进行配置。",

    "trap_help_information":"SNMP v1/v2服务，请输入团体名称。\n SNMP V3服务，请选择用户名称(注：用户密码长度不能少于8位)。",
    "trap_help_snmp_addr":"只有已保存的SNMP地址，才能进行测试。系统不会检查测试结果，请自行确认是否测试成功。",


    "whether_enable": "启用SNMP Trap告警",
    "on": "是",
    "off": "否",
    "v1": "V1",
    "v2": "V2",
    "v3": "V3",
    "community": "团体名",
    "v3_user": "V3用户",
    "not_null": "不能为空",
    "alarm_grade": "告警等级",
    "check_all": "全选",
    "urgency": "紧急",
    "critical": "严重",
    "non_critical": "轻微",
    "normal": "正常",
    "snmp_addr": "SNMP 地址",
    "snmp_test": "测试",
    "ip_incorrect": "IP地址格式不正确",
    "sent_to_ip": '测试信息已发送到 <strong>{IP}<\/strong>，请确认是否有收到，系统并不会检查接收是否成功。',
    "sent_to_ip_error": '测试SNMP 地址 <strong>{IP}<\/strong> 发生错误。',
    // ks_lz_20180727 TAB ++>>
    "title": "安全设置",
    "loginControl": "登录控制",
    "snmpv": "SNMP V1/V2 设置",
    "ssl_settings": "SSL 设置",
    "user_badpassword": "用户密码锁定设置",
    // ks_lz_20180727 TAB ++>>
});