define({
    "home": "主页",
    "settings": "BMC 设置",
    "video": "视频",
    "sol": "SOL",
    "title": "SOL 触发设置",
    "sol_trigger_settings": "",
    "recording_time_must_be_in_future": "录制时间必定是在未来",
    "strongSuccessMsg": "SOL 触发设置保存成功",
    "successMsg": "",
    "strongFailureMsg": "保存 SOL 触发设置成功",
    "failureMsg": "",
    "sol_trigger_settingscritical_events_temperaturevoltage": "重要事件 (温度\/电压)",
    "sol_trigger_settingsconfigure_which_event_on_the_page_will_trigger_the_sol_video_recording_option_to_start_you_can_checkuncheck_a_box_to_addremove_the_trigger_for_your_systembrbsaveb_click_save_to_save_any_changes_madebrbnoteb_the_date_and_time_should_be_in_advance_to_the_system_date_and_time": "页面上配置事件会触发 SOL 视频录制启动项。你可以选取\/取消复选框添加\/移除你的系统触发事件。<br><b>保存:<\/b> 点击“保存”来保存进行的任何改变。<br><b>注意:<\/b>可以在高级设置中设置系统日期与时间。",
    "sol_trigger_settingsnon_critical_events_temperaturevoltage": "非关键事件 (温度\/电压)",
    "sol_trigger_settingsnon_recoverable_events_temperaturevoltage": "不可恢复事件 (温度\/电压)",
    "sol_trigger_settingsfan_state_changed_events": "风扇状态更改事件",
    "sol_trigger_settingswatchdog_timer_events": "看门狗计时器事件",
    "sol_trigger_settingschasis_power_on_events": "机箱开启电源事件",
    "sol_trigger_settingschasis_power_off_events": "机箱关闭电源事件",
    "sol_trigger_settingschasis_reset_events": "机箱重启事件",
    "sol_trigger_settingslpc_reset_events": "LPC 重启事件",
    "sol_trigger_settingsdate_and_time_event": "日期和时间事件",
    "sol_trigger_settingsdate": "日期",
    "sol_trigger_settingstime": "时间",
    "saveLabel": "保存"
});
