define({
    "tasks_events": "任务 &amp; 事件",
    "schedules_bmcevents":"根据 BMC 事件来",
    "home": "主页",
    "delete_task" : "删除任务",
    "save_task" : "保存任务",
    "task_title" : "任务标题",
    "execute_script" : "执行下列的脚本",
    "importing_script_lib" : "从脚本库中导入脚本创建此任务的脚本的副本。而复制的脚本可以根据任务的需求客制化",
    "script_lib" : "脚本程序库",
    "search_script_lib":"搜索脚本程序库",
    "import_from" : "导入来自",
    "file_sys" : "文件系统",
    "mrac_cloud" : "MegaRAC Cloud",
    "write_script" : "设计或编写脚本",
    "mrac_cloud_saetool" : "MegaRAC Cloud SAE Tool",
    "selected_events" : "当选取的事件发生时:",
    "blank_listening_events" : "(你可以选择不填此栏位使你的任务不需要去监听任何的事件)",

    "any" :"任何",
    "temperature" :"温度",
    "voltage" :"电压",
    "current" :"电流",
    "fan" :"风扇",
    "chassis_instrusion" :"机箱防盗",
    "security_violation" :"违反安全",
    "processor" :"处理器",
    "power_supply" :"电源供给",
    "power_unit" :"电源单元",
    "cooling_device" :"冷却装置",
    "unit_based_sensor" :"其它基于单位的传感器",
    "memory" :"存储器",
    "device_slot" :"驱动槽",
    "post_memory_size" :"开机自检内存调整",
    "system_firmware_prog" :"系统固件进展",
    "events_loggoing_disabled" :"禁用事件日志",
    "bmc_watchdog" :"BMC 看门狗",
    "system" :"系统",
    "critical_interrupt" :"临界中断",
    "button_pressed" :"按下按钮",
    "board" :"模块",
    "microcontroller" :"微控制器",
    "add_card" :"附加卡",
    "chassis" :"机箱",
    "chip_set" :"芯片集",
    "other_fru" :"其他 FRU",
    "cable_connect" :"Cable 连接",
    "terminator" :"终端",
    "system_boot" :"系统启动/重启",
    "boot_error" :"引导错误",
    "os_boot" :"引导系统",
    "os_shutdown" :"系统停止/关闭",
    "slot_connector" :"插槽/连接器",
    "acpi" :"ACPI",
    "watchdog2" :"看门狗2",
    "platform_alert" :"平台警报",
    "entity_presence" :"实体存在",
    "monitor_asic" :"监视器 ASIC / IC",
    "lan_heartbeat" :"LAN心跳",
    "mangt_subsys_health" :"管理子系统运行状况",
    "battery" :"电源",
    "session_audit" :"会话审核",
    "version_change" :"版本变更",
    "fru_state" :"FRU 状态",
    "other_fruher_sensors" :"其他传感器",

    "sensor_event" : "传感器事件",
    "console_redirection" : "控制台重定向的事件",
    "webuser_logon" : "Web 用户登入",
    "login" : "登录",
    "logoff" : "注销",
    "automically_logoff" : "自动注销",
    "connection_lost" : "连线中断",
    "event" : "事件",
    "bios_genevent" :"BIOS 产生的事件",
    "sys_mangt_softevent" : "系统管理的软事件",
    "smi_event" : "SMI 事件",
    "activate_task" : "激活的任务",
    "immediately" : "立即的",
    "from" : "从",
    "repeat" : "重复",
    "repeats" : "重复",
    "every_minute" : "每分钟",
    "hourly" : "每小时",
    "daily" : "每日",
    "weekly" : "每周",
    "monthly" : "每月",
    "yearly" : "每年",
    "repeat_every" : "重复每次",
    "weeks" : "周",
    "repeat_on" : "重复接通",
    "monday" : "星期一",
    "tuesday" : "星期二",
    "wednesday" : "星期三",
    "thursday" : "星期四",
    "friday" : "星期五",
    "saturday" : "星期六",
    "sunday" : "星期天",
    "repeat_by" : "重复的",
    "day_of_month" : "每月的天数",
    "day_of_week" : "每周的天数",
    "ends" : "结束",
    "never" : "永不",
    "after" : "之后",
    "occurrences" : "发生",
    "on" : "On"


});