define({
    "home": "主页",
    "settings": "BMC 设置",
    "user_group":"用户/用户组",
    "title": "编辑用户组",
    "disabled": "(禁用)",
    "active": "(活动中)",
    "no_access": "禁止访问",
    "administrator": "管理员",
    "oem": "OEM",
    "operator": "操作员",
    "user": "用户",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "snmp": "SNMP",

    "strongSuccessMsg": "保存!",
    "successMsg": "操作成功！",
    "strongFailureMsg": "操作失败，请稍后再试。",
    "failureMsg": "我会尝试出错误的原因",
 

    /*用户组管理-多语化数据*/
    "edit_group": "编辑用户组", 
 
    "loading" : "加载中",
    "undata" : "无数据",
    "tab_users": "用户",
    "tab_groups": "用户组",
    "role": "用户组角色",
    "any_role": "任何角色",
    "privilege": "高级权限",
    "any_privilege": "任何权限",
    "add_group": "添加用户组",
    "members": "组员",
    "edit": "编辑",
    "delete": "删除",
    "user_info": "用户信息",
    "group_info": "用户组信息", 
    "save": "保存",
    "group_name": "用户组名称",
    //"group_name": "不能为空",
    "name_notNull": "名称不能为空",
    //"name_character": "特殊字符只允许 '-'(连字符), '_'(下划线), '@'(at符号)。",
    "name_character": "名称要求数字及字母组成的字符串。允许特殊字符 '-',  '_', '@'",
    "name_chinese": "名称不允许输入中文",
    "name_length": "名称长度不能大过30个字符",
    "role_notNull": "角色不能为空",
    "save_success": "保存成功！",
    "save_failed": "保存失败。",
    "name_exists": "名称已存在，请重新输入。",
    "group_deleteSure": "确定要删除用户组吗？",
    "yes": "确定",
    "no": "取消",
    "no_member": "无组员",
    "not_edited_group": "当前用户组为系统保留组，只能查看不允许编辑。",
    "allow_group_number": "系统只允许创建{n}个用户组",
    "not_deleted_group": "该用户组下存在用户，不能删除。",
    "delete_success": "删除成功！",
    "user_groups_change_note":"当前用户组下用户不为空，不允许修改用户名",   //ks_lz20181024_groupname ++
    "user_privilage_note":"None用户组无法使用任何权限",                 //ks_lz20181108_Privilage ++
});
