define({
    "home": "主页",
    "bmc_settings": "BMC 设置",
    "title": "安全设置",
    "view_sslcurrent_certificate_information": "当前凭证信息",
    "strongSuccessMsg": "SSL 凭证已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "获取 SSL 凭证发生错误。",
    "failureMsg": "",
    "view_sslcertificate_version": "凭证版本",
    "view_sslbbasic_informationbbrit_displays_the_basic_information_about_the_uploaded_ssl_certificateit_displays_the_following_fieldsulli_version_serial_numberlili_signature_algorithmlili_public_keyliul": "<b>基本信息<\/b><br>它显示关于上传SSL证书的基本信息。它显示以下字段。<ul><li> - 版本 </li><li> - 序号<\/li><li> - 签名机制<\/li><li> - 公钥<\/li><\/ul>",
    "view_sslserial_number": "序列号",
    "view_sslsignature_algorithm": "签名算法",
    "view_sslpublic_key": "公钥",
    "view_ssl": "",
    "view_sslissuer_common_name_cn": "发行机构通用名称 (CN)",
    "view_sslbissued_frombbrthis_contains_the_information_about_the_certificate_issuerulli_common_namecnlili_organizationolili_organization_unitoulili_city_or_localityllili_state_or_provincestlili_countryclili_email_addressliul": "<b>发出自<\/b><br>此项包含关于证书发行机构的信息。<ul><li>- 通用名称(CN)<\/li><li>- 组织(O)<\/li><li> - 组织单位(OU)<\/li><li>- 城市或地点(L)<\/li><li>-州或省 (ST)<\/li><li>- 国家(C)<\/li><li>-电子邮件地址<\/li><\/ul>",
    "view_sslissuer_organization_o": "发行组织 (O)",
    "view_sslissuer_organization_unit_ou": "发行组织单位 (OU)",
    "view_sslissuer_city_or_locality_l": "发行机构所在城市或地区 (L)",
    "view_sslissuer_state_or_province_st": "发行机构所在州或省 (ST)",
    "view_sslissuer_country_c": "发行机构所在国家 (C)",
    "view_sslissuer_email_address": "发行机构电子邮件地址",
    "view_sslvalid_from": "有效自",
    "view_sslbvalidity_informationbbrit_displays_the_validity_period_of_the_uploaded_certificateulli_valid_fromlili_valid_toliul": "<b>有效期信息<\/b><br>显示上传的证书的有效期。<ul><li>- 有效自<\/li><li> - 有效至<\/li><\/ul>",
    "view_sslvalid_till": "有效至",
    "view_sslissued_to_common_name_cn": "被颁发证书的用户的通用名称 (CN)",
    "view_sslbissued_tobbrit_displays_about_the_information_to_whom_the_certificate_is_issuedulli_common_namecnlili_organizationolili_organization_unitoulili_city_or_localityllili_state_or_provincestlili_countryclili_email_addressliul": "<b>发出至<\/b><br>显示证书颁发给用户的信息。<ul><li> 通用名称(CN)<\/li><li> 组织(O)<\/li><li> 组织单位(OU)<\/li><li> 城市或地点(L)<\/li><li> 州或省(ST)<\/li><li> 国家(C)<\/li><li> 电子邮件地址<\/li><\/ul>",
    "view_sslissued_to_organization_o": "被颁发证书的用户组织 (O)",
    "view_sslissued_to_organization_unit_ou": "被颁发证书的用户组织单位 (OU)",
    "view_sslissued_to_city_or_locality_l": "发往的城市或地区 (L)",
    "view_sslissued_to_state_or_province_st": "发往的州或省 (ST)",
    "view_sslissued_to_country_c": "发往的国家 (C)",
    "view_sslissued_to_email_address": "被颁发证书的用户电子邮件地址",
    "view_ssl_certificate": "查看SSL证书",
    "generate_ssl_certificate": "生成SSL证书",
    "upload_ssl_certificate": "上传SSL证书",
    "loginControl": "登录控制",
    "snmpv": "SNMP V1/V2 设置",
    "ssl_settings": "SSL 设置",
    "user_badpassword": "用户密码锁定设置"
});