define({
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "ip_oriented_firewall_rules": "IP Oriented Firewall Rules",
    "title": "Add IP Rule",
    "add_ip_rule": "",
    "invalid_ip_address_refer_help_for_more_information": "Invalid IP Address. Refer 'Help' for more Information.",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set_and_end_time_should_be_greater_than_the_start_time": "End time required when timeout is set and End time should be greater than the start time",
    "invalid_rule_selected": "Invalid Rule selected.",
    "strongSuccessMsg": "IP Rule configuration has been added successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in Adding IP Rule configuration",
    "failureMsg": "",
    "add_ip_ruleip_single_or_range_start": "IP Single (or) Range Start",
    "add_ip_rulethis_field_is_used_to_configured_the_ip_address_or_range_of_ip_addressesip_address_will_support_ipv4_address_format_onlyulli_ipv4_address_made_of_4_numbers_separated_bydots_as_in_xxxxxxxxxxxxlili_each_number_ranges_from_0_to_255lili_first_number_must_not_be_0liul": "This field is used to configured the IP Address or Range of IP Addresses.IP Address will support IPv4 Address format only:<ul><li> IPv4 Address made of 4 numbers separated bydots as in xxx.xxx.xxx.xxx.<\/li><li> Each number ranges from 0 to 255.<\/li><li> First number must not be 0.<\/li><\/ul>",
    "add_ip_ruleip_range_end": "IP Range End",
    "optional": "optional",
    "add_ip_ruleenable_timeout": "Enable Timeout",
    "add_ip_rulethis_option_used_to_enable_or_disable_firewall_rules_with_timeout": "This option used to enable or disable firewall rules with timeout.",
    "add_ip_rulestart_date": "Start Date",
    "add_ip_rulethe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "add_ip_rulestart_time": "Start Time",
    "add_ip_rulethe_respective_firewall_rule_effect_will_start_from_this_time": "The respective firewall rule effect will start from this time.",
    "add_ip_ruleend_date": "End Date",
    "add_ip_rulethe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "add_ip_ruleend_time": "End Time",
    "add_ip_rulethe_respective_firewall_rule_effect_will_end_from_this_time": "The respective firewall rule effect will end from this time.",
    "add_ip_rulerule": "Rule",
    "add_ip_ruleallow": "Allow",
    "add_ip_ruleblock": "Block",
    "saveLabel": "Save"
});
