define({
    "home": "Home",
    "settings": "BMC Settings",
    "external_user_settings": "External User Settings",
    "radius_settings": "RADIUS Settings",
    "title": "Advanced RADIUS Settings",
    "advanced_radiusradius_authorization": "RADIUS Authorization",
    "invalid_vendor_specific_stringrefer_help_for_more_information": "Invalid vendor specific string.Refer 'Help' for more information",
    "strongSuccessMsg": "Advanced RADIUS Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Advanced RADIUS Settings.",
    "failureMsg": "",
    "advanced_radiusadministrator": "Administrator",
    "advanced_radiush4radius_user_authorization_h4for_authorization_purpose_you_should_configure_radius_user_with_vendor_specific_attribute_in_server_sidebrbrh4vendor_specific_attribute_in_server_sideh4you_have_to_configure_vsa_values_in_radius_serverbrul_styleliststylenoneli_example1li_litestadmin_authtype_papcleartextpasswordadminliliauthtype_pap_vendorspecifich4liulul_styleliststylenoneli_example2lilitestoperator_authtype_papcleartextpassword_operatorliliauthtype_pap_vendorspecifich3liulbrif_you_change_the_vendorspecific_value_then_you_should_change_the_same_values_in_this_pagebrstrongnotestrongbr_ul_styleliststylenonelithese_fields_will_not_allow_more_than_127_characterslili_is_not_allowedliul": "<h4>Radius User Authorization <\/h4>For Authorization Purpose you should configure Radius user with Vendor Specific Attribute in Server side<br><br><h4>Vendor Specific Attribute in Server side<\/h4>You have to configure VSA values in Radius server<br><ul style=\"list-style:none;\"><li> Example:1<\/li> <li>testadmin Auth-Type :=PAP,Cleartext-Password:='admin'<\/li><li>Auth-Type :=PAP, Vendor-Specific='H=4'<\/li><\/ul><ul style=\"list-style:none;\"><li> Example:2<\/li><li>testoperator Auth-Type := PAP,Cleartext-Password := 'operator'<\/li><li>Auth-Type :=PAP, Vendor-Specific='H=3'<\/li><\/ul><br>If you change the Vendor-Specific value then you should change the same values in this page.<br><strong>NOTE:<\/strong><br> <ul style=\"list-style:none;\"><li>These fields will not allow more than 127 characters.<\/li><li>'#' is not allowed.<\/li><\/ul>",
    "advanced_radiusoperator": "Operator",
    "advanced_radiususer": "User",
    "advanced_radiusoem_proprietary": "OEM Proprietary",
    "advanced_radiusno_access": "No Access",
    "saveLabel": "Save",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",
});
