define({
    "alert_policiesit_shows_all_configured_alert_policies_and_available_slotsbr_you_can_modify_or_add_new_alert_policy_entry_from_herebrclick_i_classion_ionclosecircledi_icon_to_delete_an_alert_policy_from_the_listbra_maximum_of_60_slots_are_available": "It shows all configured Alert policies and available slots.<br> You can modify or add new alert policy entry from here.<br>Click <i class='ion ion-close-circled'><\/i> icon to delete an alert policy from the list.<br>A maximum of 60 slots are available.",
    "home": "Home",
    "settings": "BMC Settings",
    "platform_event_filters": "Platform Event Filters",
    "title": "Alert Policies",
    "group_": "Group: ",
    "_active": " (Active)",
    "_disabled": " (Disabled)",
    "_": "( ~ )",
    "always_send_alert_to_this_destination": "Always send alert to this destination",
    "if_previous_successful_skip_this_and_continue_if_configured": "If previous successful, skip this and continue (if configured)",
    "if_previous_successful_stop_alerting_further": "If previous successful, stop alerting further",
    "if_previous_successful_switch_to_another_channel_if_configured": "If previous successful, switch to another channel (if configured)",
    "if_previous_successful_switch_to_methods_if_configured": "If previous successful, switch to methods (if configured)",
    "lan_channel_": "LAN Channel: ",
    "sent_to_": "Sent To: ",
    "invalid_destination_selected": "Invalid Destination Selected.",
    "required_channel_number": "Required channel Number",
    "invalid_policy_group_selected": "Invalid Policy group Selected.",
    "alert_policies": "Alert Policies",
    "strongSuccessMsg": "Alert Policies has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Alert Policies.",
    "failureMsg": "",
    "alert_policiespolicy_group_number": "Policy Group Number",
    "alert_policiesstr_1": "1",
    "alert_policiesstr_2": "2",
    "alert_policiesstr_3": "3",
    "alert_policiesstr_4": "4",
    "alert_policiesstr_5": "5",
    "alert_policiesstr_6": "6",
    "alert_policiesstr_7": "7",
    "alert_policiesstr_8": "8",
    "alert_policiesstr_9": "9",
    "alert_policiesstr_10": "10",
    "alert_policiesstr_11": "11",
    "alert_policiesstr_12": "12",
    "alert_policiesstr_13": "13",
    "alert_policiesstr_14": "14",
    "alert_policiesstr_15": "15",
    "alert_policieschoose_the_policy_number_that_was_configured_in_event_filter_table": "Choose the policy number that was configured in Event filter table",
    "alert_policiesenable_this_alert": "Enable this alert",
    "alert_policiescheck_the_option_enable_to_enable_the_policy_settings": "Check the option 'Enable' to enable the policy settings.",
    "alert_policiespolicy_action": "Policy Action",
    "alert_policiesalways_send_alert_to_this_destination": "Always send alert to this destination",
    "alert_policiesif_previous_successful_skip_this_and_continue_if_configured": "If previous successful, skip this and continue (if configured)",
    "alert_policiesif_previous_successful_stop_alerting_further": "If previous successful, stop alerting further",
    "alert_policiesif_previous_successful_switch_to_another_channel_if_configured": "If previous successful, switch to another channel (if configured)",
    "alert_policiesif_previous_successful_switch_to_methods_if_configured": "If previous successful, switch to methods (if configured)",
    "alert_policieschoose_any_one_of_the_policy_set_values_from_the_listbr0_always_send_alert_to_this_destinationbr1_if_alert_to_previous_destination_was_successful_do_not_send_alert_to_this_destination_proceed_to_next_entry_in_this_policy_setbr2_if_alert_to_previous_destination_was_successful_do_not_send_alert_to_this_destination_do_not_process_any_more_entries_in_this_policy_setbr3_if_alert_to_previous_destination_was_successful_do_not_send_alert_to_this_destination_proceed_to_next_entry_in_this_policy_set_that_is_to_a_different_channelbr4_if_alert_to_previous_destination_was_successful_do_not_send_alert_to_this_destination_proceed_to_next_entry_in_this_policy_set_that_is_to_a_different_destination_type": "Choose any one of the Policy set values from the list.<br>0 - Always send alert to this destination.<br>1 - If alert to previous destination was successful, do not send alert to this destination. Proceed to next entry in this policy set.<br>2 - If alert to previous destination was successful, do not send alert to this destination. Do not process any more entries in this policy set.<br>3 - If alert to previous destination was successful, do  not send alert to this destination. Proceed to next entry in this policy set that is to a different channel.<br>4 - If alert to previous destination was successful, do not send alert to this destination. Proceed to next entry in this policy set that is to a different destination type",
    "alert_policieslan_channel": "LAN Channel",
    "alert_policieschoose_a_particular_destination_from_the_configured_destination_list": "Choose a particular destination from the configured destination list.",
    "alert_policiesdestination_selector": "Destination Selector",
    "alert_policieschoose_a_particular_destination_from_the_configured_destination_liststrongnotestrong_lan_destination_have_to_be_configured_under_configurationpeflan_destination": "Choose a particular destination from the configured destination list.<strong>NOTE:<\/strong> LAN Destination have to be configured - under Configuration->PEF->LAN Destination.",
    "alert_policiesevent_specific_alert_string": "Event Specific Alert String",
    "alert_policiescheck_the_box_to_specify_an_eventspecific_alert_string": "Check the box to specify an event-specific Alert String.",
    "alert_policiesalert_string_key": "Alert String Key",
    "alert_policieschoose_from_a_set_of_values_all_linked_to_strings_kept_in_the_pef_configuration_parameters_to_specify_which_string_is_to_be_sent_for_this_alert_policy_entry": "Choose from a set of values, all linked to strings kept in  the PEF configuration parameters, to specify which string is to be sent for this Alert Policy entry.",
    "deleteConfirmLabel": "Click OK if you want to continue deleting this record.",
    "deleteLabel": "Delete",
    "saveLabel": "Save"
});
