define({
   "title" : "Asset Information",
   "home" : "Home",
   "systeminfo":"System Information",
   "load":"loading",
   //"undata" : "Data N/A",
   "undata" : "No data",
   //资产信息
   "cpus" : "CPU",
   "mems" : "Memory",
   "hdds" : "HDD",
   "nic" : "NIC",
   "pcie" : "PCIe",
   "psus" : "PSU",
   "raid" : "RAID",
   "onside" : "Used Slots:",
   "totalSlots" : "Total Slots:",
   "present" : "Present:",
   "total" : "Total:",
   "totalCapacity" : "Total Capacity:",
   //CPU信息
   "Number" : "Number",
   "Location" : "Location",
   "Present" : "Present",
   "BrandName" : "Brand Name",
   "UPIFreq" : "UPI Frequency",
   "UPIWidth" : "UPI Width",
   "CPUID" : "CPUID",
   "CoreThread" : "Current Cores/Current Threads",
   "CPUFreq" : "Frequency",
   "Cache" : "L1/L2/L3 Cache Info",
   "SysClock" : "System Clock Speed",
   "P0CoreFreq" : "Turbo Frequency",
   "MaxThread" : "Max Cores/Max Threads",
   "Sspec" : "S-Spec",
   "PIROMIDFamily": "Family",
   "PIROMIDModel": "Model",
   "PIROMIDStepping": "Stepping",
   "PIROMID" : "PIROM CPU ID",
   "UPILinkNum" : "UPI Link Number",
   "UPILinkRate" : "Max UPI Link Transfer Rate",
   "MaxPCIeLinkRate" : "Max PCIe Link Transfer Rate",
   "NVMDIMMSize" : "Max support Intel DC Persistent Memory Size",
   "Family" : "Family",
   "Tcase" : "Tcase(℃)",
   "TDP" : "TDP",
   "Features" : "Features",
   "ExtFamily" : "Ext.Family",
   "ExtModel" : "Ext.Model",
   //内存
   "PN" : "PN",
   "DimmType" : "DRAM Type",
   "Module" : "Module",
   "Rank" : "Rank",
   "Type" : "Type",
   "Frequency" : "Frequency",
   "Size" : "Capacity",
   //硬盘
   "ModelName" : "Model",
   "Mode" : "Mode",
   "SN" : "SN",
   "FwVersion" : "FW Version",
   "VendorName" : "Vendor",
   "VendorID" : "Vendor ID",
   "MaxLinkSpeed" : "Max Link Speed",
   "MaxLinkWidth" : "Max Link Width",
   "Temp" : "Temp(℃)",
   "LeftLife" : "Left Life(%)",
   "SMART" : "SMART",
   //电源
   "Vendor" : "Vendor",
   "Revision" : "Revision",
   "Date" : "Date",
   "RatedPower" : "Rated Power",
   //网卡
   "Port" : "Port",
   "PCIeAddr" : "PCIeAddr",
   "Class" : "Class",
   "Category" : "Category",
   "LinkSpeed" : "Link Speed",
   "MacAddr" : "MAC/GUID",
   //PCIE
   "LinkWidth" : "Link Width",
   //ks_lz_20181018_assetinfo ++>>
   //language
   "NA" : "N/A",
   "CPU_NA" : "No Data",
   "CPU_Cores": "cores",
   "CPU_Threads": "threads",
   "Undefiend":"undefined",
   "Present":"Present",
   //ks_lz_20181018_assetinfo ++<<
});
