define({
    "home": "Home",
    "system_maintenance": "System Maintenance",
    "title": "Backup/Restore Configuration",
    "backup_config": "Backup Configuration",
    "backupStrongSuccessMsg": "Backup Configuration settings have been saved successfully.",
    "backupSuccessMsg": "",
    "backupStrongFailureMsg": "Error in downloading Backup Configuration settings.",
    "backupFailureMsg": "",
    "backup_configcheck_all": "Check All",
    "backup_configcheck_the_configuration_that_needs_to_be_backed_up_you_will_get_a_file_download_you_can_use_the_same_to_restore_the_configuration_when_neededbrbnote_b_network_configurations_are_interrelated_to_ipmi_and_hence_by_default_ipmi_configurations_will_be_selected_automatically_when_you_select_network_and_services_to_be_backed_up": "Check the configuration that needs to be backed up. You will get a file download. You can use the same to restore the configuration, when needed.<br><b>NOTE : <\/b> Network configurations are inter-related to IPMI, and hence by default IPMI configurations will be selected automatically when you select \u201cNetwork and Services\u201d to be backed up.",
    "backup_configsnmp": "SNMP",
    "backup_configkvm": "KVM",
    "backup_confignetwork_services": "Network & Services",
    "backup_configipmi": "IPMI",
    "backup_configntp": "NTP",
    "backup_configauthentication": "Authentication",
    "backup_configsyslog": "SYSLOG",
    "downloadLabel": "Download Config",
    //restore config
    "restore_config": "Restore Configuration",
    "upload_config_file": "Upload config file",
    "restoreStrongSuccessMsg": "Configuration has been restored successfully.",
    "restoreSuccessMsg": "---Logout",
    "restoreStrongFailureMsg": "There was a problem while restoring Backup configuration.",
    "restoreFailureMsg": "",
    "restore_configconfig_file": "Config File",
    "restore_configuse_browse_button_to_navigate_to_the_configuration_file": "Use Browse button to navigate to the Configuration file.",
    "saveConfirmLabel": "Click OK if you want to continue restoring configurations    WARNING:Restoring configurations will restart the device",
    "saveLabel": "Upload"
});
