define({
    "home": "Home",
    "settings": "BMC Settings",
    "dns": "DNS",
    "title": "DNS Configuration",
    "dns_registrationbmc_registration": "BMC Registration",
    "strongSuccessMsg": "DNS Configuration has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving DNS Configuration.",
    "failureMsg": "",
    "dns_registrationbmc_interface": "BMC Interface",
    "dns_registrationchoose_the_bmcs_network_port_to_register_with_dns_settings_check_the_option_register_bmc_to_register_with_dns_settings": "Choose the BMC's network port to register with DNS settings. Check the option 'Register BMC' to register with DNS settings.",
    "dns_registrationregister_bmc": "Register BMC",
    "dns_registrationregistration_method": "Registration method:",
    "dns_registrationnsupdate": "Nsupdate",
    "dns_registrationdhcp_client_fqdn": "DHCP Client FQDN",
    "dns_registrationhostname": "Hostname",
    "dns_registrationul_libnsupdateb_register_with_the_dns_server_using_the_nsupdate_applicationli_libdhcp_client_fqdnb_register_with_the_dns_server_using_dhcp_option_81li_libhostnameb_register_with_the_dns_server_using_dhcp_option_12li_ul_bnoteb_hostname_option_should_be_selected_if_the_dhcp_server_does_not_support_option_81": "<ul> <li><b>Nsupdate<\/b> - Register with the DNS server using the nsupdate application<\/li> <li><b>DHCP Client FQDN<\/b> - Register with the DNS server using DHCP option 81.<\/li> <li><b>Hostname<\/b> - Register with the DNS server using DHCP option 12.<\/li> <\/ul> <b>NOTE:<\/b> Hostname option should be selected if the DHCP server does not support option 81.",
    "dns_registrationmdns_enabled": "mDNS Enabled",
    "dns_registrationcheck_this_box_to_enable_multicast_dns": "Check this box to enable Multicast DNS",
    "dns_registrationtsig_authentication_enabled": "TSIG Authentication Enabled",
    "dns_registrationcheck_this_box_to_enable_tsig_authentication_while_registering_dns_via_nsupdate": "Check this box to enable TSIG authentication while registering DNS via nsupdate.",
    "saveLabel": "Save"
});
