define({
    "home": "Home",
    "logs": "Logs",
    "logInformation": "Logs Information",
    "eventLog": "Event Log",
    "auditLog": "Audit Log",
    "systemLog": "System Log",
    "currentCapacity": "Current Capacity (bytes):",
    "maximumCapacit": "Maximum Capacity (bytes):",
    "maximumQuantity": "Maximum Quantity:",
    "dateSelection": "Date",
    "startDate": "Start Date",
    "endDate": "End Date",
    "eventSelection": "Event",
    "sensor": "Sensor",
    "allevents":"All Events",
    "allsensors" : "All Sensors",
    "eventlog_statistics" : "Event Logs Statistics",
    "system_events": "System Event Records",
    "oem_events": "OEM Event Records",
    "bios_events": "BIOS Generated Events",
    "smi_events": "SMI Handler Events",
    "system_management_events": "System Management Software Events",
    "system_oem_events": "System Software - OEM Events",
    "remove_console_events": "Remote Console Software Events",
    "terminal_mode_events": "Terminal Mode Remote Console software Events",
    "ipmb_slave_address": "Ipmb Slave Address",
    "system_software_id": "System Software ID",
    "downloadLog": "Download Log",
    "clearLog": "Clear Log",
    "downloadOriginalFormat": "Download Original Format",
    "originalFormat": "Original Format",
    "conversionFormat": "Conversion Format",
    "clientTimezone": "Client Timezone",
    "bmcTimezone": "BMC Timezone",
    "UTCOffset": "UTC Offset:",
    "id": "ID",
    "time": "Time",
    "pagesize": "Page Size:",
    "loading" : "Loading",
    "undata" : "No data",
    "clearLogConfirm" : "This operation will clear all logs. Do you really want to clear the logs ?",
    "clearLogCompletion" : "The log has been clearly successful.",
    "category" : "Category",
    "startDateSoBig" : "Start date must be less than the end date.",
    "dateNotEmpty" : "Start date and end date must exist at the same time.",
    "status" : "Status",
    "operator":"User Name",
    "description" : "Description",
    "level" : "Level",
    "alllevel" : "All Level",
    "info" : "Info",
    "normal" : "Normal",
    "notCritical" : "Non Critical",
    "critical" : "Critical",
    "urgency" : "Urgency",
    "query" : "Query",
    "reset" : "Reset",
    "total" : "Total:",
    "bars": "Bar(s)",
    "pages":"Page(s)",
});
