define({
    "home": "Home",
    "settings": "BMC Settings",
    "parenttitle":"System Information",
    "raid_management": "RAID Management",
    "title": "Event Log",
    "controller": "Controller",
    "record_id": "Record Id",
    "time_stamp": "Time Stamp",
    "event_code": "Event Code",
    "event_type": "Event Type",
    "unknown": "Unknown",
    "ld_events": "LD Events",
    "pd_events": "PD Events",
    "enclosure_events": "Enclosure Events",
    "bbu_events": "BBU Events",
    "sas_events": "SAS Events",
    "controller_events": "Controller Events",
    "configuration_events": "Configuration Events",
    "cluster_events": "Cluster Events",
    "event_class": "Event Class",
    "info_events": "Info Events",
    "warning_events": "Warning Events",
    "critical_events": "Critical Events",
    "fatal_events": "Fatal Events",
    "dead_events": "Dead Events",
    "progress_events": "Progress Events",
    "debug_events": "Debug Events",
    "select_the_raid_controller_": "Select the RAID Controller "
});
