define({
    "home": "Home",
    "system_maintenance": "System Maintenance",
    "title": "Firmware Image Location",
    "fwimage_location": "",
    "invalid_tftp_server_address": "Invalid TFTP Server Address",
    "image_name_is_required": "Image Name is required",
    "invalid_tftp_retry_count": "Invalid TFTP Retry Count",
    "strongSuccessMsg": "Firmware Image Location has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Firmware Image Location.",
    "failureMsg": "",
    "fwimage_locationimage_location_type": "Image Location Type",
    "fwimage_locationweb_upload_during_flash": "Web Upload during flash",
    "fwimage_locationtftp_server": "TFTP Server",
    "fwimage_locationprotocol_to_be_used_to_transfer_the_firmware_image_into_the_bmc": "Protocol to be used to transfer the firmware image into the BMC",
    "fwimage_locationtftp_server_address": "TFTP Server Address",
    "required_if_tftp_is_chosen": "Required, if TFTP is chosen",
    "fwimage_locationaddress_of_the_server_where_the_firmware_image_is_stored_it_supports_both_ipv4_and_ipv6_ulli_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0liliipv6_address_made_of_8_groups_of_4_hexadecimal_digits_separated_by_colon_as_in_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlilihexadecimal_digits_are_expressed_as_lowercase_lettersliul": "Address of the server where the firmware image is stored. It supports both IPv4 and IPv6. <ul><li> IP Address made of 4 numbers separated by dots as in xxx.xxx.xxx.xxx.<\/li> <li> Each number ranges from 0 to 255.<\/li> <li> First number must not be 0.<\/li><li>IPv6 Address made of 8 groups of 4 Hexadecimal digits separated by colon as in \"xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx\".<\/li><li>Hexadecimal digits are expressed as lower-case letters.<\/li><\/ul>",
    "fwimage_locationtftp_image_name": "TFTP Image Name",
    "fwimage_locationimage_filename_on_tftp_server": "Image filename on TFTP server.",
    "fwimage_locationtftp_retry_count": "TFTP Retry Count",
    "fwimage_locationnumber_of_times_to_be_retried_in_case_a_transfer_failure_occurs_retry_count_ranges_from_0_to_255": "Number of times to be retried in case a transfer failure occurs. Retry count ranges from 0 to 255.",
    "saveLabel": "Save",
    "fw_FirmwareUpgrade": "Firmware Upgrade",
    "fw_BMCFirmwareUpgrade": "BMC Firmware Upgrade",
    "fw_BIOSFirmwareUpgrade": "BIOS Firmware Upgrade",
    "fw_CPLDUpgrade": "CPLD Upgrade",
    "fw_PSUUpgrade": "PSU Upgrade",
    "fw_BPUpgrade": "Backplane Upgrade",
    "fw_edit_conf": "Edit Preserve Configuration",
    "fw_restore_conf": "Restore Factory Defaults",
    "fw_fwimage_location": "Firmware Image Location",
});
