define({
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "general_firewall_settings": "General Firewall Settings",
    "title": "Existing Firewall Settings",
    "block_all_": "Block All: ",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "both": "Both",
    "timeout_": "Timeout: ",
    "disabled": "Disabled",
    "enabled": "Enabled",
    "from_": "From: ",
    "to_": "To: ",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set": "End time required when timeout is set",
    "general_firewall_rules": "",
    "strongSuccessMsg": "Firewall Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in getting Firewall Settings.",
    "failureMsg": "",
    "general_firewall_rulesblock_all": "Block All",
    "general_firewall_rulesthis_option_will_block_all_incoming_ips_and_ports": "This option will block all incoming IPs and Ports.",
    "general_firewall_rulesflush_all": "Flush All",
    "general_firewall_rulesthis_is_used_to_flush_all_the_system_firewall_rules": "This is used to flush all the system firewall rules.",
    "general_firewall_rulestimeout": "Timeout",
    "general_firewall_rulesthis_option_is_used_to_enable_or_disable_firewall_rules_with_timeout": "This option is used to enable or disable firewall rules with timeout.",
    "general_firewall_rulesstart_datetime": "Start Date&Time",
    "general_firewall_rulesthe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "general_firewall_rulesend_datetime": "End Date&Time",
    "general_firewall_rulesthe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "deleteConfirmLabel": "Click OK if you want to continue deleting this record.",
    "deleteLabel": "Delete",
    "existing_firewall_settings": "Existing Firewall Settings"
});
