define({
    "home": "Home",
    "settings": "settings",
    "external_user_settings": "External User Settings",
    "radius_settings": "RADIUS Settings",
    "title": "General RADIUS Settings",
    "general_radius": "",
    "_invalid_server_address": " Invalid Server address",
    "invalid_port_number": "Invalid Port Number",
    "invalid_secret_phrase": "Invalid Secret phrase",
    "strongSuccessMsg": "General RADIUS Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving General RADIUS Settings.",
    "failureMsg": "",
    "general_radiusenable_radius_authentication": "Enable RADIUS Authentication",
    "general_radiusselect_this_option_to_enable_radius_authentication": "Select this option to enable RADIUS Authentication.",
    "general_radiusserver_address": "Server Address",
    "general_radiusspecify_radius_server_address_server_address_supports_the_following_formats_ul_liip_address_both_ipv4_and_ipv6_formatli_lifqdn_fully_qualified_domain_name_formatli_ul": "Specify RADIUS server Address. Server address supports the following formats: <ul> <li>IP Address (Both IPv4 and IPv6 format).<\/li> <li>FQDN (Fully Qualified Domain Name) format.<\/li> <\/ul>",
    "general_radiusport": "Port",
    "general_radiusspecify_the_radius_port_number_ul_li_default_port_is_1812li_li_port_value_ranges_from_1_to_65535li_ulstrongnote_strong_port_80_is_blocked_for_tcpudp_protocols": "Specify the RADIUS Port number. <ul> <li> Default Port is 1812.<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul><strong>NOTE: <\/strong> Port 80 is blocked for TCP\/UDP protocols.",
    "general_radiussecret": "Secret",
    "general_radiusspecify_radius_server_secret_password_ul_lisecret_must_be_at_least_4_characters_longli_li_white_space_is_not_allowedli_ul_strongnotestrong_this_field_will_not_allow_more_than_32_characters": "Specify RADIUS server secret (Password) <ul> <li>Secret must be at least 4 characters long.<\/li> <li> White space is not allowed.<\/li> <\/ul> <strong>NOTE:<\/strong> This field will not allow more than 32  characters.",
    "general_radiusenable_kvm_access": "Enable KVM Access",
    "general_radiusthis_field_provides_access_to_kvm_for_radius_authenticated_users": "This field provides access to KVM for RADIUS authenticated users.",
    "general_radiusenable_vmedia_access": "Enable VMedia Access",
    "general_radiusthis_field_provides_access_to_vmedia_for_radius_authenticated_users": "This field provides access to VMedia for RADIUS authenticated users.",
    "saveLabel": "Save",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",

});
