define({
    "home": "Home",
    "settings": "BMC Settings",
    "network_setting":"Network Settings",
    "title": "Sideband Interface (NC-SI)",
    "ncsi": "",
    "strongSuccessMsg": "NC-SI Configuration has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving NC-SI Configuration.",
    "failureMsg": "",
    "ncsincsi_mode": "NCSI Mode",
    "ncsiauto_failover_mode": "Auto Failover Mode",
    "ncsimanual_switch_mode": "Manual Switch Mode",
    "ncsiselect_this_radio_button_to_change_ncsi_mode_to_auto_failover_mode_or_manual_switch_mode": "Select this radio button to change NCSI Mode to Auto Failover Mode or Manual Switch Mode.",
    "ncsincsi_interface": "NCSI Interface",
    "ncsiit_lists_the_supported_interface_names_in_list_box_choose_the_particular_interface_name_for_which_you_need_to_configure_ncsi_settings_": "It lists the supported interface names in list box. Choose the particular Interface name for which you need to configure NCSI settings. ",
    "ncsichannel_number": "Channel Number",
    "ncsichoose_the_channel_number_to_be_configured_for_the_selected_interface_name": "Choose the channel number to be configured for the selected Interface name.",
    "ncsipackage_id": "Package ID",
    "ncsichoose_the_package_id_to_be_configured_for_the_selected_interface_name": "Choose the package ID to be configured for the selected Interface name.",
    "saveLabel": "Save",
    "nt_ip": "Network IP Settings",
    "nt_bond": "Network Bond Configuration",
    "nt_dns": "DNS Configuration",
    "nt_ncsi": "Sideband Interface (NC-SI)",
    "share_lan":"Shared Lan",
    "dedicate_lan":"Dedicated Lan",
});
