define({
    "home": "Home",
    "maintenance": "System Maintenance",
    "title": "ME Firmware Update",
    "start_fw_update": "Start ME firmware update",
    "size3mb": "Max. size 3 MB",
    "reset": "Firmware reset has been called. Close the current session, and open a new session after a couple of minutes.",
    "image_upload" : "Choose the ME Firmware image to be updated.",
	"fwimage": "Select the ME Firmware Image",
	"start_update" : "Click 'Start ME Firmware Update' to upgrade the current device firmware.",
	"start_nm_fw_update": "Start ME firmware update",
	"chk_uploadimg": "Upload the ME firmware image",
	"chk_switch_flash_device": "Switch Flash Device",
	"chk_activate": "Activate Flash Mode",
	"chk_compare_version": "Compare the ME firmware version",
	"chk_erase_flash": "Start firmware update",
	"chk_ecfstatus": "Get the firmware update progress",
	"chk_deactivate": "Deactivate",
	"h_meimage_upload" : "Choose the ME image and then press the UPLOAD button to start uploading.",
	"h_steps_display" : "Each step will be checked when done.",
    "h_start_update" : "Click 'Start Firmware Update' to upgrade the current device firmware.",
    "process": "Processing...",

});
