define({
    "parenttitle": "Remote Control",
    "power_control": "Power Control",
    "tag": "on Host Server",
    "home": "Home",
    "power_actions": "Power Actions",
    "power_off": "Power Off",
    "power_on": "Power On",
    "power_cycle": "Power Cycle",
    "hard_reset": "Hard Reset",
    "acpi_shutdown": "ACPI Shutdown",
    "perform_action": "Perform Action",
    "confirm": "Are you sure to perform this operation?",
    "powerOff": "Power state: OFF",
    "powerOn": "Power state: ON",
    "warningInfo": "Operation failed, please try again later!",
    "long_control": "Long-range control",
    "online": "Host Online",
    "offline": "Host Offline",
    "strongSuccessMsg": "Log Settings Policy has been saved successfully.",
    "server_hostoff": "Host is currently off",
    "server_hoston": "Host is currently on",
    "host_retrying": "Retrying...please wait. Retries Left : ",
    "power_action_wait": "Performing Power Action.. Please Wait",
    "str_server_err1": "Performing soft power off failed. This may be because the host OS is taking unusual long time to gracefully shut down.",
    "str_server_err2": "Performing power action failed.",
    "str_server_setaction": "There was a problem while receiving response for power action",
    "str_server_getstatus": "There was a problem while receiving current status of host.",
    "help_status": "Display current server status.",
    "help_selection": "Select this option to action with server.",
    "help_forceoff": "Select this option to immediately power off the server.",
    "help_forceon": "Select this option to power on the server.",
    "help_powercycle": "Select this option to first power off, and then reboot the system (cold boot).",
    "help_hardreset": "Select this option to reboot the system without powering off (warm boot).",
    "help_acpi": "Select this option to initiate operating system shutdown prior to the shutdown.",

    "power_energy": "power and energy",
    "pe_power_control": "Power Control",
    "pe_power_hot_standby": "Power hot standby",
    "pe_me_power_policy": "ME Power Policy",
    "pe_power_restore_control": "Power Restore Control",
    // ks_lz_20170711  power button lock ++>>
    "pe_power_button_lock": "Power button lock",
    // ks_lz_20170711  power button lock ++>>
});