define({
    "home": "Home",
    "system_maintenance": "System Maintenance",
    "title": "Preserve Configuration",
    "preserve_configuration": "",
    "strongSuccessMsg": "Preserve configuration settings have been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Preserve Configuration settings.",
    "failureMsg": "",
    "preserve_configurationclick_here_to_go_to_a_hrefmaintenancefirmware_updatefirmware_updatea_or_a_hrefmaintenancerestore_configurationrestore_factory_defaults_a": "Click here to go to <a href='#maintenance\/firmware_update'>Firmware Update<\/a> or <a href='#maintenance\/restore_configuration'>Restore Factory Defaults <\/a>",
    "preserve_configurationcheck_the_configuration_that_needs_to_be_preserved_while_the_restore_configuration_is_done": "Check the configuration that needs to be preserved, while the Restore Configuration is done.",
    "preserve_configurationcheck_all": "Check All",
    "preserve_configurationselect_this_option_to_check_all_the_configuration_list": "Select this option to check all the configuration list.",
    "preserve_configurationsdr": "SDR",
    "preserve_configurationyou_can_either_checkuncheck_a_check_box_to_preserveoverwrite_the_configuration_for_your_system": "You can either check\/uncheck a check box to preserve\/overwrite the configuration for your system.",
    "preserve_configurationfru": "FRU",
    "preserve_configurationsel": "SEL",
    "preserve_configurationipmi": "IPMI",
    "preserve_configurationnetwork": "Network",
    "preserve_configurationntp": "NTP",
    "preserve_configurationsnmp": "SNMP",
    "preserve_configurationssh": "SSH",
    "preserve_configurationkvm": "KVM",
    "preserve_configurationauthentication": "Authentication",
    "preserve_configurationsyslog": "Syslog",
    "preserve_configurationweb": "Web",
    "preserve_configurationextlog": "Extlog",
    "preserve_configurationredfish": "Redfish",
    "saveLabel": "Save"
});
