define({
	"parenttitle":"Remote Control",
   "remote_control" : "Console Redirection",
   "power_controlkvm" : "Remote KVM",
   "home" : "Home",
   "search_settings" : "Search settings",
   "settings" : " Settings",
   "cd_image" : " CD Image",
   "connected_to" : "&nbsp; Connected to",

   "start_kvm" : "Start KVM",
   "stop_kvm" : "Stop KVM",
   "show_kbd" : "Show KBD",
   "start_media_redirection" : "Start Media",
   "record" : "Record Video",
   "stop" : "Stop Recording",
   "video_rec_setting" : "Record Settings",
   "videorecording" : "Video Record",
   "settings_ok" : "Ok",
   "settings_cancel" : "Cancel",
   "video_length" : "Video Length",
   "seconds" : "Seconds",
   "time" : "Time",
   "media_packets_sent" : "Media Packets sent",
   "install_spx_remoteapp" : "Install SPX KVM Remote App",
   "alert_apinotsupported" : "The File APIs are not fully supported in this browser. Media Redirection cannot be done in this browser. Use our App or use a different device with modern browser",
   "select_file" : "Please select a file",
   "stop_media_redirection" : "Stop Media",
   "start_media_redirection" : "Start Media",
   "iso_image_redirection" : "Only one ISO image redirection is supported now",
   "read_bytes" : "read bytes at",
   "is_trying_to_connect": " is trying to connect. What level of permission do you wish to grant them?",
   "is_requesting_full_access": " is requesting full KVM access. Would you like to give them full access? Or maintain their status of partial access?",
   "full_access_granted_by": "Full virtual console access granted by ",
   "user_with_ip": " user with IP address ",
   "partial_access_granted_by": "Partial access (only video) granted by ",
   "partial_status_line": "Session running with partial KVM privilige",
   "slave_none_status_body": "Master session has denied KVM control. Closing the viewer.",
   "slave_quit": "Slave session quit",
   "you_have": "You have ",
   "more_seconds": " more seconds to make a decision.",
   "full_permission": "Full Permission",
   "part_permission": "Partial Permission",
   "no_permission": "No Permission",
   "permission_requested": "Permission Requested",
   "master_has": "Master session has ",
   "status": "Status",
   "slave_permission": "Slave Permission",
   "request_full": "Request Full Access",
   "switch_master": "Switch Master",
   "switch_master_body": "Which session would you like to grant full permission after you exit?",
   "grant_permission": "Grant Permission",
   "master_reconn": "Partial access privilige to virtual console received because master session is currently reconnecting. Kindly request full permission, if required, after some time.",
   "full_access_received_timeout": "Full access privilege to virtual console received due to request timeout from ",
   "granted_full_access_timeout": "Granted full virtual console access to ",
   "due_to_request_timeout": " due to virtual console access request time out.",
   "provided_full_access_to": "Provided full access permission to ",
   "requesting_permission": "Requesting permission for virtual console access from the ",
   "master_blocked_request" : "KVM Master Session blocked incoming request.",
   "kvm_license_exp": "KVM License has expired.",
   "kvm_timed_out": "KVM Session Timed-out. Closing the Viewer...",
   "kvm_terminated": "Terminate command received from the server.\nThe KVM redirection session has been disconnected.",
   "kvm_web_restart": "WebServer has been restarted. Closing the Viewer...",
   "kvm_web_logout": "WebSession has been logged out. Closing the Viewer...",
   "kvm_conf_change": "Redirection configuration has been changed. Redirection engine will restart.\nCurrent session has been closed by redirection service. Please connect again.",
   "kvm_server_restart": "Redirection Engine has instructed Viewer to Close. Closing the Viewer... " ,
   "kvm_inv_sess": "Invalid Session token. Authentication failure. ",
   "kvm_disabled": "The user does not have the privilege to launch KVM Session.\nPlease try again from a privileged user account.",
   "kvm_inv_sess_info": "Invalid Session Information To Reconnect. Authentication failure.",
   "kvm_max_session_reached": "Maximum number of allowable sessions reached. Please close other sessions and try again" ,
   "same_kvm_client_user": "Unable to launch Virtual Console. Only one Virtual Console session is allowed form the same client ",
   "invalid_image_type" : "Invalid image file type",
   "media_redirection_running": "Virtual Media Redirection is currently running. Are you sure you want to exit and end the media redirection?",
   "hold_down": "Hold Down",
   "r_ctrl": "Right Ctrl Key",
   "r_alt": "Right Alt Key",
   "l_ctrl": "Left Ctrl Key",
   "l_alt": "Left Alt Key",
   "r_win": "Right Windows Key",
   "l_win": "Left Windows Key",
   "context_key": "Context Menu Key",
   "prtscn": "Print Screen Key",
   "press_release": "Press and Release",
   "send_keys": "Send Keys",
   "video": "Video",
   "pause_video":"Pause Video",
   "resume_video":"Resume Video",
   "refresh_video":"Refresh Video",
   "zoom" : "Zoom",
   "zoom_in":"Zoom In",
   "zoom_out":"Zoom Out",
   "mouse":"Mouse",
   "show_cli_cursor":"Show Client Cursor",
   "show_host_cursor":"Show Host Cursor",
   "mouse_mode":"Mouse Mode",
   "absolute_mm":"Absolute Mouse Mode",
   "relative_mm":"Relative Mouse Mode",
   "other_mm":"Other Mouse Mode",
   "activeuser" : "Active Users",
   "host_display" : "Host Display",
   "hdisplay_on" : "Display ON",
   "hdisplay_off" : "Display OFF",
   "capture_screen" : "Capture Screen",
   "low_bandwidth" : "Low Bandwidth Mode",
   "bw_normal" : "Normal",
   "bw_8BPP" : "8 BPP",
   "bw_8BPPBW" : "8BPP BW",
   "bw_16BPP" : "16 BPP",
   "options" : "Options",
   "block_priv_request" : "Block Privilge Request",
   "compression_mode_id": "Compression Mode",
   "YUV_420": "YUV 420",
   "YUV_444": "YUV 444",
   "YUV_444_2color": "YUV 444 + 2 color VQ",
   "YUV_444_4color": "YUV 444 + 4 color VQ",
   "DCT_Quantization_table": "DCT Quantization table",
   "zero": "0 (Best Quality)",
   "one": "1",
   "two": "2",
   "three": "3",
   "four": "4",
   "five": "5",
   "six": "6",
   "seven": "7 (Worst Quality)",
   "power" : "Power",
   "power_on" : "Power On",
   "power_cycle" : "Power Cycle",
   "power_reset" : "Power Reset",
   "power_off_immediate" : "Immediate shutdown",
   "power_off_orderly" : "Orderly shutdown",
   "record_duration_range" : "Video Record Duration range 1 to 1800 Seconds.",
   "record_duration_invalid" : "Invalid Video Record Duration range",
   "video_paused_during_record" : "Due to pausing the video redirection, video recording has been stopped.",
   "video_record_status" : "Recording Video ...",
   /* For KeyBoard Layout Dialog */
   "kbd_header" : "Keyboard Layout Language",
   "kbd_permission" : "Do you want to overwrite the default Keyboard Layout Language?",
   "yes" : "YES",
   "no" : "NO",
   /* For KeyBoard Layout Language menus
   ** Note: Extra white spaces are given at the end of some strings.
   **       When appending checklist icon it will be visually pleasing */
   "kbd_layout_hdr" : "Keyboard Layout",
   "kbd_layout_eng" : "English U.S ",
   "kbd_layout_ger" : "German ",
   "kbd_layout_jap" : "Japanese ",
   "kvm_service_disabled": "KVM service is disabled. Go to Settings-> Services page to enable KVM service.",
   "kbd_mouse_encryption":"keyboard/mouse encryption",
   "enable_encryption_status" : "Keyboard/mouse encryption is enabled by other sessions.Enabling encryption for this session",
   "disable_encryption_status" : "Keyboard/mouse encryption cannot be disabled as multiple sessions are running",
   /* For hotkeys */
   "usr_macro" : "User Defined Macros",
   "err_MaxMacroLimit" : "Maximum of 20 Hot key combinations can be specified. No more hot keys can be added.",
   "add" : "Add",
   "close" : "Close",
   "add_macro" : "Add Macro",
   "add_macro1" : "To add a User Defined Macro, Place the curser in the text box. PRESS and RELEASE the key event combination to define a Macro",
   "err_SingleMacroLimit" : "There can be a maximum of 6 key events in a Hot key combination. No more key events can be added.",
   "err_DuplicateMacro" : "The Hotkey you are trying to add, already exists. Duplicate entries are not allowed.",
   "clr" : "Clear",
   "clrAll" : "Clear All",
   "insert" : "Insert",
   "hotkeys" : "Hot Keys",
   /* End of hotkeys */
   "downloadLabel":"Launch KVM",
   "downloadJavaSOLLabel":"Download Java SOL",
   "downloadJViewerLabel":"Java Console",
   "long_control" : "Long-range control",
   "remote_java" : "Java Mode",
   "remote_html5" : "Html5 Mode",
   "operation_failed": "Operation failed, Please try again later.",
   "kvm_help": "KVM has two boot modes: HTML5 mode and Java mode. Please select a mode to start KVM.",

    //remotesession
    // "home": "Home",
    // "bmc_settings": "BMC Settings",
    // "media_redirection": "Media Redirection",
    // "title": "Remote Session",
    "remotesession": "Remote Session",
    "retry_count_must_be_a_number_from_1_to_6": "Retry count must be a number from 1 to 6",
    "retry_time_interval_must_be_a_number_from_5_to_30": "Retry time interval must be a number from 5 to 30",
    "remoteSessionStrongSuccessMsg": "Remote Session has been saved successfully.",
    "remoteSessionSuccessMsg": "",
    "remoteSessionStrongFailureMsg": "Error in saving Remote Session.",
    "remoteSessionFailureMsg": "",
    "remotesessionkvm_single_port_application": "KVM Single Port Application",
    "remotesessioncheck_this_option_to_enable_single_port_application_support_in_bmc_when_using_h5viewer": "Check this option to enable Single Port Application support in BMC  when using H5Viewer.",
    "remotesessionenable_kvm_encryption": "Enable KVM Encryption",
    "remotesessioncheck_this_option_to_enable_kvm_encryption_when_using_h5viewer_note_if_single_port_application_support_is_enabled_kvm_encryption_will_not_be_set_and_it_cannot_be_disabled_when_nonsecure_communication_is_not_allowed_": "Check this option to enable KVM Encryption when using H5Viewer. NOTE: If Single Port Application support is enabled, KVM Encryption will NOT be set and it cannot be disabled when non-secure communication is not allowed. ",
    "remotesessionkeyboard_language": "Keyboard Language",
    "remotesessionauto_detect_ad": "Auto Detect (AD)",
    "remotesessiondanish_da": "Danish (DA)",
    "remotesessiondutch_belgium_nlbe": "Dutch Belgium (NL-BE)",
    "remotesessiondutch_netherland_nlnl": "Dutch Netherland (NL-NL)",
    "remotesessionenglish_uk_gb": "English UK (GB)",
    "remotesessionenglish_us_us": "English US (US)",
    "remotesessionfinnish_fi": "Finnish (FI)",
    "remotesessionfrench_belgium_frbe": "French Belgium (FR-BE)",
    "remotesessionfrench_france_fr": "French France (FR)",
    "remotesessiongerman_germany_de": "German Germany (DE)",
    "remotesessiongerman_switzerland_dech": "German Switzerland (DE-CH)",
    "remotesessionitalian_it": "Italian (IT)",
    "remotesessionjapanese_jp": "Japanese (JP)",
    "remotesessionnorwegian_no": "Norwegian (NO)",
    "remotesessionportuguese_pt": "Portuguese (PT)",
    "remotesessionspanish_es": "Spanish (ES)",
    "remotesessionswedish_sv": "Swedish (SV)",
    "remotesessionturkish_f_tr_f": "Turkish F (TR_F)",
    "remotesessionturkish_q_tr_q": "Turkish Q (TR_Q)",
    "remotesessionselect_the_keyboard_language": "Select the Keyboard Language.",
    "remotesessionvirtual_media_attach_mode": "Virtual Media Attach Mode",
    "remotesessionattach": "Attach",
    "remotesessionauto_attach": "Auto Attach",
    "remotesessionselect_the_virtual_media_attach_mode": "Select the Virtual Media Attach Mode.",
    "remotesessionretry_count": "Retry Count",
    "retry_count": "Retry Count",
    "remotesessionnumber_of_times_to_be_retried_when_a_kvm_failure_occurs_retry_count_ranges_from_1_to_6": "Number of times to be retried when a KVM failure occurs. Retry count ranges from 1 to 6.",
    "remotesessionretry_time_intervalseconds": "Retry Time Interval(Seconds)",
    "retry_time_interval_in_seconds": "Retry Time Interval in seconds",
    "remotesessionnumber_of_seconds_to_wait_for_subsequent_retriestime_interval_ranges_from_5_to_30_seconds": "Number of seconds to wait for subsequent retries.Time interval ranges from 5 to 30 seconds.",
    "remotesessionserver_monitor_off_feature_status": "Server Monitor OFF Feature Status",
    "remotesessioncheck_this_option_to_enable_server_monitor_off_feature_status": "Check this option to enable Server Monitor OFF feature Status",
    "remotesessionautomatically_off_server_monitor_when_kvm_launches": "Automatically OFF Server Monitor, When KVM Launches",
    "remotesessioncheck_this_option_to_enable_automatically_off_server_monitor_when_kvm_launches": "Check this option to enable Automatically OFF Server Monitor, When KVM Launches",
    "remotesessionenable_server_aspect_ratio": "Respect aspect ratio when resizing JViewer window",
    "remotesessioncheck_this_option_to_enable_server_aspect_ratio": "Check this option to enable JViewer window to adapt with respect to aspect ratio",
    "remoteSessionSaveLabel": "Save",
    //mouse
    // "home": "Home",
    // "bmc_settings": "BMC Settings",
    // "title": "KVM Mouse Setting",
    "mousemouse_mode_configuration": "KVM Mouse Setting",
    "mouseStrongSuccessMsg": "KVM Mouse Setting has been saved successfully.",
    "mouseSuccessMsg": "",
    "mouseStrongFailureMsg": "Error in saving KVM Mouse Setting.",
    "mouseFailureMsg": "",
    "mousemouse_mode": "Mouse Mode",
    "mouserelative_positioning_linux": "Relative Positioning (Linux)",
    "mouseabsolute_positioning_windows": "Absolute Positioning (Windows)",
    "mouseother_mode_sles11_os_installation": "Other Mode (SLES-11)",
    "mousethe_redirection_console_handles_mouse_emulation_from_local_window_to_remote_screen_using_any_of_the_three_methods_administrator_only_have_the_rights_to_configure_this_option_ul_li_relative_mouse_modeli_li_absolute_mouse_modeli_li_other_mouse_modeli_ul_h4relative_mouse_modeh4_the_relative_mode_sends_the_calculated_relative_mouse_position_displacement_to_the_server_to_select_this_mode_select_the_set_mode_to_relative_option_h4absolute_mouse_modeh4_the_absolute_position_of_the_local_mouse_is_sent_to_the_server_to_select_this_mode_select_the_set_mode_to_absolute_option_recommended_for_windows_or_later_linux_releases_h4other_mouse_modeh4select_the_other_mode_to_have_the_calculated_displacement_from_the_local_mouse_in_the_centre_position_sent_to_the_server": "The Redirection Console handles mouse emulation from local window to remote screen using any of the three methods. 'Administrator' only have the rights to configure this option. <ul> <li>  Relative Mouse mode<\/li> <li>  Absolute Mouse mode<\/li> <li>  Other Mouse mode<\/li> <\/ul> <h4>Relative Mouse mode<\/h4> The Relative mode sends the calculated relative mouse position displacement to the server. To select this mode, select the 'Set mode to Relative' option. <h4>Absolute Mouse mode<\/h4> The absolute position of the local mouse is sent to the server. To select this mode, select the 'Set mode to Absolute' option. Recommended for Windows or later Linux releases. <h4>Other Mouse mode<\/h4>Select the \"Other Mode \" to have the calculated displacement from the local mouse in the centre position, sent to the server.",
    "mouseSaveLabel": "Save",

    "launch_java_KVM" : "Launch Java KVM",
    "launch_h5_KVM" : "Launch H5 KVM",
   });
