define({
    "home": "Home",
    "remote_control": "Remote Control",
    "image_redirection": "Image Redirection",
    //ks_lz20181024_vmmedia ++>>
    "title": "Media Redirection Settings",
    "settings": "BMC Settings",
    "tag": "",
    "remote_images": "Remote Media",
    "local_images" : "Local Media",
    "general_setting":"Function settings",
    //ks_lz20181024_vmmedia ++<<
    "tag_start": "Emulate ",
    "tag_cd_dvd": "CD\/DVD\/",
    "tag_fd": "Floppy\/",
    "tag_hd": "HDD",
    "tag_end": " images in the network to host as media through BMC",
    "media_type": "Media Type",
    "cddvd": "CD\/DVD",
    "floppy": "Floppy",
    "hard_disk": "Hard disk",
    "media_instance": "Media Instance",
    "image_name": "Image Name",
    "status": "Redirection Status",
    "halted": "Stopped",
    "started": "Started",
    //ks_lz20190130_tapd_1001755 ++>>
    "start_mounting":"Mounting...",
    "status_0": "~",
    "status_1": " - Connection Accepted",
    "status_2": " - Connection Denied",
    "status_3": " - Login Failed",
    //"status_4": " - Connection in Use",
    "status_4": " - MAX Session Reached",
    "status_5": " - Permission Denied",
    "status_6": " - Unknown Error",
    "status_7": " - Media Detach Stage",
    "status_8": " - Maximum User Reached",
    "status_9": " - Unable to Connect",
    "status_10": " - Invalid Image",
    "status_11": " - Mount Error",
    "status_12": " - Unable to Open",
    "status_13": " - Media License Expired",
    "status_14": " - Connection Lost",
    "status_15": " - Mount Cancelled By User",
    "status_16": " - Device Ejected",
    "status_17": " - Session Terminated",
    "session_index": "Connected Server Session",
    "refreshImageList":"Refresh Image List",
    "hlpRmedia":"Click Refresh Image List to get the latest Images from Remote storage.",
    "load_tip": "Click here to Load the latest image list",
    "start_redirection": "Click here to Start Redirection",
    "clear_image": "Click here to Clear the Image",
});
