define({
    "home": "Home",
    "settings": "BMC Settings",
    "title": "Users / Groups",
    "users_list": "Users List",
    "edit_title": "Edit User",
    "disabled": "(Disabled)",
    "active": "(Active)",
    "empty_slot": "(Empty Slot)",
    "no_access": "No Access",
    "administrator": "Administrator",
    "oem": "OEM",
    "operator": "Operator",
    "user": "User",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "snmp": "SNMP",
    "invalid_username_refer_help_content": "Invalid Username. Refer Help content.",
    "password_field_must_be_8_characters_atleast": "Invalid Password. Refer Help content.",
    "passwords_do_not_match": "Passwords do not match",
    "invalid_email_format_refer_help_content": "Invalid Email ID. Refer Help content.",
    "users": "",
    "strongSuccessMsg": "Saved successfully!",
    "successMsg": "",
    "strongFailureMsg": "Saved operation failed, try again later.",
    "failureMsg": "",
    "userNameIsExist": "The new user name already exists.",
    "Failed_to_get_user_information": "Failed to get user information.",
    "Failed_to_set_creation_time": "Failed to set creation time.",
    "Failed_to_set_user_information": "Failed to set user information.",
    "Failed_to_set_SNMP": "Failed to set SNMP.",
    "Failed_to_set_email": "Failed to set email.",
    "Failed_to_set_email_format": "Failed to set email format.",
    "Failed_to_set_extended_privilege": "Failed to set extended privilege.",
    "Failed_to_set_ssh_key": "Failed to set ssh key.",
    "usersusername": "Username",
    "usersenter_the_name_of_the_new_user_ulli_user_name_is_a_string_of_1_to_16_alphanumeric_charactersli_li_it_must_start_with_an_alphabetical_characterli_li_it_is_casesensitiveli_li_special_characters_hyphen_underscore_at_sign_are_allowedliul": "Enter the name of the new user.  <ul><li>User Name is a string of 1 to 16 alpha-numeric  characters.<\/li> <li>It must start with an alphabetical character.<\/li> <li>It is case-sensitive.<\/li> <li>Special characters '-'(hyphen),  '_'(underscore), '@'(at sign) are allowed.<\/li><\/ul>",
    "userspassword": "Password",
    "usersenter_a_strong_password_including_a_alphabets_numbers_symbol_and_upper_case_characters": "Enter a strong password which consist of atleast one upper case letter, alphanumeric and special characters.",
    "usersconfirm_password": "Confirm Password",
    "usersconfirm_the_password": "Confirm the password",
    "userspassword_size": "Password Size",
    "users16_bytes": "16 bytes",
    "users20_bytes": "20 bytes",
    "userssize_of_the_password": "Select the Max Size of the password.",
    "usersenable_user_access": "Enable User Access",
    "userscheck_the_box_to_enable_user_access_for_the_user": "Check the box to enable user access for the user. Upon enabling the user Access, the IPMI messaging privilege will be assigned to user. <br><strong>NOTE:</strong> It is recommended that the IPMI messaging option should be enabled for the user to choose the<strong> User Access</strong> option, while creating User through IPMI.",
    "usersnetwork_privilege": "Network Privilege",
    "usersuser": "User",
    "usersadministrator": "Administrator",
    "usersoperator": "Operator",
    "usersoem": "OEM",
    "usersnone": "None",
    "usersselect_the_privilege_level_assigned_to_this_user_when_the_user_access_bmc_through_network_interface_5_levels_are_available_administrator_operator_user_oem_and_no_access": "Select the privilege level assigned to this user when the user accesses BMC through network interface. There are 5 levels of Network Privileges (Administrator, Operator, User, OEM and No Access).",
    "usersserial_privilege": "Serial Privilege",
    "usersselect_the_privilege_level_to_be_assigned_to_this_user_when_the_user_access_bmc_through_serial_interface_5_levels_are_available_administrator_operator_user_oem_and_no_access": "Select the privilege level assigned to this user when the user accesses BMC through network interface. There are 5 levels of Network Privileges (Administrator, Operator, User, OEM and No Access).",
    "userskvm_access": "KVM Access",
    "usersthis_field_is_used_to_assign_the_kvm_privilege_for_the_user": "This field is used to assign the KVM  privilege for the user.",
    "usersvmedia_access": "VMedia Access",
    "usersthis_field_is_used_to_assign_the_vmedia_privilege_for_the_user": "This field is used to assign the VMedia privilege for the user.",
    "userssnmp_access": "SNMP Access",
    "userscheck_the_box_to_enable_snmp_access_for_the_user": "Check the box to enable SNMP access for the user.<strong>NOTE:</strong>Password is mandatory to be entered while enabling SNMP Access and should have minimum 8 characters when SNMP status is enabled.",
    "userssnmp_access_level": "SNMP Access level",
    "usersread_only": "Read Only",
    "usersread_write": "Read Write",
    "userschoose_the_snmp_access_level_option_for_user_it_can_be_either_read_only_or_read_write": "Choose the SNMP Access level option for user. It can be either Read Only or Read Write.",
    "userssnmp_authentication_protocol": "SNMP Authentication Protocol",
    "userssha": "SHA",
    "usersmd5": "MD5",
    "userschoose_an_authentication_protocol_for_snmp_settings_strongnotestrong_password_field_is_mandatory_if_authentication_protocol_is_changed": "Choose an Authentication Protocol for SNMP settings. <strong>NOTE:<\/strong> Password field is mandatory, if  Authentication protocol is changed.",
    "userssnmp_privacy_protocol": "SNMP Privacy Protocol",
    "usersdes": "DES",
    "usersaes": "AES",
    "userschoose_the_encryption_algorithm_to_use_for_snmp_settings": "Choose the Encryption algorithm to use for SNMP settings.",
    "usersemail_format": "Email Format",
    "usersamiformat": "AMI-Format",
    "usersfixedsubjectformat": "FixedSubject-Format",
    "usersspecify_the_format_for_the_email_this_format_will_be_used_while_sending_the_email_two_type_of_formats_are_available_ulli_amiformat_the_subject_of_this_mail_format_is_alert_from_your_hostname_the_mail_content_shows_sensor_information_ex_sensor_type_and_descriptionliul_ulli_fixedsubjectformat_this_format_displays_the_message_according_to_users_setting_you_must_set_the_subject_and_message_for_email_alertliul": "Specify the format for the email. This format will be used,  while sending the email. Two type of formats are available: <ul><li>AMI-Format: The subject of this mail format is 'Alert from (your Hostname)'. The mail content shows sensor information, ex: Sensor type  and Description.<\/li><\/ul> <ul><li>FixedSubject-Format: This format displays the message according to user's setting.  You must set the subject and message for email alert.<\/li><\/ul>",
    "usersemail_id": "Email ID",
    "usersenter_the_email_id_for_the_user_if_user_forgets_the_password_new_password_will_be_mailed_to_the_configured_email_id_strongnotestrong_smtp_server_must_be_configured_to_send_the_email": "Enter the email ID for the user. If user forgets the password,  new password will be mailed to the configured email ID.<br/> <strong>NOTE:<\/strong> SMTP Server must be configured to send  the email.<br/>Maximum allowed size for Email ID is 64 bytes which includes username and domain name.",
    "usersexisting_ssh_key": "Existing SSH Key",
    "usersthe_uploaded_ssh_key_information_will_be_displayed_read_only": "The uploaded SSH key information will be displayed (read only).",
    "usersupload_ssh_key": "Upload SSH Key",
    "usersuse_browse_button_to_navigate_to_the_public_ssh_key_file_ulli_ssh_key_file_should_be_of_pub_typeliul": "Use Browse button to navigate to the public SSH key file. <ul><li>SSH key file should be of pub type.<\/li><li>SSH key file size should not exceed 4KB.<\/li><\/ul>",
    "usersupload_ssh_key_exceed": "SSH key file size should not exceed 4KB.",
    "deleteLabel": "Delete",
    "saveLabel": "Save",
    "user_management": "User Management",
    "non_privilege_user_delete": "You don't have permission to delete this user.",
    "delete_confirmation_message": "Are you sure want to delete the user?",
    "Failed_to_delete_user_email": "Failed to delete user email.",
    "Failed_to_delete_lan_information": "Failed to delete lan information.",
    "Failed_to_delete_snmp": "Failed to delete snmp.",
    "Failed_to_delete_user": "Failed to delete user.",
    "user_hlp":"The list below shows the current list of available users. To Add,Delete or Edit a user, click on icon.<br/>A maximum of 10 slots are available and include the default of admin and anonymous.<br/>It is advised that the anonymous user's privilege and password should be modified as a security measure. To view the page, you must have Operator privileges.To modify or add a user, You must have Administrator privileges.",
    "add_user":"Add User",
    "password_complexity":"User Password Complexity",
    //fanysh_jd_user_require_0509
    "usersenter_a_strong_password_minlenth_to_maxlenth": "Enter a password which must be 8 characters at least.",
    "userscheck_the_box_to_enable_password_complexity":"If enable user password complexity which password should consist of at least one upper case letter, one lower case letter, an alphanumeric and one special character.",
    "userscheck_the_box_to_change_password":"Select this option to change the password.",
    "change_password":"Change Password",
    "belong_group":"Group",
    "belong_group_help":"By selecting the group, the user will have different privileges. User privileges are controlled by grouping.",
    "select_group":"Please Select the user group",
    "turnon_password_expiry_help":"When select this option, the systerm will validate the expiration date of the user password.",
    "turnon_password_expiry":"Enable Password Expiration",
    "password_expiry_help":"Used to control the expiration date of user's password.",
    "password_expiry_date":"Password Expiration Date",
    "setting_password_expiry_date":"Please selects password expiration date",
    "allow_user_number": "System only allows to create {n} users",

    /*用户组管理-多语化数据*/
    "edit_group": "Edit Group",
    "edit_user": "Edit User",
    "loading" : "Loading",
    "undata" : "No data",
    "tab_users": "Users",
    "tab_groups": "Groups",
    "role": "Groups Role",
    "any_role": "Any Role",
    "privilege": "Advanced Privileges",
    "any_privilege": "Any Privilege",
    "add_group": "Add Group",
    "members": "Members",
    "edit": "Edit",
    "delete": "Delete",
    "user_info": "User Info",
    "group_info": "Group Info",
    "save": "Save",
    "group_name": "Group Name",
    "name_notNull": "Name cannot be empty",
    "role_notNull": "Role cannot be empty",
    "save_success": "Saved successfully!",
    "save_failed": "Saved failed.",
    "name_exists": "Name already exists, please re-enter.",
    "group_deleteSure": "Are you sure want to delete the group?",
    "yes": "Yes",
    "no": "No",
    "no_member": "No Member",
    "not_edited_group": "The current group is reserved for the system and cannot be edited.",
    "allow_group_number": "System only allows to create {n} groups",
    "not_deleted_group": "There is users in the group and cannot be deleted.",
    "delete_success": "Deleted successfully!",
    "login_again": "Password has been modified, please login again!",
    // ks_lz_20190228_TAPDID_1015590 ++
    "repeat_verify_config_error": "Please ensure that the password to be changed is different from the password set in the last three times."
});
