define({
    "home": "Home",
    "settings": "BMC Settings",
    "user_group":"Users / Groups",
    "title": "Edit Group",
    "disabled": "(Disabled)",
    "active": "(Active)",
    "empty_slot": "(Empty Slot)",
    "no_access": "No Access",
    "administrator": "Administrator",
    "oem": "OEM",
    "operator": "Operator",
    "user": "User",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "snmp": "SNMP",
    "strongSuccessMsg": "Saved!",
    "successMsg": "Operated successfully!",
    "strongFailureMsg": "Operation failed, try again later.",
    "failureMsg": "I'll try to reason out the error",


    /*用户组管理-多语化数据*/
    "edit_group": "Edit Group",
    "edit_user": "Edit User",
    "loading": "Loading",
    "undata": "No data",
    "tab_users": "Users",
    "tab_groups": "Groups",
    "role": "Groups Role",
    "any_role": "Any Role",
    "privilege": "Advanced Privileges",
    "any_privilege": "Any Privilege",
    "add_group": "Add Group",
    "members": "Members",
    "edit": "Edit",
    "delete": "Delete",
    "user_info": "User Info",
    "group_info": "Group Info",
    "save": "Save",
    "group_name": "Group Name",
    "name_notNull": "Group Name cannot be empty",
    //"name_character": "Special characters are only allowed for '-' (hyphen), '_' (underscore), '@' (at sign).",
    "name_character": "Group Name requires a string of numbers and letters.Special characters '-',  '_', '@' are allowed.",
    "name_chinese": "Group Name is not allowed to enter Chinese.",
    "name_length": "Group Name cannot be longer than 30 characters",
    "role_notNull": "Role cannot be empty",
    "save_success": "Saved successfully!",
    "save_failed": "Saved failed.",
    "name_exists": "Name already exists, please re-enter.",
    "group_deleteSure": "Are you sure want to delete the group?",
    "yes": "Yes",
    "no": "No",
    "no_member": "No Member",
    "not_edited_group": "The current group is reserved for the system and cannot be edited.",
    "allow_group_number": "System only allows to create {n} groups",
    "not_deleted_group": "There is users in the group and cannot be deleted.",
    "delete_success": "Deleted successfully!",
    "user_groups_change_note": "The user in the current user group is not empty. It is not allowed to modify the user group name.",  //ks_lz20181024_groupname ++
    "user_privilage_note":"None user groups cannot use any permissions",                 //ks_lz20181108_Privilage ++
});