define({
    "home": "主页",
    "settings": "BMC 设置",
    "alarm_settings": "告警设置",

    //snmp
    "snmp_trap_title": "SNMP Trap 设置",
    "snmp": "SNMP Trap 设置",
    "no_snmp_trap_information": "查询SNMP Trap 设置信息发生错误。",
    "snmpTrapStrongSuccessMsg": "SNMP Trap 设置保存成功",
    "snmpTrapSuccessMsg": "",
    "snmpTrapStrongFailureMsg": "SNMP Trap 设置发生错误",
    "snmpTrapFailureMsg": "",
    "rw_char": "读写团体名",
    "ro_char": "只读团体名",
    "snmpcheck_this_option_to_enable_snmp_support_for_the_bmc" : "按下此选项将启动BMC上的SNMP支持。",
    "snmp_support": "SNMP 支持",
    "snmp_protocol": "SNMP 协议",
    "snmp_visit": "SNMP 访问",
    "privacy_protocol": "隐私协议",


    "snmpTrapSaveLabel": "保存",
    "help_information":"设置SNMP v1/v2服务，团体名的读写权限。\n SNMP v3服务，请通过\"用户管理\"页面进行配置。",
    "trap_help_information":"SNMP v1/v2服务，请输入团体名称。\n SNMP V3服务，请选择用户名称（注：用户密码长度不能少于8位）。",
    "trap_help_snmp_addr":"只有已保存的SNMP地址，才能进行测试。系统不会检查测试结果，请自行确认是否测试成功。",

    "whether_enable": "启用SNMP Trap告警",
    "on": "是",
    "off": "否",
    "v1": "V1",
    "v2": "V2",
    "v3": "V3",
    "community": "团体名",
    "v3_user": "V3用户（注：密码长度不能少于8位）",
    "not_null": "不能为空",
    "alarm_grade": "告警等级",
    "check_all": "全选",
    "urgency": "紧急",
    "critical": "严重",
    "non_critical": "轻微",
    "normal": "正常",
    "snmp_addr": "SNMP 地址",
    "snmp_test": "测试",
    "ip_incorrect": "IP地址格式不正确",
    "sent_to_ip": '测试信息已发送到 <strong>{IP}<\/strong>，请确认是否有收到，系统并不会检查接收是否成功。',
    "sent_to_ip_error": '测试SNMP 地址 <strong>{IP}<\/strong> 发生错误。',

    //smtp
    "smtp_title": "SMTP 设置",
    "no_smtp_setting_information": "查询SMTP 设置信息发生错误。",
    "smtpStrongSuccessMsg": "SMTP 设置已保存成功。",
    "smtpStrongFailureMsg": "保存 SMTP 设置发生错误。",
    "smtpprimary_smtp_support": "启用 SMTP",
    "smtpcheck_this_option_to_enable_smtp_support_for_the_bmc": "点击复选框此选项来启动 BMC 上的 SMTP 支持。",
    "smtpsender_email_id": "发件人邮箱地址",
    "smtpcheck_email_help":"在SMTP服务器上输入有效的电子邮件。最大允许大小的电子邮件是64字节，其中包括用户名和域名。",
    "smtpprimary_server_name": "服务器名称",
    "smtpenter_the_machine_name_of_the_smtp_server_ul_li_machine_name_is_a_string_of_maximum_15_alphanumeric_charactersli_li_space_special_characters_are_not_allowedli_ul": "输入 SMTP 服务器的“主机名”。 <ul> <li> 主机名是一个最长为 25 个字母数字的字串。<\/li> <li> 不允许使用空白, 特殊字符。<\/li> <\/ul>",
    "smtpprimary_server_ip": "服务器 IP",
    "smtp_enter_the_ip_address_of_the_smtp_server_it_is_a_mandatory_field_ul_li_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxx_xxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul_server_address_will_support_the_following_ul_li_ipv4_address_format_li_ipv6_address_format_ul": " 输入 SMTP 服务器“IP 地址”。此为必填栏位。 <ul> <li> IP 地址由 4 个数字并以点来隔开如下， 'xxx.xxx.xxx.xxx'。<\/li> <li> 每一个数字范围为 0 到 255。<\/li> <li> 第一个数字不能为 0。 <\/li> <\/ul> 服务器地址支持以下格式: <ul> <li> IPv4 地址格式。 <li> IPv6 地址格式。 <\/ul>",
    "smtpenter_the_password_for_the_smtp_user_account_ul_li_password_must_be_at_least_4_characters_longli_li_white_space_is_not_allowedli_ul_strongnotestrong_this_field_will_not_allow_more_than_64_characters": "输入 发件人邮箱的密码。 <ul> <li> 密码至少要有四个字符。<\/li> <li> 不允许使用空格。<\/li> <\/ul> <strong>注意:<\/strong> 此栏位不允许超过 64 个字符。",
    "smtpprimary_password": "发件人邮箱密码",
    "mail_theme_help": "发送告警邮件的主题。",
    "mail_theme": "邮件主题",
    "alarm_grade": "告警等级",
    "check_all": "全选",
    "urgency": "紧急",
    "critical": "严重",
    "non_critical": "轻微",
    "normal": "正常",
    "receiving_mail_help":"输入接收告警的电子邮箱信息。 <ul> <li> 输入正确的邮箱地址后，才能启用接收告警功能。<\/li> <li> 保存邮箱信息后，才能进行测试。<\/li> <\/ul> <strong>注意:<\/strong> 系统不会检查测试结果，请自行确认是否测试成功。",
    "receiving_mail": "收件人邮箱信息",
    "mailbox": "邮箱",
    "description": "描述",
    "test_mailbox": "测试",
    "sent_to_mailAddr": '测试邮件已发送到 <strong>{mailAddr}<\/strong>，请确认是否有收到，系统并不会检查接收是否成功。',
    "sent_to_mailAddr_error": '测试邮箱 <strong>{mailAddr}<\/strong> 发生错误。',
    "primary_server_ip_is_required_valid": "输入有效的服务器 IP。",
    "primary_server_name_is_required": "输入有效的服务器名称。",
    "smtp_invalid_email_format_refer_help_content": "输入有效的邮箱地址。",
    "username_for_primary_server_is_required": "输入有效的邮件主题。",
    "password_for_primary_server_is_required": "输入有效的发件人邮箱密码。",
    "smtpSaveLabel": "保存",

    ///////////////////////////
    /*"smtp": "",
    "primary_smtp_support_is_required": "需要主要 SMTP 支持",
    "primary_server_port_is_required": "需要主服务器端口，端口范围于 1-65535",
    "primary_server_secure_port_is_required": "需要有效的服务器安全端口",
    "primary_server_ip_is_required": "需要有效的主服务器 IP",
    "secondary_server_name_is_required": "需要验证主服务器名称",
    "secondary_server_port_is_required": "需要验证主服务器端口",
    "secondary_server_secure_port_is_required": "需要有效的从服务器安全端口",
    "secondary_server_ip_is_required": "需要有效的主服务器 IP",
    "username_for_secondary_server_is_required": "需要从服务器用户名",
    "password_for_secondary_server_is_required": "需要从服务器密码",
    "successMsg": "",
    "failureMsg": "",
    "smtplan_interface": "LAN 界面",
    "smtpprimary_smtp_port": "主 SMTP 端口",
    "smtpspecify_the_smtp_port_ul_li_default_port_is_25li_li_port_value_ranges_from_1_to_65535li_ul": "指定 SMTP 端口。 <ul> <li> 默认端口号是 25.<\/li> <li> 端口范围为 1 到 65535。<\/li> <\/ul>",
    "smtpprimary_secure_smtp_port": "主 SMTP 安全端口",
    "smtpspecify_the_smtp_secure_port_ul_li_default_port_is_465li_li_port_value_ranges_from_1_to_65535li_ul": "指定 SMTP 安全端口。 <ul> <li> 默认端口号是465.<\/li> <li> 端口范围为 1 到 65535。<\/li> <\/ul>",
    "smtpprimary_smtp_authentication": "主 SMTP 身份认证",
    "smtpcheck_the_option_enable_to_enable_smtp_authentication_note_smtp_server_authentication_types_supported_are_ul_li_crammd5li_li_loginli_li_plainli_ul_if_the_smtp_server_does_not_support_any_one_of_the_above_authentication_types_the_user_will_get_an_error_message_stating_iauthentication_type_is_not_supported_by_smtp_serveri":"点击选项“启用” SMTP 身份认证。 注意: SMTP 服务器认证支持以下方式如: <ul> <li> CRAM-MD5<\/li> <li> LOGIN<\/li> <li> PLAIN<\/li> <\/ul> 如果 SMTP 服务器不支持以上任何一种认证方式，用户会收到错误信息， <i>“认证类型不受 SMTP 服务器支持”<\/i>",
    "smtpprimary_username": "主要用户名",
    "smtpenter_the_username_to_access_smtp_accounts_ul_li_user_name_can_be_of_length_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetli_li_special_characters_comma_colon_semicolon_space_and_backslash_are_not_allowedli_ul":"输入用户名来存取 SMTP 账号。 <ul> <li> 用户名可以是长度 4-64 字母数字组成的字符串。<\/li> <li> 开头必需要是字母。<\/li> <li> 不允许使用特殊字符','(comma), ':'(colon), ';'(semicolon), ' '(space) and '\\'(backslash)。<\/li> <\/ul>",
    "smtpprimary_smtp_ssltls_enable": "启用主要 SMTP SSLTLS",
    "smtpcheck_the_option_enable_to_enable_smtp_ssltls_protocol": "点击选项“启用”来启用 SMTP SSLTLS 协议。",
    "smtpprimary_smtp_starttls_enable": "启用主要 SMTP STARTTLS ",
    "smtpcheck_the_option_enable_to_enable_smtp_starttls_protocol": "点击选项“启用”来启用 SMTP SSLTLS 协议。",
    "smtpupload_smtp_ca_certificate_file": "上传 SMTP CA 认证文件",
    "smtpuse_browse_button_to_navigate_to_upload_cacert_ulli_cacert_key_file_should_be_of_pem_typeliul": "使用浏览按钮来上传 CACERT. <ul><li> CACERT 密钥文件应该为 pem 类型。<\/li><\/ul>",
    "smtpupload_smtp_certificate_file": "上传 SMTP 认证文件",
    "smtpuse_browse_button_to_navigate_to_upload_cert_ulli_cert_key_file_should_be_of_pem_typeliul": "使用浏览按钮来上传 CERT. <ul><li> CERT 密钥文件应该为 pem 类型。<\/li><\/ul>",
    "smtpupload_smtp_private_key": "上传 SMTP 私有密钥",
    "smtpuse_browse_button_to_navigate_to_upload_smtp_key_ulli_smtp_key_file_should_be_of_pem_typeliul": "使用浏览按钮来上传 SMTP 密钥. <ul><li> SMTP 密钥文件应该为 pem 类型。<\/li><\/ul>",
    "smtpsecondary_smtp_support": "次要 SMTP 支持",
    "smtpcheck_this_option_to_enable_secondary_smtp_support_for_the_bmc": "点击选项来启用 BMC 上的次要 SMTP 支持。",
    "smtpsecondary_server_name": "从服务器名称",
    "smtpenter_the_machine_name_of_the_secondary_smtp_server_ul_li_machine_name_is_a_string_of_maximum_15_alphanumeric_charactersli_li_space_special_characters_are_not_allowedli_ul": "输入次要 SMTP 服务器的“主机名”。 <ul> <li> 主机名是一个最长为 15 个字母数字的字串。<\/li> <li> 不允许空格以及特殊字符。<\/li> <\/ul>",
    "smtpsecondary_server_ip": "从服务器 IP",
    "smtp_enter_the_ip_address_of_the_secondary_smtp_server_ul_li_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxx_xxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul_server_address_will_support_the_following_ul_li_ipv4_address_format_li_ipv6_address_format_ul":
    "输入次要 SMTP 服务器“IP 地址”。  <ul> <li> IP 地址由 4 个数字并以点来隔开如下， 'xxx.xxx. xxx.xxx'。<\/li> <li>每一个数字范围为 0 到 255。<\/li> <li> 第一个数字不能为 0。<\/li> <\/ul> 服务器地址支持以下格式: <ul> <li> IPv4 地址格式。 <li> IPv6 地址格式。<\/ul>",
    "smtpsecondary_smtp_port": "次要 SMTP 端口",
    "smtpspecify_the_secondary_smtp_port_ul_li_default_port_is_25li_li_port_value_ranges_from_1_to_65535li_ul": "指定次要 SMTP 端口。 <ul> <li> 默认端口是 25。<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpsecondary_smtp_secure_port": "次要 SMTP 安全端口",
    "smtpspecify_the_secondary_smtp_secure_port_ul_li_default_port_is_465li_li_port_value_ranges_from_1_to_65535li_ul": "指定次要 SMTP 安全端口。 <ul> <li> 默认端口是 465。<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpsecondary_smtp_authentication": "次要 SMTP 认证",
    "smtpcheck_the_option_enable_to_enable_secondary_smtp_authentication_note_smtp_server_authentication_types_supported_are_ul_li_crammd5li_li_loginli_li_plainli_ul_if_the_smtp_server_does_not_support_any_one_of_the_above_authentication_types_the_user_will_get_an_error_message_stating_iauthentication_type_is_not_supported_by_smtp_serveri": "点击选项“启用”次要 SMTP 身份认证。注意: SMTP 服务器认证支持以下方式如： <ul> <li> CRAM-MD5<\/li> <li> LOGIN<\/li> <li> PLAIN<\/li> <\/ul> 如果 SMTP 服务器不支持以上任何一种认证方式，用户会收到错误信息， <i>“认证类型不受 SMTP 服务器支持”<\/i>",
    "smtpsecondary_username": "次要用户名",
    "smtpsecondary_password": "次要密码",
    "smtpsecondary_smtp_ssltls_enable": "启用次要 SMTP SSLTLS",
    "smtpsecondary_smtp_starttls_enable": "启用次要 SMTP STARTTLS ",
    "smtpuse_browse_button_to_navigate_to_upload_key_ulli_key_file_should_be_of_pem_typeliul": "Use Browse button to navigate to upload KEY. <ul><li>  密钥文件应该为 pem 类型。<\/li><\/ul>",
    "must_upload_files": "请选择一个 .pem 的档案来上传",*/


    //syslog
    "advancedLogTitle": "Syslog 设置",
    "advanced_log": "Syslog 设置",
    "invalid_remote_log_server_address_refer_help_for_more_information": "无效的远程日志服务器地址。请点击“帮助”来获取更多信息。",
    "invalid_port_refer_help_for_more_information": "无效的端口。请点击“帮助”来获取更多信息。",
    "invalid_file_size_refer_help_for_more_information": "无效的文件大小。请点击“帮助”来获取更多信息。",
    "invalid_rotate_count_value_refer_help_for_more_information": "无效的循环数量。请点击“帮助”来获取更多信息。",
    "advancedLogStrongSuccessMsg": "日志设置成功保存。",
    "advancedLogSuccessMsg": "",
    "advancedLogStrongFailureMsg": "日志设置保存失败。",
    "advancedLogFailureMsg": "",
    "advanced_logenable_system_log": "启用系统日志",
    "advanced_logselect_enable_system_log_to_view_all_system_events_entries_can_be_filtered_based_on_their_classification_levels": "选择启用系统日志来查看所有系统事件。 可以通过分类级别对栏位进行筛选。",
    "advanced_loglocation": "位置",
    "advanced_loglocal_log": "本地日志",
    "advanced_logremote_log": "远程日志",
    "advanced_logfile_sizebytes": "文件大小(字节)",
    "size_in_bytes": "大小 (字节)",
    "advanced_logif_local_log_is_selected_specify_the_size_of_the_file_in_bytesulli_size_ranges_from_3_to_65535lililog_files_are_rotated_when_the_size_is_larger_than_the_mentioned_bytes_with_regards_for_the_last_rotation_time_interval_1_minuteliul": "如果选择本地日志, 指定文件大小 (字节)。<ul><li> 大小范围从 3 到 65535。<\/li><\/ul>",
    "advanced_logrotate_count": "旋转计数",
    "maximum_count": "最大数量",
    "advanced_logwhen_logged_information_exceeds_the_specified_file_size_the_old_log_information_automatically_gets_moved_to_back_up_files_based_on_the_rotate_count_value_if_the_rotate_count_is_zero_the_old_log_information_gets_cleared_permanently_each_timeulli_rotate_count_value_must_be_0_or_1liul": "当登录时超过指定文件大小的信息，旧的日志信息基于旋转计数值自动获取到备份文件。如果旋转计数为零，则旧的日志信息每次永久清除。<ul><li> 旋转计数值必须为 0 或 1。<\/li><\/ul>",
    "advanced_logremote_log_server": "远程日志服务器1",
    "advanced_logremote_log_server1": "远程日志服务器2",
    "server_ip_or_hostname": "服务器 IP 或主机名",
    "advanced_logspecify_the_remote_server_address_to_log_system_events_server_address_support_the_followingulli_ip_address_both_ipv4_and_ipv6_formatlili_fqdn_fully_qualified_domain_name_formatliulstrongnotestrong_maximum_allowed_size_for_remote_log_server_address_is_64_bytes": "服务器地址支持以下格式:<ul><li> IP 地址 ( IPv4 和 IPv6 格式)。<\/li><li> 域名全称格式<\/li><\/ul>",
    "advanced_logremote_server_port": "远程服务器1端口",
    "advanced_logremote_server_port1": "远程服务器2端口",
    "server_port": "服务器端口",
    "advanced_logspecify_the_port_number_to_log_system_eventsbrstrongnotestrong_the_default_port_number_is_514": "指定端口来记录系统事件。<br><strong>注意:<\/strong> 默认端口号是 514.",
    "advanced_logenable_audit_log": "启用审计日志",
    "advanced_logselect_enable_audit_log_to_view_all_audit_events_for_this_device": "选择启用审计日志来查看所有装置上的审计日志。",
    "advancedLogSaveLabel": "保存",
    "audit_log_to_remote": "远程审计日志",
    "pef_sel_to_remote": "远程PEF事件",
    "enable_remote_log": "启动远程日志",
    "alarm_grade": "告警等级",
    "check_all": "全选",
    "urgency": "紧急",
    "critical": "严重",
    "non_critical": "轻微",
    "normal": "正常",
    "not_null": "不能为空",
});
