define({
    "system_maintenance": "系统维护",
    "title": "备份/恢复配置",
    "home": "主页",
    "backup_config": "备份配置",
    "backupStrongSuccessMsg": "备份配置设置已成功保存。",
    "backupSuccessMsg": "",
    "backupStrongFailureMsg": "下载备份配置设置发生错误。",
    "backupFailureMsg": "",
    "backup_configcheck_all": "全选",
    "backup_configcheck_the_configuration_that_needs_to_be_backed_up_you_will_get_a_file_download_you_can_use_the_same_to_restore_the_configuration_when_neededbrbnote_b_network_configurations_are_interrelated_to_ipmi_and_hence_by_default_ipmi_configurations_will_be_selected_automatically_when_you_select_network_and_services_to_be_backed_up": "选取配置中需要备份的项目。你将会取得一个下载文档。你需要的时候可以使用相同的配置恢复<br><b>注意 : <\/b> 网路设置与内部IPMI相关，因此IPMI默认设置将会被挑选当你选择'网路和服务'去做备份",
    "backup_configsnmp": "SNMP",
    "backup_configkvm": "KVM",
    "backup_confignetwork_services": "网络 & 服务",
    "backup_configipmi": "IPMI",
    "backup_configntp": "NTP",
    "backup_configauthentication": "认证",
    "backup_configsyslog": "SYSLOG",
    "downloadLabel": "下载配置",
    //恢复配置
    "restore_config": "恢复配置",
    "upload_config_file": "上传配置文件",
    "restoreStrongSuccessMsg": "配置恢复成功。",
    "restoreSuccessMsg": "---Logout",
    "restoreStrongFailureMsg": "恢复备份配置时发生错误。",
    "restoreFailureMsg": "",
    "restore_configconfig_file": "配置文件",
    "restore_configuse_browse_button_to_navigate_to_the_configuration_file": "使用搜索按钮来浏览配置文件。",
    "saveConfirmLabel": "点击 OK 来继续进行恢复配置    警告:恢复配置设备将重新启动",
    "saveLabel": "上传"
});