define({
    "parenttitle":"远程控制",
    "cooling_policy" : "散热策略",
    "tag" : "配置散热策略",
    "home" : "主页",
    "cooling_policy_action" : "散热策略",
    "load":"加载中",
    "balance" : "平衡模式",
    "manual":"手动模式",
    "performance" : "性能模式",
    "silent" : "静音模式",
    "unknow":"未知",
    "duty":"设置手动转速百分比(%)",
    "less_than_50":"<50，",
    "positive_integer_within_100":"请输入100以内的正整数",
    "perform_action" : "执行",
    "server_config" : "服务器配置",
    "confirm" : "确定执行该操作吗？",
    "long_control" : "远程控制",
    "help_selection":"展示并配置散热策略",
    "status":"当前状态:",
    "is_manual_duty": "设置当前模式最低转速百分比(%)",
    "on": "是",
    "off": "否",
    "positive_integer_within_20_100":"请输入20-100的正整数",

});
