define({
    "home": "主页",
    "settings": "BMC 设置",
    "title": "日期 &amp; 时间",
    "general_date_timeconfigure_date_amp_time": "配置日期 &amp; 时间",
    "primary_ntp_server_is_required": "需要主 NTP 服务器",
    "date_time_setting_valid_ntp": "请输入一个有效的 IP 地址或域名",
    "strongSuccessMsg": "日期 & 时间设置已保存成功。这会花数秒时间使配置生效,请关闭浏览器并再次开启浏览器。",
    "successMsg": "",
    "strongFailureMsg": "保存日期 &amp; 时间发生错误",
    "failureMsg": "",
    "general_date_timethis_field_is_used_to_set_the_date_on_the_bmc": "本栏位用来设置 BMC 上的日期与时间。",
    "general_date_timepicker": "BMC 日期 & 时间",
    "general_date_timetimezone": "时区",
    "general_date_timethis_field_is_used_to_set_the_timezone_of_the_bmc": "本栏位用来设置 BMC时区。",
    "general_date_timeprimary_ntp_server": "主 NTP 服务器",
    "ntp_server_name": "NTP 服务器名称",
    "general_date_timethis_field_is_used_to_configure_a_primary_ntp_server_to_use_when_automatically_setting_the_date_and_time": "本栏位用来配置主 NTP 服务器用来自动设置日期与时间。",
    "general_date_timesecondary_ntp_server": "次 NTP 服务器",
    "general_date_timethis_field_is_used_to_configure_a_secondary_ntp_server_to_use_when_automatically_setting_the_date_and_time": "本栏位用来配置次 NTP 服务器用来自动设置日期与时间。",
    "general_sync_cycle": "NTP同步周期（1-59分钟）",
    "general_sync_cycle_time": "NTP同步周期(分钟)",
    "general_date_timeautomatic_date_amp_time": "自动更新日期 &amp; 时间",
    "general_date_timethis_field_is_used_to_enabledisable_the_use_of_ntp_servers_to_automatically_set_the_date_and_time": "本栏位用来启用\/禁用 NTP 服务器自动设置日期与时间。",
    "refreshLabel": "刷新",
    "samentpserver":"主 NTP 和次 NTP 服务器不能为同一个",
    "saveLabel": "保存",
    "saveConfirmLabel": "保存日期 & 时间设置会自动关闭此会话。请关闭浏览器并重新连接使配置生效。确认要继续进行吗?",
    	"hlp_select_time_zone": "点击下拉框或地图选择时区",
});
