define({
    "home": "主页",
    "settings": "BMC 设置",
    "network_setting":"网络设置",
    "title": "DNS 配置",
    "dns_settingsdomain_name_server_configuration": "网域服务器配置",
    "strongSuccessMsg": "DNS 配置已经重设成功。设定会花几秒来重启界面，请关闭浏览器并再开启一个新的浏览器会话使用新的 IP 来连接到装置",
    "successMsg": "---注销",
    "strongFailureMsg": "保存 DNS 配置时发生错误",
    "failureMsg": "",
    "saveConfirmLabel": "保存 DNS 设定将会重启 BMC 的网络服务。网页在重启结束之前将无法服务。确定要继续进行吗?",
    "dns_settingsbmc_reg": "BMC 注册设置",
    "dns_settingsreg_count": "reg 数量",
    "dns_settingsip_count": "ip 数量",
    "dns_settingsdns_enabled": "DNS启用",
    "dns_settingscheck_this_box_to_enable_all_dns_services": "点击复选框来启用所有的 DNS 服务",
    "dns_settings": "",
    "dns_settingshost_name_setting": "主机名称设置",
    "dns_settingsautomatic": "自动",
    "dns_settingsmanual": "手动",
    "dns_settingsselect_whether_the_host_name_will_be_configured_manually_or_automatically": "选择主机名称是否要配置成手动或是自动。",
    "dns_settingshost_name": "主机名称",
    "dns_settingsif_automatic_host_name_configuration_was_selected_above_this_field_displays_the_automatic_hostname_else_use_to_specify_the_hostname_of_the_device": "如果自动主机名称配置已经在上面选取,此拦为将会显示自动主机名称, 其他则会显示装置指定的主机名称。",
    "dns_settingsbmc_interface": "BMC 界面: ",
    "dns_settingschoose_the_bmcs_network_port_to_register_with_dns_settigs_check_the_option_register_bmc_to_register_with_dns_settings": "选择 BMC 网络端口与 DNS 设置注册。请按一下选项“注册 BMC”来注册。",
    "dns_settingsregister_bmc": "注册 BMC",
    "dns_settingsregistration_method": "注册方法:",
    "dns_settingsnsupdate": "Nsupdate",
    "dns_settingsdhcp_client_fqdn": "DHCP 客户端 FQDN",
    "dns_settingshostname": "主机名称",
    "dns_settingsul_libnsupdateb_register_with_the_dns_server_using_the_nsupdate_applicationli_libdhcp_client_fqdnb_register_with_the_dns_server_using_dhcp_option_81li_libhostnameb_register_with_the_dns_server_using_dhcp_option_12li_ul_bnoteb_hostname_option_should_be_selected_if_the_dhcp_server_does_not_support_option_81": "<ul> <li><b>Nsupdate<\/b> - 使用Nsupdate应用程序向 DNS 服务器来注册<\/li> <li><b>DHCP 客户端 FQDN<\/b> - 使用 DHCP 选项 81 来向 DNS 服务器注册。<\/li> <li><b>主机名称<\/b> - 使用 DHCP 选项 12 来向 DNS 服务器注册。<\/li> <\/ul> <b>注意:<\/b> 如果 DHCP 服务器不支持 DHCP 选项 81, 则应选择主机名称。",
    "dns_settingsmdns_enabled": "mDNS 启用",
    "dns_settingscheck_this_box_to_enable_multicast_dns": "点击复选框来启用组播 DNS",
    "dns_settingscheck_this_box_to_modify_tsig_authentication_for_both_eth0_and_eth1":"点击复选框来修改接口TSIG认证",
    "tsig_configuration":"TSIG 配置",
    "dns_settingstsig_authentication_enabled": "TSIG 启用身份认证",
    "dns_settingscheck_this_box_to_enable_tsig_authentication_while_registering_dns_via_nsupdate": "点击复选框来启用 TSIG 身份认证通过Nsupdate来注册 DNS。",
    "dns_settingscurrent_tsig_private_file": "当前 TSIG 私人文件",
    "dns_settingsdisplays_the_current_tsig_private_file_and_its_upload_date_readonly": "显示当前 TSIG 私人文件以及上传日期(只读)",
    "dns_settingstsig_private_file_date": "TSIG 私人文件日期",
    "dns_settingsdisplays_current_tsig_private_key_file_date": "显示当前 TSIG 私钥文件日期",
    "dns_settingsnew_tsig_private_file": "新的 TSIG 私人文件",
    "dns_settingsbrowse_for_a_new_tsig_private_file_to_upload": "浏览一个新的 TSIG 私人文件并上传。",
    "dns_settingsdomain_setting": "网域设置",
    "dns_settingsselect_whether_the_domain_interface_will_be_configured_manually_or_automatically": "选择网域界面是否要配置成手动或自动。",
    "dns_settingsdomain_interface": "网域界面",
    "dns_settingsspecify_the_domain_interface": "指定网域界面。",
    "dns_settingsdomain_name": "网域名称",
    "dns_settingsdisplays_the_domain_name_of_the_device_or_if_manual_was_selected_specify_the_domain_name_of_the_device": "显示设备的域名。或是如果选择“手动模式”,请指定设备的域名。",
    "dns_settingsdomain_name_server_setting": "域名服务器设置",
    "dns_settingsselect_whether_the_dns_interface_will_be_configured_manually_or_automatically": "选择是否将配置 DNS 界面手动或自动模式。",
    "dns_settingsdns_interface": "DNS 界面",
    "dns_settingsspecify_the_interface_to_be_used": "指定要使用的界面。",
    "dns_settingsip_priority": "IP 优先权",
    "dns_settingsipv4": "IPv4",
    "dns_settingsipv6": "IPv6",
    "dns_settingsif_ip_priority_is_ipv4_2_ipv4_and_1_ipv6_dns_servers_are_used_if_ip_priority_is_ipv6_1_ipv4_and_2_ipv6_dns_servers_are_used": "如果 IP 优先权为 IPv4,将会使用到两个 IPv4 和一个 IPv6 DNS 服务器。如果 IP 优先权是 IPv6 则会使用一个 IPv4 和两个 IPv6 DNS 服务器。",
    "dns_settingsdns_server_1": "DNS 服务器 1",
    "dns_settingsspecify_the_dns_domain_name_system_server_address_to_be_configured_for_the_bmc_ul_liipv4_addresses_should_be_given_in_dotted_decimal_representationliliipv6_addresses_are_supported_and_must_be_global_unicast_addressesliul": "指定 DNS (域名系统)服务器地址为 BMC 配置。 <ul> <li>IPv4 应当以点隔开并以十进制表示。<\/li><li>支持 IPv6 地址且必须是全局单播地址。<\/li><\/ul>",
    "dns_settingsdns_server_2": "DNS 服务器 2",
    "dns_settingsdns_server_3": "DNS 服务器 3",
    "domain_name_must_consist_of_two_or_more_alphanumeric_labels_separated_by_periods_eg_subdomainexamplecom_the_total_length_of_the_domain_name_string_must_be_less_than_256_characters": "域名必须包括两个或更多个由点分隔的数字字母标记, 例如：“sub.domain.example.com”。域名字符串的总长度必须小于 256 个字符。",

    "invalid_domain_name_refer_help_for_more_information": "无效的域名。请按帮助来取得更多信息。",
    "invalid_host_name_refer_help_for_more_information": "无效的主机名。请按帮助来取得更多信息。",
    "invalid_dns_server_address_1refer_help_for_more_information": "无效的 DNS 服务器地址 1。请按帮助来获取更多信息。",
    "invalid_dns_server_address_2refer_help_for_more_information": "无效的 DNS 服务器地址 2。请按帮助来获取更多信息。",
    "invalid_dns_server_address_3refer_help_for_more_information": "无效的 DNS 服务器地址 3。请按帮助来获取更多信息。",
    "required_domain_interface": "需要的网域界面。",
    "required_dns_interface": "需要的 DNS 界面。",
    "required_ip_priority": "要的 IP 优先权。",
    "saveLabel": "保存",
    "network_shared_lan":"共享网络",
    "network_dedicated_lan":"专用网络",
    "nt_ip": "网络 IP 设置",
    "nt_bond": "网络绑定配置",
    "nt_dns": "DNS 配置",
    "nt_ncsi": "Sideband 界面 (NC-SI)",
    "Not_Available":"不可用",    //ks_lz20181013_NOT_Available ++
});
