define({
    "home": "主页",
    "maintenance": "系统维修",
    "title": "Dual 固件升级",
    "start_fw_update": "启动固件更新",
    "fwimage": "选择固件镜像",
    "strongSuccessMsg": "保存!",
    "successMsg": "保存成功",
    "strongFailureMsg": "",
    "failureMsg": "我会尝试出错误的原因",
    "size32mb": "Max. 大小 32 MB",
    "reset": "固件重置将关闭当前会话及 2 分钟后打开一个新的会话",
    "section_based_flashing_body": "只有选定的部分将被更新:",
    "cont_update": "选择部分 Flash",
    "current_active_image": "当前活动的镜像",
    "image_update": "更新的镜像",
    "dual_inactive_image": "无效的镜像",
    "dual_image1": "镜像 1",
    "dual_image2": "镜像 2",
    "dual_both_images": "2 个镜像",
    "select_all": "选择全部",
    "select_none": "取消选择",
    "section_name": "部分名称",
    "update_section": "更新部分",
    "note_for_table" : "所有配置下列项目将作为默认配置恢复操作期间保存。 点击 \"Edit Preserve Configuration\" 修改保存状态设置。",
    "preserve_all_config" : "保存所有配置。 在固件更新，这将保存所有配置设置 - 不论个别项目标记为保存/覆盖在下面的表格。",
    "image_upload" : "选择要更新的固件映像。",
    "start_update" : "点击“启动固件更新”来升级当前的设备固件。",
    "preserve_config" : "要保留任何现有的配置数据, 跳转 <a href='#maintenance/preserve_configuration'>保存配置</a> 页面并选择",
    "preserve_configuration": "保存配置",
    "preserve_conf_0": "SDR",
    "preserve_conf_1": "FRU",
    "preserve_conf_2": "SEL",
    "preserve_conf_3": "IPMI",
    "preserve_conf_4": "Network",
    "preserve_conf_5": "NTP",
    "preserve_conf_6": "SNMP",
    "preserve_conf_7": "SSH",
    "preserve_conf_8": "KVM",
    "preserve_conf_9": "验证",
    "preserve_conf_10": "系统日志",
    "preserve_conf_10": "系统日志",
    "http": "HTTP/HTTPS",
    "tftp": "TFTP",
    "process": "加载中……",
});
