define({
    "home": "主页",
    "logs": "日志",
    "logInformation": "日志查询",
    "eventLog": "事件日志",
    "auditLog": "审计日志",
    "systemLog": "系统日志",
    "currentCapacity": "当前容量 (字节)：",
    "maximumCapacit": "最大容量(字节)： ",
    "maximumQuantity": "最大数量：",
    "dateSelection": "日期选择",
    "startDate": "开始日期",
    "endDate": "结束日期",
    "eventSelection": "事件选择",
    "sensor": "传感器",
    "allevents":"所有事件",
    "allsensors" : "所有传感器",
    "eventlog_statistics" : "事件日志统计",
    "system_events": "系统事件日志",
    "oem_events": "OEM 事件日志",
    "bios_events": "由 BIOS 产生的事件",
    "smi_events": "SMI 处理事件",
    "system_management_events": "系统管理软事件",
    "system_oem_events": "系统软件 - OEM 事件",
    "remove_console_events": "远程控制台软事件",
    "terminal_mode_events": "终端模式远程控制台软事件",
    "downloadLog": "下载日志",
    "clearLog": "清空日志",
    "downloadOriginalFormat": "下载原始格式",
    "originalFormat": "原始格式",
    "conversionFormat": "转换格式 ",
    "clientTimezone": "客户端时区",
    "bmcTimezone": "BMC时区",
    "UTCOffset": "UTC偏移：",
    "id": "ID",
    "time": "时间",
    "pagesize": "每页显示：",
    "undata" : "无数据",
    "clearLogConfirm" : "该操作将清除所有日志，确定要清空日志吗？",
    "clearLogCompletion" : "清空日志操作完成。",
    "category" : "类别",
    "startDateSoBig" : "开始日期必须小于结束日期",
    "status" : "状态",
    "operator":"用户名",
    "description" : "描述",
    "level" : "事件级别",
    "alllevel" : "所有级别",
    "info" : "信息",
    "normal" : "正常",
    "notCritical" : "轻微",
    "critical" : "严重",
    "urgency" : "紧急",//yjj revise
    "query" : "查询",
    "reset" : "重置",
    "total" : "总计：",
    "bars" : "条",
    "pages":"页",

});
