define({

    "fru" : "FRU 信息",
    "field_replaceunit" : "现场可替换单元",
    "home" : "主页",
    "search_fru" : "搜索 FRU",
    "available_frudev" : "可用的 FRU 设备",
    "fru_devid" : "FRU 设备 ID",
    "fru_devname" : "FRU 设备名称",
    "chassis_info" : "机箱信息",
    "chassis_info_version" : "机箱信息地区格式版本",
    "chassis_type" : "机箱类型",
    "chassis_partno" : "机箱部件编号",
    "chassis_serialno" : "机箱序号",
    "chassis_extra" : "机箱额外",
    "board_info" : "主板信息",
    "board_info_version" : "主板信息地区格式版本",
    "language" : "语言",
    "manufacture_datetime" : "制造日期时间",
    "board_manufac" : "主板制造商",
    "board_productname" : "主板产品名称",
    "board_serialno" : "主板序号",
    "board_partno" : "主板部件编号",
    "fru_fileid" : "FRU 文件 ID",
    "board_extra" : "主板额外",
    "product_info" : "产品信息",
    "product_info_version" : "产品信息地区格式版本",
    "product_manufac" : "产品制造商",
    "product_name" : "产品名称",
    "product_version" : "产品版本",
    "product_part_number" : "产品部件编号",
    "product_serialno" : "产品序号",
    "assettag" : "资产标签",
    "product_extra" : "产品额外",
    "page_desc" : "这个页面显示 BMC的装置资讯. 页面显示资讯，例如像基本资讯，机箱资讯，机板资讯，以及FRU的产品资讯.<br><b>FRU Device ID<\/b><br>从下拉式菜单里选择一个FRU装置ID，可查询其详细资讯.<br><b>FRU Device Name<\/b><br> 会显示所选择的 FRU装置的装置名称.<br>",
    "parenttitle":"系统信息",
});
