define({
    "home": "主页",
    "settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "radius_settings": "RADIUS 设置",
    "title": "一般 RADIUS 设置",
    "general_radius": "",
    "_invalid_server_address": " 无效的服务器地址",
    "invalid_port_number": "无效的端口",
    "invalid_secret_phrase": "无效的私密 Phase",
    "strongSuccessMsg": "一般 RADIUS 设置已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "一般 RADIUS 设置保存发生错误。",
    "failureMsg": "",
    "general_radiusenable_radius_authentication": "启用 RADIUS 认证",
    "general_radiusselect_this_option_to_enable_radius_authentication": "选择启用选项来启用 RADIUS 认证。",
    "general_radiusserver_address": "服务器地址",
    "general_radiusspecify_radius_server_address_server_address_supports_the_following_formats_ul_liip_address_both_ipv4_and_ipv6_formatli_lifqdn_fully_qualified_domain_name_formatli_ul": "指定 RADIUS 服务器地址。服务器地址支持下列格式: <ul> <li>- IP 地址 (IPv4 和 IPv6 格式)。</li> <li>- FQDN (完全限定域名) 格式。</li> </ul>",
    "general_radiusport": "端口",
    "general_radiusspecify_the_radius_port_number_ul_li_default_port_is_1812li_li_port_value_ranges_from_1_to_65535li_ulstrongnote_strong_port_80_is_blocked_for_tcpudp_protocols": "指定 RADIUS 端口。 <ul> <li> 默认端口号是 1812。</li> <li>- 端口范围在 1 到 65535 。</li> </ul><strong>注意: </strong> 端口80用来阻挡TCP/UDP协议。",
    "general_radiussecret": "密钥",
    "general_radiusspecify_radius_server_secret_password_ul_lisecret_must_be_at_least_4_characters_longli_li_white_space_is_not_allowedli_ul_strongnotestrong_this_field_will_not_allow_more_than_32_characters": "指定 RADIUS 服务器密钥(密码) <ul> <li>- 密码至少需要 4 个字符长度。</li> <li>- 不允许使用空格。</li> </ul> <strong>NOTE:</strong> 不允许超过 32 个字符。",
    "general_radiusenable_kvm_access": "启用 KVM 存取",
    "general_radiusthis_field_provides_access_to_kvm_for_radius_authenticated_users": "此栏位是提供用户通过 RADIUS 来存取 KVM 的权限。",
    "general_radiusenable_vmedia_access": "启用 VMedia 存取",
    "general_radiusthis_field_provides_access_to_vmedia_for_radius_authenticated_users": "此栏位是提供用户通过 RADIUS 来存取 VMedia 的权限。",
    "saveLabel": "保存",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
});
