define({
    "home": "主页",
    "settings": "BMC 设置",
    "media_redirection": "媒体重定向",
    "title": "媒体重定向",
    "general": "",
    "atleast_one_media_should_be_mounted_when_remote_media_support_is_enabled": "当远程媒体支持启用，至少需要挂载一个媒体",
    "valid_server_address_is_required": "需要有效的服务器地址",
    "source_path_is_required": "需要源路径",
    "username_is_required_for_cifs_location": "cift 地址需要用户名",
    "password_is_required_for_cifs_location": "cift 地址需要用户密码",
    "strongSuccessMsg_noSupport": "<b>媒体重定向设置改变保存成功。</b>",
    "strongSuccessMsg_support": "<b>媒体重定向设置改变保存成功，请等候 10-20 秒来挂载..</b>",
    "strongFailureMsg": "保存媒体重定向发生错误。",
    "failureMsg": "",
    "generallocal_media_support": "本地媒体支持",
    "generalto_enable_or_disable_local_media_support_check_or_uncheck_the_checkbox_respectively": "请通过选取/取消来启用/禁用本地媒体支持。",
    "generalremote_media_support": "远程媒体支持",
    "generalto_enable_or_disable_remote_media_support_check_or_uncheck_the_checkbox_respectivelybr_if_it_is_selected_then_following_remote_media_types_will_be_displayedulli_cddvdli_lifloppylili_harddisk_liulon_selecting_the_individual_media_types_its_respective_configurations_will_be_displayedbr_user_can_configure_different_settings_for_different_remote_media_types": "通过选取/取消来启用/禁用远程媒体支持。<\/br> 如果已选取则对应的远程媒体类型将会显示。<ul><li> CD\/DVD<\/li> <li>软盘<\/li><li> 硬盘 <\/li><\/ul>当选择不同的媒体类型，将会显示其对应的配置。<\/br> 用户可以配置不同的设置于不同的远程媒体类型。",
    "generalmount_cddvd": "挂载 CD\/DVD",
    "generalserver_address_for_cddvd_images": "CD\/DVD 镜像的服务器地址",
    "server_ip_or_host_name": "服务器 IP 或 Host 名称",
    "generaladdress_of_the_server_where_the_remote_media_images_are_stored": "远程媒体镜像服务器地址将会被保存。",
    "generalpath_in_server": "服务器中的路径",
    "eg_optbmcnfs": "eg. \/opt\/bmc\/nfs",
    "generalsource_path_to_the_remote_media_images": "远程媒体镜像来源路径。",
    "generalshare_type_for_cddvd": "共享类型为 CD\/DVD",
    "generalnfs": "nfs",
    "generalcifs": "cifs",
    "generalshare_type_of_the_remote_media_server_either_nfs_or_sambacifs": "远程媒体共享类型可以为 NFS 或 Samba(CIFS)。",
    "generaldomain_name": "网域名称",
    "generalusername_password_and_domain_nameulliif_share_type_is_sambacifs_then_enter_user_credentials_to_authenticate_on_the_serverlilistrongnotestrong_domain_name_field_is_optionalliul": "用户名称，密码和网域名称。<ul><li>如果共享类型为 Samba(CIFS), 则需要输入用户凭证来通过服务器认证。<\/li><li><strong>NOTE:<\/strong> 网域名称为可选填栏位。<\/li><\/ul>",
    "generalusername": "用户",
    "generalpassword": "密码",
    "generalsame_settings_for_floppyharddisk_images": "硬盘\/软盘设置相同",
    "generalif_same_settings_for_floppyharddisk_images_option_selected_then_the_entered_cddvd_media_type_data_configurations_will_be_same_for_floppy_and_harddisk_remote_media_types": "如果选择硬盘与软盘设置相同，然后进入 CD\/DVD媒体类型资料配置将会与软盘和硬盘类型一致。",
    "generalmount_floppy": "挂载软盘",
    "generalserver_address_for_floppy_images": "软盘镜像的服务器地址",
    "generalshare_type_for_floppy": "共享类型为软盘",
    "generalmount_harddisk": "挂载硬盘",
    "generalserver_address_for_harddisk_images": "硬盘镜像的服务器地址",
    "generalshare_type_for_harddisk": "共享类型为硬盘",
    "saveConfirmLabel": "保存设置会重新启动 VMedia 服务。这会关掉你目前所有使用中的会话。确定要继续嘛?",
    "saveLabel": "保存",
    "instancethis_options_will_emulate_sd_media_on_bmc_as_a_usb_device_to_host_server": "此选项用来模拟 SD 媒体对 BMC 作为主机服务器的 USB 装置",
    "instanceemulate_sd_media_as_usb_disk_to_host": "模拟 SD 媒体作为主机 USB 磁盘",
    //ks_lz20181024_vmmedia ++>>
    "remote_images": "远程镜像",
    "local_images": "本地镜像",
    "general_setting": "功能设置",
    //ks_lz20181024_vmmedia ++>>
});