define({
    "bmc_settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "ldapedirectory_settings": "LDAP\/E-directory 设置",
    "title": "一般 LDAP 设置",
    "home": "主页",
    "general_ldap": "",
    "invalid_server_address_refer_help_for_more_information": "无效的服务器地址。请参考“帮助”来获取更多信息。",
    "invalid_port_refer_help_for_more_information": "无效的端口。请参考“帮助”来获取更多信息。",
    "invalid_bind_dn_refer_help_for_more_information": "无效的 Bind DN。请参考“帮助”来获取更多信息。",
    "invalid_password_refer_help_for_more_information": "无效的密码。请参考“帮助”来获取更多信息。",
    "invalid_search_base_refer_help_for_more_information": "无效的搜索起点。请参考“帮助”来获取更多信息。",
    "strongSuccessMsg": "一般 LDAP 设置已保存成功。",
    "successMsg": "",
    "strongFailureMsg": "保存一般 LDAP 设置发生错误。",
    "failureMsg": "",
    "general_ldapenable_ldapedirectory_authentication": "启用 LDAP\/E-directory 认证",
    "general_ldapcheck_the_box_below_to_enable_ldapedirectory_authentication": "点击复选框来启用 LDAP\/E-Directory 认证。",
    "general_ldapencryption_type": "加密类型",
    "general_ldapno_encryption": "未加密",
    "general_ldapssl": "SSL",
    "general_ldapstarttls": "StartTLS",
    "general_ldapselect_the_encryption_type_for_ldapedirectory_brstrongnotestrongconfigure_proper_port_number_when_ssl_is_enabled": "选择 LDAP\/E-Directory 的加密类型。<strong>注意:<\/strong> 当 SSL 启用时，配置适当的端口。",
    "general_ldapcommon_name_type": "常见名称类型",
    "general_ldapip_address": "IP 地址",
    "general_ldapfqdn": "FQDN",
    "general_ldapserver_address": "服务器地址",
    "general_ldapldapedirectory_server_address_will_support_the_following_ulliipv4_address_formatli_liipv6_address_formatliul_strongnotestrong_configure_fqdn_address_when_using_starttls_with_fqdn": "LDAP\/E-Directory 服务器地址支持以下格式: <ul><li> IPv4 地址格式。<\/li> <li> IPv6 地址格式。<\/li><\/ul> <strong>NOTE:<\/strong> 当使用 StartTLS 与 FQDN 时，需配置 FQDN 地址。",
    "general_ldapport": "端口",
    "general_ldapspecify_the_ldapedirectory_port_ulli_default_port_is_389li_li_for_ssl_connections_default_port_is_636li_li_port_value_ranges_from_1_to_65535liul": "指定 LDAP\/E-Directory 端口。 <ul><li> 默认端口号是 389。<\/li> <li> 对于 SSL 连线，默认的端口号为 636。<\/li> <li> 端口号的范围由 1 ～ 65535。<\/li><\/ul>",
    "general_ldapbind_dn": "Bind DN",
    "eg_cnadminoulogindcdomaindccom": "E.g., cn=admin,ou=login,dc=domain,dc=com",
    "general_ldapthe_bind_dn_is_used_in_bind_operation_which_authenticates_the_client_to_the_server_ul_li_bind_dn_is_a_string_of_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetli_li_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_cnmanageroulogin_dcdomaindccomli_ul": "Bind DN 是用在 Bind 操作，让服务器对客户端进行身份验证。 <ul> <li>- Bind DN 是由 4 - 64 个字母数字所组成的字串。<\/li> <li> 开头必需要是字母。<\/li> <li> 允许使用特殊字符如点（.），逗号（,），连字符（-），下划线（_），等号（=）。<\/li> <li> 例如: cn=manager,ou=login, dc=domain,dc=com<\/li> <\/ul>",
    "general_ldappassword": "密码",
    "whitespace_not_allowed": "不允许空白",
    "general_ldapthe_bind_password_is_used_in_bind_operation_which_authenticates_the_client_to_the_server_ulli_password_must_be_at_least_1_character_longli_li_white_space_is_not_allowedliul_strongnotestrong_this_field_will_not_allow_more_than_20_characters": "密码是用在 Bind 操作，让客户端对服务器进行身份验证。 <ul><li> 密码的长度至少要有 1 个字符。<\/li> <li> 不允许空白。<\/li><\/ul> <strong>NOTE:<\/strong> 密码长度不允许超过 20 个字符。",
    "general_ldapsearch_base": "Search Base",
    "eg_oulogindcdomaindccom": "E.g., ou=login,dc=domain,dc=com",
    "general_ldapthe_search_base_allows_the_ldapedirectory_server_to_find_which_part_of_the_external_directory_tree_to_be_searched_the_search_base_may_be_something_equivalent_to_the_organization_group_of_external_directoryul_li_searchbase_is_a_string_of_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetical_characterli_li_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_oulogindcdomaindccomli_ul": "用搜索库告知 LDAP\/E-Directory 服务器需要搜索外部目录的一个部分。搜索库可能等同于组织或外部目录群组。 <ul> <li> 搜索库是由 4 ～ 64 个字母数字所组成的字串。<\/li> <li> 开头必需要是字母。 <\/li> <li> 可以使用特殊字符，例如点（.），逗号（,），连字符（-），下划线（_），等号（=）。<\/li> <li> 例如: ou=login,dc=domain,dc=com<\/li> <\/ul>",
    "general_ldapattribute_of_user_login": "用户登录属性",
    "general_ldapcn": "cn",
    "general_ldapuid": "uid",
    "general_ldapthe_attribute_of_user_login_field_allows_the_ldapedirectory_server_to_find_which_attribute_should_be_used_to_identify_the_user_ul_li_only_support_cn_or_uidli_ul": "用户登录属性告知 LDAP\/E-Directory 服务器要用那种属性来识别用户。  <ul> <li> 只支持 cn 或 uid<\/li> <\/ul>",
    "general_ldapca_certificate_file": "CA certificate 文件",
    "general_ldapfile_that_contains_the_certificate_of_the_trusted_ca_certsulli_ca_certificate_file_should_be_of_the_type_pem_liul": "包含可信任的 CA 证书的文件。",
    "general_ldapcertificate_file": "Certificate 文件",
    "general_ldapclient_certificate_filenameulli_certificate_file_should_be_of_the_type_pem_liul": "客户端 Certificate 文件。",
    "general_ldapprivate_key": "私钥",
    "general_ldapclient_private_key_filenameulli_private_key_should_be_of_the_type_pem_liul_brstrongnotestrong_all_of_the_3_files_are_required_when_starttls_enabled": "客户端的私钥文件。<br><strong>注意:<\/strong> 当启用 StartTLS 时，这三个文件是必需的。",

    "general_ldapclient_upload_a_valid_CA_certificate_file": "请上传有效的 CA certificate 文件。",
    "general_ldapclient_upload_a_valid_Certificate_file": "请上传有效的 Certificate 文件。",
    "general_ldapclient_upload_a_valid_Certificate_file": "请上传有效的 Certificate 文件。",
    "general_ldapclient_upload_a_valid_Private_Key": "请上传有效的私钥。",
    "general_ldapclient_upload_a_file": "请选择要上传的文件",

    "saveLabel": "保存",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
});
