define({
		"tittle":"历史记录",
	   "tag" : "展示和下载历史记录",
	   "home" : "主页",
	   "power_consumption" : "功耗历史记录",
	   "inlet_history" : "进风口温度记录",
	   "filter_bydate":"时间筛选",
	   "start_date":"开始时间",
	   "end_date":"结束时间",
	   "common_setting":"通用设置",
	   "one_day":"一天",
	   "one_week":"一周",
	   "two_week":"两周",
	   "one_month":"一月",
	   "three_month":"三月",
	   "half_year":"半年",
	   "one_year":"一年",
	   "custom":"自定义",
	   "check":"查询",
	   "server_config" : "服务器配置",
	   "systeminfo":"系统信息",
	   "inquery_type":"查询类型",
	   "wrongdate":"开始时间或结束时间无效，请检查!",
    	"download": "下载",
		"strongSuccessMsg": "正在保存并下载，请耐心等待……",
		"strongFailureMsg": "下载错误，请稍后再试",
   		 "help_information":"点击下载按钮，历史记录将会自动下载，请耐心等待。",
		"csvFormat": "CSV 格式",
		"xmlFormat": "XML 格式",
		"history_download_title": "历史记录下载",
		"history_search_title": "历史记录查询",
		"download_tip1": "记录频率：1小时",
		"download_tip2": "记录内容：进风口，处理器，内存温度值",
});
