define({
    "home": "主页",
    "settings": "BMC 设置",
    "network_setting": "网络设置",
    "title": "网络 IP 设置",
    "ip": "",
    "please_choose_ipv4_enable_or_ipv6_enable": "请选择启用 IPv4 或 IPv6",
    "invalid_ipv4_address_refer_help_for_more_information": "无效的 IPv4 地址。请参考“帮助”来获取更多的信息。",
    "invalid_ipv4_subnet_refer_help_for_more_information": "无效的 IPv4 子网掩码。请参考“帮助”来获取更多的信息。",
    "invalid_ipv4_gateway_refer_help_for_more_information": "无效的 IPv4 默认网关。请参考“帮助”来获取更多的信息。",
    "invalid_ipv6_address_refer_help_for_more_information": "无效的 IPv6 地址。请参考“帮助”来获取更多的信息。",
    "invalid_ipv6_prefix_refer_help_for_more_information": "无效的 IPv6 前缀。请参考“帮助”来获取更多的信息。",
    "invalid_vlan_id_refer_help_for_more_information": "无效的 VLAN ID。请参考“帮助”来获取更多的信息。",
    "invalid_vlan_priority_refer_help_for_more_information": "无效的 VLAN 优先权。请参考“帮助”来获取更多的信息。",
    "strongSuccessMsg": "网络配置重置成功。将会在数秒后重启界面，请关闭浏览器会话，并根据新的设置重新开启浏览器。",
    "successMsg": "---注销",
    "strongFailureMsg": "保存网络 IP 设置发生错误。",
    "failureMsg": "",
    "ipenable_lan": "启用 LAN",
    "ipcheck_this_option_to_enable_lan_support_for_the_selected_interface": "选中此选项可启用 LAN 对所选接口的支持。",
    "iplan_interface": "LAN 界面",
    "ipselect_the_lan_interface_to_be_configured": "选择要配置的 LAN 接口。",
    "ipmac_address": "MAC 地址",
    "ipthis_field_displays_the_mac_address_of_the_selected_interface_read_only": "此处显示所选接口的 MAC 地址(只读)。",
    "ipenable_ipv4": "启用 IPv4",
    "ip_check_this_option_to_enable_ipv4_support_for_the_selected_interface": " 选中此选项可以为选定的接口上启用 IPv4 支持",
    "ipenable_ipv4_dhcp": "启用 IPv4 DHCP",
    "ip_check_this_option_to_enable_ipv4_dhcp_support_for_the_selected_interface_h4obtain_an_ip_address_automaticallyh4_enable_use_dhcp_to_dynamically_configure_ipv4_address_using_dynamic_host_configuration_protocol_dhcp": "点击选项来启用所选界面的 IPv4 DHCP 支持。 <h4>自动获取一组 IP 地址<\/h4> 启用“使用 DHCP”来动态配置 IPv4 地址(DHCP)。",
    "ipipv4_address": "IPv4 地址",
    "ip_if_dhcp_is_disabled_specify_a_static_ipv4_address_to_be_configured_for_the_selected_interface_ul_li_ip_address_consists_of_4_sets_of_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_set_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul": " 如果禁用 DHCP, 请指定一组静态 IPv4 地址配置给所选的界面。 <ul> <li>- IP 地址包含 4 组由点隔开的数字如“xxx.xxx.xxx.xxx”.<\/li> <li>- 范围为 0 - 255。<\/li> <li>- 第一个数字不能为 0。<\/li> <\/ul>",
    "ipipv4_subnet": "IPv4 子网掩码",
    "ipif_dhcp_is_disabled_specify_a_static_subnet_mask_to_be_configured_for_the_selected_interface_ul_li_ip_address_consists_of_4_sets_of_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_set_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul": "如果禁用 DHCP, 请指定一组静态 IPv4 子网掩码配置给所选的界面。 <ul> <li>- IP 地址包含 4 组由点隔开的数字如“xxx.xxx.xxx.xxx”.<\/li> <li>- 范围为 0 - 255。<\/li> <li>- 第一个数字不能为 0。<\/li> <\/ul>",
    "ipipv4_gateway": "IPv4 默认网关",
    "ipif_dhcp_is_disabled_specify_a_static_default_gateway_to_be_configured_for_the_selected_interface_ul_li_ip_address_consists_of_4_sets_of_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_set_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul": "如果禁用 DHCP, 请指定一组静态 IPv4 默认网关配置给所选的界面。 <ul> <li>- IP 地址包含 4 组由点隔开的数字如“xxx.xxx.xxx.xxx”.<\/li> <li>- 范围为 0 - 255。<\/li> <li>- 第一个数字不能为 0。<\/li> <\/ul>",
    "ipenable_ipv6": "启用 IPv6",
    "ip_check_this_option_to_enable_ipv6_support_for_the_selected_interface": " 点击选项来启用所选界面的 IPv6 支持",
    "ipenable_ipv6_dhcp": "启用 IPv6 DHCP",
    "ipcheck_this_option_to_enable_ipv6_support_for_the_selected_interfaceh4obtain_an_ip_address_automaticallyh4enable_use_dhcp_to_dynamically_configure_ipv6_address_using_dynamic_hostconfiguration_v6_protocol_dhcpv6": "点击选项来启用所选界面的 IPv6 支持。<h4>自动取得一组 IP 地址<\/h4>启用“使用 DHCP”来动态配置 IPv6 地址(DHCPv6)。",
    "ipipv6_index": "IPv6 索引",
    "ipchoose_the_ipv6_index": "选择 IPv6 索引",
    "ipipv6_address": "IPv6 地址",
    "ipspecify_a_static_ipv6_address_to_be_configured_for_the_selected_interface": "指定一个固定的 IPv6 地址来配置给所选的界面。",
    "ipsubnet_prefix_length": "子网掩码前缀长度",
    "ipspecify_the_subnet_prefix_length_for_the_ipv6_settingsulli_value_ranges_from_0_to_128liul": "指定一个子网掩码前缀长度给 IPv6 设置。<ul><li>- 数值范围为 0 到 128。<\/li><\/ul>",
    "ipenable_vlan": "启用 VLAN",
    "ip_check_this_option_to_enable_vlan_support_for_the_selected_interface": " 点击选项来启用所选界面的 VLAN 支持。",
    "ipvlan_id": "VLAN ID",
    "ipspecify_the_identification_for_vlan_configuration_ulli_value_ranges_from_2_to_4094liul_strongnotestrong_vlan_id_cannot_be_changed_without_resetting_the_vlan_configuration_vlan_id_0_1_4095_are_reserved_vlan_ids": "指定 VLAN 配置 ID。 <ul><li>- 数值范围为 2 到 4094。<\/li><\/ul> <strong>注意:<\/strong> VLAN ID 更改后必须要进行重启。 VLAN ID 0, 1, 4095 为保留的 VLAN ID's.",
    "ipvlan_priority": "VLAN 优先权",
    "ipspecify_the_priority_for_vlan_configuration_ulli_value_ranges_from_0_to_7liul_strongnotestrong_7_is_the_highest_priority_for_vlan": "指定 VLAN 优先权配置。 <ul><li>- 数值范围为 0 到 7。<\/li><\/ul> <strong>注意:<\/strong> 7 为 VLAN 最高权限。",
    "saveConfirmLabel": "此功能可能会改变装置的 IP 地址，以及你可能会失去浏览器的连接。请在数秒后重启使更新生效。确定要继续进行?",
    "saveLabel": "保存",
    "ETH0": "eth0",
    "ETH1": "eth1",
    "Undefined": "未定义",
    "share_lan":"共享网络",
    "dedicate_lan":"专用网络",
    "nt_ip": "网络 IP 设置",
    "nt_bond": "网络绑定配置",
    "nt_dns": "DNS 配置",
    "nt_ncsi": "Sideband 界面 (NC-SI)",
});
