define({
    "title": "安全设置",
    "parentTitle": "BMC 设置",
    "home": "主页",
    "load": "加载中",
    "undata": "无数据",
    "save": "保存",
    "loginRule": "登录规则",
    "rule": "规则",
    "startTime": "开始时间",
    "endTime": "结束时间",
    "ipAddr": "IP段",
    "macAddr": "MAC段",
    "selectState": "选择状态",
    "allow": "允许",
    "block": "阻止",
    "off": "关",
    "on": "开",
    "logingRuleInfo": "关闭所有登录规则时，不启动登录控制；开启某个登录规则时，时间段、IP、MAC至少填写一个作为控制条件。",
    "timeDescription": "时间段：支持三种格式，YYYY-MM-DD HH:mm, YYYY-MM-DD, HH:mm; 起始时间的格式必须与结束时间保持一致。",
    "IPDescription": "IP段：支持两种格式，xxx.xxx.xxx.xxx 和 xxx.xxx.xxx.xxx/mask; xxx.xxx.xxx.xxx是单个完整IP地址，xxx.xxx.xxx.xxx/mask是指一个IP段，mask取值范围为1~32。",
    //ks_lz20180822 mac 
    "MACDescription": "MAC段：支持一种格式，xx:xx:xx:xx:xx:xx; xx:xx:xx:xx:xx:xx是单个完整的MAC地址。",
    "startTimeTooBig": "结束时间应大于开始时间",
    "formatNotConsistent": "时间格式不一致",
    "checkInfo": "请按要求输入数据",
    "whiteListCheck": "选择白名单时，至少开启一个登录规则。",
    "turnOnCheck": "开启某个登录规则时，时间段、IP、MAC至少填写一个作为控制条件。",
    "saveSucess": "登录规则保存成功!",
    "white_list": "白名单",
    "black_list": "黑名单",
    "white_list_confirm": "白名单对登录控制比较严格，确定要设置白名单吗？",
    // ks_lz_20180727 TAB ++>>
    "loginControl": "登录控制",
    "snmpv": "SNMP V1/V2 设置",
    "ssl_settings": "SSL 设置",
    "user_badpassword": "用户密码锁定设置",
    // ks_lz_20180727 TAB ++>>
    "timeRule": "起始时间的格式必须与结束时间保持一致。",

});