define({
    "home": "主页",
    "settings": "BMC 设置",
    "parenttitle":"系统信息",
    "raid_management": "RAID 管理",
    "title": "物理设备信息",
    "ld_name": "LD 名称",
    "controller": "控制器",
    "type": "类型",
    "state": "状态",
    "offline": "离线",
    "degraded": "降级",
    "rebuild": "重建",
    "optimal": "最佳化",
    "read_policy": "读取机制",
    "no_read_ahead": "未预先读取",
    "read_ahead": "预读",
    "write_policy": "写入机制",
    "write_through": "直写",
    "write_back": "回写",
    "cache_policy": "快取机制",
    "direct_io": "直接 IO",
    "cache_io": "快取 IO",
    "select_the_raid_controller_": "选择 RAID 控制器 ",
    "logical_device_info": "",
    "logical_device_infostripe_size_mb_": "带宽 (MB) ",
    "logical_device_infobgi": "BGI",
    "logical_device_infossd_caching": "SSD 快取",
    "logical_device_infoprogress": "进度(%)",
    "logical_device_infobad_blocks_table": "损坏磁区表",
    "logical_device_infosize_gb": "大小 (GB)",
    "logical_device_information": "物理设备信息",
	"create_logical":"创建虚拟装置",
    "type_0":"RAID0",
    "type_1":"RAID1",
    "type_2":"RAID5",
    "type_3":"RAID6",
    "type_4":"RAID1E",
    "type_5":"RAID1E_RLQ0",
    "type_6":"RAID1E0_RLQ0",
    "type_7":"RAID00",
    "type_8":"RAID10",
    "type_9":"RAID50",
    "type_10":"RAID60",
    "bgi_enabled":"启用",
    "bgi_disabled":"停用",
    "ssd_enabled":"启用",
    "ssd_disabled":"停用",
    "not_available":"N/A",
    "blocks_empty":"空",
    "blocks_not_empty":"非空",
    "no_phy_devices":"物理设备编号",
    "create_logical_devicefast_initialization": "快速初始化",
    "create_logical_deviceslow_initialization": "慢速/完整初始化",
    "delete_success":"成功删除虚拟装置",
    "locate_success":"成功放置逻辑装置",
    "consistency_success":"成功选取一致性检查",
    "initialization_success":"成功选取初始化装置",
    "raid_logical_hlp":"这个页面会显示RAID控制器的逻辑装置资讯LD名称，状态，读写政策，实体编号，等等... 。按 <strong>'+'</strong>图示以示更多选项.<br> 按 <strong><i class='ion ion-navicon btn-success'> </i></strong> 可查询所选的虚拟drive的物理装置资讯.<br> 按 <strong><i class='ion ion-navicon btn-success'> </i></strong> 看进阶属性.<br> 按 <strong><i class='fa fa-circle btn-success'></i></strong> 配置虚拟装置.<br> 按 <strong><i class='fa fa-circle btn-success'></i></strong> 开始/取消 持续性检查.<br> 按 <strong><i class='fa fa-circle btn-success'></i></strong> 开始/取消 初始化检查.<br> 按 <strong><i class='ion ion-close-circled btn-danger'></i></strong> 删除虚拟装置. <br> NOTE: RAID0 的 RAID Level 不支援持续性检查.",
    "hlp_logical_advanced_properties":"This page displays Advanced Properties details about the Logical Device Information of RAID Controller like Stripe Size," +
                "BGI,SSD Caching,Progress,Bad Blocks Table etc..",
    "access_policy_0":"Read-Write",
    "access_policy_1":"Read Only",
    "access_policy_2":"Blocked",
    "access_policy": "Access Policy",
    "raid_logical_no_rows":"逻辑装置资讯不存在.",
    "progress_0":"未知",
    "progress_1":"Rebuild",
    "progress_2":"BGI in progress"
});
