define({
    "parenttitle": "远程控制",
    "title": "ME功耗封顶",
    "tag": "配置ME功耗封顶策略",
    "home": "主页",
    "domain": "作用域",
    "load": "加载中",
    "status": "状态",
    "policy": "策略",
    "current_power": "当前功耗(瓦特)",
    "min_power": "最小功耗(瓦特)",
    "max_power": "最大功耗(瓦特)",
    "unknow_status": "ME功耗状态未知",
    "policy_id": "策略ID",
    "policy_item": "策略项",
    "whether_enable": "是否启用",
    "on": "是",
    "off": "否",
    "limiting_value": "限制值(瓦特)",
    "operation": "操作",
    "modify": "修改",
    "entire_limit": "全平台功耗限制",
    "cpu_limit": "CPU功耗限制",
    "mem_limit": "内存功耗限制",
    "policy_max": "策略最大值",
    "recommend_min_val": "策略最小值",
    "recommend_undefined_val": "未能确定",
    "na": "N/A",
    "saveLabel": "保存",
    "cancel": "取消",
    "save_success": "保存成功!",
    "save_failed": "操作失败，请稍后再试。",
    "entire_platform": "全平台",
    "unknown_policy": "ME功耗策略未知",
    "cpu": "CPU",
    "memory": "内存",
    "long_control": "远程控制",
    "confirm": "确定执行操作？",
    "server_con": "服务器配置",
    "me_power_policy": "ME功耗策略",
    "me_pow_edit": "ME功耗策略设置",
    "policy_id_help": "<b>策略ID</b> <br>展示当前功耗策略ID",
    "me_pow_edit_id": "策略ID",
    "me_pow_edit_entire": "全平台",
    "me_pow_edit_cpu": "CPU",
    "me_pow_edit_mem": "内存",
    "policy_status_help": "<b>当前状态</b> <br>展示当前功耗状态<br>点击开启功耗状态",
    "policy_enable": "生效",
    "policy_domain_help": "<b>策略作用域</b><br>展示策略的作用域，用户可以任何有效作用域。",
    "policy_domain": "作用域",
    "policy_max_help": "<b>策略最大值</b><br>设置当前策略最大值。",
    "me_power_res_error": "收到错误的策略!",
    "me_power_send_error": "策略设置错误!",
    "me_power_empty_policy": "确定保存空的策略?",
    "me_power_wrong_value": "错误的数值",
    "note": "注意 : 策略 ",
    "tosave": " 将要被保存。",
    "positive_integer": "请输入正整数",
    "recommend_min_val_help": "策略最小值是实现功耗封顶的最低建议值，设置较低封顶值可能导致封顶失败。",
    "policy_setting_error": "设置功耗封顶失败",
    "policy_value_too_small": "设定值应当不小于最小值",

    "power_energy": "电源与能耗",
    "pe_power_control": "开关机控制",
    "pe_power_hot_standby": "电源备份策略设置",
    "pe_me_power_policy": "ME功耗封顶",
    "pe_power_restore_control": "系统掉电恢复策略",
    // ks_lz_20170711  power button lock ++>>
    "pe_power_button_lock": "前面板锁定",
    // ks_lz_20170711  power button lock ++>>
    "exception_status": "获取数据异常，请重试",
});