define({
    "parenttitle": "远程控制",
    "power_control": "电源控制器",
    "tag": "对主机服务器",
    "home": "主页",
    "power_actions": "电源动作",
    "power_off": "关闭电源",
    "power_on": "开启电源",
    "power_cycle": "电源循环",
    "hard_reset": "硬重启",
    "acpi_shutdown": "ACPI 关闭",
    "perform_action": "执行动作",
    "confirm": "确认是否要执行此操作?",
    "online": "服务器在线",
    "offline": "服务器离线",
    "strongSuccessMsg": "日志设置机制改变保存成功。",
    "server_hostoff": "服务器当前关闭",
    "server_hoston": "服务器当前启动",
    "host_retrying": "重试中...请等待。重试剩余: ",
    "power_action_wait": "执行电源动作.... 请等待",
    "str_server_err1": "执行软关机失败。这可能是由于服务器正常关机所花费时间太久所导致。",
    "str_server_err2": "执行电源动作失败。",
    "str_server_setaction": "当接收服务器电源动作回应时发生问题",
    "str_server_getstatus": "当接收服务器电源当前状态时发生问题",
    "help_status": "展示服务器当前状态。",
    "help_selection": "此部分用于选择服务器电源操作。",
    "help_forceoff": "立刻关闭服务器",
    "help_forceon": "开启服务器",
    "help_powercycle": "关闭服务器，然后重启系统。(冷重启)",
    "help_hardreset": "在不关闭电源的情况下重启系统。(热重启)",
    "help_acpi": "触发操作系统关机优先级到关机。",

    "power_energy": "电源与能耗",
    "pe_power_control": "开关机控制",
    "pe_power_hot_standby": "电源备份策略设置",
    "pe_me_power_policy": "ME功耗封顶",
    "pe_power_restore_control": "系统掉电恢复策略",
    // ks_lz_20170711  power button lock ++>>
    "pe_power_button_lock": "前面板锁定",
    // ks_lz_20170711  power button lock ++>>
});