define({
    "home": "主页",
    "settings": "BMC 设置",
    "video": "视频",
    "auto_settings": "自动设置",
    "title": "Pre-Event 视频录制",
    "pre_event": "",
    "strongSuccessMsg": "Pre-Event 视频录制已保存成功",
    "successMsg": "",
    "strongFailureMsg": "保存 Pre-Event 视频录制时发生错误",
    "failureMsg": "",
    "this_page_used_to_configure_the_preevent_video_recording_configurationspreevent_video_recording_is_currently_disabled_to_enable_the_preevent_video_recording_in_a_hrefsettingsvideoautotrigger_settings_styletextdecoration_underlineb_triggers_configuration_ba_page_and_trigger_the_video_":"本页用来设置 Pre-Event 视频录制配置。Pre-Event 视频录制目前禁用。要启用 Pre-Event 视频录制可在 <a href='#settings\/video\/auto\/trigger_settings' style='text-decoration: underline;'><b> 触发配置 <\/b><\/a> 页面设置触发视频录制。 ",
    "this_page_used_to_configure_the_preevent_video_recording_configurations_": "本页用来配制 Pre-Event 视频录制配置。 ",
    "pre_eventvideo_quality": "视频质量",
    "pre_eventvery_low": "非常低",
    "pre_eventlow": "低",
    "pre_eventaverage": "平均",
    "pre_eventnormal": "一般",
    "pre_eventhigh": "高",
    "pre_eventchoose_the_video_quality_from_the_dropdown_list_to_adjust_the_preevent_bootcrash_record_video":"下拉式选单中选择视频质量来调整 Pre-event 启动\/损坏录制视频。",
    "pre_eventcompression_mode": "压缩模式",
    "pre_eventno": "no",
    "pre_eventselect_the_compression_mode_from_the_dropdown_list_that_consists_of_various_types_of_compression_modes_for_preevent_trigger_videos":"从下拉式选单中选择压缩模式，支持多种压缩模式供 Pre-event 触发视频使用。",
    "pre_eventframes_per_second": "画面每秒帧数 (Frames Per Second)",
    "pre_event1": "1",
    "pre_event2": "2",
    "pre_event3": "3",
    "pre_event4": "4",
    "pre_eventchoose_the_fps_to_recored_the_number_of_frames_per_second": "选择视频画面每秒的帧数 (FPS)。",
    "pre_eventvideo_duration": "视频周期",
    "pre_event10": "10",
    "pre_event20": "20",
    "pre_event30": "30",
    "pre_event40": "40",
    "pre_event50": "50",
    "pre_event60": "60",
    "pre_eventchoose_this_to_set_the_time_duration_of_the_video_that_needs_to_be_recorded": "选择此项来设置视频录制时间周期。",
    "saveLabel": "保存"
});
