define({
    "home": "主页",
    "system_maintenance": "系统维护",
    "title": "保存配置",
    "preserve_configuration": "",
    "strongSuccessMsg": "保存配置设置已成功保存。",
    "successMsg": "",
    "strongFailureMsg": "保存配置设置发生错误。",
    "failureMsg": "",
    "preserve_configurationclick_here_to_go_to_a_hrefmaintenancefirmware_updatefirmware_updatea_or_a_hrefmaintenancerestore_configurationrestore_factory_defaults_a": "点击前往 <a href='#maintenance/firmware_update'>BMC固件更新</a> or <a href='#maintenance/restore_configuration'>恢复出厂设置</a>",
    "preserve_configurationcheck_the_configuration_that_needs_to_be_preserved_while_the_restore_configuration_is_done": "检查需要保留的配置，当恢复配置/固件更新完成并不会更新/恢复所保存的配置。",
    "preserve_configurationcheck_all": "全选",
    "preserve_configurationselect_this_option_to_check_all_the_configuration_list": "选择这个选项去查看所有安装的表单。",
    "preserve_configurationsdr": "SDR",
    "preserve_configurationyou_can_either_checkuncheck_a_check_box_to_preserveoverwrite_the_configuration_for_your_system": "你可以点选或取消点选一个复选框去保存或覆写你系统上的配置。",
    "preserve_configurationfru": "FRU",
    "preserve_configurationsel": "SEL",
    "preserve_configurationipmi": "IPMI",
    "preserve_configurationnetwork": "Network",
    "preserve_configurationntp": "NTP",
    "preserve_configurationsnmp": "SNMP",
    "preserve_configurationssh": "SSH",
    "preserve_configurationkvm": "KVM",
    "preserve_configurationauthentication": "认证",
    "preserve_configurationsyslog": "系统日志",
    "preserve_configurationweb": "Web",
    "preserve_configurationextlog": "Extlog",
    "preserve_configurationredfish": "Redfish",
    "saveLabel": "保存"
});
