define({
    "parenttitle":"远程控制",
   "remote_control" : "控制台重定向",
   "power_controlkvm" : "远程 KVM",
   "home" : "主页",
   "search_settings" : "搜索设置",
   "settings" : " 设置",
   "cd_image" : " CD 镜像",
   "connected_to" : "&nbsp; 连接到",

   "start_kvm" : "启动 KVM",
   "stop_kvm" : "停止 KVM",
   "show_kbd" : "显示 KBD",
   "start_media_redirection" : "开启媒体",
   "record" : "录制视频",
   "stop" : "停止录制",
   "video_rec_setting" : "录制设置",
   "videorecording" : "视频录制",
   "settings_ok" : "Ok",
   "settings_cancel" : "取消",
   "video_length" : "视频长度",
   "seconds" : "秒数",
   "time" : "时间",
   "media_packets_sent" : "媒体封包发送",
   "install_spx_remoteapp" : "安装 SPX KVM 远程应用程序",
   "alert_apinotsupported" : "浏览器未完全支持此文件 API。此浏览器无法完成媒体重定向。请使用应用程序或是不同的装置以及支持的浏览器",
   "select_file" : "请选择一个文件",
   "stop_media_redirection" : "停止媒体",
   "start_media_redirection" : "启动媒体",
   "iso_image_redirection" : "目前只支持一个 ISO 镜像重定向",
   "read_bytes" : "读取字节于",
   "is_trying_to_connect": " 正在尝试连接。你希望授权给它什么权限等级?",
   "is_requesting_full_access": " 要求完整的 KVM 访问。你希望给它完整访问权限吗？或是维持目前部分存取的状态？",
   "full_access_granted_by": "由完整虚拟控制台访问授权 ",
   "user_with_ip": " 用户与 IP 地址 ",
   "partial_access_granted_by": "由部分访问 (只有视频) 授权",
   "partial_status_line": "会话以部分 KVM 权限执行",
   "slave_none_status_body": "主会话使用 KVM 控制被拒绝。关闭 viewer。",
   "slave_quit": "从会话离开",
   "you_have": "你有 ",
   "more_seconds": " 需要多几秒决定。",
   "full_permission": "完整权限",
   "part_permission": "部分权限",
   "no_permission": "没有权限",
   "permission_requested": "请求权限",
   "master_has": "主会话有 ",
   "status": "状态",
   "slave_permission": "从权限",
   "request_full": "请求完整访问",
   "switch_master": "切换成主要的",
   "switch_master_body": "在你离开之后想要授权给哪一个会话完整权限？",
   "grant_permission": "以授权的权限",
   "master_reconn": "由于主会话正在重连，所以收到虚拟控制台部分访问权限。并请求新的完整访问权限，如需要，请等候一段时间。",
   "full_access_received_timeout": "从虚拟控制台的完全访问权限得到适当的请求超时",
   "granted_full_access_timeout": "授予完全虚拟控制台访问 ",
   "due_to_request_timeout": " 由于虚拟控制台访问请求超时。",
   "provided_full_access_to": "提供完整访问的权限",
   "requesting_permission": "请求允许从虚拟控制台访问",
   "master_blocked_request" : "KVM 主会话进入请求被阻挡。",
   "kvm_license_exp": "KVM 许可证已过期。",
   "kvm_timed_out": "KVM 会话超时。关闭 Viewer...",
   "kvm_terminated": "从服务器收到终止命令。\nKVM 重定向会话已断开连接。",
   "kvm_web_restart": "WebServer 已经重启。正在关闭 Viewer...",
   "kvm_web_logout": "WebSession 已经注销。正在关闭 Viewer...",
   "kvm_conf_change": "重定向配置已更改。重定向引擎将会重启。\n当前会话已被重定向服务关闭。请重新连接。",
   "kvm_server_restart": "重定位引擎将会指示 Viewer 进行关闭。正在关闭 Viewer... " ,
   "kvm_inv_sess": "无效的会话凭证。认证失败。 ",
   "kvm_disabled": "用户没有权限来开始 KVM 会话。\n请使用拥有KVM权限的用户访问。",
   "kvm_inv_sess_info": "无效的会话信息重连。认证失败。",
   "kvm_max_session_reached": "已到达可允许的会话最大数量。请关闭其他会话并重试一次" ,
   "same_kvm_client_user": "无法启动虚拟控制台。一个客户端只允许开启一个虚拟控制台会话。",
   "invalid_image_type" : "无效的镜像文件类型",
   "media_redirection_running": "虚拟媒体重定向正在运行中。确定要离开并且关闭媒体重定向吗？",
   "hold_down": "Hold Down",
   "r_ctrl": "Right Ctrl Key",
   "r_alt": "Right Alt Key",
   "l_ctrl": "Left Ctrl Key",
   "l_alt": "Left Alt Key",
   "r_win": "Right Windows Key",
   "l_win": "Left Windows Key",
   "context_key": "Context Menu Key",
   "prtscn": "Print Screen Key",
   "press_release": "按下并放开",
   "send_keys": "传送密钥",
   "video": "视频",
   "pause_video":"暂停视频",
   "resume_video":"恢复视频",
   "refresh_video":"刷新视频",
   "zoom" : "Zoom",
   "zoom_in":"Zoom In",
   "zoom_out":"Zoom Out",
   "mouse":"鼠标",
   "show_cli_cursor":"显示客户端鼠标",
   "show_host_cursor":"显示主机端鼠标",
   "mouse_mode":"鼠标模式",
   "absolute_mm":"绝对鼠标模式",
   "relative_mm":"相对鼠标模式",
   "other_mm":"其他鼠标模式",
   "activeuser" : "使用中的用户",
   "host_display" : "主机显示",
   "hdisplay_on" : "显示 ON",
   "hdisplay_off" : "显示 OFF",
   "capture_screen" : "截取屏幕画面",
   "low_bandwidth" : "低频宽模式",
   "bw_normal" : "一般",
   "bw_8BPP" : "8 BPP",
   "bw_8BPPBW" : "8BPP BW",
   "bw_16BPP" : "16 BPP",
   "options" : "选项",
   "block_priv_request" : "阻挡特权请求",
   "compression_mode": "压缩模式",
   "YUV_420": "YUV 420",
   "YUV_444": "YUV 444",
   "YUV_444_2color": "YUV 444 + 2 color VQ",
   "YUV_444_4color": "YUV 444 + 4 color VQ",
   "DCT_Quantization_table": "DCT 量化表",
   "zero": "0 (最佳质量)",
   "one": "1",
   "two": "2",
   "three": "3",
   "four": "4",
   "five": "5",
   "six": "6",
   "seven": "7 (最差质量)",
   "power" : "电源",
   "power_on" : "电源开启",
   "power_cycle" : "电源循环",
   "power_reset" : "电源重启",
   "record_duration_range" : "视频录制范围为 1 -1800 秒。",
   "record_duration_invalid" : "无效的视频录制范围",
   "video_paused_during_record" : "由于按下暂停影像重新导向，录像将停止.",
   "video_record_status" : "录像中 ...",
   /* For KeyBoard Layout Dialog */
   "kbd_header" : "键盘布局语言",
   "kbd_permission" : "你想覆盖默认的键盘布局的语言？",
   "yes" : "是",
   "no" : "没有",
   /* For KeyBoard Layout Language menus
   ** Note: Extra white spaces are given at the end of some strings.
   **       When appending checklist icon it will be visually pleasing */
   "kbd_layout_hdr" : "键盘布局",
   "kbd_layout_eng" : "英语 U.S ",
   "kbd_layout_ger" : "德语 ",
   "kbd_layout_jap" : "日本 ",
   "kvm_service_disabled": "KVM 服务已经停用。前往设置->服务页面来启用 KVM 服务。",
   "kbd_mouse_encryption":"键盘/鼠标加密",
   "enable_encryption_status" : "键盘/鼠标加密已经由其他会话启用。启用加密于此会话。",
   "disable_encryption_status" : "键盘/鼠标加密由于有多个会话使用中，导致无法停用。",

   /* For hotkeys */
   "usr_macro" : "使用者自定义巨集",
   "err_MaxMacroLimit" : "因为最多只可设定20个热键，所以目前不能再增加热键了.",
   "add" : "新增",
   "close" : "关闭",
   "add_macro" : "新增巨集",
   "add_macro1" : "如要新增使用者自定义巨集，请将鼠标移到文字框内。 按下后放掉按键来定义巨集.",
   "err_SingleMacroLimit" : "最多6组按键组合。现在不能再新增按键组合了.",
   "err_DuplicateMacro" : "你所新增的按键组合已存在。不允许重覆的设定值.",
   "clr" : "清除",
   "clrAll" : "清除全部",
   "insert" : "插入",
   "hotkeys" : "热键",
   /* End of hotkeys */
   "downloadLabel":"启动 KVM",
   "downloadJavaSOLLabel":"下载  Java",
   "downloadJViewerLabel":"Java 控制台",
   "long_control" : "远程控制",
   "remote_java" : "Java 模式",
   "remote_html5" : "Html5 模式",
   "operation_failed": "操作失败，请稍后再试。",
   "kvm_help": "KVM有两种启动模式：HTML5模式和Java模式。请选择一种模式启动KVM。",

    //remotesession
    // "bmc_settings": "BMC 设置",
    // "media_redirection": "媒体重定向",
    // "title": "远程会话",
    //"home": "主页",
    "remotesession": "远程会话",
    "retry_count_must_be_a_number_from_1_to_6": "重试计数必须在 1 到 6 ",
    "retry_time_interval_must_be_a_number_from_5_to_30": "重试时间间隔必须在 5 到 30",
    "remoteSessionStrongSuccessMsg": "远程会话已保存成功。",
    "remoteSessionSuccessMsg": "",
    "remoteSessionStrongFailureMsg": "保存远程会话发生错误。",
    "remoteSessionFailureMsg": "",
    "remotesessionkvm_single_port_application": "KVM 单个连接端口应用程序",
    "remotesessioncheck_this_option_to_enable_single_port_application_support_in_bmc_when_using_h5viewer": "当使用 H5Viewer 时选中此选项可在 BMC 中启用单端口的应用支持。",
    "remotesessionenable_kvm_encryption": "启用 KVM 加密",
    "remotesessioncheck_this_option_to_enable_kvm_encryption_when_using_h5viewer_note_if_single_port_application_support_is_enabled_kvm_encryption_will_not_be_set_and_it_cannot_be_disabled_when_nonsecure_communication_is_not_allowed_": "当使用 H5Viewer 时，选取此选项来启用“KVM 加密”。注意: 如果已启用单个端口的应用程序支持则不能启用 KVM 加密且不能被取消当不安全通讯不被允许。",
    "remotesessionkeyboard_language": "键盘语言",
    "remotesessionselect_the_keyboard_language": "选择键盘语言",
    "remotesessionvirtual_media_attach_mode": "虚拟媒体连接模式",
    "remotesessionselect_the_virtual_media_attach_mode": "选择虚拟媒体连接模式。",
    "remotesessionretry_count": "重试次数",
    "retry_count": "重试次数",
    "remotesessionnumber_of_times_to_be_retried_when_a_kvm_failure_occurs_retry_count_ranges_from_1_to_6": " KVM 连线失败重试次数。重试的次数在 1 到 6。",
    "remotesessionretry_time_intervalseconds": "重试时间间隔(秒)",
    "retry_time_interval_in_seconds": "重试时间间隔 (秒)",
    "remotesessionnumber_of_seconds_to_wait_for_subsequent_retriestime_interval_ranges_from_5_to_30_seconds": "后续重试秒数。时间间隔在 5 到 30 秒。",
    "remotesessionserver_monitor_off_feature_status": "服务器监控 OFF 功能状态",
    "remotesessioncheck_this_option_to_enable_server_monitor_off_feature_status": "点击此选项来启动服务器监控 OFF 功能状态",
    "remotesessionautomatically_off_server_monitor_when_kvm_launches": "当 KVM 启动时，自动 OFF 服务器监控",
    "remotesessioncheck_this_option_to_enable_automatically_off_server_monitor_when_kvm_launches": "当 KVM 启动时，点击此选项来启动自动 OFF 服务器监控",
    "remotesessionenable_server_aspect_ratio": "KVM窗口自适应纵横比",
    "remotesessioncheck_this_option_to_enable_server_aspect_ratio": "选中此项可启用KVM窗口自适应纵横比",
    "remoteSessionSaveLabel": "保存",

    //mouse
    // "bmc_settings": "BMC 设置",
    // "title": "KVM 鼠标设置",
    // "home": "主页",
    "mousemouse_mode_configuration": "KVM 鼠标设置",
    "mouseStrongSuccessMsg": "KVM 鼠标设置已保存成功。",
    "mouseSuccessMsg": "",
    "mouseStrongFailureMsg": "保存 KVM 鼠标设置发生错误。",
    "mouseFailureMsg": "",
    "mousemouse_mode": "鼠标模式",
    "mouserelative_positioning_linux": "相对位置模式 (Linux)",
    "mouseabsolute_positioning_windows": "绝对位置模式 (Windows)",
    "mouseother_mode_sles11_os_installation": "其他模式 (SLES-11)",
    "mousethe_redirection_console_handles_mouse_emulation_from_local_window_to_remote_screen_using_any_of_the_three_methods_administrator_only_have_the_rights_to_configure_this_option_ul_li_relative_mouse_modeli_li_absolute_mouse_modeli_li_other_mouse_modeli_ul_h4relative_mouse_modeh4_the_relative_mode_sends_the_calculated_relative_mouse_position_displacement_to_the_server_to_select_this_mode_select_the_set_mode_to_relative_option_h4absolute_mouse_modeh4_the_absolute_position_of_the_local_mouse_is_sent_to_the_server_to_select_this_mode_select_the_set_mode_to_absolute_option_recommended_for_windows_or_later_linux_releases_h4other_mouse_modeh4select_the_other_mode_to_have_the_calculated_displacement_from_the_local_mouse_in_the_centre_position_sent_to_the_server": "重定向的控制台处理鼠标模拟来自本地窗口到远程屏幕使用三种方法之一。只有“管理员”有权限配置此选项。<ul> <li> - 相对鼠标模式 <\/li> <li> - 绝对鼠标模式<\/li> <li> - 其它鼠标模式<\/li> <\/ul> <h4>相对鼠标模式<\/h4> 相对模式会计算鼠标的相对位移量并传送到服务器，要选择此模式请点选“将模式设置为相对”选项。 <h4>绝对鼠标模式<\/h4> 绝对模式会将本地端鼠标的绝对位置传送到服务器，要选择此模式请点选“将模式设置为绝对”，建议服务器为 Windows 或较新版的 Linux 使用。<h4>其它鼠标模式<\/h4> 其它模式会计算本地鼠标在中心位置的位移量并传送到服务器。",
    "mouseSaveLabel": "保存",

    "launch_java_KVM" : "启动 Java KVM",
    "launch_h5_KVM" : "启动 H5 KVM",
});
