define({
    "system_maintenance": "系统维护",
    "title": "恢复出厂设置",
    "restore_configuration": "",
    "strongSuccessMsg": "成功! 装置将会重启。请关闭浏览器 Session 并开启一个新的浏览器 Session 来重新连接到裝置。",
    "successMsg": "---注销",
    "strongFailureMsg": "恢复出厂设置发生错误。",
    "failureMsg": "",
    "restore_configurationfollowing_checked_configuration_will_be_preserved_you_can_make_changes_to_them_in_a_hrefmaintenancepreserve_configurationpreserve_configurationa_page": "下列选取的配置将会保留设定。您可以到此页更改它们 <a href='#maintenance/firmware_update'>编辑保存配置</a> 。",
    "restore_configurationto_preserve_any_existing_configuration_data_goto_a_hrefmaintenancepreserve_configurationpreserve_configurationa_page_and_select_them": "保留所有现有的配置数据，前往 <a href='#maintenance/firmware_update'>编辑保存配置</a> 页面并选择要保留的配置",
    "restore_configurationsdr": "SDR",
    "restore_configurationfru": "FRU",
    "restore_configurationsel": "SEL",
    "restore_configurationipmi": "IPMI",
    "restore_configurationnetwork": "Network",
    "restore_configurationntp": "NTP",
    "restore_configurationsnmp": "SNMP",
    "restore_configurationssh": "SSH",
    "restore_configurationkvm": "KVM",
    "restore_configurationauthentication": "认证",
    "restore_configurationsyslog": "系统日志",
    "restore_configurationweb": "Web",
    "restore_configurationextlog": "Extlog",
    "restore_configurationredfish": "Redfish",
    "saveConfirmLabel": "点击 OK 来继续进行恢复配置   警告:恢复配置将会重启设备",
    "saveLabel": "恢复出厂设置",

    "home": "主页",
    "maintenance": "系统维护",
    "start_fw_update": "开始固件更新",
    "fwimage": "选择固件镜像",
    "size32mb": "最大容量 32 MB",
    "reset": "固件重置将会关闭当前的会话并在两分后建立出新的会话",
    "section_based_flashing_body": "只有选定的部分将被更新(无法勾选部分表示强制更新):",
    //"cont_update": "更新所选的部分",
    "cont_update": "开始更新",
    "select_all": "全部选择",
    "select_none": "没有选择",
    "section_name": "部分名称",
    "update_section": "更新部分",
    "note_for_table" : "如果你选择恢复配置操作则所有配置项目将会被保存。点击 \"编辑保存配置\"来修改保存状态设置。",
    "preserve_all_config" : "保存所有配置。这会在进行固件更新时保存所有的配置 - 单个项目的保存状态 (保存/覆写)会如下列表格所示。",
    "image_upload" : "选择要进行更新的固件镜像。",
    "start_update" : "点击“开始固件更新”来更新当前设备固件。",
    "preserve_config" : "为了保存当前的配置资料，请前往 <a href='#maintenance/firmware_update'>编辑保存配置</a> 页面并选择",
    "preserve_configuration": "保存配置",
    "preserve_conf_0": "SDR",
    "preserve_conf_1": "FRU",
    "preserve_conf_2": "SEL",
    "preserve_conf_3": "IPMI",
    "preserve_conf_4": "网络",
    "preserve_conf_5": "NTP",
    "preserve_conf_6": "SNMP",
    "preserve_conf_7": "SSH",
    "preserve_conf_8": "KVM",
    "preserve_conf_9": "验证",
    "preserve_conf_10": "系统日志",
    "http": "http/https",
    "tftp": "tftp",
    "public_key_info":"上传 signImage Public Key 资讯",
    "new_signImg_publicKey": "New signImage Public Key",
    "signimage_upload" : "请选择已加密固件的 Sign Image public key 来更新.",
    "prepare_flash":"准备更新...",
    "start_flash":"开始更新...",
    "process":"处理中...",
    "uploading":"上传 ",
    "verify":"校验中...",
    "flashing":"更新...",
    "con_reset":"系统正在重置，请稍后...",
    "prepare_download":"准备下载...",
    "downloading":"下载 ",
    "fwimage_maintance_info":"固件更新文件传输协议如下所示。请通过系统维护下的\"选择文件\"按钮选择需要上传的固件。",
    "protocol_type":"协议类型:",
    "server_address":"服务器地址:",
    "image_name":"固件名称:",
    "retry_count":"重试次数:",
    "href_perser_conf":"编辑保存配置",
    "perserve_config_number":"序号",
    "perserve_config_item":"保存配置内容",
    "preserve_status":"  保存状态 ",
    "upload":"上传",
    "option_overwrite":"覆盖",
    "option_preserve":"保留",
    "option_even":"奇数",
    "option_odd":"偶数",
    "notify_chose_signedImage_publickey_file":"请选择signImage Public Key文件",
    "notify_signedImage_file_upload_success":"SignImage PublicKey上传成功",
    "notify_upload_signedImage_publickey_file":"请上传 SignImage Public Key 文件",
    "confirm_start_fw_upgrade":"固件升级将要开始，固件升级期间将失去BMC的控制和访问权，确定继续吗？",
    "notify_chose_fw_image_file":"请选择要更新的固件文件",
    "alert_invalid_file":"无效的固件文件,只支持 IMA 文件",
    "notify_no_section_select":"请至少选择一个要升级的部分",
    "existing_version":"现有版本",
    "uploading_version":"上传版本",
    "selectFile":"选择文件",
    "fw_FirmwareUpgrade": "固件更新",
    "fw_BMCFirmwareUpgrade": "BMC 固件更新",
    "fw_BIOSFirmwareUpgrade": "BIOS 固件更新",
    "fw_CPLDUpgrade": "CPLD 固件更新",
    "fw_PSUUpgrade": "PSU 固件更新",
    "fw_BPUpgrade": "背板固件更新",
    "fw_edit_conf": "编辑保存配置",
    "fw_restore_conf": "恢复出厂设置",
    "fw_fwimage_location": "固件镜像位置",
    "preserve_configurationsdr": "SDR",
    "preserve_configurationfru": "FRU",
    "preserve_configurationsel": "SEL",
    "preserve_configurationipmi": "IPMI",
    "preserve_configurationnetwork": "Network",
    "preserve_configurationntp": "NTP",
    "preserve_configurationsnmp": "SNMP",
    "preserve_configurationssh": "SSH",
    "preserve_configurationkvm": "KVM",
    "preserve_configurationauthentication": "Authentication",
    "preserve_configurationsyslog": "Syslog",
    "preserve_configurationweb": "Web",
    "preserve_configurationextlog": "Extlog",
    "preserve_configurationredfish": "Redfish",
});
