define({
    "rolegroup_active_directorystrongnotestrong_freeunconfigured_slots_are_denoted_by_noneullito_add_role_group_select_a_free_slot_and_click_on_it_to_add_a_new_role_group_to_the_devicelilito_modify_role_group_select_a_configured_slot_and_click_on_it_to_modify_that_role_groupli_lito_delete_a_role_group_select_the_desired_role_group_to_be_deleted_and_click_on_delete_icon_present_at_right_top_cornerliul": "<strong>注意:</strong> 空闲/未安装的槽被标记为'None'。 <ul><li>选择一个空闲的槽并点击它去新增角色群组到装置。 </li><li>选择一个安装过的槽且点击它去修改角色群组。 </li> <li>选择一个想要删除的角色群组且点击右上角的删除标示。 </li></ul>",
    "home": "主页",
    "settings": "BMC 设置",
    "external_user_settings": "外部用户设置",
    "active_directory_settings": "Active directory 设置",
    "title": "角色组",
    "none": "无",
    "no_access": "没有存取",
    "administrator": "Administrator",
    "oem": "OEM",
    "operator": "操作员",
    "user": "用户",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "invalid_role_group_name_refer_help_for_more_information": "无效的角色组名称。请参考 “帮助” 来获取更多的信息。",
    "invalid_role_group_domain_refer_help_for_more_information": "无效的角色群域。请参考 “帮助” 来获取更多的信息。",
    "rolegroup_active_directory": "",
    "strongSuccessMsg": "角色组设置已成功保存。",
    "successMsg": "",
    "strongFailureMsg": "角色组设置保存失败。",
    "failureMsg": "",
    "rolegroup_active_directorygroup_name": "群组名称",
    "rolegroup_active_directoryenter_the_role_group_name_this_name_identifies_the_role_group_in_active_directoryulli_role_group_name_is_a_string_of_64_alphanumeric_characterslili_special_symbols_hyphen_and_underscore_are_allowedliul": "输入角色群域名。此名称用于识别 Active Directory中的角色组。<ul><li> 角色组名称是一个由 64 个字母数字组成的字符。</li><li> 不允许特殊符号连字符和下划线。</li></ul>",
    "rolegroup_active_directorygroup_domain": "群域",
    "eg_mydomaincom": "eg., MyDomain.com",
    "rolegroup_active_directoryenter_the_role_group_domain_this_is_the_domain_where_the_role_group_is_located_ulli_domain_name_is_a_string_of_255_alphanumeric_characterslili_special_symbols_hyphen_underscore_and_dot_are_allowedliul": "输入角色群域。此处是角色组所在的域。<ul><li> 域名是一个由 255 个字母数字组成的字符。</li><li> 不允许特殊符号连字符、下划线和点。</li></ul>",
    "rolegroup_active_directorygroup_privilege": "群组权限",
    "rolegroup_active_directoryuser": "用户",
    "rolegroup_active_directoryadministrator": "管理员",
    "rolegroup_active_directoryoperator": "操作员",
    "rolegroup_active_directorynone": "无",
    "rolegroup_active_directoryenter_the_role_group_privilege_this_is_the_level_of_privilege_to_be_assigned_for_this_role_group": "输入角色组权限。此处用来分配角色组的权限等级。",
    "rolegroup_active_directorykvm_access": "KVM 存取",
    "rolegroup_active_directorythis_field_provides_access_to_kvm_for_ad_authenticated_role_group_user": "此处用来指定 AD 认证角色组的 KVM 权限等级。",
    "rolegroup_active_directoryvmedia_access": "VMedia 存取",
    "rolegroup_active_directorythis_field_provides_access_to_vmedia_for_ad_authenticated_role_group_user": "此处用来指定 AD 认证角色组的 VMedia 权限等级。",
    "saveLabel": "保存",
    "role_groups": "角色组",

    "external_user_services": "外部用户服务",
    "ext_ldap": "LDAP/E-directory 设置",
    "ext_active_directory": "Active Directory 设置",
    "ext_radius": "RADIUS 设置",
    "ext_general_ldap_settings": "一般 LDAP 设置",
    "ext_role_groups": "角色组 ",
    "ext_active_directory_settings": "一般 Active Directory 设置",
    "ext_general_radius_settings": "一般 RADIUS 设置",
    "ext_advanced_radius_settings": "高级 RADIUS 设置",
    "delete_tip": "确定删除该角色组？",
});
