define({
    "home": "主页",
    "settings": "BMC 设置",
    "title": "服务",
    "service_configuration": "服务配置",
    "service": "服务",
    "status": "状态",
    "active": "活动的",
    "inactive": "非活动的",
    "interfaces": "界面",
    "non_secure_port": "非安全端口",
    "na": "N\/A",
    "secure_port": "安全端口",
    "timeout": "超时",
    "maximum_sessions": "最大会话数",
    "invalid_non_secure_port_refer_help_for_more_information": "无效的非安全端口。请参考“帮助”来取得更多信息。",
    "invalid_secure_port_refer_help_for_more_information": "无效的安全端口。 请参考“帮助”来取得更多信息。",
    "invalid_time_out_refer_help_for_more_information": "无效超时。请参考“帮助”来取得更多信息。",
    "services": "服务",
    "strongSuccessMsg": "服务已保存成功",
    "successMsg": "",
    "strongFailureMsg": "保存服务时发生错误",
    "failureMsg": "",
    "servicesservice_name": "服务名称",
    "servicesbservice_nameb_br_displays_service_name_of_the_selected_slotreadonly": "<b>服务名称<\/b> <br> 显示出所选栏位的服务名称(只读)。",
    "servicesactive": "活动的",
    "servicesbcurrent_stateb_br_displays_the_current_status_of_the_service_either_active_or_inactive_check_this_box_to_start_the_inactive_service": "<b>当前状态<\/b> <br> 显示当前服务状态，为活动或非活动。点击复选框来启动非活动的服务。",
    "servicesinterface_name": "界面名称",
    "servicesbinterfacesbbrit_shows_the_interface_on_which_service_is_running_the_user_can_choose_any_one_of_the_available_interfacesbrbnotebulli_service_mapping_to_disabled_interfaces_will_not_workstatus_of_interface_can_be_checkedenabled_under_configuration_network_lan_settingslili_kvm_and_media_interfaces_are_readonly_when_single_port_is_enabledliul": "<b>界面<\/b><br>此处显示服务运行的网络界面。用户可以选择任意可用的网络界面。<br><b>注意:<\/b><ul><li>- 如服务对应到禁用的网络界面将无法运行。网络界面状态可在 BMC设置 -> 网络设置 -> 网络IP设置 下查看和启用。<\/li><li>- 当单个端口启用时，KVM 和媒体界面为只读。<\/li><\/ul>",
    "servicesnonsecure_port": "不安全端口",
    "valid_unused_port": "有效未使用的端口",
    "servicesbnonsecure_portbbrused_to_configure_non_secure_port_number_for_the_serviceulli_web_default_port_is_80lili_kvm_default_port_is_7578lili_cd_media_default_port_is_5120lili_fd_media_default_port_is_5122lili_hd_media_default_port_is_5123lili_telnet_default_port_is_23lili_port_value_ranges_from_1_to_65535liulbnotebbrssh_service_will_not_support_a_non_secure_port": "<b>非安全端口<\/b><br>用于配置非安全的服务的端口号。<ul><li>- Web 默认端口是 80。<\/li><li>- KVM 默认端口是 7578。<\/li><li>- CD 媒体默认端口是 5120。<\/li><li>- FD 媒体默认端口是 5122。<\/li><li>- HD 媒体默认端口是 5123。<\/li><li>- Telnet 默认端口是 23。<\/li><li>- 端口数值的范围为 1 到 65535。<\/li><\/ul><b>注意:<\/b><br>SSH 服务将不支持不安全的端口。",
    "servicessecure_port": "安全端口",
    "servicesbsecure_portbbrused_to_configure_secure_port_number_for_the_serviceulli_web_default_port_is_443lili_kvm_default_port_is_7582lili_cd_media_default_port_is_5124lili_fd_media_default_port_is_5126lili_hd_media_default_port_is_5127lili_ssh_default_port_is_22lili_port_value_ranges_from_1_to_65535liulbnotebbr_telnet_service_will_not_support_a_secure_port": "<b>安全端口<\/b><br>用于配置安全服务的端口号。<ul><li>- Web 默认端口是 443。<\/li><li>- KVM 默认端口是 7582。<\/li><li>- CD 媒体默认端口是 5124。<\/li><li>- FD 媒体默认端口是 5126。<\/li><li>- HD 媒体默认端口是 5127。<\/li><li>- SSH 默认端口是 22。<\/li><li>- 端口数值范围为 1 到 65535。<\/li><\/ul><b>注意:<\/b><br> Telnet 服务不支持安全端口。",
    "servicestimeout": "超时",
    "in_seconds": "数秒内",
    "servicesbtimeoutbbrdisplays_the_session_timeout_value_of_the_service_for_web_ssh_and_telnet_service_user_can_configure_the_session_timeout_valueulli_web_and_kvm_timeout_value_ranges_from_300_to_1800_secondslili_web_timeout_would_be_ignored_if_there_exists_any_alive_kvm_sessionlili_ssh_and_telnet_timeout_value_ranges_from_60_to_1800_secondslili_ssh_and_telnet_timeout_value_should_be_in_multiples_of_60_secondsliulbnotebbr_ssh_and_telnet_service_will_be_using_the_same_timeout_value_if_the_user_configures_the_ssh_timeout_value_that_will_be_applied_to_the_telnet_service_also_and_vice_versa": "<b>超时<\/b><br>显示服务的会话超时值。为 Web, SSH 和 Telnet 服务，用户可以配置会话超时数值。<ul><li>- Web 和 KVM 超时数值范围为 300 到 1800 秒。<\/li><li>- 如果存在任何活着的 KVM 会话，Web 超时将被忽略。<\/li><li>- SSH 和 Telnet 超时数值范围为 60 到 1800 秒。<\/li><li>- 超时数值应为 60 的倍数。<\/li><\/ul><b>注意:<\/b><br>SSH 和 Telnet 服务将会使用相同的超时数值。如果用户配置 SSH 的超时数值，则 Telnet 服务也同是会被设定相同的数值，反之亦然。",
    "servicesmaximum_sessions": "最大会话数",
    "servicesdisplays_the_maximum_number_of_allowed_sessions_for_the_service": "显示服务允许最大会话数。",
    "hlp_services": "下方陈列了运行在BMC上的服务，显示该项服务当前的状态以及其他基础信息. </br>只有管理员权限能够更改服务的状态.</br> 点击按钮 <i class='ion ion-edit btn-success'></i> 可以修改服务的配置. </br> 点击按钮 <i class='ion ion-navicon btn-default'></i> 可以查看该项服务的配置或者关闭该项服务.",
    "saveConfirmLabel": "正在改变配置中，已经开启服务的会话将会被影响到，此项服务将会重启。按一下 OK 来继续进行?",
    "saveLabel": "保存",
    "active_sessions": "激活会话",
    "servicesdisplays_the_active_number_of_sessions_for_the_service": "显示这个服务的活动会话数目.",
    "NumberOfactive_sessions": "激活会话",
    "network_shared_lan": "共享网络",
    "network_dedicated_lan": "专用网络",
    "enableRedfish": "启用 Redfish",
    "enableRedfishSuccessMsg": "启用 Redfish 成功",
    "enableRedfishFailureMsg": "启用 Redfish 失败，请重试",
    "disableRedfishSuccessMsg": "禁用 Redfish 成功",
    "disableRedfishFailureMsg": "禁用 Redfish 失败，请重试",
    "get_redfish_status_error": "获取 Redfish 失败，请重试",
    "whether_enable_redfish": "是否启用Redfish",
    "whether_disable_redfish": "是否禁用Redfish",
    "save": "保存",
    "enable_redfish_alert": "启用Redfish需等待一分钟左右，请耐心等待。",
    "sshconfirminfo": "注意：配置的超时值也应用于Telnet服务。",
    "Telnetconfirminfo": "注意：配置的超时值也应用于SSH服务。",
    "Webfirminfo": "注意登陆界面将会被退出",
});