define({
   "title" : "存储系统",
   "home" : "主页",
   "systeminfo":"系统信息",
   "load" : "数据加载中",
   "undata" : "无数据",
   "no_raid_controller" : "当前系统没有控制器信息。",
   "physical_undata" : "当前系统没有物理磁盘信息",
   "logical_undata" : "当前系统没有逻辑磁盘信息",
   "no_raid_bbu" : "当前系统没有BBU信息。",
   "eventLog_undata" : "当前系统没有Raid事件日志",
   "operation_succeeded": "操作成功！",
   "operation_failed": "操作失败，请稍后再试",


   "controller_info" : "控制器信息",
   "physical_disk" : "物理磁盘",
   "logical_disk" : "逻辑磁盘",
   "bbu" : "BBU",
   "event_logs" : "事件日志",
   "serial_number" : "Serial Number",
   "package_version" : "Firmware Package Version",
   "bios_version" : "BIOS Version",
   "hii_version" : "HII Version",
   "expander_version" : "Expander Version",
   "seeprom_version" : "NVDATA Version",
   "cpld_version" : "CPLD Version",
   "pci_vendor_id" : "Vendor ID",
   "pci_device_id" : "Device ID",
   "pci_subvendor_id" : "SubVendor ID",
   "pci_subsystem_id" : "SubDevice ID",
   "roc_temp" : "ROC Temp (°C)",
   "expander_temp" : "Expander Temp (°C)",
   "tmm_status" : "TMM Size (MB)",
   "app_version":"Firmware Version",
   "firmware_time":"Firmware Build Time",
   "device_interface":"Device Interface",
   "host_interface":"Host Interface",
   "sas_Addr":"SAS Address",
   "PD_count":"Physical Drive Count",
   "VD_count":"Virtual Drive Count",
   "nvram_size":"NVRAM Size(KB)",
   "memory_size":"Memory Size(MB)",
   "flash_size":"Flash Size(MB)",
   "stripesize_min":"Min Strip Size(KB)",
   "stripesize_max":"Max Strip Size(KB)",
   "spindown_time":"Spin Down Time(Minutes)",
   "rebuild_rate":"Rebuild Rate",
   "bgi_rate":"Back Ground Init(BGI) Rate",
   "cc_rate":"Consistency Check(CC) Rate",
   "recon_rate":"Reconstruction Rate",
   "predfail_poll_interval":"S.M.A.R.T Polling",
   "cache_flush_interval":"Cache Flush Interval(s)",
   "spinup_drive_count":"Spinup Drive Count",
   "spinup_delay":"Spinup Delay",
   "port_count":"Port Count",
   "maintain_PdFailHistory":"Maintain PD Fail History",
   "disable_BatteryWarning":"Battery Warning",
   "disable_AutoRebuild":"AutoRebuild",
   "disable_copyBack":"Smart Copyback Enable",
   "enable_alarm":"Alarm Control",
   "coercion_Mode":"Coercion Mode",
   "disable_NCQ":"NCQ",
   "enable_cluster":"Cluster Mode",
   "enable_SpinDownUnconfigured":"Unconfigured Good Spin Down",
   "disable_SpinDownHS":"Hot Spare Spin Down",
   "support_ShieldState":"Shield State Supported",
   "disable_CtrlR":"Control-R",

   "pd_ID": "序号",
   "device_id": "设备 ID",
   "controller": "控制器",
   "media_type": "媒体类型",
   "state": "状态",
   "hot_spare": "热备份",
   "offline": "离线",
   "failed": "失败",
   "rebuild": "重建",
   "online": "上线",
   "JBOD":"JBOD",
   "copyback": "驱动拷贝",
   "shield_ug": "中间状态",
   "shield_ub": "中间状态",
   "shield_configured": "中间状态",
   "slot": "插槽",
   "speed": "速度",
   "link_speed": "连接速度",
   "size_gb": "大小 (GB)",
   "temp_c": "温度 (℃)",
   "vendor_id": "厂商 ID",
   "product_id": "产品 ID",
   "pd_serial_number": "序列号",
   "power_state": "电源状态",
   "interface_type": "接口类型 ",
   "unconfigured_good": "良好(空闲)",
   "unconfigured_bad": "故障(空闲)",
   "hot_spare": "热备份",
   "offline": "离线",
   "failed": "失败",
   "rebuild": "重建",
   "online": "上线",
   "speed_0":"未定义",
   "speed_1":"1.5Gb/s",
   "speed_2":"3.0Gb/s",
   "speed_3":"6.0Gb/s",
   "speed_4":"12.0Gb/s",
   "ps_state_0":"Spun Up",
   "ps_state_1":"Spun Down",
   "interface_type_0":"未知",
   "interface_type_1":"SCSI",
   "interface_type_2":"SAS",
   "interface_type_3":"SATA",
   "interface_type_4":"FC",

   "add_hotSpare":"添加热备份",
   "remove_hotSpare":"移除热备份",
   "undo_prepare_for_removal":"取消“移除”",
   "prepare_for_removal":"移除",
   "view_available_logical_devices":"查看可用于热备份的逻辑设备",
   "locate_physical_device":"定位物理设备",
   "locate_physical_device_stop":"停止定位物理设备",
   "add_as_dedicated_hotSpare": "添加专用的热备份",
   // ks_lz_20190123_tapdid_1014201++>>  
   "are_you_sure": "确定要执行这个操作吗？",
   "delete_virtual_confirm": "删除RAID有风险，数据将丢失，请谨慎操作。请再次确认是否删除？",
   "no_exist_logical_device": "不存在可用于添加热备份的逻辑磁盘。",

   "ld_ID": "序号",
   "ld_name": "虚拟磁盘名称",
   "type": "类型",
   "read_policy": "读取策略",
   "no_read_ahead": "无预读",
   "read_ahead": "预读",
   "write_policy": "写入策略",
   "write_through": "直写",
   "write_back": "回写",
   "cache_policy": "缓存策略",
   "direct_io": "直接 IO",
   "cache_io": "缓存 IO",
   "access_policy": "访问策略",
   "access_policy_0":"读/写",
   "access_policy_1":"只读",
   "access_policy_2":"锁定",
   "no_phy_devices":"物理磁盘数量",
   "logical_device_infostripe_size_mb": "带宽 (MB) ",
   "logical_device_infobgi": "后台初始化",
   "logical_device_infossd_caching": "SSD 缓存",
   "logical_device_infoprogress": "进度(%)",
   "logical_device_infobad_blocks_table": "坏块表",
   "logical_device_infosize_gb": "大小 (GB)",
   "logical_device_information": "物理磁盘信息",
   "create_logical":"创建虚拟磁盘",

   "view_physical_disk":"查看物理磁盘信息",
   "physical_disk_info": "下面是控制器: {controller} 和  逻辑磁盘ID: {devid} 对应的物理磁盘信息",
   "view_advanced_properties": "查看高级属性",
   "delete_virtual_device": "删除虚拟磁盘",
   "locate_virtual_device": "定位虚拟磁盘",
   "locate_virtual_device_stop": "停止定位虚拟磁盘",
   "consistency_start": "启动一致性检查",
   "consistency_cancel": "取消一致性检查",
   "consistency_start_success": "成功启动一致性检查。",
   "consistency_cancel_success": "成功取消一致性检查。",
   "view_initialize_type": "查看初始化类型",
   "create_logical_devicefast_initialization": "快速初始化",
   "create_logical_deviceslow_initialization": "慢速/完整初始化",
   "initialize":"初始化",
   "initialization_success":"成功初始化。",


    //"logical_device_infostripe_size_mb_": "带宽 (MB) ",
    "logical_device_infostripe_size_mb_": "带宽",
    "logical_device_infobgi": "后台初始化",
    "logical_device_infossd_caching": "SSD 快取",
    "logical_device_infoprogress": "进度(%)",
    "logical_device_infobad_blocks_table": "损坏磁区表",
    "logical_device_infosize_gb": "大小 (GB)",



   "type_0":"RAID0",
   "type_1":"RAID1",
   "type_2":"RAID5",
   "type_3":"RAID6",
   "type_4":"RAID1E",
   "type_5":"RAID1E_RLQ0",
   "type_6":"RAID1E0_RLQ0",
   "type_7":"RAID00",
   "type_8":"RAID10",
   "type_9":"RAID50",
   "type_10":"RAID60",

   "offline": "离线",
   "degraded": "降级",
   "rebuild": "重建",
   "optimal": "最佳化",

   "no_read_ahead": "无预读",
   "read_ahead": "预读",

   "write_through": "直写",
   "write_back": "回写",

   "blocks_empty":"空",
   "blocks_not_empty":"非空",

   "not_available":"N/A",
   "progress_0":"未知",
   "progress_1":"重建",
   "progress_2":"后台初始化中",

   "enabled":"启用",
   "disabled":"停用",

   "create_logical":"创建虚拟磁盘",

   "unknown": "未知",
   "supercap": "超级电容",
   "bbu": "BBU",
   "tbbu": "TBBU",
   "ibbu": "iBBU",
   "itbbu": "iTBBU",
   "battery_backup_subsystem_is_missing": "缺少电池备份子系统",
   "battery_backup_subsystem_is_currently_initializing": "电池备份子系统当前正在初始化",
   "battery_backup_subsystem_is_ready": "电池备份子系统已准备好",
   "battery_backup_subsystem_is_executing_a_learning_cycle": "电池备份子系统正在执行学习循环",
   "battery_backup_subsystem_has_failed": "电池备份子系统失败",
   "super_capacitor_pack_has_exceeded_the_maximum_temperature_threshold": "超级电容温度已超过最高温度阈值",
   "super_capacitor_pack_has_exceeded_the_warning_temperature_threshold": "超级电容温度已超过警告温度阈值",
   "super_capacitor_pack_is_over_voltage": "超级电容电压过高。",
   "battery_backup_subsystem_has_exceeded_the_maximum_charging_current": "电池备份子系统充电电流过大",
   "battery_backup_subsystem_learning_cycle_has_passed": "电池备份子系统学习循环成功",
   "battery_backup_subsystem_learning_cycle_has_failed": "电池备份子系统学习循环失败",
   "bbu_infovoltage_mv": "电压 (mV)",
   "bbu_infocurrent_ma": "电流 (mA)",

   "all_events": "所有事件",
   "event_type_1": "LD 事件",
   "event_type_2": "PD 事件",
   "event_type_3": "封闭事件",
   "event_type_4": "BBU 事件",
   "event_type_5": "SAS 事件",
   "event_type_6": "控制器事件",
   "event_type_7": "配置事件",
   "event_type_8": "Cluster 事件",
   "clear_event_log":"清除事件记录",
   "downLoad_event_log":"下载事件记录",

   "record_id": "记录号",
   "time_stamp": "时间戳",
   "event_code": "事件代码",
   "event_type": "事件类型",
   "event_class": "事件级别",
   "info_events": "信息事件",
   "warning_events": "警告事件",
   "critical_events": "关键事件",
   "fatal_events": "致命事件",
   "dead_events": "Dead 事件",
   "progress_events": "进度事件",
   "debug_events": "调试事件",
   "event_desc":"事件描述",

   "clearLogConfirm" : "该操作将清除所有日志，确定要清空日志吗？",
   "clearLogCompletion" : "清空日志操作完成。",

   "bgi_enabled":"启用后台初始化",
   "bgi_disabled":"禁用后台初始化",
   "ssd_enabled":"启用",
   "ssd_disabled":"停用",


   /* SAS卡信息 */
   "board_name": "名称",
   "sas_address": "SAS 地址",
   "firmware_version": "固件版本",
   "nvdata_version": "NVDATA 版本",
   "ioc_temp": "IOC 温度 (°C)",

   "sasit_physical_device_infodevice_id": "设备 ID",
   "sasit_physical_device_infovendor_id": "厂商 ID",
   "sasit_physical_device_infoproduct_id": "产品 ID",
   "sasit_physical_device_infoserial_number": "序列号",
   "sasit_physical_device_infofw_revision": "FW 版本",
   "sasit_physical_device_infopower_state": "电源状态",
   "sasit_physical_device_infointerface_type_": "接口类型",
   "sasit_physical_device_infosmart": "SMART",
   "na": "N\/A",
   "errors_detected": "检查到错误",
   "errors_not_detected": "未检查到错误",

   "topology_information": "拓朴信息",

    "hide_initialize_type": "隐藏初始化类型",
    
    "show_more_info": "展示更多信息",
    "hide_more_info": "隐藏更多信息",

});
