define({
    "home": "主页",
    "settings": "BMC 设置",
    "video": "视频",
    "auto_settings": "自动设置",
    "title": "视频触发设置",
    "trigger_settings": "",
    "strongSuccessMsg": "视频触发设置已保存成功",
    "successMsg": "",
    "strongFailureMsg": "保存视频触发设置发生错误",
    "failureMsg": "",
    "recording_time_must_be_in_future": "视频时间必定要在未来",
    "trigger_settingscritical_events_temperaturevoltage": "关键事件 (温度\/电压)",
    "trigger_settingsnon_critical_events_temperaturevoltage": "非关键事件 (温度\/电压)",
    "trigger_settingsnon_recoverable_events_temperaturevoltage": "不可恢复事件 (温度\/电压)",
    "trigger_settingsfan_state_changed_events": "风扇状态更改事件",
    "trigger_settingswatchdog_timer_events": "看门狗计时器事件",
    "trigger_settingschassis_power_on_events": "机箱电源开启事件",
    "trigger_settingschassis_power_off_events": "机箱电源关闭事件",
    "trigger_settingschassis_reset_events": "机箱重启事件",
    "trigger_settingslpc_reset_events": "LPC 重启事件",
    "trigger_settingsdate_and_time_event": "日期和时间事件",
    "trigger_settingsdate": "日期",
    "trigger_settingstime": "时间",
    "trigger_settingspreevent_video_recording": "Pre-Event 视频录制",
    "trigger_settingspreevent_video_recording_informations": "Pre-Event 视频录制信息。",
	"event_list_you_can_checkuncheck_a_box_to_add_remove_the_trigger_for_your_system_note":"<b>事件列表:<\/b><br>你可以选取\/取消来添加或删除你的系统的触发器。<br><b>注意:<\/b><br> 应该要启用 KVM 服务来执行自动视频录制。<br>可在高级配置中设置系统日期和时间。",
    "trigger_settingscrash_reset": "Crash Reset",
    "trigger_settingsprecrash": "Pre-crash",
    "trigger_settingsprereset": "Pre-reset",
    "saveLabel": "保存"
});
