define({
    "home": "主页",
    "settings": "BMC 设置",
    "title": "用户/用户组",
    "users_list": "用户列表",
    "edit_title": "编辑用户",
    "disabled": "(禁用)",
    "active": "(活动中)",
    "empty_slot": "(空槽)",
    "no_access": "禁止访问",
    "administrator": "管理员",
    "oem": "OEM",
    "operator": "操作员",
    "user": "用户",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "snmp": "SNMP",
    "invalid_username_refer_help_content": "无效的用户名。请参考“帮助”。",
    "password_field_must_be_8_characters_atleast": "无效的密码。请参考“帮助”。",
    "passwords_do_not_match": "两次密码输入不一致",
    "invalid_email_format_refer_help_content": "无效的电子邮件 ID，请参考“帮助”。",
    "users": "",
    "strongSuccessMsg": "保存成功！",
    "successMsg": "",
    "strongFailureMsg": "保存失败，请稍后再试。",
    "failureMsg": "",
    "userNameIsExist": "新建用户名已存在。",
    "Failed_to_get_user_information": "获取用户信息错误。",
    "Failed_to_set_creation_time": "设置创建时间错误。",
    "Failed_to_set_user_information": "设置用户信息错误。",
    "Failed_to_set_SNMP": "设置用户SNMP信息错误。",
    "Failed_to_set_email": "设置用户邮箱错误。",
    "Failed_to_set_email_format": "设置用户邮箱格式错误。",
    "Failed_to_set_extended_privilege": "设置用户扩展权限错误。",
    "Failed_to_set_ssh_key": "设置用户ssh秘钥错误。",
    "usersusername": "用户名",
    "usersenter_the_name_of_the_new_user_ulli_user_name_is_a_string_of_1_to_16_alphanumeric_charactersli_li_it_must_start_with_an_alphabetical_characterli_li_it_is_casesensitiveli_li_special_characters_hyphen_underscore_at_sign_are_allowedliul":"请输入添加的用户名。  <ul><li> 用户名是一个长度为 1 到 16 个数字及字母组成的字符串。<\/li> <li> 必须要以字母作为起始的字符。<\/li> <li> 区分大小写。<\/li> <li> 允许特殊字符 '-'(连字符),  '_'(下划线), '@'(at符号)。<\/li><\/ul>",
    "userspassword": "密码",
    "usersenter_a_strong_password_including_a_alphabets_numbers_symbol_and_upper_case_characters": "请输入强度更强的密码包含字母、数字、符号、以及大写字符。",
    "usersconfirm_password": "确认密码",
    "usersconfirm_the_password": "再一次确认密码。",
    "userspassword_size": "密码大小",
    "users16_bytes": "16 字节",
    "users20_bytes": "20 字节",
    "userssize_of_the_password": "选择可输入的最大密码长度。",
    "usersenable_user_access": "启用用户访问",
    "userscheck_the_box_to_enable_user_access_for_the_user": "勾选该选项为启用用户访问。",
    "usersnetwork_privilege": "网络权限",
    "usersuser": "用户",
    "usersadministrator": "管理员",
    "usersoperator": "操作员",
    "usersoem": "OEM",
    "usersnone": "无",
    "usersselect_the_privilege_level_assigned_to_this_user_when_the_user_access_bmc_through_network_interface_5_levels_are_available_administrator_operator_user_oem_and_no_access": "选择用户通过网络接口访问BMC的权限。五个等级的用户权限可使用: 管理员, 操作员, 用户, OEM 和 禁止访问。",
    "usersserial_privilege": "串口权限",
    "usersselect_the_privilege_level_to_be_assigned_to_this_user_when_the_user_access_bmc_through_serial_interface_5_levels_are_available_administrator_operator_user_oem_and_no_access": "选择用户通过串行接口访问BMC的权限。五个等级的用户权限可使用: 管理员, 操作员, 用户, OEM 和 禁止访问。",
    "userskvm_access": "KVM 访问",
    "usersthis_field_is_used_to_assign_the_kvm_privilege_for_the_user": "勾选该选项为给用户分配 KVM 访问权限。",
    "usersvmedia_access": "VMedia 访问",
    "usersthis_field_is_used_to_assign_the_vmedia_privilege_for_the_user": "勾选该选项为给用户分配 VMedia 访问权限。",
    "userssnmp_access": "SNMP 访问",
    "userscheck_the_box_to_enable_snmp_access_for_the_user": "勾选该选项为启用用户 SNMP 访问权限。<strong>注意:</strong> 当 SNMP 状态为启用时，密码栏位必填且至少具有八个字符。",
    "userssnmp_access_level": "SNMP 访问级别",
    "usersread_only": "只读",
    "usersread_write": "读写",
    "userschoose_the_snmp_access_level_option_for_user_it_can_be_either_read_only_or_read_write": "选择用户 SNMP 访问级别选项。可选择只读或读写。",
    "userssnmp_authentication_protocol": "SNMP 认证协议",
    "userssha": "SHA",
    "usersmd5": "MD5",
    "userschoose_an_authentication_protocol_for_snmp_settings_strongnotestrong_password_field_is_mandatory_if_authentication_protocol_is_changed": "选择一种身份认证协议以供 SNMP 设置使用。 <strong>注意:<\/strong> 如果更改身份认证协议，则密码栏位强制必填。",
    "userssnmp_privacy_protocol": "SNMP 隐私协议",
    "usersdes": "DES",
    "usersaes": "AES",
    "userschoose_the_encryption_algorithm_to_use_for_snmp_settings": "选择一种加密方式供 SNMP 设置使用。",
    "usersemail_format": "电子邮件格式",
    "usersamiformat": "AMI-格式",
    "usersfixedsubjectformat": "FixedSubject-格式",
    "usersspecify_the_format_for_the_email_this_format_will_be_used_while_sending_the_email_two_type_of_formats_are_available_ulli_amiformat_the_subject_of_this_mail_format_is_alert_from_your_hostname_the_mail_content_shows_sensor_information_ex_sensor_type_and_descriptionliul_ulli_fixedsubjectformat_this_format_displays_the_message_according_to_users_setting_you_must_set_the_subject_and_message_for_email_alertliul":
    "指定电子邮件格式。此格式将会在传送电子邮件时使用。两种格式皆可使用: <ul><li> AMI-格式: 电子邮件格式标题为 'Alert from (您的主机名)'。此封邮件会显示传感器信息, 例如: 传感器类型和描述。<\/li><\/ul> <ul><li> FixedSubject-格式: 此格式显示消息根据用户的设置。 您必须设置电子邮件通知的主题和消息。<\/li><\/ul>",
    "usersemail_id": "电子邮件 ID",
    "usersenter_the_email_id_for_the_user_if_user_forgets_the_password_new_password_will_be_mailed_to_the_configured_email_id_strongnotestrong_smtp_server_must_be_configured_to_send_the_email":"输入用户的电子邮件 ID。如果用户忘记密码，新密码将会发送到配置的电子邮件 ID。 <strong>注意:<\/strong> SMTP 服务器必须要配置为发送电子邮件。",
    "usersexisting_ssh_key": "现有的 SSH 密钥",
    "usersthe_uploaded_ssh_key_information_will_be_displayed_read_only": "显示已上传的 SSH 密钥信息 (只读).",
    "usersupload_ssh_key": "上传 SSH 密钥",
    "usersuse_browse_button_to_navigate_to_the_public_ssh_key_file_ulli_ssh_key_file_should_be_of_pub_typeliul": "使用搜寻按钮来浏览公用的 SSH 密钥文件。 <ul><li> SSH 密钥文件应该要为公用类型。<\/li><li> SSH 密钥文件大小不能超过4MB。<\/li><\/ul>",
    "usersupload_ssh_key_exceed": "SSH 密钥文件大小不能超过4KB。",
    "deleteLabel": "删除",
    "saveLabel": "保存",
    "user_management": "用户管理",
    "non_privilege_user_delete": "你没有权限去删除这位用户。",
    "delete_confirmation_message": "确定要删除该用户吗？",
    "Failed_to_delete_user_email": "删除用户邮箱错误。",
    "Failed_to_delete_lan_information": "删除用户网络信息错误。",
    "Failed_to_delete_snmp": "删除用户snmp信息错误。",
    "Failed_to_delete_user": "删除用户错误。",
    "user_hlp":"下列清单显示当前可用的用户。要添加、修改或编辑用户，请按一下图示。<br/>最多为十个栏位可以使用，并包含了预设的管理员以及匿名账号。<br/>建议匿名用户权限以及密码应该要适当的修改以符合安全的标准。查看此页面，须要具有操作者的权限。并只限管理员权限才可进行修改。",
    "add_user":"添加用户",
    //fanysh_jd_user_require_0509
    "usersenter_a_strong_password_minlenth_to_maxlenth": "请输入至少8个字符的密码。",
    "password_complexity":"启用密码复杂度",
    "userscheck_the_box_to_enable_password_complexity":"如果启用密码复杂度，密码应同时包含大小写字母、数字及特殊符号。",
    "userscheck_the_box_to_change_password":"勾选该选项为启用密码更改。",
    "change_password":"更改密码",
    "belong_group":"所属分组",
    "belong_group_help":"通过选择所属分组，用户会拥有不同的权限。用户的权限是通过分组来控制的。",
    "select_group":"请选择用户组",
    "turnon_password_expiry_help":"选中此项后，开启验证用户密码有效期的功能。",
    "turnon_password_expiry":"启用密码有效期",
    "password_expiry_help":"用来控制用户密码的到期日期。",
    "password_expiry_date":"密码有效期",
    "setting_password_expiry_date":"请选择密码有效期",
    "allow_user_number": "系统只允许创建{n}个用户",

    /*用户组管理-多语化数据*/
    "edit_group": "编辑用户组",
    "edit_user": "编辑用户",
    "loading" : "加载中",
    "undata" : "无数据",
    "tab_users": "用户",
    "tab_groups": "用户组",
    "role": "用户组角色",
    "any_role": "任何角色",
    "privilege": "高级权限",
    "any_privilege": "任何权限",
    "add_group": "添加用户组",
    "members": "组员",
    "edit": "编辑",
    "delete": "删除",
    "user_info": "用户信息",
    "group_info": "用户组信息",
    "save": "保存",
    "group_name": "用户组名称",
    //"group_name": "不能为空",
    "name_notNull": "名称不能为空",
    "role_notNull": "角色不能为空",
    "save_success": "保存成功！",
    "save_failed": "保存失败。",
    "name_exists": "名称已存在，请重新输入。",
    "group_deleteSure": "确定要删除用户组吗？",
    "yes": "确定",
    "no": "取消",
    "no_member": "无组员",
    "not_edited_group": "当前用户组为系统保留组，只能查看不允许编辑。",
    "allow_group_number": "系统只允许创建{n}个用户组",
    "not_deleted_group": "该用户组下存在用户，不能删除。",
    "delete_success": "删除成功！",
    "login_again": "密码已被修改，请重新登录！",
    // ks_lz_20190228_TAPDID_1015590 ++>>
    "repeat_verify_config_error": "请保证要更改的密码与最近三次设置的密码不同。"
});
