define({
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "port_oriented_firewall_rules": "Port Oriented Firewall Rules",
    "title": "Add Port Rule",
    "add_port_rule": "",
    "enter_valid_port_number_refer_help_for_more_information": "Enter valid Port Number, Refer 'Help' for more Information",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set": "End time required when timeout is set",
    "strongSuccessMsg": "Port Rule configurations has been updated successfully.",
    "successMsg": "",
    "strongFailureMsg": "",
    "failureMsg": "Error in updating the Port Rule configurations.",
    "add_port_ruleport_single_or_range_start": "Port Single (or) Range Start",
    "add_port_rulethis_field_is_used_to_configured_the_port_or_range_of_port_addressesul_li_port_value_ranges_from_1_to_65535liulstrongnote_strong_port_80_is_blocked_for_tcpudp_protocols": "This field is used to configured the Port or Range of Port Addresses.<ul> <li> Port value ranges from 1 to 65535.<\/li><\/ul><strong>NOTE: <\/strong> Port 80 is blocked for TCP\/UDP protocols.",
    "add_port_ruleport_range_end": "Port Range End",
    "optional": "optional",
    "add_port_rulethis_field_is_used_to_configured_the_port_or_range_of_port_addressesul_li_port_value_ranges_from_1_to_65535_ulstrongnote_strong_port_80_is_blocked_for_tcpudp_protocols": "This field is used to configured the Port or Range of Port Addresses.<ul> <li> Port value ranges from 1 to 65535. <\/ul><strong>NOTE: <\/strong> Port 80 is blocked for TCP\/UDP protocols.",
    "add_port_ruleprotocol": "Protocol",
    "add_port_ruletcp": "TCP",
    "add_port_ruleudp": "UDP",
    "add_port_ruleboth": "Both",
    "add_port_rulenetwork_type": "Network Type",
    "add_port_ruleipv4": "IPv4",
    "add_port_ruleipv6": "IPv6",
    "add_port_ruleenable_timeout": "Enable Timeout",
    "add_port_rulethis_option_used_to_enable_or_disable_firewall_rules_with_timeout": "This option used to enable or disable firewall rules with timeout.",
    "add_port_rulestart_date": "Start Date",
    "add_port_rulethe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "add_port_rulestart_time": "Start Time",
    "add_port_rulethe_respective_firewall_rule_effect_will_start_from_this_time": "The respective firewall rule effect will start from this time.",
    "add_port_ruleend_date": "End Date",
    "add_port_rulethe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "add_port_ruleend_time": "End Time",
    "add_port_rulethe_respective_firewall_rule_effect_will_end_from_this_time": "The respective firewall rule effect will end from this time.",
    "add_port_rulerule": "Rule",
    "add_port_ruleallow": "Allow",
    "add_port_ruleblock": "Block",
    "saveLabel": "Save"
});
