define({
    "home": "Home",
    "settings": "BMC Settings",
    "alarm_settings": "Alarm Settings",

    //snmp
    "snmp_trap_title": "SNMP Trap Setting",
    "snmp": "SNMP Trap Setting",
    "no_snmp_trap_information": "Error in querying SNMP Trap Setting information.",
    "snmpTrapStrongSuccessMsg": "SNMP Trap Settings has been saved successfully",
    "snmpTrapSuccessMsg": "",
    "snmpTrapStrongFailureMsg": "Error in saving SNMP Trap Settings",
    "snmpTrapFailureMsg": "",
    "rw_char": "RW Community Name",
    "ro_char": "RO Community Name",
    "snmpcheck_this_option_to_enable_snmp_support_for_the_bmc" : "Check this option to enable SNMP support for the BMC.",
    "snmp_support": "SNMP Status Enable",
    "snmp_protocol": "SNMP Protocol",
    "snmp_visit": "SNMP Visit",
    "privacy_protocol": "Privacy Protocol",


    "snmpTrapSaveLabel": "Save",
    "help_information":"Sets the read and write permissions for the community name of the SNMP v1/v2. If it’s the SNMP V3 , please sets by the user management page.",

    "trap_help_information":"The SNMP v1/v2, please input the community name. The SNMP V3, plesse select the user name (The length of user's password should not be less than 8 bits).",
    "trap_help_snmp_addr":"The saved SNMP Address can be tested. The system will not check the test results, please confirm whether it is successful.",


    "whether_enable": "Enable SNMP Trap Alarm",
    "on": "ON",
    "off": "OFF",
    "v1": "V1",
    "v2": "V2",
    "v3": "V3",
    "community": "Community Name",
    "v3_user": "V3 User (The length of user's password should not be less than 8 bits)",
    "not_null": "Cannot be empty",
    "alarm_grade": "Alarm Grade",
    "check_all": "Check All",
    "urgency": "Urgency",
    "critical": "Critical",
    "non_critical": "Non Critical",
    "normal": "Normal",
    "snmp_addr": "SNMP Address",
    "snmp_test": "Test",
    "ip_incorrect": "IP address format is incorrect",
    "sent_to_ip": 'The test information has been sent to <strong>{IP}<\/strong>. please confirm , and the system will not check whether the reception is successful.',
    "sent_to_ip_error": 'Error in testing SNMP Address <strong>{IP}<\/strong>.',

    //smtp
    "smtp_title": "SMTP Settings",
    "no_smtp_setting_information": "Error in querying SMTP setting information.",
    "smtpStrongSuccessMsg": "SMTP Settings has been saved successfully.",
    "smtpStrongFailureMsg": "Error in saving SMTP Settings.",
    "smtpprimary_smtp_support": "Enable SMTP",
    "smtpcheck_this_option_to_enable_smtp_support_for_the_bmc": "Check this option to enable SMTP support for the BMC.<br>",
    "smtpsender_email_id": "Sender Email",
    "smtpcheck_email_help": "Enter the valid  'Sender Email' on the SMTP Server. Maximum allowed size for Email is 64 bytes which includes username and domain name.",
    "smtpprimary_server_name": "Server Name",
    "smtpenter_the_machine_name_of_the_smtp_server_ul_li_machine_name_is_a_string_of_maximum_15_alphanumeric_charactersli_li_space_special_characters_are_not_allowedli_ul": "Enter the 'Machine Name' of the SMTP Server.<strong> It is a mandatory field. </strong><ul> <li> Machine Name is a string of maximum 25 alpha-numeric characters.<\/li> <li> Space, special characters are not allowed.<\/li> <\/ul>",
    "smtpprimary_server_ip": "Server IP",
    "smtp_enter_the_ip_address_of_the_smtp_server_it_is_a_mandatory_field_ul_li_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxx_xxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul_server_address_will_support_the_following_ul_li_ipv4_address_format_li_ipv6_address_format_ul": " Enter the 'IP address' of the SMTP Server.<strong> It is a mandatory field. </strong> <ul> <li> IP Address made of 4 numbers separated by dots as in 'xxx.xxx.xxx.xxx'.<\/li> <li> Each Number ranges from 0 to 255.<\/li> <li> First Number must not be 0.<\/li> <\/ul> Server address will support the following: <ul> <li> IPv4 Address format. <li> IPv6 Address format. <\/ul>",
    "smtpenter_the_password_for_the_smtp_user_account_ul_li_password_must_be_at_least_4_characters_longli_li_white_space_is_not_allowedli_ul_strongnotestrong_this_field_will_not_allow_more_than_64_characters": "Enter the password for the Sender Email. <ul> <li> Password must be at least 4 characters long.<\/li> <li> White space is not allowed.<\/li> <\/ul> <strong>NOTE:<\/strong> This field will not allow more than 64 characters.",
    "smtpprimary_password": "Sender Email Password",
    "mail_theme_help": "Mail theme of sending alarm mail.",
    "mail_theme": "Mail Theme",
    "alarm_grade": "Alarm Grade",
    "check_all": "Check All",
    "urgency": "Urgency",
    "critical": "Critical",
    "non_critical": "Non Critical",
    "normal": "Normal",
    "receiving_mail_help":"Enter the electronic mailbox information that receives the alarm.<ul> <li> Enters the correct emial address, the reception alarm function can be enabled.<\/li> <li> Saves the mailbox information, it can be tested. <\/li> <\/ul> <strong> Note:<\/strong> System does not check the test results, please confirm whether the test is successful or not.",
    "receiving_mail": "Recipient Mailbox Information",
    "mailbox": "Mailbox",
    "description": "Description",
    "test_mailbox": "Test",
    "sent_to_mailAddr": 'The test mail has been sent to <strong>{mailAddr}<\/strong>. please confirm , and the system will not check whether the reception is successful.',
    "sent_to_mailAddr_error": 'Error in testing mailbox <strong>{mailAddr}<\/strong>.',
    "primary_server_ip_is_required_valid": "Enter valid the Server IP.",
    "primary_server_name_is_required": "Enter valid the Server Name.",
    "smtp_invalid_email_format_refer_help_content": "Enter valid the Email.",
    "username_for_primary_server_is_required": "Enter valid the Mail Theme.",
    "password_for_primary_server_is_required": "Enter valid the Sender Email Password.",
    "smtpSaveLabel": "Save",

    ///////////////////////////
    /*"smtp": "",
    "primary_smtp_support_is_required": "Primary SMTP Support is required",
    "primary_server_port_is_required": "Enter valid primary server port range between 1-65535",
    "primary_server_secure_port_is_required":" Enter valid primary secure SMTP port",
    "primary_server_ip_is_required": "Enter valid primary server IP",
    "secondary_server_name_is_required": "Enter valid secondary server name ",
    "secondary_server_port_is_required": "Enter valid secondary server port ",
    "secondary_server_secure_port_is_required": "Enter valid secondary server secure port",
    "secondary_server_ip_is_required": "Enter valid secondary server IP",
    "username_for_secondary_server_is_required": "Enter valid secondary username",
    "password_for_secondary_server_is_required": "Enter valid secondary password",
    "successMsg": "",
    "failureMsg": "",
    "smtplan_interface": "LAN Interface",
    "smtpprimary_smtp_port": "Primary SMTP port",
    "smtpspecify_the_smtp_port_ul_li_default_port_is_25li_li_port_value_ranges_from_1_to_65535li_ul": "Specify the SMTP Port.<strong> It is a mandatory field. </strong> <ul> <li> Default Port is 25.<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpprimary_secure_smtp_port": "Primary Secure SMTP port",
    "smtpspecify_the_smtp_secure_port_ul_li_default_port_is_465li_li_port_value_ranges_from_1_to_65535li_ul": "Specify the SMTP Secure Port. <ul> <li> Default Port is 465.<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpprimary_smtp_authentication": "Primary SMTP Authentication",
    "smtpcheck_the_option_enable_to_enable_smtp_authentication_note_smtp_server_authentication_types_supported_are_ul_li_crammd5li_li_loginli_li_plainli_ul_if_the_smtp_server_does_not_support_any_one_of_the_above_authentication_types_the_user_will_get_an_error_message_stating_iauthentication_type_is_not_supported_by_smtp_serveri": "Check the option 'Enable' to enable SMTP Authentication. Note: SMTP Server Authentication Types supported are: <ul> <li> CRAM-MD5<\/li> <li> LOGIN<\/li> <li> PLAIN<\/li> <\/ul> If the SMTP server does not support any one of the above authentication types, the user will get an error message stating, <i>'Authentication type is not supported by SMTP Server'<\/i>",
    "smtpprimary_username": "Primary Username",
    "smtpenter_the_username_to_access_smtp_accounts_ul_li_user_name_can_be_of_length_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetli_li_special_characters_comma_colon_semicolon_space_and_backslash_are_not_allowedli_ul": "Enter the username to access SMTP Accounts. <ul> <li> User Name can be of length 4 to 64 alpha-numeric characters, dot(.), hyphen(-), and underscore(_).<\/li> <li> It must start with an alphabet.<\/li> <li> Other special characters are not allowed.<\/li> <\/ul>",
    "smtpprimary_smtp_ssltls_enable": "Primary SMTP SSLTLS Enable",
    "smtpcheck_the_option_enable_to_enable_smtp_ssltls_protocol": "Check the option 'Enable' to enable SMTP SSLTLS protocol.",
    "smtpprimary_smtp_starttls_enable": "Primary SMTP STARTTLS Enable",
    "smtpcheck_the_option_enable_to_enable_smtp_starttls_protocol": "Check the option 'Enable' to enable SMTP STARTTLS protocol.",
    "smtpupload_smtp_ca_certificate_file": "Upload SMTP CA Certificate File",
    "smtpuse_browse_button_to_navigate_to_upload_cacert_ulli_cacert_key_file_should_be_of_pem_typeliul": "Use Browse button to navigate to upload CACERT. <ul><li> CACERT key file should be of pem type.<\/li><\/ul>",
    "smtpupload_smtp_certificate_file": "Upload SMTP Certificate File",
    "smtpuse_browse_button_to_navigate_to_upload_cert_ulli_cert_key_file_should_be_of_pem_typeliul": "Use Browse button to navigate to upload CERT. <ul><li> CERT key file should be of pem type.<\/li><\/ul>",
    "smtpupload_smtp_private_key": "Upload SMTP Private Key",
    "smtpuse_browse_button_to_navigate_to_upload_smtp_key_ulli_smtp_key_file_should_be_of_pem_typeliul": "Use Browse button to navigate to upload SMTP KEY. <ul><li> SMTP key file should be of pem type.<\/li><\/ul>",
    "smtpsecondary_smtp_support": "Secondary SMTP Support",
    "smtpcheck_this_option_to_enable_secondary_smtp_support_for_the_bmc": "Check this option to enable Secondary SMTP support for the BMC.",
    "smtpsecondary_server_name": "Secondary Server Name",
    "smtpenter_the_machine_name_of_the_secondary_smtp_server_ul_li_machine_name_is_a_string_of_maximum_15_alphanumeric_charactersli_li_space_special_characters_are_not_allowedli_ul": "Enter the 'Machine Name' of the Secondary SMTP Server. <ul> <li> Machine Name is a string of maximum 25 alpha-numeric characters.<\/li> <li> Space, special characters are not allowed.<\/li> <\/ul>",
    "smtpsecondary_server_ip": "Secondary Server IP",
    "smtp_enter_the_ip_address_of_the_secondary_smtp_server_ul_li_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxx_xxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0li_ul_server_address_will_support_the_following_ul_li_ipv4_address_format_li_ipv6_address_format_ul": " Enter the 'IP address' of the Secondary SMTP Server.  <ul> <li> IP Address made of 4 numbers separated by dots as in 'xxx.xxx. xxx.xxx'.<\/li> <li> Each Number ranges from 0 to 255.<\/li> <li> First Number must not be 0.<\/li> <\/ul> Server address will support the following: <ul> <li> IPv4 Address format. <li> IPv6 Address format. <\/ul>",
    "smtpsecondary_smtp_port": "Secondary SMTP port",
    "smtpspecify_the_secondary_smtp_port_ul_li_default_port_is_25li_li_port_value_ranges_from_1_to_65535li_ul": "Specify the Secondary SMTP Port. <ul> <li> Default Port is 25.<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpsecondary_smtp_secure_port": "Secondary SMTP Secure port",
    "smtpspecify_the_secondary_smtp_secure_port_ul_li_default_port_is_465li_li_port_value_ranges_from_1_to_65535li_ul": "Specify the Secondary SMTP Secure Port. <ul> <li> Default Port is 465.<\/li> <li> Port value ranges from 1 to 65535.<\/li> <\/ul>",
    "smtpsecondary_smtp_authentication": "Secondary SMTP Authentication",
    "smtpcheck_the_option_enable_to_enable_secondary_smtp_authentication_note_smtp_server_authentication_types_supported_are_ul_li_crammd5li_li_loginli_li_plainli_ul_if_the_smtp_server_does_not_support_any_one_of_the_above_authentication_types_the_user_will_get_an_error_message_stating_iauthentication_type_is_not_supported_by_smtp_serveri": "Check the option 'Enable' to enable Secondary SMTP Authentication. Note: SMTP Server Authentication Types supported are: <ul> <li> CRAM-MD5<\/li> <li> LOGIN<\/li> <li> PLAIN<\/li> <\/ul> If the SMTP server does not support any one of the above authentication types, the user will get an error message stating, <i>'Authentication type is not supported by SMTP Server'<\/i>",
    "smtpsecondary_username": "Secondary Username",
    "smtpsecondary_password": "Secondary Password",
    "smtpsecondary_smtp_ssltls_enable": "Secondary SMTP SSLTLS Enable",
    "smtpsecondary_smtp_starttls_enable": "Secondary SMTP STARTTLS Enable",
    "smtpuse_browse_button_to_navigate_to_upload_key_ulli_key_file_should_be_of_pem_typeliul": "Use Browse button to navigate to upload KEY. <ul><li>  KEY file should be of pem type.<\/li><\/ul>",
    "must_upload_files": "Please select a .pem file to upload",*/

    //advanced_log
    "advancedLogTitle": "Syslog Settings",
    "advanced_log": "Syslog Settings",
    "invalid_remote_log_server_address_refer_help_for_more_information": "Invalid Remote Log Server address. Refer 'Help' for more Information.",
    "invalid_port_refer_help_for_more_information": "Invalid port. Refer 'Help' for more Information.",
    "invalid_file_size_refer_help_for_more_information": "Invalid File Size. Refer 'Help' for more Information.",
    "invalid_rotate_count_value_refer_help_for_more_information": "Invalid Rotate Count value. Refer 'Help' for more Information.",
    "advancedLogStrongSuccessMsg": "Log Settings has been saved successfully.",
    "advancedLogSuccessMsg": "",
    "advancedLogStrongFailureMsg": "Error in saving Log Settings.",
    "advancedLogFailureMsg": "",
    "advanced_logenable_system_log": "Enable System Log",
    "advanced_logselect_enable_system_log_to_view_all_system_events_entries_can_be_filtered_based_on_their_classification_levels": "Select Enable System Log to view all system events. Entries can be filtered based on their classification levels.",
    "advanced_loglocation": "Location",
    "advanced_loglocal_log": "Local Log",
    "advanced_logremote_log": "Remote Log",
    "advanced_logfile_sizebytes": "File Size(bytes)",
    "size_in_bytes": "Size in bytes",
    "advanced_logif_local_log_is_selected_specify_the_size_of_the_file_in_bytesulli_size_ranges_from_3_to_65535lililog_files_are_rotated_when_the_size_is_larger_than_the_mentioned_bytes_with_regards_for_the_last_rotation_time_interval_1_minuteliul": "If Local log is selected, specify the size of the file in bytes.<ul><li> Size ranges from 3 to 65535.<\/li><li>Log files are rotated when the size is larger than the mentioned bytes, with regards for the last rotation time interval (1 minute).<\/li><\/ul>",
    "advanced_logrotate_count": "Rotate Count",
    "maximum_count": "Maximum count",
    "advanced_logwhen_logged_information_exceeds_the_specified_file_size_the_old_log_information_automatically_gets_moved_to_back_up_files_based_on_the_rotate_count_value_if_the_rotate_count_is_zero_the_old_log_information_gets_cleared_permanently_each_timeulli_rotate_count_value_must_be_0_or_1liul": "When logged information exceeds the specified file size, the old log information automatically gets moved to back up files based on the rotate count value. If the rotate count is zero, the old log information gets cleared permanently each time.<ul><li> Rotate count value must be 0 or 1.<\/li><\/ul>",
    "advanced_logremote_log_server": "Remote Log Server1",
    "advanced_logremote_log_server1": "Remote Log Server2",
    "server_ip_or_hostname": "Server IP or Hostname",
    "advanced_logspecify_the_remote_server_address_to_log_system_events_server_address_support_the_followingulli_ip_address_both_ipv4_and_ipv6_formatlili_fqdn_fully_qualified_domain_name_formatliulstrongnotestrong_maximum_allowed_size_for_remote_log_server_address_is_64_bytes": "Server address support the following:<ul><li> IP Address (Both IPv4 and IPv6 format).<\/li><li> FQDN (Fully qualified domain name) format<\/li><\/ul><strong>NOTE:<\/strong> Maximum allowed size for Remote Log Server Address is 64 bytes.",
    "advanced_logremote_server_port": "Remote Server1 Port",
    "advanced_logremote_server_port1": "Remote Server2 Port",
    "server_port": "Server Port",
    "advanced_logspecify_the_port_number_to_log_system_eventsbrstrongnotestrong_the_default_port_number_is_514": "Specify the port number to log system events.<br><strong>NOTE:<\/strong> The default port number is 514.",
    "advanced_logenable_audit_log": "Enable Audit Log",
    "advanced_logselect_enable_audit_log_to_view_all_audit_events_for_this_device": "Select Enable Audit Log to view all audit events for this device.",
    "advancedLogSaveLabel": "Save",
    "audit_log_to_remote": "Audit Log To Remote",
    "pef_sel_to_remote": "PEF SEL To Remote",
    "enable_remote_log": "Enable Remote Log",
    "alarm_grade": "Alarm Grade",
    "check_all": "Check All",
    "urgency": "Urgency",
    "critical": "Critical",
    "non_critical": "Non Critical",
    "normal": "Normal",
    "not_null": "Cannot be empty",
});
