define({
    "home": "Home",
    "system_information": "System information",
    "raid_management": "RAID Management",
    "title": "BBU Information",
    "bbu_info": "",
    "bbu_inforaid_controller": "RAID Controller",
    "bbu_infoon_selecting_any_particular_raid_controllerthis_page_displays_typestatustempvoltage_and_current_details_about_the_battery_backup_unit_of_raid_controller": "On selecting any particular RAID Controller,this page displays Type,Status,Temp,Voltage and Current details about the Battery Backup Unit of RAID Controller.",
    "bbu_infotype": "Type",
    "unknown": "Unknown",
    "supercap": "SuperCap",
    "bbu": "BBU",
    "tbbu": "TBBU",
    "ibbu": "iBBU",
    "itbbu": "iTBBU",
    "bbu_infostatus": "Status",
    "battery_backup_subsystem_is_missing": "Battery Backup subsystem is missing.",
    "battery_backup_subsystem_is_currently_initializing": "Battery Backup subsystem is currently initializing.",
    "battery_backup_subsystem_is_ready": "Battery Backup subsystem is ready.",
    "battery_backup_subsystem_is_executing_a_learning_cycle": "Battery Backup subsystem is executing a learning cycle.",
    "battery_backup_subsystem_has_failed": "Battery Backup subsystem has failed.",
    "super_capacitor_pack_has_exceeded_the_maximum_temperature_threshold": "Super capacitor pack has exceeded the maximum temperature threshold.",
    "super_capacitor_pack_has_exceeded_the_warning_temperature_threshold": "Super capacitor pack has exceeded the warning temperature threshold.",
    "super_capacitor_pack_is_over_voltage": "Super capacitor pack is over voltage.",
    "battery_backup_subsystem_has_exceeded_the_maximum_charging_current": "Battery Backup subsystem has exceeded the maximum charging current.",
    "battery_backup_subsystem_learning_cycle_has_passed": "Battery Backup subsystem learning cycle has passed.",
    "battery_backup_subsystem_learning_cycle_has_failed": "Battery Backup subsystem learning cycle has failed.",
    "bbu_infotemp_c": "Temp (C)",
    "na": "N\/A",
    "bbu_infovoltage_mv": "Voltage (mV)",
    "bbu_infocurrent_ma": "Current (mA)"
});
