define({
    "home": "Home",
    "system_maintenance": "System Maintenance",
    "title": "BMC Recovery",
    "bmc_recovery": "",
    "boot_retry_count_must_be_a_number_between_1_and_5": "Boot Retry Count must be a number between 1 and 5",
    "recovery_retry_count_must_be_a_number_between_1_and_5": "Recovery Retry Count must be a number between 1 and 5",
    "invalid_server_address_refer_help_for_more_information": "Invalid Server address. Refer 'Help' for more Information.",
    "strongSuccessMsg": "BMC Recovery has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving BMC Recovery.",
    "failureMsg": "",
    "bmc_recoveryforce_recovery": "Force Recovery",
    "bmc_recovery_choose_enabledisable_to_start_autorecovery_immediately_at_next_reboot": " Choose Enable\/Disable to start auto-recovery immediately at next reboot.",
    "bmc_recoveryboot_retry_count": "Boot Retry Count",
    "bmc_recovery_enter_the_number_of_retries_to_reset_the_bmc_and_this_count_ranges_from_1_to_5": " Enter the number of retries to reset the BMC and this count ranges from 1 to 5.",
    "bmc_recoveryrecovery_retry_count": "Recovery Retry Count",
    "bmc_recovery_enter_the_number_of_retries_to_recover_firmware_image_during_the_recovery_process_and_this_count_ranges_from_1_to_5": " Enter the number of retries to recover firmware image during the recovery process and This count ranges from 1 to 5.",
    "bmc_recoveryserver_address": "Server Address",
    "bmc_recoveryaddress_of_the_server_where_the_firmware_image_is_stored_ulli_ip_address_made_of_4_numbers_separated_by_dots_as_in_xxxxxxxxxxxxli_li_each_number_ranges_from_0_to_255li_li_first_number_must_not_be_0liul": "Address of the server where the firmware image is stored. <ul><li> IP Address made of 4 numbers separated by dots as in xxx.xxx.xxx.xxx.<\/li> <li> Each number ranges from 0 to 255.<\/li> <li> First number must not be 0.<\/li><\/ul>",
    "bmc_recoveryimage_name": "Image Name",
    "image_name_without_extension": "Image name without extension",
    "bmc_recoveryenter_the_image_name_to_edit_the_default_recovery_image_name_is_mentioned_as_romima_ulli_image_name_should_contain_only_5_alpha_numeric_charactersli_li_if_you_enter_new_imagename_enter_the_imagename_without_extensionimaliul": "Enter the Image Name to edit the default recovery image name is mentioned as rom.ima. <ul><li> Image name should contain only 5 Alpha numeric characters.<\/li> <li> If you enter new imagename, enter the imagename without extension(.ima).<\/li><\/ul>",
    "saveLabel": "Save"
});
