define({
    "parenttitle":"Remote Control",
    "cooling_policy" : "Cooling Policy",
    "tag" : "Change Cooling Policy",
    "home" : "Home",
    "cooling_policy_action" : "Cooling Policy",
    "load":"loading",
    "balance" : "Balance Mode",
    "manual":"Manual Mode",
    "performance" : "Performance Mode",
    "silent" : "Silent Mode",
    "duty":"Set fan duty for manual mode",
    "less_than_50":" <50,",
    "positive_integer_within_100":"Please enter a positive integer value within 100",
    "unknow":"UNKNOWN",
    "perform_action" : "Perform Action",
    "server_config" : "Server Configuration",
    "confirm" : "Are you sure to perform this operation?",
    "long_control" : "Long-range control",
    "help_selection":"Display current status and Configuration to select Cooling Policy mode.",
    "status":"Current Status:",
    "is_manual_duty": "Set minimum duty limitation for current mode.",
    "on": "Yes",
    "off": "No",
    "positive_integer_within_20_100":"Pleasse  enter a positive integer value within 20-100. ",

});
