define({
    "home": "Home",
    "maintenance": "System Maintenance",
    "title": "CPLD Firmware Upgrade",
    "info":"You'd better not perform any other tasks until CPLD upgrade is complete. Click Ok if you want to enter the update mode",
    "prepare":"Prepare to Flash...",
    "upload":"Uploading...",
    "flash":"Flashing...",
    "upload_fail":"CPLD Flash Firmware Upload Failed",
    "start_fw_update": "Start firmware update",
    "verifying":"Verifying...",
    "success":"CPLD Firmware update success!",
    "cancle":"Cancle",
    "cancle_info":"CPLD Update Canceled!",
    "fwimage": "Select Firmware Image",
    "pre_flash_error":"There was a problem while preparing device for CPLD upgrade.Please check and try later.",
    "chassis_power_is_on":"Server is power on, please close server first!",
    "strongSuccessMsg": "Saved!",
    "successMsg": "Saved Successfully",
    "strongFailureMsg": "",
    "failureMsg": "I'll try to reason out the error",
    "size512kb": "Max. size 512 KB",
    "reset": "firmware reset is called close the current session and open a new session after 2 minutes",
    "confirm1":"Clicking 'OK' will start the actual upgrade operation, where the storage is written with the new CPLD image. It is essential that the upgrade operation is not interrupted once it starts. Do you wish to proceed?",
    //"cont_update": "Flash selected sections",
    "cont_update": "Start Upgrade",
    "select_all": "Select All",
    "select_none": "Select None",
    "section_name": "Section Name",
    "cpld_flash_progress":"CPLD upgrade is in progress! Please try later!",
    "cpld_prepare_error":"There was a problem while preparing device for CPLD upgrade.",
    "cpld_verify_error":"CPLD image verification is unsuccessful. Please check if you uploaded the correct image. Press OK to exit the upgrade mode.",
    "image_information":"Firmware Version Information",
    "current_image_version":"Current Image Version:",
    "new_image_version":"New Image Version:",
    "diff_image_info":"CPLD Image has been verifid,New Image Version is different with Current Image Version",
    "same_image_info":"CPLD Image is same to Current Image Version",
    "different_image_info":"CPLD Image has been verifid,New Image Version is different to Current Image Version",
    "flash_error":"CPLD Flash Error,please check!",
    "update_section": "Update Section",
    "prepare_flash":"Preparing to flash...",
    "start_flash":"Starting flash...",
    "process":"Processing...",
    "upload":"Uploading ",
    "flashing":"Flashing...",
    "con_reset":"Resetting...",
    "protocol_type":"Protocol Type:",
    "server_address":"Server Address:",
    "image_name":"Image Name:",
    "retry_count":"Retry Count:",
    "fwimage_maintance_info":"The protocol information to be used for firmware image transfer during this update is as follows. To configure, choose \"Firmware Image Location\" under Maintenance.",
    "confirm_start_fw_upgrade":"We will start the firmware upgrade now. You'd better not operate server until it flashes over. Do you want to continue?",
    "notify_chose_fw_image_file":"Please choose the firmware file to upgrade",
    "alert_upload_fail":"CPLD Flash Firmware Upload Failed",
    "alert_flash_finish":"CPLD Firmware update success!",
    "selectFile":"Select File",
    "fw_FirmwareUpgrade": "Firmware Upgrade",
    "fw_BMCFirmwareUpgrade": "BMC Firmware Upgrade",
    "fw_BIOSFirmwareUpgrade": "BIOS Firmware Upgrade",
    "fw_CPLDUpgrade": "CPLD Upgrade",
    "fw_PSUUpgrade": "PSU Upgrade",
    "fw_BPUpgrade": "Backplane Upgrade",
});
