define({
    "home": "Home",
    "bmc_settings": "BMC Settings",
    "title": "Safe Settings",
    "generate_ssl": "",
    "invalid_common_name": "Invalid Common Name",
    "invalid_organization": "Invalid Organization",
    "invalid_organization_unit": "Invalid Organization Unit",
    "invalid_city_or_locality": "Invalid City or Locality",
    "invalid_state_or_province": "Invalid State or Province",
    "invalid_country": "Invalid Country",
    "invalid_email_address": "Invalid Email Address",
    "invalid_time_until_expiry": "Invalid Time Until Expiry",
    "strongSuccessMsg": "The HTTPS certificate has been updated and the page will automatically jump to the login page after 30 seconds. Please log in again to make the new certificate take effect!",
    "successMsg": "",
    "strongFailureMsg": "Error in updating the SSL Certificate.",
    "failureMsg": "",
    "generate_sslcommon_name_cn": "Common Name (CN)",
    "generate_sslcommon_name_for_which_the_certificate_is_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "Common name for which the certificate is to be generated. <ul><li> Maximum length of 64 characters.<\/li> <li> It is a string of alpha-numeric characters. <li> Special characters '#' and '$' are not allowed. <\/li><\/ul>",
    "generate_sslorganization_o": "Organization (O)",
    "generate_sslorganization_name_for_which_certificate_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "Organization name for which certificate to be generated. <ul><li> Maximum length of 64 characters.<\/li> <li> It is a string of alpha-numeric characters. <li> Special characters '#' and '$' are not allowed. <\/li><\/ul>",
    "generate_sslorganization_unit_ou": "Organization Unit (OU)",
    "generate_sslover_all_organization_section_unit_name_for_which_certificate_to_be_generated_ulli_maximum_length_of_64_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "Over all organization section unit name for which  certificate to be generated. <ul><li> Maximum length of 64 characters.<\/li> <li> It is a string of alpha-numeric characters. <li> Special characters '#' and '$' are not allowed. <\/li><\/ul>",
    "generate_sslcity_or_locality_l": "City or Locality (L)",
    "generate_sslcity_or_locality_has_to_be_givenulli_maximum_length_of_128_characterslili_it_is_a_string_of_alphanumeric_charactersli_special_characters_and_are_not_allowedliul": "City or Locality has to be given.<ul><li> Maximum length of 128 characters.<\/li><li> It is a string of alpha-numeric characters.<li> Special characters '#' and '$' are not allowed.<\/li><\/ul>",
    "generate_sslstate_or_province_st": "State or Province (ST)",
    "generate_sslstate_or_province_has_to_be_given_ulli_maximum_length_of_128_charactersli_li_it_is_a_string_of_alphanumeric_characters_li_special_characters_and_are_not_allowed_liul": "State or Province has to be given. <ul><li> Maximum length of 128 characters.<\/li> <li> It is a string of alpha-numeric characters. <li> Special characters '#' and '$' are not allowed. <\/li><\/ul>",
    "generate_sslcountry_c": "Country (C)",
    "generate_sslcountry_code_has_to_be_given_ulli_only_two_characters_are_allowedli_li_special_characters_are_not_allowedliul": "Country code has to be given. <ul><li> Only two characters are allowed.<\/li> <li> Special characters are not allowed.<\/li><\/ul>",
    "generate_sslemail_address": "Email Address",
    "generate_sslemail_address_of_the_organization_has_to_be_given": "Email Address of the organization has to be given.",
    "generate_sslvalid_for": "Valid for",
    "in_days": "in days",
    "generate_sslnumber_of_days_the_certificate_to_be_validated_ulli_value_ranges_from_1_to_3650_daysliul": "Number of days the certificate to be validated. <ul><li> Value ranges from 1 to 3650 days.<\/li><\/ul>",
    "generate_sslkey_length": "Key Length",
    "generate_sslstr_2048_bits": "2048 bits",
    "generate_sslchoose_the_key_length_bit_value_of_the_certificate": "Choose the key length bit value of the certificate.",
    "saveLabel": "Save",
    "view_ssl_certificate": "View SSL certificate",
    "generate_ssl_certificate": "Generate SSL certificate",
    "upload_ssl_certificate": "Upload SSL certificate",
    "loginControl": "Login Control",
    "snmpv": "SNMP V1/V2 Settings",
    "ssl_settings": "SSL Settings",
    "user_badpassword": "User Password Lock",
    "generate_ssl_tip": "SSL certificate is being generated, please wait.",
    "confirm_start_generate": "we will start the SSL certificate generation now. You'd better not operate the server until it generates over. Do you want to continue?",
});
