define({
    "home": "Home",
    "settings": "BMC Settings",
    "external_user_settings": "External User Settings",
    "active_directory_settings": "Active directory Settings",
    "title": "General Active Directory Settings",
    "general_active_directory": "",
    "invalid_user_name_refer_help_for_more_information": "Invalid user name. Refer 'Help' for more Information.",
    "invalid_password_refer_help_for_more_information": "Invalid password. Refer 'Help' for more Information.",
    "invalid_user_domain_name_refer_help_for_more_information": "Invalid User Domain Name. Refer help for more information.",
    "invalid_domain_controller_server_address_1refer_help_for_more_information": "Invalid Domain Controller Server Address 1.Refer Help for more information.",
    "invalid_domain_controller_server_address_2refer_help_for_more_information": "Invalid Domain Controller Server Address 2.Refer Help for more information.",
    "invalid_domain_controller_server_address_3refer_help_for_more_information": "Invalid Domain Controller Server Address 3.Refer Help for more information.",
    "strongSuccessMsg": "General Active Directory Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving General Active Directory Settings.",
    "failureMsg": "",
    "general_active_directoryenable_active_directory_authentication": "Enable Active directory Authentication",
    "general_active_directoryselect_check_box_to_enable_active_directory_authentication": "Select check box to enable Active Directory Authentication",
    "general_active_directorysecret_username": "Secret Username",
    "general_active_directoryspecify_the_username_of_the_active_directory_server_ulli_user_name_is_a_string_of_1_to_64_alphanumeric_characterslili_it_must_start_with_an_alphabetical_characterlili_it_is_casesensitivelili_special_characters_and_space_are_not_allowedliulstrongnotestrong_if_secret_username_and_password_are_not_needed_both_can_stay_empty_": "Specify the Username of the Active Directory Server. <ul><li> User Name is a string of 1 to 64 alpha-numeric characters.<\/li><li> It must start with an alphabetical character.<\/li><li> It is case-sensitive.<\/li><li> Special characters and space are not allowed,Ex:comma,conclude,colon,semicolon,slash,backslash,braces,brackets,pipe,equate,plus,minus,asterisk,question mark,& sign,Blank space,Quotation marks.<\/li><\/ul><strong>NOTE:<\/strong> If Secret Username and Password are not needed, both can stay empty. ",
    "general_active_directorysecret_password": "Secret Password",
    "general_active_directoryspecify_the_password_of_the_active_directory_serverulli_password_must_be_at_least_6_character_longlili_white_space_is_not_allowedliulstrongnotestrong_this_field_will_not_allow_more_than_127_characters": "Specify the Password of the Active Directory Server.<ul><li> Password must be at least 6 character long.<\/li><li> White space is not allowed.<\/li><\/ul><strong>NOTE:<\/strong> This field will not allow more than 127 characters.",
    "general_active_directoryuser_domain_name": "User Domain Name",
    "general_active_directoryspecify_the_domain_name_for_the_usereg_mydomaincom": "Specify the Domain Name for the user.e.g. MyDomain.com",
    "general_active_directorydomain_controller_server_address_1": "Domain Controller Server Address 1",
    "general_active_directoryenter_the_ip_address_of_active_directory_server_at_least_one_domain_controller_server_address_must_be_configured_domain_controller_server_address_supports_the_following_formatulliipv4_address_formatlili_ipv6_address_formatliul": "Enter the IP address of Active Directory server. At least one Domain Controller Server Address must be configured. Domain Controller Server Address supports the following format:<ul><li>IPv4 Address format.<\/li><li> IPv6 Address format.<\/li><\/ul>",
    "general_active_directorydomain_controller_server_address_2": "Domain Controller Server Address 2",
    "general_active_directorydomain_controller_server_address_3": "Domain Controller Server Address 3",
    "saveLabel": "Save",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",
});
