define({
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "general_firewall_settings": "General Firewall Settings",
    "title": "Add Firewall Settings",
    "general_firewall": "",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set": "End time required when timeout is set",
    "strongSuccessMsg": "Firewall Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Firewall Settings.",
    "failureMsg": "",
    "general_firewallblock_all": "Block All",
    "general_firewallipv4": "IPv4",
    "general_firewallipv6": "IPv6",
    "general_firewallboth": "Both",
    "general_firewallthis_option_will_block_all_incoming_ips_and_ports": "This option will block all incoming IPs and Ports.",
    "general_firewallflush_all": "Flush All",
    "general_firewallthis_is_used_to_flush_all_the_system_firewall_rules": "This is used to flush all the system firewall rules.",
    "general_firewalltimeout": "Timeout",
    "general_firewallthis_option_is_used_to_enable_or_disable_firewall_rules_with_timeout": "This option is used to enable or disable firewall rules with timeout.",
    "general_firewallstart_date": "Start Date",
    "general_firewallthe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "general_firewallstart_time": "Start Time",
    "general_firewallthe_respective_firewall_rule_effect_will_start_from_this_time": "The respective firewall rule effect will start from this time.",
    "general_firewallend_date": "End Date",
    "general_firewallthe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "general_firewallend_time": "End Time",
    "general_firewallthe_respective_firewall_rule_effect_will_end_from_this_time": "The respective firewall rule effect will end from this time.",
    "saveLabel": "Save"
});
