define({
    "home": "Home",
    "bmc_settings": "BMC Settings",
    "external_user_settings": "External User Settings",
    "ldapedirectory_settings": "LDAP\/E-directory Settings",
    "title": "General LDAP Settings",
    "general_ldap": "",
    "invalid_server_address_refer_help_for_more_information": "Invalid Server Address. Refer 'Help' for more Information.",
    "invalid_port_refer_help_for_more_information": "Invalid port. Refer 'Help' for more Information.",
    "invalid_bind_dn_refer_help_for_more_information": "Invalid Bind DN. Refer 'Help' for more Information.",
    "invalid_password_refer_help_for_more_information": "Invalid Password. Refer 'Help' for more Information.",
    "invalid_search_base_refer_help_for_more_information": "Invalid Search Base. Refer 'Help' for more Information.",
    "strongSuccessMsg": "General LDAP Settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving General LDAP Settings.",
    "failureMsg": "",
    "general_ldapenable_ldapedirectory_authentication": "Enable LDAP\/E-directory Authentication",
    "general_ldapcheck_the_box_below_to_enable_ldapedirectory_authentication": "Check the box below to enable LDAP\/E-Directory authentication.",
    "general_ldapencryption_type": "Encryption Type",
    "general_ldapno_encryption": "No Encryption",
    "general_ldapssl": "SSL",
    "general_ldapstarttls": "StartTLS",
    "general_ldapselect_the_encryption_type_for_ldapedirectory_brstrongnotestrongconfigure_proper_port_number_when_ssl_is_enabled": "Select the Encryption Type for LDAP\/E-Directory.  <br><strong>NOTE:<\/strong>Configure proper port number, when SSL is enabled.",
    "general_ldapcommon_name_type": "Common Name Type",
    "general_ldapip_address": "IP Address",
    "general_ldapfqdn": "FQDN",
    "general_ldapserver_address": "Server Address",
    "general_ldapldapedirectory_server_address_will_support_the_following_ulliipv4_address_formatli_liipv6_address_formatliul_strongnotestrong_configure_fqdn_address_when_using_starttls_with_fqdn": "LDAP\/E-Directory Server Address will support the following: <ul><li>IPv4 Address format.<\/li> <li>IPv6 Address format.<\/li><\/ul> <strong>NOTE:<\/strong> Configure FQDN address, when  using StartTLS with FQDN.",
    "general_ldapport": "Port",
    "general_ldapspecify_the_ldapedirectory_port_ulli_default_port_is_389li_li_for_ssl_connections_default_port_is_636li_li_port_value_ranges_from_1_to_65535liul": "Specify the LDAP\/E-Directory Port. <ul><li> Default Port is 389.<\/li> <li> For SSL connections, default port is 636.<\/li> <li> Port value ranges from 1 to 65535.<\/li><\/ul>",
    "general_ldapbind_dn": "Bind DN",
    "eg_cnadminoulogindcdomaindccom": "E.g., cn=admin,ou=login,dc=domain,dc=com",
    "general_ldapthe_bind_dn_is_used_in_bind_operation_which_authenticates_the_client_to_the_server_ul_li_bind_dn_is_a_string_of_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetli_li_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_cnmanageroulogin_dcdomaindccomli_ul": "The Bind DN is used in bind operation, which authenticates the client to the server. <ul> <li> Bind DN is a string of 4 to 64 alpha-numeric  characters.<\/li> <li> It must start with an Alphabet.<\/li> <li> Special Symbols like dot(.), comma(,), hyphen(-),  underscore(_), equal-to(=) are allowed.<\/li> <li> Example: cn=manager,ou=login, dc=domain,dc=com<\/li> <\/ul>",
    "general_ldappassword": "Password",
    "whitespace_not_allowed": "Whitespace not allowed",
    "general_ldapthe_bind_password_is_used_in_bind_operation_which_authenticates_the_client_to_the_server_ulli_password_must_be_at_least_1_character_longli_li_white_space_is_not_allowedliul_strongnotestrong_this_field_will_not_allow_more_than_20_characters": "The Bind password is used in bind operation, which  authenticates the client to the server. <ul><li> Password must be at least 1 character long.<\/li> <li> White space is not allowed.<\/li><\/ul> <strong>NOTE:<\/strong> This field will not allow more than  20 characters.",
    "general_ldapsearch_base": "Search Base",
    "eg_oulogindcdomaindccom": "E.g., ou=login,dc=domain,dc=com",
    "general_ldapthe_search_base_allows_the_ldapedirectory_server_to_find_which_part_of_the_external_directory_tree_to_be_searched_the_search_base_may_be_something_equivalent_to_the_organization_group_of_external_directoryul_li_searchbase_is_a_string_of_4_to_64_alphanumeric_charactersli_li_it_must_start_with_an_alphabetical_characterli_li_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_oulogindcdomaindccomli_ul": "The Search base allows the LDAP\/E-Directory server to find which part of the external directory tree  to be searched. The search base may be something equivalent to the organization, group of external directory.<ul> <li> Searchbase is a string of 4 to 64 alpha-numeric  characters.<\/li> <li> It must start with an alphabetical character.<\/li> <li> Special Symbols like dot(.), comma(,), hyphen(-),  underscore(_), equal-to(=) are allowed.<\/li> <li> Example: ou=login,dc=domain,dc=com<\/li> <\/ul>",
    "general_ldapattribute_of_user_login": "Attribute of User Login",
    "general_ldapcn": "cn",
    "general_ldapuid": "uid",
    "general_ldapthe_attribute_of_user_login_field_allows_the_ldapedirectory_server_to_find_which_attribute_should_be_used_to_identify_the_user_ul_li_only_support_cn_or_uidli_ul": "The Attribute of User Login field allows the LDAP\/E-Directory server to find which attribute should be used to identify the user.  <ul> <li> Only support cn or uid<\/li> <\/ul>",
    "general_ldapca_certificate_file": "CA certificate file",
    "general_ldapfile_that_contains_the_certificate_of_the_trusted_ca_certsulli_ca_certificate_file_should_be_of_the_type_pem_liul": "File that contains the certificate of the trusted CA certs.<ul><li> CA certificate file should be of the type pem <\/li><\/ul>",
    "general_ldapcertificate_file": "Certificate File",
    "general_ldapclient_certificate_filenameulli_certificate_file_should_be_of_the_type_pem_liul": "Client certificate filename.<ul><li> Certificate File should be of the type pem <\/li><\/ul>",
    "general_ldapprivate_key": "Private Key",
    "general_ldapclient_private_key_filenameulli_private_key_should_be_of_the_type_pem_liul_brstrongnotestrong_all_of_the_3_files_are_required_when_starttls_enabled": "Client private key filename.<ul><li> Private Key should be of the type pem <\/li><\/ul> <br><strong>NOTE:<\/strong> All of the 3 files are required when StartTLS enabled.",

    "general_ldapclient_upload_a_valid_CA_certificate_file": "Please upload a valid CA certificate file.",
    "general_ldapclient_upload_a_valid_Certificate_file": "Please upload a valid Certificate File.",
    "general_ldapclient_upload_a_valid_Private_Key": "Please upload a valid Private Key.",
    "general_ldapclient_upload_a_file": "Please choose a file to upload.",

    "saveLabel": "Save",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",
});
