define({
		"tittle":"Historical Records",
	   "tag" : "Show and Download History Curve ",
	   "home" : "Home",
	   "power_consumption" : "Power Consumption Curve",
	   "inlet_history" : "Inlet Temperature Curve",
	   "filter_bydate":"Filter by Date",
	   "start_date":"Start Date",
	   "end_date":"End Date",
	   "common_setting":"Common Setting",
	   "one_day":"One Day",
	   "one_week":"One Week",
	   "two_week":"Two Week",
	   "one_month":"One Month",
	   "three_month":"Three Month",
	   "half_year":"Half Year",
	   "one_year":"One Year",
	   "custom":"Custom",
	   "check":"Search",
	   "systeminfo":"System Information",
	   "inquery_type":"Inquery Type",
	   "wrongdate":"Get illegal start or end date,please check!",
		"download": "download",
		"strongSuccessMsg": "Saving and downloading, please be patient......",
		"strongFailureMsg": "Error in downloading,please try again later.",
    "help_information":"Please Click \"Download\" button,the historical records will be downloaded automatically,please be patient.",
    "csvFormat": "CSV Format",
    "xmlFormat": "XML Format",
    "history_download_title": "Historical Records Download",
    "history_search_title": "Historical Records Search",
    "download_tip1": "Recording frequency: 1 hour",
    "download_tip2": "Recording content: Inlet Temperature, Processor, Memory Temperature",
});
