define({
	"parenttitle":"Remote Control",
   "server_locate" : "Server Locate",
   "tag" : "Turn On/Off ID LED",
   "home" : "Home",
   "idled_actions" : "Server Locate",
   "force_on" : "Force On",
   "force_off" : "Force Off",
   "identify":"Identify Blink Time",
   "blink_time" : "Blink Time",
   "perform_action" : "Perform Action",
   "server_config" : "Server Configuration",
   "confirm" : "Are you sure to perform this operation?",
   "long_control" : "Long-range control",
   "id_led_status" : "Current Status",
   "offStatus" : "Unlocated",
   "onStatus" : "Located",
   "blinkStatus" : "Blink",
   "seconds":"seconds",
   "hours":"hours",
   "days":"days",
   "help_selection":"Display current status and Configuration option to turn on/off ID LED.",
   "interval_value_tip":"Please enter a positive integer.",
   "saveSucess" : "Successful operation.",

});
