define({
    "ip_rulesthis_page_displays_list_of_existing_ip_firewall_rulesbrclick_i_classion_ionclosecircledi_icon_to_delete_an_item_from_the_listbrto_view_the_page_user_must_at_least_be_an_operator_to_add_or_delete_a_firewall_user_must_be_an_administrator": "This page displays list of existing ip firewall rules.<br>Click <i class='ion ion-close-circled'><\/i> icon to delete an item from the list.<br>To view the page, user must at least be an Operator. To add or delete a firewall, user must be an Administrator.",
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "ip_oriented_firewall_rules": "IP Oriented Firewall Rules",
    "title": "Existing IP Rules",
    "ip_range_": "IP Range: ",
    "_": " - ",
    "rule_": "Rule: ",
    "allow": "Allow",
    "block": "Block",
    "timeout_": "Timeout: ",
    "disabled": "Disabled",
    "enabled": "Enabled",
    "from_": "From: ",
    "to_": "To: ",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set": "End time required when timeout is set",
    "ip_rules": "",
    "strongSuccessMsg": "Existing IP Rules has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in getting Existing IP Rules.",
    "failureMsg": "",
    "ip_rulesip_single_or_range_start": "IP Single (or) Range Start",
    "ip_rulesthis_field_is_used_to_show_the_configured_port_address_or_range_of_ports": "This field is used to show the configured Port Address or Range of Ports.",
    "ip_rulesip_range_end": "IP Range End",
    "ip_rulesenable_timeout": "Enable Timeout",
    "ip_rulesstart_datetime": "Start Date&Time",
    "ip_rulesthe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "ip_rulesend_datetime": "End Date&Time",
    "ip_rulesthe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "ip_rulesrule": "Rule",
    "ip_rulesthis_column_indicates_the_current_setting_of_the_listed_port_or_range_of_port_rules_allow_or_block": "This column indicates the current setting of the listed Port or Range of Port rules (Allow or Block).",
    "deleteConfirmLabel": "Click OK if you want to continue deleting this record.",
    "deleteLabel": "Delete",
    "existing_ip_rules": "Existing IP Rules"
});
