define({
    "home": "Home",
    "settings": "BMC Settings",
    "network": "Network",
    "title": "Network Link Configuration",
    "link": "",
    "strongSuccessMsg": "Network Link Configuration has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Network Link Configuration.",
    "failureMsg": "",
    "linklan_interface": "LAN Interface",
    "link_select_the_network_interface_from_the_list_for_which_the_link_speed_and_duplex_mode_are_to_be_configured": " Select the network interface from the list for which the Link speed and duplex mode are to be configured.",
    "linkauto_negotiation": "Auto Negotiation",
    "linkthis_option_is_enabled_to_allow_the_device_to_perform_automatic_configuration_to_achieve_the_best_possible_mode_of_operation_speed_and_duplex_over_a_link": "This option is enabled to allow the device to perform automatic configuration to achieve the best possible mode of operation (speed and duplex) over a link.",
    "linklink_speed": "Link Speed",
    "_mbps": " Mbps",
    "link_link_speed_will_list_all_the_supported_capabilities_of_the_network_interface_it_can_be_101001000_mbps_strongnotestrong_link_speed_of_1000_mbps_is_not_applicable_when_auto_negotiation_is_off": " Link speed will list all the supported capabilities of the network interface. It can be 10\/100\/1000 Mbps. <strong>Note:<\/strong> Link speed of 1000 Mbps is not applicable, when Auto Negotiation is OFF.",
    "linkstr_100mbps": "100Mbps",
    "linkstr_10mbps": "10Mbps",
    "linkduplex_mode": "Duplex Mode",
    "_duplex": " Duplex",
    "linkselect_any_one_of_the_following_duplex_modes_ul_li_half_duplexli_li_full_duplexli_ul": "Select any one of the following Duplex Modes. <ul> <li> Half Duplex<\/li> <li> Full Duplex<\/li> <\/ul>",
    "linkfull_duplex": "Full duplex",
    "linkhalf_duplex": "Half duplex",
    "saveLabel": "Save"
});
