define({
    "home": "Home",
    "remote_control": "Remote Control",
    "image_redirection": "Image Redirection",
    
    //ks_lz20181024_vmmedia ++>>
    "title": "Media Redirection Settings",
    "settings": "BMC Settings",
    "tag": "",
    "remote_images": "Remote Media",
    "local_images" : "Local Media",
    "general_setting":"Function settings",
    //ks_lz20181024_vmmedia ++<<
    
    //"title": "Local Media",
    //"tag": "Emulate CD\/DVD\/Floppy\/HDD images within the BMC to host as media",
    "tag_start": "Emulate ",
    "tag_cd_dvd": "CD\/DVD\/",
    "tag_fd": "Floppy\/",
    "tag_hd": "HDD",
    "tag_end": " images within the BMC to host as media",
    "media_type": "Media Type",
    "cddvd": "CD\/DVD",
    "floppy": "Floppy",
    "hard_disk": "Hard disk",
    "media_instance": "Media Instance",
    "image_name": "Image Name",
    "status": "Redirection Status",
    "halted": "Stopped",
    "started": "Started",
    "status_0": "~",
    "status_1": " - Connection Accepted",
    "status_2": " - Connection Denied",
    "status_3": " - Login Failed",
    //"status_4": " - Connection in Use",
    "status_4": " - MAX Session Reached",
    "status_5": " - Permission Denied",
    "status_6": " - Unknown Error",
    "status_7": " - Media Detach Stage",
    "status_8": " - Maximum User Reached",
    "status_9": " - Unable to Connect",
    "status_10": " - Invalid Image",
    "status_11": " - Mount Error",
    "status_12": " - Unable to Open",
    "status_13": " - Media License Expired",
    "status_14": " - Connection Lost",
    "status_15": " - Mount Cancelled By User",
    "status_16": " - Device Ejected",
    "status_17": " - Session Terminated",
    "session_index": "Connected Server Session",
    "start_redirection": "Click here to Start Redirection",
    "stop_redirection": "Click here to Stop Redirection",
    "delete_image": "Click here to Delete the Image",
});
