define({
    "parenttitle": "Remote Control",
    "title": "ME Power Policy",
    "tag": "Configure ME Power Policy Settings",
    "home": "Home",
    "domain": "Domain",
    "load": "loading",
    "status": "Status",
    "policy": "Policy",
    "current_power": "Current Power(Watts)",
    "min_power": "Minimum Power(Watts)",
    "max_power": "Maximum Power(Watts)",
    "unknow_status": "ME Power Status is unknown",
    "policy_id": "Policy ID",
    "policy_item": "Policy Item",
    "whether_enable": "Whether Enable",
    "on": "ON",
    "off": "OFF",
    "limiting_value": "Limiting Value (Watt)",
    "operation": "Operation",
    "modify": "Modify",
    "entire_limit": "Entire Platform Power Limit",
    "cpu_limit": "CPU Power Limit",
    "mem_limit": "Memory Power Limit",
    "policy_max": "Policy Max Value",
    "recommend_min_val": "Policy Min Value",
    "recommend_undefined_val": "Unknown",
    "na": "N/A",
    "saveLabel": "Save",
    "cancel": "Cancel",
    "save_success": "Save success!",
    "save_failed": "Operation failed, try again later.",
    "entire_platform": "Entire Platform",
    "unknown_policy": "ME Power Policy is unknown",
    "cpu": "CPU",
    "memory": "Memory",
    "long_control": "Long-range control",
    "confirm": "Are you sure to perform this operation?",
    "server_con": "Server Configure",
    "me_power_policy": "ME Power Policy",
    "me_pow_edit": "ME Power Policy Setting",
    "policy_id_help": "<b>Policy ID</b> <br>Displays policy id of the selected policy.",
    "me_pow_edit_id": "Policy ID",
    "me_pow_edit_entire": "Entire Platform",
    "me_pow_edit_cpu": "CPU",
    "me_pow_edit_mem": "MEM",
    "policy_status_help": "<b>Current State</b> <br>Displays the current status of the policy, either enable or disable. <br>Check this box to start the disable service.",
    "policy_enable": "Enable    ",
    "policy_domain_help": "<b>Ploicy Domain</b><br>It shows the domain on which policy is running. User can choose any one of the available domain.",
    "policy_domain": "Domain",
    "policy_max_help": "<b>Policy Max Value</b><br>Use this to set the max value of this policy.",
    "policy_max": "Policy Max Value",
    "me_power_res_error": "reserved policy error!",
    "me_power_send_error": "Policy setting error!",
    "me_power_empty_policy": "Are you sure to save this empty policy?",
    "me_power_wrong_value": "Wrong value!",
    "note": "NOTE: Policy ",
    "tosave": " is going to save.",
    "positive_integer": "Please enter a positive integer",
    "recommend_min_val_help": "The minimum value of policy is the minimum recommended value to achieve power consumption, and setting a lower top value may result in failure.",
    "policy_setting_error": "Error setting me power policy",
    "policy_value_too_small": "Setting value should not be less than the minimum",

    "power_energy": "power and energy",
    "pe_power_control": "Power Control",
    "pe_power_hot_standby": "Power hot standby",
    "pe_me_power_policy": "ME Power Policy",
    "pe_power_restore_control": "Power Restore Control",
    // ks_lz_20170711  power button lock ++>>
    "pe_power_button_lock": "Power button lock",
    // ks_lz_20170711  power button lock ++>>
    "exception_status": "Get data exception, please try again",

});