define({
	"title": "System Overview",
	"home": "Home",
	//服务器信息
    "serverInfo": "Server Info",
    "productType" : "Product Type",
    "productName": "Product Name",
    "guid": "GUID",
    "uptime": "Uptime",
    "power": "Power",
    //固件版本信息
    "fwInfo": "FW Info",
    "biosVersion": "BIOS Version",
    "meVersion": "ME Version",
    "bmcVersion": "BMC Version",
    "psuVersion": "PSU Version",
    "cpldVersion": "CPLD Version",
    //网络信息
    "lanShared": "Shared LAN ",
    "lanDeicated": "Dedicated LAN ",
    "lanBond": "Network ",
    "lanSwitchTo": "Show",
    "lineType": "LAN Type",
    "macAddress": "MAC Address",
    "ipAddress": "IPv4 Address",
    "ipSource": "IPv4 Source",
    "webOnline": "Web Online",
    //服务器运行状态
    "hoston": "Host On",
    "hostoff": "Host Off",
    //sugon_caichb_tapd1011466 ++>>
    "powersts": "Power Status",
    "id_led_blink":"Blink",
    "id_led_off":"Unlocated",
    "id_led_on":"Located",
    "uid_led":"UID LED Status",
    //sugon_caichb_tapd1011466 ++<<
    "serverState": "Server State",
    "cpuState": "CPU",
    "memState": "Memory",
    "hddState": "HDD",
    "psuState": "PSU",
    "fanState": "FAN",
    //常用操作
    "commonOperations": "Common Operations",
    "powerControl": "Power Control",
    "remoteControl": "Console Redirection",
    "userSettings": "User Management",
    "networkSettings": "Network Settings",
    "firmwareUpdate": "BMC FW Update",
    "dateOrTime": "Date&Time",
    //告警信息
    "alarmInfo": "Alarm Info",
    "alarmDetails": "Details",
    "alarmNoData": "No Alarm",
    "loading": "Loading",
    "Info": "Info",
    "NonCritical": "Non Critical",
    "Critical": "Critical",
    "Urgency": "Urgency",
    //CPU使用率
    "cpuUsageRate": "CPU Usage Rate",
    "notBoot": "Not Boot",
    //内存使用率
    "memUsageRate": "MEM Usage Rate",
    //服务器错误等级
    "levelUrgency":"Urgency",
    "levelCritical":"Critical",
    "levelNonCritical":"Non Critical",
    "levelNormal":"Normal",
    "healthsts":"Health Status",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "IPv4_info": "IPv4 Info",
    "IPv6_info": "IPv6 Info",
    "ipv6Address": "IPv6 Address",
    "ipv6Source": "IPv6 Source",
});
