define({
    "port_rulesthis_page_displays_list_of_existing_port_firewall_rulesbrclick_i_classion_ionclosecircledi_icon_to_delete_an_item_from_the_listbrto_view_the_page_user_must_at_least_be_an_operator_to_add_or_delete_a_firewall_user_must_be_an_administratorbrstrongnote_strong_port_80_is_blocked_for_tcpudp_protocols": "This page displays list of existing port firewall rules.<br>Click <i class='ion ion-close-circled'><\/i> icon to delete an item from the list.<br>To view the page, user must at least be an Operator. To add or delete a firewall, user must be an Administrator.<br><strong>NOTE: <\/strong> Port 80 is blocked for TCP\/UDP protocols.",
    "home": "Home",
    "settings": "BMC Settings",
    "firewall": "Firewall",
    "port_oriented_firewall_rules": "Port Oriented Firewall Rules",
    "title": "Existing Port Rules",
    "port_range_": "Port Range: ",
    "_": " - ",
    "protocol_": "Protocol: ",
    "tcp": "TCP",
    "udp": "UDP",
    "both": "Both",
    "network_type_": "Network Type: ",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "allow": "Allow",
    "block": "Block",
    "timeout_": "Timeout: ",
    "disabled": "Disabled",
    "enabled": "Enabled",
    "from_": "From: ",
    "to_": "To: ",
    "start_time_required_when_timeout_is_set": "Start time required when timeout is set",
    "end_time_required_when_timeout_is_set": "End time required when timeout is set",
    "port_rules": "",
    "strongSuccessMsg": "Port Rule has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in getting Port Rules.",
    "failureMsg": "",
    "port_rulesport_single_or_range_start": "Port Single (or) Range Start",
    "port_rulesport_range_end": "Port Range End",
    "port_rulesprotocol": "Protocol",
    "port_rulesnetwork_type": "Network Type",
    "port_rulesenable_timeout": "Enable Timeout",
    "port_rulesthis_option_is_used_to_enable_or_disable_firewall_rules_with_timeout": "This option is used to enable or disable firewall rules with timeout.",
    "port_rulesstart_datetime": "Start Date&Time",
    "port_rulesthe_respective_firewall_rule_effect_will_start_from_this_date": "The respective firewall rule effect will start from this date.",
    "port_rulesend_datetime": "End Date&Time",
    "port_rulesthe_respective_firewall_rule_effect_will_end_from_this_date": "The respective firewall rule effect will end from this date.",
    "port_rulesrule": "Rule",
    "deleteConfirmLabel": "Click OK if you want to continue deleting this record.",
    "deleteLabel": "Delete",
    "existing_port_rules": "Existing Port Rules"
});
