define({
    "home": "Home",
    "maintenance": "System Maintenance",
    "title": "PSU Firmware Update",
    "info":"You'd better not perform any other tasks until PSU upgrade is complete. Click Ok if you want to enter the update mode",
    "prepare":"Prepare to Flash...",
    "upload":"Uploading...",
    "flash":"Flashing...",
    "upload_fail":"PSU Flash Firmware Upload Failed",
    "start_fw_update": "Start firmware update",
    "verifying":"Verifying...",
    "success":"PSU Firmware update success!",
    "cancle":"Cancle",
    "cancle_info":"PSU Update Canceled!",
    "fwimage": "Select Firmware Image",
    "pre_flash_error":"There was a problem while preparing device for PSU upgrade.Please check and try later.",
    "chassis_power_is_on":"Server is power on, please close server first!",
    "strongSuccessMsg": "Saved!",
    "successMsg": "Saved Successfully",
    "strongFailureMsg": "",
    "failureMsg": "I'll try to reason out the error",
    "size512kb": "Max. size 512 KB",
    "reset": "firmware reset is called close the current session and open a new session after 2 minutes",
    "confirm1":"Clicking 'OK' will start the actual upgrade operation, where the storage is written with the new PSU image. It is essential that the upgrade operation is not interrupted once it starts. Do you wish to proceed?",
    //"cont_update": "Flash selected sections",
    "cont_update": "Start Upgrade",
    "select_all": "Select All",
    "select_none": "Select None",
    "section_name": "Section Name",
    "PSU_flash_progress":"PSU upgrade is in progress! Please try later!",
    "PSU_prepare_error":"There was a problem while preparing device for PSU upgrade.",
    "PSU_verify_error":"PSU image verification is unsuccessful. Please check if you uploaded the correct image. Press OK to exit the upgrade mode.",
    "image_information":"Firmware Version Information",
    "current_image_version":"Current Image Version:",
    "new_image_version":"New Image Version:",
    "diff_image_info":"PSU Image has been verifid,New Image Version is different with Current Image Version",
    "same_image_info":"PSU Image is same to Current Image Version",
    "different_image_info":"PSU Image has been verifid,New Image Version is different to Current Image Version",
    "flash_error":"PSU Flash Error,please check!",
    "update_section": "Update Section",
    "prepare_flash":"Preparing to flash...",
    "start_flash":"Starting flash...",
    "process":"Processing...",
    "upload":"Uploading ",
    "uploading":"Uploading...",
    "flashing":"Flashing...",
    "con_reset":"Resetting...",
    "protocol_type":"Protocol Type:",
    "server_address":"Server Address:",
    "image_name":"Image Name:",
    "retry_count":"Retry Count:",
    "fwimage_maintance_info":"The protocol information to be used for firmware image transfer during this update is as follows. To configure, choose \"Firmware Image Location\" under PSU Firmware Update.Please wait for the PSU device information to be loaded correctly on the current page, and then select the  device number before performing the upgrade.",
    "PsuNote":"Note: In order to ensure the security of the upgrade PSU firmware upgrade operation, we limit the operation to the power backup policy in the master-slave mode, and the PSU firmware is allowed to be updated if the power supply is not the Main Power.",
    "confirm_start_fw_upgrade":"We will start the firmware upgrade now. You'd better not operate server until it flashes over. Do you want to continue?",
    "notify_chose_fw_image_file":"Please choose the firmware file to upgrade",
    "alert_upload_fail":"PSU Flash Firmware Upload Failed",
    "alert_flash_finish":"PSU Firmware update success!",
    "selectFile":"Select File",
    "psuIndex":"Select PSU index",
    "getPsuInfo":"Get device information, please wait..",
    "psuPowerOn_1":"The current number of PSU devices is 1. In this case, when you upgrade the PSU firmware, make sure that the server is powered off.",
    "psuStatusNotReady":"Please wait for the PSU device information to be loaded correctly on the current page, and then select the  device number before performing the upgrade.",
    "psu_power_status_abnormal":"Abnormal power supply status.",
    "psu_fw_init":"PSU firmware is initializing, please wait ",
    "fw_FirmwareUpgrade": "Firmware Upgrade",
    "fw_BMCFirmwareUpgrade": "BMC Firmware Upgrade",
    "fw_BIOSFirmwareUpgrade": "BIOS Firmware Upgrade",
    "fw_CPLDUpgrade": "CPLD Upgrade",
    "fw_PSUUpgrade": "PSU Upgrade",
    "fw_BPUpgrade": "Backplane Upgrade",
    "PSU_checksume": "PSU firmware checking...",
    "Unknown_error":"An unknown error occurred during the refresh process. Please check the power supply or firmware validity and refresh.",
    //ks_lz_20180724 psu ++>>
    "error_code_1308": "The PSU firmware update failed. Please check the power supply or firmware validity and refresh it.",
    "error_code_1488": "The PSU failed to enter the refresh mode. Please check the power supply or firmware validity and refresh it.",
    "error_code_1489": "PSU failed to work mode. Please check the power supply or firmware validity and refresh it.",
    "error_code_1490": "Write PSU image verification failed.Please check the power supply or firmware validity and refresh it.",
    "mode_error1":"The current power mode is load balancing mode, in which the PSU firmware is not allowed to be updated. Please set the power backup policy selection to the Main/Standby Power , and the power to be updated cannot be set as the main power",
    "mode_error2":"The power supply to be updated cannot be the main power supply. Please reset the firmware before updating.",
    "mode_error_default":"The power status is abnormal. Please check and try again!"
    //ks_lz_20180724 psu ++>>

});
