define({
    "system_maintenance": "System Maintenance",
    "title": "Restore Factory Defaults",
    "restore_configuration": "",
    "strongSuccessMsg": "Success! Device has been reset. Please close this browser session and open a new browser session to reconnect to the device.",
    "successMsg": "---Logout",
    "strongFailureMsg": "Error in Restore Factory Defaults.",
    "failureMsg": "",
    "restore_configurationfollowing_checked_configuration_will_be_preserved_you_can_make_changes_to_them_in_a_hrefmaintenancepreserve_configurationpreserve_configurationa_page": "Following checked configuration will be preserved. You can make changes to them in <a href='#maintenance\/firmware_update'>preserve configuration<\/a> page.",
    "restore_configurationto_preserve_any_existing_configuration_data_goto_a_hrefmaintenancepreserve_configurationpreserve_configurationa_page_and_select_them": "To preserve any existing configuration data, goto <a href='#maintenance\/firmware_update'>preserve configuration<\/a> page and select them",
    "restore_configurationsdr": "SDR",
    "restore_configurationfru": "FRU",
    "restore_configurationsel": "SEL",
    "restore_configurationipmi": "IPMI",
    "restore_configurationnetwork": "Network",
    "restore_configurationntp": "NTP",
    "restore_configurationsnmp": "SNMP",
    "restore_configurationssh": "SSH",
    "restore_configurationkvm": "KVM",
    "restore_configurationauthentication": "Authentication",
    "restore_configurationsyslog": "Syslog",
    "restore_configurationweb": "Web",
    "restore_configurationextlog": "Extlog",
    "restore_configurationredfish": "Redfish",
    "saveConfirmLabel": "Click OK if you want to continue restoring configurations    WARNING:Restoring configurations will restart the device",
    "saveLabel": "Restore Factory Defaults",


    "home": "Home",
    "maintenance": "System Maintenance",
    "start_fw_update": "Start firmware update",
    "fwimage": "Select Firmware Image",
    "size32mb": "Max. size 32 MB",
    "reset": "Firmware reset has been called. Close the current session, and open a new session after a couple of minutes.",
    "section_based_flashing_body": "Only the selected sections will be updated(which cannot be checked means forcely updating):",
    //"cont_update": "Flash selected sections",
    "cont_update": "Start Upgrade",
    "select_all": "Select All",
    "select_none": "Select None",
    "section_name": "Section Name",
    "update_section": "Update Section",
    "note_for_table" : "All configuration items below will be preserved as default during the restore configuration operation. Click \"Edit Preserve Configuration\" to modify the Preserve status settings.",
    "preserve_all_config" : "Preserve all Configuration. This will preserve all the configuration settings during the firmware update - irrespective of the individual items marked as preserve/overwrite in the table below.",
    "image_upload" : "Choose the Firmware image to be updated.",
    "start_update" : "Click 'Start Firmware Update' to upgrade the current device firmware.",
    "preserve_config" : "To preserve any existing configuration data, goto <a href='#maintenance/firmware_update'>preserve configuration</a> page and select them",
    "preserve_configuration": "Preserve Configuration",
    "preserve_conf_0": "SDR",
    "preserve_conf_1": "FRU",
    "preserve_conf_2": "SEL",
    "preserve_conf_3": "IPMI",
    "preserve_conf_4": "Network",
    "preserve_conf_5": "NTP",
    "preserve_conf_6": "SNMP",
    "preserve_conf_7": "SSH",
    "preserve_conf_8": "KVM",
    "preserve_conf_9": "Authentication",
    "preserve_conf_10": "Syslog",
    "http": "http/https",
    "tftp": "tftp",
    "public_key_info":"Uploaded signImage Public Key Info",
    "new_signImg_publicKey": "New signImage Public Key",
    "signimage_upload" : "Choose the Sign Image public key of the encrypted firmware to be  updated.",
    "prepare_flash":"Preparing to flash...",
    "start_flash":"Starting flash...",
    "process":"Processing...",
    "uploading":"Uploading ",
    "verify":"Verifying...",
    "flashing":"Flashing...",
    "con_reset":"Resetting. Please wait a minute...",
    "prepare_download":"Preparing to download...",
    "downloading":"Downloading ",
    "fwimage_maintance_info":"The protocol information to be used for firmware image transfer during this update is as follows. To configure, choose \"Firmware Image Location\" under Maintenance.",
    "protocol_type":"Protocol Type:",
    "server_address":"Server Address:",
    "image_name":"Image Name:",
    "retry_count":"Retry Count:",
    "href_perser_conf":"Edit Preserve Configuration",
    "perserve_config_number":"S.No",
    "perserve_config_item":"Preserve Configuration Item",
    "preserve_status":"Preserve Status",
    "upload":"Upload",
    "option_overwrite":"Overwrite",
    "option_preserve":"Preserve",
    "option_even":"even",
    "option_odd":"odd",
    "notify_chose_signedImage_publickey_file":"Please choose a SignImage Public Key file",
    "notify_signedImage_file_upload_success":"SignImage PublicKey Uploaded successfully",
    "notify_upload_signedImage_publickey_file":"Please Upload SignImage Public Key file",
    "confirm_start_fw_upgrade":"We will start the firmware upgrade now. You will not be able to access BMC until it flashes and restarts. Do you want to continue?",
    "notify_chose_fw_image_file":"Please choose the firmware file to upgrade",
    "alert_invalid_file":"Invalid Firmware image. Only IMA file is supported",
    "notify_no_section_select":"Please select at least 1 section to upgrade",
    "existing_version":"Existing version",
    "uploading_version":"Uploaded version",
    "selectFile":"Select File",
    "fw_FirmwareUpgrade": "Firmware Upgrade",
    "fw_BMCFirmwareUpgrade": "BMC Firmware Upgrade",
    "fw_BIOSFirmwareUpgrade": "BIOS Firmware Upgrade",
    "fw_CPLDUpgrade": "CPLD Upgrade",
    "fw_PSUUpgrade": "PSU Upgrade",
    "fw_BPUpgrade": "Backplane Upgrade",
    "fw_edit_conf": "Edit Preserve Configuration",
    "fw_restore_conf": "Restore Factory Defaults",
    "fw_fwimage_location": "Firmware Image Location",
    "preserve_configurationsdr": "SDR",
    "preserve_configurationfru": "FRU",
    "preserve_configurationsel": "SEL",
    "preserve_configurationipmi": "IPMI",
    "preserve_configurationnetwork": "Network",
    "preserve_configurationntp": "NTP",
    "preserve_configurationsnmp": "SNMP",
    "preserve_configurationssh": "SSH",
    "preserve_configurationkvm": "KVM",
    "preserve_configurationauthentication": "Authentication",
    "preserve_configurationsyslog": "Syslog",
    "preserve_configurationweb": "Web",
    "preserve_configurationextlog": "Extlog",
    "preserve_configurationredfish": "Redfish",
});
