define({
    "rolegroup_active_directorystrongnotestrong_freeunconfigured_slots_are_denoted_by_noneullito_add_role_group_select_a_free_slot_and_click_on_it_to_add_a_new_role_group_to_the_devicelilito_modify_role_group_select_a_configured_slot_and_click_on_it_to_modify_that_role_groupli_lito_delete_a_role_group_select_the_desired_role_group_to_be_deleted_and_click_on_delete_icon_present_at_right_top_cornerliul": "<strong>NOTE:<\/strong> Free\/Unconfigured slots  are denoted by 'None'.<ul><li>To add Role Group, select a free slot and click on it to add a new role group to the device.<\/li><li>To modify Role Group, select a configured slot and click on it to modify that role group.<\/li> <li>To Delete a Role Group, select the desired role group to be deleted and click on delete icon present at right top corner.<\/li><\/ul>",
    "home": "Home",
    "settings": "BMC Settings",
    "external_user_settings": "External User Settings",
    "active_directory_settings": "Active directory Settings",
    "title": "Role Groups",
    "none": "None",
    "no_access": "No Access",
    "administrator": "Administrator",
    "oem": "OEM",
    "operator": "Operator",
    "user": "User",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "invalid_role_group_name_refer_help_for_more_information": "Invalid Role Group Name. Refer 'Help' for more Information.",
    "invalid_role_group_domain_refer_help_for_more_information": "Invalid Role Group Domain. Refer 'Help' for more Information.",
    "rolegroup_active_directory": "",
    "strongSuccessMsg": "Role Group settings have been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving Role Group settings.",
    "failureMsg": "",
    "rolegroup_active_directorygroup_name": "Group Name",
    "rolegroup_active_directoryenter_the_role_group_name_this_name_identifies_the_role_group_in_active_directoryulli_role_group_name_is_a_string_of_64_alphanumeric_characterslili_special_symbols_hyphen_and_underscore_are_allowedliul": "Enter the Role Group Name. This name identifies the role group in Active Directory.<ul><li> Role Group Name is a string of 64 alpha-numeric characters.<\/li><li> Special symbols hyphen and underscore are not allowed.<\/li><\/ul>",
    "rolegroup_active_directorygroup_domain": "Group Domain",
    "eg_mydomaincom": "eg., MyDomain.com",
    "rolegroup_active_directoryenter_the_role_group_domain_this_is_the_domain_where_the_role_group_is_located_ulli_domain_name_is_a_string_of_255_alphanumeric_characterslili_special_symbols_hyphen_underscore_and_dot_are_allowedliul": "Enter the Role Group Domain. This is the domain where the role group is located. <ul><li> Domain Name is a string of 255 alpha-numeric characters.<\/li><li> Special symbols hyphen, underscore and dot are not allowed.<\/li><\/ul>",
    "rolegroup_active_directorygroup_privilege": "Group Privilege",
    "rolegroup_active_directoryuser": "User",
    "rolegroup_active_directoryadministrator": "Administrator",
    "rolegroup_active_directoryoperator": "Operator",
    "rolegroup_active_directorynone": "None",
    "rolegroup_active_directoryenter_the_role_group_privilege_this_is_the_level_of_privilege_to_be_assigned_for_this_role_group": "Enter the Role Group Privilege. This is the level of privilege to be assigned for this role group",
    "rolegroup_active_directorykvm_access": "KVM Access",
    "rolegroup_active_directorythis_field_provides_access_to_kvm_for_ad_authenticated_role_group_user": "This field provides access to KVM for AD authenticated role group user.",
    "rolegroup_active_directoryvmedia_access": "VMedia Access",
    "rolegroup_active_directorythis_field_provides_access_to_vmedia_for_ad_authenticated_role_group_user": "This field provides access to VMedia for AD authenticated role group user.",
    "saveLabel": "Save",
    "role_groups": "Role Groups",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",
    "delete_tip": "Are you sure to perform this operation?",
});
