define({
    "rolegroup_ldapstrongnotestrong_freeunconfigured_slots_are_denoted_by_noneullito_add_role_group_select_a_free_slot_and_click_on_it_to_add_a_new_role_group_to_the_devicelilito_modify_role_group_select_a_configured_slot_and_click_on_it_to_modify_that_role_groupli_lito_delete_a_role_group_select_the_desired_role_group_to_be_deleted_and_click_on_delete_icon_present_at_right_top_cornerliul": "<strong>NOTE:<\/strong> Free\/Unconfigured slots  are denoted by 'None'.<ul><li>To add Role Group, select a free slot and click on it to add a new role group to the device.<\/li><li>To modify Role Group, select a configured slot and click on it to modify that role group.<\/li> <li>To Delete a Role Group, select the desired role group to be deleted and click on delete icon present at right top corner.<\/li><\/ul>",
    "home": "Home",
    "settings": "BMC Settings",
    "external_user_settings": "External User Settings",
    "ldapedirectory_settings": "LDAP\/E-directory Settings",
    "title": "Role Groups",
    "none": "None",
    "no_access": "No Access",
    "administrator": "Administrator",
    "oem": "OEM",
    "operator": "Operator",
    "user": "User",
    "kvm": "KVM",
    "vmedia": "VMedia",
    "invalid_role_group_name_refer_help_for_more_information": "Invalid Role Group Name. Refer 'Help' for more Information.",
    "invalid_role_group_domain_refer_help_for_more_information": "Invalid Role Group Domain. Refer 'Help' for more Information.",
    "rolegroup_ldap": "",
    "strongSuccessMsg": "Role Group has been updated successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in updating Role Group.",
    "failureMsg": "",
    "rolegroup_ldapgroup_name": "Group Name",
    "rolegroup_ldapenter_the_role_group_name_this_name_identifies_the_role_group_in_ldapedirectoryulli_role_group_name_is_a_string_of_64_alphanumeric_characterslili_special_symbols_hyphen_and_underscore_are_allowedliul": "Enter the Role Group Name. This name identifies the role group in LDAP\/E-directory.<ul><li> Role Group Name is a string of 64 alpha-numeric characters.<\/li><li> Special symbols hyphen and underscore are allowed.<\/li><\/ul>",
    "rolegroup_ldapgroup_domain": "Group Domain",
    "eg_dcdomain": "eg., dc=domain",
    "rolegroup_ldapenter_the_role_group_domain_this_is_the_domain_where_the_role_group_is_located_ulli_domain_name_is_a_string_of_4_to_64_alphanumeric_characterslili_it_must_start_with_an_alphabetical_characterlili_special_symbols_like_dot_comma_hyphen_underscore_equalto_are_allowedli_li_example_cnmanageroulogin_dcdomaindccomliul": "Enter the Role Group Domain. This is the domain where the role group is located. <ul><li> Domain Name is a string of 4 to 64 alpha-numeric characters.<\/li><li> It must start with an alphabetical character.<\/li><li> Special Symbols like dot(.), comma(,), hyphen(-),  underscore(_), equal-to(=) are allowed.<\/li> <li> Example: cn=manager,ou=login, dc=domain,dc=com<\/li><\/ul>",
    "rolegroup_ldapgroup_privilege": "Group Privilege",
    "rolegroup_ldapuser": "User",
    "rolegroup_ldapadministrator": "Administrator",
    "rolegroup_ldapoperator": "Operator",
    "rolegroup_ldapoem": "OEM",
    "rolegroup_ldapnone": "None",
    "rolegroup_ldapenter_the_role_group_privilege_this_is_the_level_of_privilege_to_be_assigned_for_this_role_group": "Enter the Role Group Privilege. This is the level of privilege to be assigned for this role group",
    "rolegroup_ldapkvm_access": "KVM Access",
    "rolegroup_ldapthis_field_used_to_assign_the_kvm_privilege_for_this_role_group": "This field used to assign the KVM privilege for this role group.",
    "rolegroup_ldapvmedia_access": "VMedia Access",
    "rolegroup_ldapthis_field_used_to_assign_the_vmedia_privilege_for_this_role_group": "This field used to assign the VMedia privilege for this role group.",
    "saveLabel": "Save",
    "role_groups": "Role Groups",

    "external_user_services": "External User Settings",
    "ext_ldap": "LDAP/E-directory Settings",
    "ext_active_directory": "Active directory Settings",
    "ext_radius": "RADIUS Settings",
    "ext_general_ldap_settings": "General LDAP Settings",
    "ext_role_groups": "Role Groups",
    "ext_active_directory_settings": "General Active directory Settings",
    "ext_general_radius_settings": "General RADIUS Settings",
    "ext_advanced_radius_settings": "Advanced RADIUS Settings",
    "delete_tip": "Are you sure to perform this operation?",
});
