define({
    "home": "Home",
    "parentTitle": "BMC Settings",
    "alarm_settings": "Alarm Settings",
    "snmp_trap": "SNMP Trap Setting",
    "snmp": "",
    "no_snmp_trap_information": "Error in querying SNMP Trap Setting information.",
    "strongSuccessMsg": "SNMP Trap Settings has been saved successfully",
    "successMsg": "",
    "strongFailureMsg": "Error in saving SNMP Trap Settings",
    "failureMsg": "",
    "rw_char": "RW Community Name",
     "ro_char": "RO Community Name",
    "snmpcheck_this_option_to_enable_snmp_support_for_the_bmc" : "Check this option to enable SNMP support for the BMC.",
    "snmp_support": "SNMP Status Enable",
    "snmp_protocol": "SNMP Protocol",
    "snmp_visit": "SNMP Visit",
    "privacy_protocol": "Privacy Protocol",


    "saveLabel": "Save",
    "help_information":"Sets the read and write permissions for the community name of the SNMP v1/v2. If it’s the SNMP V3 , please sets by the user management page.",

    "trap_help_information":"The SNMP v1/v2, please input the community name. The SNMP V3, plesse select the user name (The length of user's password should not be less than 8 bits).",
    "trap_help_snmp_addr":"The saved SNMP Address can be tested. The system will not check the test results, please confirm whether it is successful.",


    "whether_enable": "Enable SNMP Trap Alarm",
    "on": "ON",
    "off": "OFF",
    "v1": "V1",
    "v2": "V2",
    "v3": "V3",
    "community": "Community Name",
    "v3_user": "V3 User",
    "not_null": "Cannot be empty",
    "alarm_grade": "Alarm Grade",
    "check_all": "Check All",
    "urgency": "Urgency",
    "critical": "Critical",
    "non_critical": "Non Critical",
    "normal": "Normal",
    "snmp_addr": "SNMP Address",
    "snmp_test": "Test",
    "ip_incorrect": "IP address format is incorrect",
    "sent_to_ip": 'The test information has been sent to <strong>{IP}<\/strong>. please confirm , and the system will not check whether the reception is successful.',
    "sent_to_ip_error": 'Error in testing SNMP Address <strong>{IP}<\/strong>.',
    // ks_lz_20180727 TAB ++>>
    "title": "Safe Settings",
    "loginControl": "Login Control",
    "snmpv": "SNMP V1/V2 Settings",
    "ssl_settings": "SSL Settings",
    "user_badpassword": "User Password Lock",
    // ks_lz_20180727 TAB ++>>
});