define({
    "home": "Home",
    "settings": "BMC Settings",
    "video": "video",
    "sol": "Sol",
    "title": "SOL video Remote Storage",
    "sol_remote_storage": "",
    "invalid_log_sizerefer_help_for_more_information": "Invalid Log size.Refer 'Help' for more Information.",
    "invalid_log_file_countrefer_help_for_more_information": "Invalid Log file count.Refer 'Help' for more Information.",
    "invalid_server_address_refer_help_for_more_information": "Invalid Server address. Refer 'Help' for more Information.",
    "invalid_path_refer_help_for_more_information": "Invalid path. Refer 'Help' for more Information.",
    "username_is_required_for_cifs_location": "Username is required for CIFS location",
    "password_is_required_for_cifs_location": "Password is required for CIFS location",
    "strongSuccessMsg": "SOL video Remote Storage settings has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in saving SOL video Remote Storage settings.",
    "failureMsg": "",
    "sol_remote_storagelog_size_kb": "Log Size (KB)",
    "sol_remote_storageenter_the_size_of_log_file_in_kbs_and_value_will_support_maximum_length_of_10_digits": "Enter the Size of log file in KB's and Value will support maximum length of 10 digits.",
    "sol_remote_storagelog_file_count": "Log File Count",
    "sol_remote_storageenter_the_number_of_log_files_countdefault_values_ranges_from_1_to_10": "Enter the number of Log files count.Default values ranges from 1 to 10.",
    "sol_remote_storagerecord_video_to_remote_server": "Record Video to Remote Server",
    "sol_remote_storageto_enable_or_disable_remote_video_support_check_or_uncheck_the_enable_checkbox_respectively_strongnote_strongby_default_video_files_will_be_stored_in_local_path_of_bmc_if_remote_video_support_is_enabled_then_the_video_files_will_be_stored_only_in_remote_path_not_within_bmc": "To enable or disable Remote Video support, check or  uncheck the 'Enable' checkbox respectively. <strong>NOTE: <\/strong>By default, video files will be  stored in local path of BMC. If remote video support is  enabled, then the video files will be stored only in remote  path, not within BMC.",
    "sol_remote_storageserver_address": "Server Address",
    "server_ip_or_host_name": "Server IP or Host name",
    "sol_remote_storageserver_address_of_the_server_where_remote_videos_are_to_be_storedbr_server_address_will_support_the_following_ul_li_ip_address_both_ipv4_and_ipv6_formatli_li_fqdn_fully_qualified_domain_name_formatli_ul": "Server address of the server where remote videos are to be  stored.<br> Server address will support the following:  <ul> <li> IP Address (Both IPv4 and IPv6 format).<\/li>  <li> FQDN (Fully qualified domain name) format.<\/li>  <\/ul>",
    "sol_remote_storagepath_in_server": "Path in server",
    "eg_optbmcvideos": "eg. \/opt\/bmc\/videos",
    "sol_remote_storagesource_path_to_directory_where_the_remote_videos_will_be_stored_ul_li_special_characters_less_than_greater_than_colon_asterisk_vertical_bar_dot_question_mark_are_not_allowedli_ul": "Source path to directory where the remote videos  will be stored. <ul> <li> Special characters '<'(less than),  '>'(greater than), ':'(colon), '*'(asterisk),  '|'(vertical bar), '.'(dot), '?'(question mark)  are not allowed.<\/li>  <\/ul>",
    "sol_remote_storageshare_type": "Share Type",
    "sol_remote_storagenfs": "NFS",
    "sol_remote_storagecifs": "CIFS",
    "sol_remote_storageshare_type_of_the_remote_video_server_either_nfs_or_sambacifs": "Share Type of the remote video server either NFS or Samba(CIFS).",
    "sol_remote_storagedomain_name": "Domain Name",
    "sol_remote_storageenter_the_domain_name_for_the_remote_video_server": "Enter the Domain name for the remote video server.",
    "sol_remote_storageusername": "Username",
    "sol_remote_storageenter_the_username_for_the_remote_video_server": "Enter the Username for the remote video server.",
    "sol_remote_storagepassword": "Password",
    "sol_remote_storageenter_the_password_for_the_remote_video_server": "Enter the Password for the remote video server.",
    "saveLabel": "Save"
});
