define({
    "home": "Home",
    "bmc_settings": "BMC Settings",
    "title": "Safe Settings",
    "upload_ssl": "",
    "strongSuccessMsg": "The HTTPS certificate has been uploaded. The page will automatically jump to the login page after 30 seconds. Please log in again to make the certificate take effect!",
    "successMsg": "",
    "strongFailureMsg": "Error in uploading the SSL Certificate",
    "failureMsg": "",
    "upload_sslcurrent_certificate": "Current Certificate",
    "upload_sslthe_information_as_current_certificate_and_uploaded_datetime_will_be_displayed_readonly": "The information as Current certificate and uploaded date\/time will be displayed (readonly).",
    "upload_sslnew_certificate": "New Certificate",
    "upload_sslbrowse_and_navigate_to_the_certificate_fileulli_certificate_file_should_be_of_pem_typeliul": "Browse and navigate to the certificate file.<ul><li> Certificate file should be of pem type<\/li><\/ul>",
    "upload_sslcurrent_private_key": "Current Private Key",
    "upload_sslthe_information_as_current_private_key_and_uploaded_datetime_will_be_displayed_readonly": "The information as current private key and uploaded date\/time will be displayed (readonly).",
    "upload_sslnew_private_key": "New Private Key",
    "upload_sslbrowse_and_navigate_to_the_private_key_fileulli_private_key_file_should_be_of_the_type_pem_liul": "Browse and navigate to the private key file.<ul><li> Private key file should be of the type pem <\/li><\/ul>",
    "saveLabel": "Upload",
    "view_ssl_certificate": "View SSL certificate",
    "generate_ssl_certificate": "Generate SSL certificate",
    "upload_ssl_certificate": "Upload SSL certificate",
    "loginControl": "Login Control",
    "snmpv": "SNMP V1/V2 Settings",
    "ssl_settings": "SSL Settings",
    "user_badpassword": "User Password Lock"
});
