define({
    "home": "Home",
    "bmc_settings": "BMC Settings",
    "title": "Safe Settings",
    "view_sslcurrent_certificate_information": "Current Certificate Information",
    "strongSuccessMsg": "SSL Certificate has been saved successfully.",
    "successMsg": "",
    "strongFailureMsg": "Error in getting SSL Certificate.",
    "failureMsg": "",
    "view_sslcertificate_version": "Certificate Version",
    "view_sslbbasic_informationbbrit_displays_the_basic_information_about_the_uploaded_ssl_certificateit_displays_the_following_fieldsulli_version_serial_numberlili_signature_algorithmlili_public_keyliul": "<b>Basic Information<\/b><br>It displays the basic information about the uploaded SSL certificate.It displays the following fields.<ul><li> Version </li><li> Serial Number<\/li><li> Signature Algorithm<\/li><li> Public Key<\/li><\/ul>",
    "view_sslserial_number": "Serial Number",
    "view_sslsignature_algorithm": "Signature Algorithm",
    "view_sslpublic_key": "Public Key",
    "view_ssl": "",
    "view_sslissuer_common_name_cn": "Issuer Common Name (CN)",
    "view_sslbissued_frombbrthis_contains_the_information_about_the_certificate_issuerulli_common_namecnlili_organizationolili_organization_unitoulili_city_or_localityllili_state_or_provincestlili_countryclili_email_addressliul": "<b>Issued From<\/b><br>This contains the information about the Certificate Issuer.<ul><li> Common Name(CN)<\/li><li> Organization(O)<\/li><li> Organization Unit(OU)<\/li><li> City or Locality(L)<\/li><li> State or Province(ST)<\/li><li> Country(C)<\/li><li> Email Address<\/li><\/ul>",
    "view_sslissuer_organization_o": "Issuer Organization (O)",
    "view_sslissuer_organization_unit_ou": "Issuer Organization Unit (OU)",
    "view_sslissuer_city_or_locality_l": "Issuer City or Locality (L)",
    "view_sslissuer_state_or_province_st": "Issuer State or Province (ST)",
    "view_sslissuer_country_c": "Issuer Country (C)",
    "view_sslissuer_email_address": "Issuer Email Address",
    "view_sslvalid_from": "- Valid From",
    "view_sslbvalidity_informationbbrit_displays_the_validity_period_of_the_uploaded_certificateulli_valid_fromlili_valid_toliul": "<b>Validity Information<\/b><br>It displays the validity period of the uploaded certificate.<ul><li> Valid From<\/li><li> - Valid Till<\/li><\/ul>",
    "view_sslvalid_till": "Valid Till",
    "view_sslissued_to_common_name_cn": "Issued to Common Name (CN)",
    "view_sslbissued_tobbrit_displays_about_the_information_to_whom_the_certificate_is_issuedulli_common_namecnlili_organizationolili_organization_unitoulili_city_or_localityllili_state_or_provincestlili_countryclili_email_addressliul": "<b>Issued To<\/b><br>It displays about the information to whom the certificate is issued.<ul><li> Common Name(CN)<\/li><li> Organization(O)<\/li><li> Organization Unit(OU)<\/li><li> City or Locality(L)<\/li><li> State or Province(ST)<\/li><li> Country(C)<\/li><li> Email Address<\/li><\/ul>",
    "view_sslissued_to_organization_o": "Issued to Organization (O)",
    "view_sslissued_to_organization_unit_ou": "Issued to Organization Unit (OU)",
    "view_sslissued_to_city_or_locality_l": "Issued to City or Locality (L)",
    "view_sslissued_to_state_or_province_st": "Issued to State or Province (ST)",
    "view_sslissued_to_country_c": "Issued to Country (C)",
    "view_sslissued_to_email_address": "Issued to Email Address",
    "view_ssl_certificate": "View SSL certificate",
    "generate_ssl_certificate": "Generate SSL certificate",
    "upload_ssl_certificate": "Upload SSL certificate",
    "loginControl": "Login Control",
    "snmpv": "SNMP V1/V2 Settings",
    "ssl_settings": "SSL Settings",
    "user_badpassword": "User Password Lock"
});
